### ISSUE TITLE
Service Worker: App Shortcuts

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#10009]
With Chrome 85 [App Shortcuts](https://web.dev/app-shortcuts/) have been added for Android and Windows, this allows long press/right click options to be added to allow access to tasks more quickly, such as "Write a post".

**Describe the solution you'd like**

A forem maintainer should be able to add custom actions that appear in their service worker, they would need to add:
 - a name
 - a short name
 - a description 
 - a location
 - an icon _though I'm sure there can be a default_

```js
"shortcuts": [
  {
    "name": "Write a post",
    "short_name": "New post",
    "description": "Start writing a new post",
    "url": "/new",
    "icons": [{ "src": "/icons/new.png", "sizes": "192x192" }]
  },
]
```

**Describe alternatives you've considered**

 - we don't offer this as a feature
 - we have a set of built in shortcuts that the maintainer can't modify easily

**Additional context**

![Menu example](https://user-images.githubusercontent.com/3534427/91285622-5de24d00-e785-11ea-90b3-9883d8f529c0.png)

**Comment by rhymes** [comment]
Linking the browser support section, from https://web.dev/app-shortcuts/#browser-support

> App shortcuts are available on Android (Chrome 84) and Windows (Chrome 85 and Edge 85). More desktop platform support will follow.

**Comment by boardfish** [comment]
I'm curious about this one. Not going to formally pin it down, but it seems well-documented and I'd like to look into it potentially.

**Comment by cmgorton** [comment]
Thank you for opening this request Andrew!
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
