### ISSUE TITLE
"Tag Mods" link under "/admin/mods" blows up when there are no tag mods

### ISSUE THREAD

**Issue by msarit** [forem/forem#10060]
**Describe the bug**

When there are no tag moderators, the `Tag Mods` link under `/admin/mods` blows up when clicked.

**To Reproduce**

1. Make sure your current user has the role `admin` or `super_admin`
(to do so, in `rails console`, run the command `User.find(<your_user_id>).add_role(:admin).save!`)
2. Make sure there are no tag moderators in your local app
(in `rails console`, the command `User.with_role("tag_moderator").count` should return `0`)
3. Navigate to `localhost:xxxx/admin/mods`
4. Click on the `Tag Mods` link
5. An `ActiveRecord::RecordNotFound` error should result

**Expected behavior**

There are many alternative behaviors, but I would expect to see a message like `"There are no Tag Moderators"`, maybe followed by short directions for making a user a tag moderator.

**Screenshots**

https://www.loom.com/share/cec177c9c91d453ab88403a2538316f3

**Desktop (please complete the following information):**

- OS, version: macOS Catalina version 10.15.5
- Browser, version: Google Chrome version 85.0.4183.83 (Official Build) (64-bit)

**Comment by diogoosorio** [comment]
I was looking into this and I think that the problem here might be that the role itself (a role named `tag_moderator`) doesn't exist in your local database and that's what's triggering the exception.

If you manipulate the `state=` query string parameter to any non-existing role name, it'll also trigger this problem, which is not a very elegant way to handle that input I guess (see my screenshot's query string).

![image](https://user-images.githubusercontent.com/1484824/91659223-9ad07b80-eac6-11ea-849c-a6d852b00c74.png)

A valid role (any role, not just the ones linked on the sub-navigation of mods page) filters the list of users by that role (screenshot filtering by the `super_admin` role):

![image](https://user-images.githubusercontent.com/1484824/91659675-35ca5500-eac9-11ea-8c3e-8ddad45805f2.png)

Here's the output of filtering by a valid role, but with no results (which I think was what you mentioned on the issue's initial description):

![image](https://user-images.githubusercontent.com/1484824/91663619-e17f9f00-eae1-11ea-9f72-279eb8528db2.png)

So I believe that we're looking at 2 different things:

1. How to properly validate the `state` parameter:

    1. Should we assume that those roles always exist on the database? Or should we disable (or something similar) the mod filter buttons if the corresponding roles are missing from the database?

    1. Should the controller validate that input and only accept `tag_moderator` & `potential` as input? If so, what should happen if an invalid input is provided?

1. In the scenario of the query return a list of empty users, we can definitely add a more descriptive message instead of showing an empty table (as you suggested in the issue's initial description)

I'd like to tackle this as my first contribution to the project, but I definitely need your guidance figuring out what's the behaviour the page should assume. @msarit can you help me out figuring out a more concrete specification, before I implement anything? 🙏

**Comment by msarit** [comment]
@diogoosorio thank you for tackling this issue! Give me some time to confer with the other devs, after which I (or they) shall get back to you! Thanks again! 🙏

**Comment by Zhao-Andy** [comment]
Hi @diogoosorio! Thanks for your interest in working on this issue. To answer your questions:
1. I think instead of assuming the roles exist, we can add better error handling if the role does not exist. In our query, we do a `find_by!` which errors out, and I think we should change that to `find_by`. 
2. I don't think we need to validate the input in the controller, but we should send a proper response if the input is not valid. I haven't looked at the code here, but something like `if... elsif... else` would probably work okay.
3. If the query returns a list of empty users, at least for tag moderators I think we can add a message that links to adding a tag moderator -- IMO this is a nice-to-have and definitely not necessary. 

Hope that helps! Let us know if you have any more questions.

**Comment by diogoosorio** [comment]
All right thanks for all the help @msarit and @Zhao-Andy.

I'll picking this one up (I was actually waiting of October 1 to start it, because now there are free t-shirts involved 😂 ).

**Comment by rhymes** [comment]
Assigned this to you @diogoosorio, thanks!
