### ISSUE TITLE
Team/Group Creation for collaborated contribution

### ISSUE THREAD

**Issue by abhinav1602** [forem/forem#10072]
**Is your feature request related to a problem? Please describe.**
Publish articles in collaboration under a group name. 

**Describe the solution you'd like**
- "**Create Group**" option on DEV in which I can add multiple DEV users. 
- Each of these users should be allowed to **post articles in this group** as an individual contributor. 
- Author name for each article should be the original contributor's name.
- But, the link for that articles should be something like **https://dev.to/{group_Name}/{articleName}.**
- All the published articles should also be visible on individual contributors' dashboards.
- On the Group Dashboard, all the articles published by all the members should be visible.

**Describe alternatives you've considered** 
I thought of creating it as an **organization** but then it won't work right? 
Since, it is just like a collaborative group, I cannot create it as an organization. 
It doesn't have a URL, GitHub, Twitter etc on its name, it is just meant for DEV platform.

**Additional context**
I'll add in the thread if required.

**Comment by citizen428** [comment]
@abhinav1602 

1. Organizations have their own profiles, see e.g. https://dev.to/devteam. 
2. Articles have the organization name in the URL, since we treat organizations mostly like users: https://dev.to/devteam/get-in-on-the-action-github-actions-hackathon-reminder-208d
3. The original author will show as author for the post, the organization will be displayed on top:
    <img width="728" alt="Get_in_on_the_action_—_GitHub_Actions_Hackathon_reminder__⏰_-_DEV" src="https://user-images.githubusercontent.com/47985/91680695-3f5dc680-eb76-11ea-840b-d31b874fd8f7.png">
4. Articles show in the user's dashboard but also reference the organization:
    <img width="646" alt="Screen Shot 2020-08-31 at 10 42 13" src="https://user-images.githubusercontent.com/47985/91680982-3a4d4700-eb77-11ea-9d4c-7161642fd8ae.png">

So it seems like organizations would fit your intended use case. Can you confirm and report back here please?

**Comment by abhinav1602** [comment]
@citizen428 Thanks for the clarity. It worked for me.
