### ISSUE TITLE
Generalise the liquid tags editor help '_editor_liquid_help.html.erb'

### ISSUE THREAD

**Issue by leewynne** [forem/forem#10129]
At the moment in /app/views/pages/_editor_liquid_help.html.erb there are lots of references to Dev users, github and other Dev specific resources.

**Describe the solution you'd like**

An area in siteconfig to allow an admin to determin which liquid tags are supported for a Forem instance and then some text to support the editor help section.

**Describe alternatives you've considered**

Hard coding :(

**Additional context**

Nope, but whoever gets to read this text I hope that you are having a glorious day. You're amazing!

**Comment by jacobherrington** [comment]
I think there are a few solutions we could use.

Ideally, I'd like to keep this out of `SiteConfig`. I'm wondering if there is a compelling reason the editor guide is hard-coded versus just being a page a la `/admin/pages`.

From what I can see, `_editor_guide_text.html.erb` is only rendered here: 
https://github.com/forem/forem/blob/0b849341e0f4dda762953964500a57fc9df67f04/app/views/pages/editor_guide.html.erb#L10

There is some erb in that file, but I think we shouldn't set this pattern in DEV if we don't expect future (and current) Forem admins to do the same.

My thought is that we should remove our hard-coded editor guide in favor of using the pages tool. However, as @maestromac pointed out, we lose the benefit of having new Liquid tags documented in version control ([example](https://github.com/forem/forem/pull/4958/files#diff-510e478dbfd3cc93e63476a8b90b9ffe)). This seems like the easiest approach to solve @leewynne's problem.

Alternatively, another solution is creating an interface and database column that allows an admin to store/edit documentation for a given tag, so that the editor guide is generated based on those values. That approach would also allow the admin to hide or show liquid tags in the guide based on preference. This seems like the better approach, but probably requires more work.

I'd like to get @benhalpern's opinion since this might set a bit of a precedent for the product.

**Comment by benhalpern** [comment]
I feel like site pages might be tough because then it is up to the admin to edit it any time there is a reasonable change, but maybe something a little more dynamic and interactive.

To be honest, I think the editor guide was always meant to be a placeholder for something a little more friendly and approachable.....

So instead of having the docs-oriented style we have now, which we know is sort of digestible among developers, but not what the typical user would expect, and instead try and replace this altogether with something more friendly and specific?

In the meantime I think the best short term scenario is to revisit the copy and friendliness of what we do have in place in a way that maybe isn't custom, but just more usable period.

**Comment by atsmith813** [comment]
2 quick notes for anyone that tackles this in the future:
- **We should consolidate where we document liquid tags.** Currently, we render hardcoded liquid tag documentation in 2 different partials - [_editior_guide_text.html.erb](https://github.com/forem/forem/blob/master/app/views/pages/_editor_guide_text.html.erb) and [_editior_liquid_help.html.erb](https://github.com/forem/forem/blob/master/app/views/pages/_editor_liquid_help.html.erb).
- **We conditionally render liquid tag documentation based on a variety of factors.** There are a few different factors we could take into account when rendering liquid tag documentation - roles, Forem instance, context (Article, Comment, etc), and more. We'll probably want to understand which of these factors we want to make configurable by an Admin and tie those into some dynamic documentation.

**Comment by citizen428** [comment]
@atsmith813 

> We should consolidate where we document liquid tags.

Ideally we take this out of any view and make it part of some data structure or even a yml file. We can then use the stored values in views, but also repurpose them to send them to the editor for the Liquid tag auto-completion @nickytonline will be tackling during cooldown (see https://github.com/forem/forem/pull/10241 for the first PR).
