### ISSUE TITLE
Elements at top of feed are not removed when scrolling to bottom

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#10134]
**Describe the bug**

In the home feed page when you scroll down new elements are added to the feed. But elements at the top of the page that are not visible are not removed. It should probably removed after some threshold.

**To Reproduce**

   1. Go to dev.to
   2. Run the query ```document.getElementsByClassName("crayons-story").length``` in developer tools
   3. Keep scrolling down and run this query each time after the new item loads
   4. This count keeps increasing
 

**Expected behaviour**

Elements at the top should probably be removed after some point.

**Desktop:**

OS, version: Ubuntu 20.04
Browser, version: Brave Version 1.12.112 Chromium: 84.0.4147.125 (Official Build) (64-bit)

**Additional context**

This behaviour seems to be happening in few other places too.

**Comment by Link2Twenty** [comment]
DOM recycling is very good way to do this, here is a related article. 

https://developers.google.com/web/updates/2016/07/infinite-scroller

**Comment by Rafi993** [comment]
If DOM recycling is implemented then it may break **Ctrl + F** search in chrome.

**Comment by Rafi993** [comment]
I think PR https://github.com/forem/forem/pull/11560 does some thing similar.

**Comment by cmgorton** [comment]
Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
