### ISSUE TITLE
Add a notification when resetting password

### ISSUE THREAD

**Issue by mrmir** [forem/forem#10130]
**Is your feature request related to a problem? Please describe.**
When you currently enter an email address on the forgot password page, it redirects you to the login page without any notification showing up

**Describe the solution you'd like**
Some sort of flash or notification saying 'An email has been sent' or similar showing up above the login box

**Describe alternatives you've considered**
Some sort of flash or notification showing up in the password page itself, maybe?

**Comment by mrmir** [comment]
I'll work on this

**Comment by rhymes** [comment]
Thank you @mrmir, I've assigned you!

**Comment by tuang3142** [comment]
nicely done @mrmir 
@rhymes I think we can close this

**Comment by rhymes** [comment]
I think this is still vlaid @tuang3142

**Comment by mrmir** [comment]
@rhymes Can you reassign it to me, please? I was too new to Rails then, but I can handle it now and would love to give it a shot.

**Comment by rhymes** [comment]
Done @mrmir, thank you!

**Comment by mrmir** [comment]
On it

**Comment by mrmir** [comment]
@rhymes @tuang3142 Do you know what I can do about this while setting up the app locally? 

![image](https://user-images.githubusercontent.com/7458152/136058423-c3469af5-a31b-4665-94cf-bd8eb7c7fb6e.png)

**Comment by rhymes** [comment]
Hi @mrmir, sorry I dropped the ball on this. 

The error you're experiencing is usually because `APP_DOMAIN` in your local environment isn't correctly set. On development it should be `localhost:3000`, also check if `APP_PROTOCOL` is set to `http://`

Regarding the style of notification. I think just adding a regular Rails redirect notice should suffice, the controller should be able to pick it up and show it, we have a `global_notice` key if the regular notice doesn't work:

https://github.com/forem/forem/blob/cceb175d5d8e09bab9df945f8973a9231e21a4a3/app/views/layouts/application.html.erb#L86-L90
