### ISSUE TITLE
sort articles for Dev profiles

### ISSUE THREAD

**Issue by krishnadevz** [forem/forem#10163]
**Sort articles for Dev profiles**

hello there 
so we can sort Dev.to articles in the dashboard with all options means by (views/date published etc.)
but in the case when we click on profile section then I can pin the posts but I can't sort all articles by my preference I am talking by everyone perspectives so  we can add drop in pin section with help of that we can sort posts according to our preference on main profile section thank you.**
I can work on this?

**GIF'S**
**live description of the feature request**
![descripfeature](https://user-images.githubusercontent.com/42638797/91992594-f2364c00-ed51-11ea-8f7b-24e78086ddbd.gif)

**Comment by rhymes** [comment]
Hi @krishnadevz: FYI sorting the dashboard has no relation with how the articles appear in your public profile. That's always sorted by reverse publication date

**Comment by krishnadevz** [comment]
> 
> 
> Hi @krishnadevz: FYI sorting the dashboard has no relation with how the articles appear in your public profile. That's always sorted by reverse publication date, well for now :) Thanks for this feature request!

I am talking about dashboard sorting I am talking about we can sort articles in public profile with instead of the only PIN the article we can sort according to individual preferences.

**Comment by rhymes** [comment]
Sure, I got it, I'm just saying that the dashboard and the profile aren't connected. If this gets approved we should probably have a specific settings in https://dev.to/settings/profile to let people decide which order they want their profile pages to be sorted in

**Comment by madarsbiss** [comment]
@rhymes I get the idea of @krishnadevz 👍
Tho, in my opinion, there is no need to push any particular order of articles by an author and all the sorting (if needed) should be left to visitors, so the following model could be more appropriate:
1. Leave the order in the user's profile as it is currently (by date).
2. Add an option to sort by most views/reactions/comments for visitors.

**Comment by saurabhdaware** [comment]
That's a great suggestion! In my opinion,  I think it will be helpful to have an option to reorder pins. But having remaining posts in order of date will be better since it is a standard way. 

Also as @madarsbiss suggested, we can have an option to sort (and maybe filter? so that we can filter by tags) would look good.

**Comment by cmgorton** [comment]
Thank you for opening this request!
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
