### ISSUE TITLE
Empty series should be automatically deleted in Dashboard

### ISSUE THREAD

**Issue by madarsbiss** [forem/forem#10176]
**To Reproduce**

Create a unique series name for any post.
That adds a particular series name in Dashboard. So far so good.

Edit the same post and remove the series.
Go back and check the Dashboard. The series name is still there and says ["your_series_name"] (0 Part Series).

![chrome_xqNhRp9DTd](https://user-images.githubusercontent.com/42511917/92034771-61be3280-ed76-11ea-8037-b41fe10c0b84.png)

**Expected behavior**

If the series is empty, it should be automatically removed from Dashboard.
As the user can make it anytime later if he decides. No need to keep around empty ones.

**Comment by rhymes** [comment]
Hi @madarsbiss, I'm not sure we should automatically delete it but we could add a "delete series" button, as I mentioned in here https://github.com/forem/forem/issues/9658#issuecomment-670414576

We could also make it so that empty series don't appear in the public profile, see also https://github.com/forem/forem/issues/9658

**Comment by madarsbiss** [comment]
Yeah, or that. 💯🎯

**Comment by rhymes** [comment]
I'm going to close this in favor of the other solution, please add a note over there with your proposal @madarsbiss so we can keep track of it in context :) Thank you!
