### ISSUE TITLE
Enable comments on Forem pages

### ISSUE THREAD

**Issue by leewynne** [forem/forem#10316]
As a Forem admin, it makes sense in some scenarios to create content in the form of a static page, and then maybe to include links to that page in other parts of the Forem.

I'd like to be able to keep these pages evergreen by optionally enabling comments on them.

**Describe the solution you'd like**

In the admin console, when creating a page, having the option to enable comments on a page by page basis.

**Describe alternatives you've considered**

Just using a post to create the content, but they rust.

**Comment by cmgorton** [comment]
Hey Lee! I think this would be a pretty interesting conversation to have on Forem.dev so that we could all talk about the trade-offs, complexities, and user experience behind this. Since this has been open for awhile without much progress would you be interested in kicking off a conversation on Forem.dev? Thanks!
