### ISSUE TITLE
Generalise Badge allocation

### ISSUE THREAD

**Issue by leewynne** [forem/forem#10319]
At the moment, automated badge allocation is specific to Dev. Ideally it would be great to generalise this and make it available for other Forems.

**Describe the solution you'd like**

When creating a new badge in the admin console, I would like the ability to allocated the badge based on a number of conditions such as:

Is the member in their first year?
Has the member contributed with their first comment or article?
Does the member meet some other condition on the User table for custom badges.

**Comment by cmgorton** [comment]
Hey Lee! I think this would be a pretty interesting conversation to have on Forem.dev so that we could all talk about the trade-offs, complexities, and user experience behind this. Since this has been open for awhile without much progress would you be interested in kicking off a conversation on Forem.dev? Thanks!
