### ISSUE TITLE
Allow html banner campaigns to be displayed on more pages for new Forems to support growth.

### ISSUE THREAD

**Issue by leewynne** [forem/forem#10315]
When banners are created or campaigns (see picture below) by default they show on the primary root index page only. I think it would be a good idea for smaller Forem's to have the option for the campaign banners to be displayed on more pages to help incentivize sign ups and growth.

At the very least, on custom pages and the default single article view

**Describe the solution you'd like**

When new campaigns and banners are created, an option for Forem admins to select where they would like the campaign banner placed. Default, index root only, options for pages and single article view.

**Additional context**

Screenshot of example campaign banner on index page

<img width="1623" alt="Screenshot 2020-09-14 at 09 05 44" src="https://user-images.githubusercontent.com/12694270/93060100-9204ab80-f669-11ea-9d90-3a83681b2b71.png">

**Comment by cmgorton** [comment]
Hey Lee! I think this would be a pretty interesting conversation to have on Forem.dev so that we could all talk about the trade-offs, complexities, and user experience behind this. Since this has been open for awhile without much progress would you be interested in kicking off a conversation on Forem.dev? Thanks!
