### ISSUE TITLE
A Gallery for Badges

### ISSUE THREAD

**Issue by leewynne** [forem/forem#10318]
A great way of helping a new Forem grow would be to provide access to a creative gallery for Badge creation for the basics like:

* first comment
* first article
* first year
* second year
* third year

And then to provide examples from other Forems where badges are being used, to aid in creativity.

Badges are really important and a new Forem admin should be encouraged to get started with them as soon as possible.

**Describe the solution you'd like**

An external gallery from Github that allows a Forem admin to browse an market place for Badge creation that encourages creation and consumption

**Comment by cmgorton** [comment]
Hey Lee! I think this would be a pretty interesting conversation to have on Forem.dev so that we could all talk about the trade-offs, complexities, and user experience behind this. Since this has been open for awhile without much progress would you be interested in kicking off a conversation on Forem.dev? Thanks!
