### ISSUE TITLE
Create Gallery for Campaigns and Footers

### ISSUE THREAD

**Issue by leewynne** [forem/forem#10317]
As new Forems come online I think it would be a really useful feature to provide access to an open gallery of campaigns in the form of banners and footers. 

**Describe the solution you'd like**

Maybe the gallery is hosted outside of Forem or Github, just a simple browser and select, replace the image and text, and then an option to copy the code. A market place that encourages creation and consumption

**Describe alternatives you've considered**

None as of yet!

**Comment by cmgorton** [comment]
Hey Lee! I think this would be a pretty interesting conversation to have on Forem.dev so that we could all talk about the trade-offs, complexities, and user experience behind this. Since this has been open for awhile without much progress would you be interested in kicking off a conversation on Forem.dev? Thanks!
