### ISSUE TITLE
I cant write a post

### ISSUE THREAD

**Issue by johngrueto** [forem/forem#10328]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by fdoxyz** [comment]
Hi @johngrueto thank you for reaching out with the bug report. Can you please share more information by filling out the prompts? (Describe the bug,  To Reproduce,  Expected behavior, Screenshots, etc..) 

This way we can understand what can be causing the issue. Can you also please share your DEV username as well so we can verify it's not a problem specific to your account? Thanks.

**Comment by citizen428** [comment]
Hello @username, thanks for notifying us of this problem, this looks an issue specific to your account.
Please email yo@dev.to for more help.

**Comment by johngrueto** [comment]
@johnholder
