### ISSUE TITLE
Auto dark mode in app

### ISSUE THREAD

**Issue by mityaua** [forem/forem#10404]
Hi Devs! What about auto dark mode in your app (android)? 
This will be very convenient, because a lot of users have to switch manually every evening and morning.

![Auto dark mode](https://i.ibb.co/Xjr7zd8/photo-2020-09-21-17-42-46.jpg)

**Comment by ludwiczakpawel** [comment]
Hey, this will definitely come, sooner or later! We still have to do some other frontend-infra related things to make it smooth process. The idea is to have default theme with light and dark skin. Appropriate skin will be used based on system preferences but it could be overwritten by user settings as well.

I'm removing label `area: for Android` since this is more global thing. I also let myself rename this issue to reflect that.

**Comment by Link2Twenty** [comment]
We'd use [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) I guess. It has good support but is still in `Editor's Draft`.

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
