### ISSUE TITLE
Squash migrations

### ISSUE THREAD

**Issue by abenettt** [forem/forem#10465]
**Is your feature request related to a problem? Please describe.**
At this time the migrations count 541 and take, at least on my machine, ~12 seconds. 

**Describe the solution you'd like**
I don't know, whether there is a tool for that available, but maybe it is possible to squash all existing migrations together into a single one, this should hopefully reduce the amount of time the migrations take to run, which would also improve the deployment process, be it production or development. 

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
FYI: I know of https://github.com/jalkoby/squasher but I've never used it

**Comment by abenettt** [comment]
I tried this locally and there I could squash the migrations, they at least run without failing.

**Comment by krzysiek1507** [comment]
I used `squasher` for squashing 200 migrations and it worked w/o issues. There is one thing though. Migrations that change data and those with raw SQL cannot be squashed in a project like this because they might be required for the data integrity.

**Comment by krzysiek1507** [comment]
I can take care of it.

**Comment by rhymes** [comment]
Hi @krzysiek1507, thanks for the offer, we have not yet had a discussion about this. As it's a non approved feature request I'd suggest waiting before we circle back on this type of optimization, also in the context of the wider Forem universe

**Comment by mstruve** [comment]
I have squashed migrations in the past and it was great for saving time when creating new environments. However, given [Rails recent additions of db:prepare](https://github.com/rails/rails/blob/98754de1412870d7dae9eba1c7bac944b9b90093/activerecord/lib/active_record/railties/databases.rake#L298) which ensures schema is loaded for a fresh database rather than migrate, I think this is likely something we can forego.

I also find it interesting that [Rails docs themselves mention the ability to remove old migrations](https://edgeguides.rubyonrails.org/active_record_migrations.html#old-migrations) rather than suggesting squashing them. This would make me lean towards removing them if we wanted to do anything since that seems more of a Rails way and Rails has been built with that in mind. 

@citizen428 what are your thoughts here?

Also @abenettt could you describe what steps you are executing that causes all the migrations to run? If your database if not present Rails should create it and load the schema rather than running the migrations.

**Comment by krzysiek1507** [comment]
If we remove the migrations, [`bin/rails db:prepare`](https://github.com/forem/forem/blob/70725665acecfbd53c7812642f102d775de53da3/lib/tasks/app_initializer.rake#L8) on a new installation won't work because it calls `bin/rails db:migrate` which fails if migrations are corrupt, e.g. a migration tries to add a column to a nonexistent table.

If we wanted to remove the migrations, we would need to remove all of them at once, then update the setup task to load schema + migrations (since after the removal of the migrations, we will add new ones).

Downsides: that would be painful for everybody. If somebody wanted to update their instance to master, they would just fail. At first they would need to update their application to the commit before one that removes the migrations, and then make another deploy to master.

I think it would be better to squash migrations from 2015-2018 into one file (the timestamp would be one from the last migration in 2018). After a few months squash 2019, and in Q3 2021 squash 2020. That would give everybody time to update their instances without a headache.

**Comment by abenettt** [comment]
@mstruve I setup the project anew, installed squasher globally and ran it for all existing migration files, I then had to manually edit thes generated migration to first disable constraint validation and then create a second migration in which I enabled constriant validation again, otherwise `strong_migrations` would have complained. After this I ran the migrations with `bin/rails db:migrate`.

**Comment by mstruve** [comment]
@krzysiek1507 I don't think at this point we should remove any of the migrations, I only brought that up bc it seems like Rails is more built for removing them than squashing them which makes me lean towards not squashing them. 

> At this time the migrations count 541 and take, at least on my machine, ~12 seconds.

@abenettt what I want to know is the situation that led you to run all of the migrations when setting up the application. I talking about setting it up without squasher or anything. I just want to know what your workflow was for setting up the app that caused all the migrations to run. If you are setting up a new app and fresh database, the migrations shouldn't run since Rails should create the database schema from the schema file which is why I am curious as to what caused that not to happen.

**Comment by citizen428** [comment]
> If we remove the migrations, `bin/rails db:prepare `on a new installation won't work because it calls `bin/rails db:migrate` 

@krzysiek1507 It only runs migrations when a DB exists but doesn't have an up to date schema, which would e.g. happen if you run `db:create`. The task description also mentions this:

> Runs setup if database does not exist, or runs migrations if it does. 

I regularly run `rails db:drop` followed by `bin/setup` (which calls `db:prepare`) and it always recreates the database. It works because of the following snippet from the task (annotated):

```ruby
      ActiveRecord::Base.establish_connection(db_config)

      # Skipped when no database
      ActiveRecord::Tasks::DatabaseTasks.migrate
      # @citizen428: this raises ActiveRecord::NoDatabaseError when trying to migrate on a new app

    rescue ActiveRecord::NoDatabaseError
      #  @citizen428: here the schema gets loaded instead
```

```
$ rm -rf db/migrate/* && rails db:drop && rails db:prepare

2020-11-09 09:59:41 +0700: HEAD http://localhost:9200/chat_channel_memberships_development [status:404, request:0.032s, query:N/A]
[ES output snipped]
Dropped database 'PracticalDeveloper_development'
Dropped database 'PracticalDeveloper_test'
Created database 'PracticalDeveloper_development'
Created database 'PracticalDeveloper_test'
Seeding with multiplication factor: 1

  1. Creating Organizations.
  [seeding snipped]
```

**Comment by citizen428** [comment]
> @citizen428 what are your thoughts here?

@mstruve I'm quite indifferent. I used Squasher on 1 or 2 projects in the past, but I generally don't bother anymore. If they start to annoy me I'd probably just delete them.

**Comment by abenettt** [comment]
@mstruve Oh yeah sorry. I think after I've followed the setup guide in the documentation, I deleted the tables again and ran `bin/rails db:migrate`.

**Comment by mstruve** [comment]
Ah, thanks for the clarification @abenettt. Next time if you want to reset your data definitely would recommend drop and prepare or `db:reset` is what I often use. 

Since the feeling here is mostly indifference and I think it kinda goes against the way Rails has setup database management to work I am going to close this issue. Thanks so much for suggesting it though and being apart of the Forem community!
