### ISSUE TITLE
Publishing to DEV from RSS Does Not Bring Stories into Drafts

### ISSUE THREAD

**Issue by TephlonDude** [forem/forem#10477]
**Describe the bug**
I am attempting to publish to DEV.TO using RSS from Medium. I followed the instructions and set up everything as instructed [here](https://dev.to/settings/publishing-from-rss) and clicked on the Save button.

My expectation was that the article from [here](https://medium.com/n8n-io/nathan-your-n8n-virtual-assistant-98ac611ee7a7) would appear in my Dashboard but I do not see any drafts from the RSS feed.

**To Reproduce**
I don't know if this is reproducible as it appears to only happen to my account

**Expected behavior**
I expected that my stories from Medium would appear as drafts in my DEV.TO dashboard.

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version: 85.0.4183.121 (Official Build) (64-bit)

**Comment by Zhao-Andy** [comment]
Hey @TephlonDude, sorry about that bug. I think it's an issue specific to your Medium article and how it was parsed either on our end, or how the data pulled in on Medium's end. The short version is I've made a draft post under your account for you. You'll want to make sure the formatting of the post is correct, and to add a `canonical_url` (not sure why that wasn't pulled in either).

The longer version is that this specific section in your post was pulled in like this, with the `{{#node...}}` not in a codeblock:
> ```
> Here is what Louis emailed you:
> 
> ```
> 
> {{$node[“Merge Excuse and Mail Data”].json[“textPlain”]}}
> 
> ```
> 
> Here is how “you” responded:
> 
> \> {{$node[“Merge Excuse and Mail Data”].json[“excuse”]}}
> 
> :+1: \*You’re Welcome!\* :smirk:
> ```

I manually updated it to look like this instead:
>
>Here is what Louis emailed you:
> ```
> {{$node[“Merge Excuse and Mail Data”].json[“textPlain”]}}
> ```
>
> Here is how “you” responded:
> 
> ```
> \> {{$node[“Merge Excuse and Mail Data”].json[“excuse”]}}
> ```
> :+1: \*You’re Welcome!\* :smirk:

Closing this issue since it seems to be a one off case, specific to the issue of using `{{` outside of a codeblock -- which we prevent for security reasons.
