### ISSUE TITLE
Missing Stats button for the article I wrote

### ISSUE THREAD

**Issue by lucieva** [forem/forem#10496]
Hi folks, I have written an article on dev.to and I would love to see more statistics about that. Unfortunately I do not see "Stats" button on top of the article, next to the Edit and Manage buttons. Is it possible to enable this feature for me? Thanks a lot, Lucie

**Comment by rhymes** [comment]
Hi @lucieva, we don't have stats available right now other than what you can see in the [dashboard](https://dev.to/dashboard), an example from one of my articles:

![Screenshot_2020-09-30 Dashboard - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/94696764-b3d38300-0337-11eb-8a56-7d47438a76c7.png)

Is that what you're looking for?

I think this request is also part of https://github.com/forem/forem/issues/6608, does that sound correct to you?

**Comment by cmgorton** [comment]
Hey @lucieva I think this issue is resolved with the context Rhymes mentioned above. The stats we show are found in your dashboard. If that isn't what you were hoping for I think we can leave more context in issue #6608. I am going to go a head and close this issue. Thanks for writing this feature request. Please feel free to leave any comments/requests on issue #6608.
