### ISSUE TITLE
Add left sidebar to Series on user dashboard

### ISSUE THREAD

**Issue by eusonlito** [forem/forem#10718]
**Is your feature request related to a problem? Please describe.**

The `Series` section on users dashboard is the unique option without the common dashboard layout and sidebar.

**Describe the solution you'd like**

Use same layout as other dashboard sections, adding the left sidebar and content.

**Additional context**

Section with content

![Screenshot from 2020-10-07 17-10-48](https://user-images.githubusercontent.com/644551/95350490-813e0300-08c0-11eb-820d-4f03310c49bd.png)

Section without content

![Screenshot from 2020-10-07 17-10-29](https://user-images.githubusercontent.com/644551/95350514-87cc7a80-08c0-11eb-9f3e-8c0f7509ed4a.png)

Series

![Screenshot from 2020-10-07 17-10-18](https://user-images.githubusercontent.com/644551/95350542-8e5af200-08c0-11eb-8613-69cc775455c2.png)

**Comment by eusonlito** [comment]
mmm, all sidebar links are `/dashboard/XXXX` but series link is `/lito/series`.

**Comment by rhymes** [comment]
Hi @eusonlito, this is because `/dashboard/{resource}` is private to the user (and that's where the managing part of series should lie) and `/rhymes/series` is public, even to non authenticated users.

So:

- https://dev.to/rhymes/series should list my series with at least one article in them
- https://dev.to/dashboard/series should be the place where I go manage the series collections

I think this will be addressed by https://github.com/forem/forem/issues/9008

Let us know @eusonlito if this satisfies your enquiry

**Comment by eusonlito** [comment]
Yes, I think that all dashboard sidebar options must be private and relative to `/dashboard`. Currently when you click in `Series` you lost your dashboard panel and you need to go again to Avatar > Dashboard.

I think that integrate series into a new `/dashboard/series` panel is not complicated, no?

**Comment by rhymes** [comment]
@eusonlito managing series in the dashboard is another feature that will be addressed by #9008 - the link will be fixed when that's addressed

**Comment by eusonlito** [comment]
Perfect!
