### ISSUE TITLE
Ability to upload multiple videos at once.

### ISSUE THREAD

**Issue by MishManners** [forem/forem#10727]
**Is your feature request related to a problem? Please describe.**

Currently, when uploading videos to Dev.to, you can only upload one video at a time. Not only that, you must wait until the video has uploaded AND transcoded before uploading another. If you do not, then the multiple videos you uploaded will be all smooshed together. Meaning you have to delete them all and start again.

Currently, have to wait a significant amount of time between uploads. The transcoding screen also does not automatically update, meaning you have to wait for the notification email to tell you the video is transcoded. If you refresh, the video is also lost.

**Describe the solution you'd like**

Ability to upload multiple videos at once and have them go into their own "draft" formats.

**Describe alternatives you've considered**

Thought... not discovered.

**Additional context**

**Comment by cmgorton** [comment]
Hey! Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
