### ISSUE TITLE
support RSS feed discovery from articles and profile pages

### ISSUE THREAD

**Issue by chdsbd** [forem/forem#10723]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to subscribe to a user's posts via RSS by pasting their article url or profile url into my feed reader.

**Describe the solution you'd like**

Add `<link rel="alternate" type="application/rss+xml"  href="/feed/<username>" />` tags to articles and user profile pages to support RSS feed discovery.

RSS readers use these tags to discover feeds. I didn't find an official article on this, but this post discusses this feature: https://www.petefreitag.com/item/384.cfm

**Describe alternatives you've considered**

After some searching I found the feed url is `dev.to/feed/<username>`. A link to this URL on the profile page would be useful too.

**Additional context**

**Comment by query-string** [comment]
Hello there! I'd love to work on this one please :)

**Comment by rhymes** [comment]
Assigned to you @query-string, thanks!

**Comment by cmgorton** [comment]
Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
