### ISSUE TITLE
Listings page functionality is broken

### ISSUE THREAD

**Issue by VladimirMikulic** [forem/forem#10937]
A page for managing listing is completely broken :(
I can't edit/delete my listings. When I click edit/delete buttons
nothing happens except some network requests which fail.

https://dev.to/listings/dashboard

**Screenshots**

![error](https://user-images.githubusercontent.com/35997844/96502944-cf54ee00-1252-11eb-8e7a-5cb29923cb42.jpg)

**Desktop (please complete the following information):**

- OS, version: Kubuntu 20.04
- Browser, version: Chrome 86

Thanks.

**Comment by fdoxyz** [comment]
It looks like in order to edit the Listing you have to click on the Listing's name. 

Clicking the available buttons (View draft, Edit & Delete) doesn't work. A network call isn't even called so I'm thinking the problem may be in the HTML/CSS or JS that's supposed to make this calls work.

I haven't tried it yet but maybe swapping out these `<buttons>` and use anchor tags with Crayons classes would fix this.

**Comment by Danondso** [comment]
If no ones taken this I wouldn't mind taking a crack at it.

**Comment by citizen428** [comment]
Thanks for volunteering @Danondso, I assigned you the issue.

**Comment by Danondso** [comment]
Thanks!

**Comment by cmgorton** [comment]
Hey @Danondso 
Thank you so much for jumping on this issue! Since this issue has not been active for awhile I wanted to see if this was something you still wanted to work on.
No worries if you don't have the time right now! We can unassign you from this issue so that we can get more visibility on it from others in the community.

**Comment by Danondso** [comment]
Hey @cmgorton! Go ahead and un-assign me, working on this totally got away from me.

**Comment by cmgorton** [comment]
No problem! Thanks for your willingness. If you ever want to hop on another issue/pr just let us know. 😄

**Comment by cmgorton** [comment]
> Hey @cmgorton! Go ahead and un-assign me, working on this totally got away from me.

No problem! Thanks for your willingness. If you ever want to hop on another issue/pr just let us know. 😄
