### ISSUE TITLE
Listings should have impressions statistics

### ISSUE THREAD

**Issue by trashhalo** [forem/forem#10993]
**Is your feature request related to a problem? Please describe.**

I discovered the listing feature today and made a fun listing. https://dev.to/listings/misc/remember-to-get-up-and-stretch-your-legs-4j6c

Thinking bout the ux of the pages involved I think if I actually wanted to run real ads on this platform I would need to know how much visibility my "ad" was getting. This is a really common feature ad platforms like pinterst/twitter/reddit provide for you to measure effectiveness of your advertising.

**Describe the solution you'd like**

https://dev.to/listings/dashboard on this page a number on the listing of the number of impressions your listing has had.

**Comment by cmgorton** [comment]
Hey! Thank you for opening this request. I definitely think it is an interesting idea. 
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
