### ISSUE TITLE
Ability to insert to date / time in article that gets converted to users timezone 

### ISSUE THREAD

**Issue by Rafi993** [forem/forem#11002]
**Is your feature request related to a problem? Please describe.**

It would awesome if you could insert date / time in article that shows in users timezone. This would be useful for users in different timezone especially for events. This could be achieved using a date time liquid tag or some formatting option.

**Describe the solution you'd like**

We could use liquid tag or some formatting option to show date / time in users timezone

**Additional context**

1. Go to article with date / time example https://dev.to/thisdotmedia/react-meetup-online-february-13th-15-30-pm-est-1ejp
2. The article shows time in EST both in title and content
3. But for users in different timezone like they have to manually see what that time corresponds to
4. But if there was a way to insert date / time that showed in users time zone it would awesome

**Comment by citizen428** [comment]
Thanks for the issue @Rafi993. Note that I tagged this as a feature request, I think you might have gotten the wrong issue template here.

**Comment by Rafi993** [comment]
Thank you @citizen428.  Sorry I just realised that have created it as a bug instead of feature. I'll change the description.

**Comment by cmgorton** [comment]
Hey! Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏

**Comment by Rafi993** [comment]
Thank you @cmgorton I have created post in forem.dev https://forem.dev/rafi993/ability-to-insert-to-date-time-in-article-that-gets-converted-to-users-timezone-dk2 about this feature so that the discussion can happen there.

**Comment by cmgorton** [comment]
> Thank you @cmgorton I have created post in forem.dev https://forem.dev/rafi993/ability-to-insert-to-date-time-in-article-that-gets-converted-to-users-timezone-dk2 about this feature so that the discussion can happen there.

Awesome. Thank you Rafi!
