### ISSUE TITLE
UX: Reading list on mobile puts tags before items

### ISSUE THREAD

**Issue by Link2Twenty** [forem/forem#11033]
**Describe the bug**

When viewing the reading list on a mobile device followed tags are listed first, pushing posts below the 'fold', but I'd bet people would rather get to their posts faster

**To Reproduce**

1. Go to https://dev.to/readinglist on a mobile device
2. See tag list

**Expected behavior**

1. Make selecting possible for only one tag
2. Collapse nav into the `select` on mobile breakpoint.

**Screenshots**

This image is pixel 2 width but I've included the whole page.
![image](https://user-images.githubusercontent.com/3534427/96972367-5681ba80-150e-11eb-85c7-0b3717848939.png)

**Additional context**

This is a UI/UX question so ping @lisasy @ludwiczakpawel

**Comment by ludwiczakpawel** [comment]
Yeap, something we definitely have to work on. The thing is, usually we just take left sidebar navigation and collapse it to `<select>` field on mobile breakpoints (see `/settings` for example) and that's pretty standard pattern. But since in Reading List you can basically select multiple tags in left navigation, the `<select>` field will no longer make sense here.. Ideally we'd take the nav and turn it into some fullscreen overlay trigger by clicking the button "Filters" or something.

**Comment by lisasy** [comment]
@ludwiczakpawel 

Do you think that there might be 2 changes we make here? Assuming that multiple select is *not* the experience we stick with, we can do this:

1. Make selecting possible for only one tag
2. Collapse nav into the `select` on mobile. 

If single-select is the direction we go, we can totally break this task up into 2 separate ones and have contributors help us out with #1.

**Comment by ludwiczakpawel** [comment]
Yea, I think that makes sense. Just make sure there's no historical evidence of that multiselect being added for a particular reason so we don't break some important flow.  I'm pretty sure @benhalpern may know.

Then, if we drop it, this entire thing may need refactoring because the tags in left sidebar are not actually links (the URL in browsers doesn't really change when you click the tag.. it's basically all JS). That would also be needed for `select` to work properly on mobile I think.

**Comment by lisasy** [comment]
@ludwiczakpawel I'm going to revise the description of this bug report in "Expected behavior" with the 2 steps so that whoever can pick it up and implement it in this way. 👍
