### ISSUE TITLE
Incorporate create an organization into new user onboarding flow

### ISSUE THREAD

**Issue by AdekunleA** [forem/forem#11119]
**Is your feature request related to a problem? Please describe.**

It's a bit tedious connecting with new users on our forem community - Cluster Employment, and having to walk them through creating an organization profile on the platform (creating an organization profile is important to our community). 

'
**Describe the solution you'd like**

Incorporating the organization creation form into one of the steps during the new user onboarding process on the platform. This will inform new users of the need to create organization profiles and also give them the ability to create the organization profile as soon as they're signed up on the platform.

**Describe alternatives you've considered**

Having create an organization profile on the onboarding task card. While this is not our optimal solution, it will go a substantial way in making the onboarding process easier for new users on the platform.

**Additional context**

**Screenshot for the first solution:**

![onboarding1](https://user-images.githubusercontent.com/32549192/97314888-e6916e00-1846-11eb-8817-21ac9b0bdff2.png)
 
Create an organization form during this process

**Screenshot for the alternate solution:**

![91216724-ce895b00-e6ec-11ea-9893-78f739d05318](https://user-images.githubusercontent.com/32549192/97315564-9c5cbc80-1847-11eb-8e4a-c4b60b23da95.png)

**Comment by AdekunleA** [comment]
Just thought I'd revive this feature request :D

**Comment by cmgorton** [comment]
Thank you for opening this request!
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
