### ISSUE TITLE
Add trigger warnings / content notes to posts and users

### ISSUE THREAD

**Issue by abenerd** [forem/forem#11159]
**Is your feature request related to a problem? Please describe.**
With more specialized, or even more generalized forems, posts that are written might end up containing triggering content. 

**Describe the solution you'd like**
Allow posts to specify whether they contain possible triggers and if so, what those triggers are. When users open a post they can be warned about the triggers, or when they have an account, they can specify triggers that are filtered out of their feed so that the posts don't even show up.

**Describe alternatives you've considered**

**Additional context**

**Comment by abenettt** [comment]
The most trivial implementation I can think of is to use a `trigger` table, that contains the trigger and maybe a description of what this trigger is and then using a pivot table to indicate which post contains what trigger. Although this might work, I think this is a little too trivial, it would require the forem team to maintain the list of triggers and it might also add complications when using internationalization. Maybe there is a third party api where one can fetch triggers and their descriptions, but this would add another third-party dependency and would not allow consistency in the database. 
Another way might be using the first trivial approach and have the community maintain it, this way new triggers could be added easily and updated but this also begs the question of how to prevent abuse and how to sync the new and updated triggers with other forems.

**Comment by cmgorton** [comment]
Thank you for opening this request!
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
