### ISSUE TITLE
Filter Posts/Feed according to gender

### ISSUE THREAD

**Issue by Maybach91** [forem/forem#11167]
**Describe the solution you'd like**

A button to filter the posts by gender of the author. 

**Additional context**

I’m trying to shift my own "bubble" from the mainly male dominated tech world to a more diverse one. I know dev.to is a good source for diverse people, buts till the feed is very male driven. I just want to know how certain things are seen, understanded and explained by non-cis people.

**Comment by cmgorton** [comment]
Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
