### ISSUE TITLE
Support Starboard.gg notebook embeds (liquid tags)

### ISSUE THREAD

**Issue by gzuidhof** [forem/forem#11232]
**Describe the solution you'd like**

`{% starboard https://gz.starboard.host/v1/embed/0.6.2/br0qtd223akg00eiaos0/noNeOQB/ %}`

This is the embed URL that can be retrieved from the `Share or Embed` button at the top of a Starboard notebook. Here's the [link to the above example notebook](https://starboard.gg/nb/noNeOQB).

Starboard is an [open source](https://github.com/gzuidhof/starboard-notebook) system for fully in-browser notebooks. This makes it different from solutions like codesandbox and repl.it, you don't have to wait for a machine to boot up - everything runs in the browser (it even supports Python through Pyodide, so you can have interactive Python examples in your post, or interactive visualizations :))

**Additional context**
All it should take is an iframe, it looks nicer with `frameborder="0"`, example:
```html
<iframe src="https://gz.starboard.host/v1/embed/0.6.2/br0qtd223akg00eiaos0/noNeOQB/" frameborder="0"></iframe>
```

The width should be the full width, and for the height.. pick some reasonable value (or perhaps it can be configurable?).

**Comment by gzuidhof** [comment]
I would like to pick up this issue, but I'd like to have the proposal approved before I start on the implementation, is there something I can do?

**Comment by fdoxyz** [comment]
Hello @gzuidhof , thank you for the proposal and also volunteering to work on it.

At the moment we're prioritizing non-DEV related liquid tags to better support the broader Forem ecosystem. That's why we haven't approved or moved forward with this one and other liquid tag proposals.

I'm confident we'll review the liquid tag feature requests in the future but we can't give a timeline for it right now. I can encourage you to check back in another time if we still haven't moved forward or given a more definite response on the topic.

Thank you for your interest in contributing to the project!

**Comment by gzuidhof** [comment]
Makes sense, thank you for taking the time to reply! I'll keep an eye on this issue for updates :)

**Comment by cmgorton** [comment]
Thank you for opening this request.
Like Fernando mentioned we are currently prioritizing non-DEV related liquid tags to better support the broader Forem ecosystem. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
