### ISSUE TITLE
Move Forem Docs into Their Own Repository 

### ISSUE THREAD

**Issue by mstruve** [forem/forem#11285]
The Forem repo has grown considerably over the last year and a large chunk of the repo is our documentation. While it is convenient to have the docs and code all in one place it also comes with some downsides. 
* If you change the documentation you have to wait for a full CI spec run to complete before you can merge the change
* Any documentation change when merged triggers a deploy. This certainly does not hurt anything, but it also isn't ideal. 
* When our deploy process to Netlify breaks it blocks our ability to merge code changes which might have no documentation changes.
* ~Our repository slug size is nearing the limit for Heroku. While ideally, we won't be on Heroku forever, this is something that could affect us in the near term while we are.~ I believe we exclude these from the slug  

Having documentation in its own repository could really streamline the process of making changes to it and would really lower the barrier for contributors wanting to make changes. They would no longer need to worry about pulling down the entire application, instead, they would only have to pull down and focus on the docs.

**Comment by rhymes** [comment]
The downside of this is that it could make keeping the documentation in sync a little bit harder, especially for third party contributors. I'm not sure eh, it might make it easier to build a completely separate community around docs.

I think this sits in a wider discussion about separating what's documentation about using Forem and documentating about installing Forem. Installation and setup docs in my opinion should remain inside the repo. Docs for Forem admins could stay in a different repository.

Regarding size: the docs folder is 716Kb, I don't think it impacts much the slug size:

```shell
 ➜  forem git:(master) du -chs docs
716K	docs
```

The reason why it appears to be big locally it's because we tend to have had compiled it at least once, which balloons it to 20 megabyte or so. Is this compiled inside the slug as well? Since we deploy the docs on Netlify, we don't necessarily need to generate Ruby and API docs on Heroku

**Comment by mstruve** [comment]
Oops, [we actually ignore the docs for the Heroku slug](https://github.com/forem/forem/pull/10067/files), I forgot I did that. I updated the description

**Comment by Zhao-Andy** [comment]
Don't have an opinion (yet) of whether it should be moved to a separate repo or not, but if we did move it, it wouldn't be too hard. There are three parts to our docs:
- docs.forem.com, static site generated by GitDocs
- docs.forem.com/api, documentation about how to use our API, auto generated by ReDoc
- docs.forem.com/ruby-doc, Ruby documentation on our code, auto generated by (??? I forget)

All of it is hosted on Netlify, and we run a custom `make` command for all three parts. It _should_ be as simple as extracting the code out into a repo, and rehosting on Netlify.

**Comment by mstruve** [comment]
One example of a project that has separated their docs and code is VSCode 
Code: https://github.com/Microsoft/vscode
Docs: https://github.com/microsoft/vscode-docs

Another plus to separating out the docs is that I think it would save developers a bit of time since we could hand off some doc change reviews in the doc repo to someone like @cmgorton or even @michael-tharrington, people who are closer to the end-user and can likely have a better take on what is clear.

**Comment by cmgorton** [comment]
> Another plus to separating out the docs is that I think it would save developers a bit of time since we could hand off some doc change reviews in the doc repo to someone like @cmgorton or even @michael-tharrington, people who are closer to the end-user and can likely have a better take on what is clear.

Yep! I would be happy to help here. :)

**Comment by vaidehijoshi** [comment]
We had a separate "docs engine" at my previous role at Skylight, and in some ways, I think it worked well and in other ways, it was a pain.

In my experience, the pros of this were:
- updating the docs was a separate task and could be done by anyone
- our codebase had a bundled version of the most recent version of the docs gem
- hosting relevant gifs/screenshots/feature content did not clutter up the _actual_ repo code

The downside, however, included:
- developers having to make a bunch of separate changes to the docs gem/repo whenever a something was released or something changed
- a clunky "docs release" process since the gem had to be tagged and released and then the actual repo code had to point to the latest version

There are some major differences in our workflow, though.
1) As our codebase grows, it won't be just developers who will update the docs, most likely.
2) We _mostly_ churn out code changes that actually _not_ documentation heavy (at least, right now).
3) We are going to have two product/platform repos to maintain in the foreseeable future: `forem` and `forem-app`.

Keeping all that in mind, I would say that I lean towards putting those docs into a separate repo makes sense. But we should keep those other possible pain points in mind.

**Comment by mstruve** [comment]
Given our roadmap and the goal we want to accomplish this year of dramatically increasing healthy Forems, I don't think this really helps us accomplish that and at this point would only introduce more systematic workflow change which we already have enough of at this point. 

I am going to close this for now and we can always revisit in the future when docs actually become a pain point.
