### ISSUE TITLE
Oauth2.0 API

### ISSUE THREAD

**Issue by zctocm** [forem/forem#11292]
**Is your feature request related to a problem? Please describe.**
Oauth2.0 API

**Describe the solution you'd like**

I found that 'OAuth2 authentication is still in [private alpha](https://docs.dev.to/api/#section/Authentication)' in your API doc. So I want to know about the latest progress of this API.

Do the oauth2.0 works? I want to make a tool that can help someone to publish the article to dev.to. So, I want to use the oauth2.0 API.

**Describe alternatives you've considered**

**Additional context**
A few months ago, I sent an email to yo@dev.to and ben, but no reply

**Comment by benhalpern** [comment]
> A few months ago, I sent an email to yo@dev.to and ben, but no reply

Sorry about that, but thanks for bringing it up here.

This is something we could bring out of beta, the underlying stuff all works fine. We originally rolled it out for one key feature to let folks generate static sites from their DEV posts in a way that ensured we wouldn't the the all-consuming center of the universe....

But since that initial proof of concept was our main motivation, we haven't expanded this much. We use the doorkeeper gem and all the functionality we need is there in place, so I think we could expand this as long as we do it piece by piece, ensuring security and compatibility as we go.

**Comment by zctocm** [comment]
> > A few months ago, I sent an email to [yo@dev.to](mailto:yo@dev.to) and ben, but no reply
> 
> Sorry about that, but thanks for bringing it up here.
> 
> This is something we could bring out of beta, the underlying stuff all works fine. We originally rolled it out for one key feature to let folks generate static sites from their DEV posts in a way that ensured we wouldn't the the all-consuming center of the universe....
> 
> But since that initial proof of concept was our main motivation, we haven't expanded this much. We use the doorkeeper gem and all the functionality we need is there in place, so I think we could expand this as long as we do it piece by piece, ensuring security and compatibility as we go.

Thanks for your reply, ben. Looking forward to new version including the Oauth2.0.
