### ISSUE TITLE
Open profile picture

### ISSUE THREAD

**Issue by Franqsanz** [forem/forem#11306]
**Describe the solution you'd like**
Hi, I was wondering if you could open the profile image by clicking on it, to see it larger.

**Comment by Link2Twenty** [comment]
Very loosely connected with #413

**Comment by cmgorton** [comment]
Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
