### ISSUE TITLE
Settings - Profile: Weird styling for logo button

### ISSUE THREAD

**Issue by harshhhdev** [forem/forem#11349]
*Is your feature request related to a problem? Please describe.*

Not really. It just doesn't fit with the overall look of dev.to

*Describe the solution you'd like*

Add some basic styling, to make it blend in more. Add different styles for each of the themes offered aswell.

*Describe alternatives you've considered*

Just add one style (something is better than nothing), which is very basic, and gets rid of the default look.

**Comment by ludwiczakpawel** [comment]
Hey can you provide some screenshots and elaborate a bit more what's the actual issue here so we can better understand what are you referring to?

**Comment by harshhhdev** [comment]
Yep, sure, sorry for not providing them before.

![image](https://user-images.githubusercontent.com/69592270/98677586-341fd780-232b-11eb-94cb-b8559e7c8703.png)

When I go into my settings, there is a "upload file" button you can see (which sticks out like a sour thumb due to the lack of styling on it)

**Comment by ludwiczakpawel** [comment]
Oh, I see. So this is actually an `<input type="file">` button - it's not like a classic button even though it initially looks like one...

Unfortunately, it's always a bit tricky to style this type of input and to make it bulletproof. Taking that into consideration as well as "popularity" of this view (in other words, how often users see it) I think the solution for this will not be worth the effort put to make it work.

I also want to point out we have some designs "in progress" that will likely _readjust_ some of these form fields.  Here's an example: 

![image](https://user-images.githubusercontent.com/108287/98682872-b4aefa00-2364-11eb-9a32-228f7dd499ea.png)

So we're aiming to make this thing looks a bit more friendly but it's still a quite far on our roadmap. And that makes it even less sensible to implement extra styling for that input since it will be gone at some point anyway...

**Comment by ludwiczakpawel** [comment]
I'm closing the issue but leaving the conversation open if there's anything we need to clarify or discuss. Cheers!
