### ISSUE TITLE
Jumping over 2 feed items with keyboard navigation

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#11371]
**Describe the bug**

We've recently introduced keyboard navigation for jumping between feed items with `j` and `k`. But in SOME cases it jumps over 2 cards at once. It's pretty hard for me to determine when exactly that happens and what causes it...

**To Reproduce**

As mentioned above: not sure :D In the video below it started happening after returning back to home page from an article view.

**Screenshots**

Video:  https://d.pr/v/RimTip

**Desktop (please complete the following information):**

- OS, version: macOS X 10.15.7
- Browser, version: Chrome 86.0.42x

**Comment by reobin** [comment]
The feed might have some differences between production and local. I'll check it out today.

**Comment by reobin** [comment]
It happens pretty consistently with these steps:

1. Jump in an article
2. Go back using a mouse a click on the DEV logo

**Notes**:

-  Doesn't happen using the browser's back button (unless you clicked on DEV logo before and going back to that buggy page)
- Doesn't happen using a shortcut to back like `cmd+[`
- Doesn't happen if I tab on the DEV logo and press enter (sometimes twice #11372), so it's something with the mouse hover on links

Like #11372 , it might have something to do with how links are preloaded, but I'm not sure what happens here. I'll go ahead to debug it locally.

**Comment by Link2Twenty** [comment]
Is the keyboard shortcut not unregistering when you navigate away? Just an idea I've not looked into it and probably won't get a change to for a bit

**Comment by reobin** [comment]
@Link2Twenty From what I understand of it (could be wrong), the page content is replaced using `body.replaceChild()`, and the components don't officially unmount. So the shortcuts are not unregistered.

**Comment by reobin** [comment]
Can be tested easily using these:
![Screen Shot 2020-11-13 at 09 21 12](https://user-images.githubusercontent.com/5920450/99081982-9417b780-2591-11eb-9a2c-661c7b365087.png)

Every time one of the links is clicked, the list navigation shortcut skips 1 article more.

**Comment by nickytonline** [comment]
I think this might be a bigger issue with InstantClick and Preact components not unmounting when InstantClick does its thing.

**Comment by reobin** [comment]
That's my take on it as well @nickytonline 

There's some investigation to do with instant clicks and the whole "replacing the body" part.

There are some notes on how React updates components [here](https://reactjs.org/docs/implementation-notes.html#updating-composite-components) if you scroll down a little. Basically, they unmount the component manually before calling `replaceChild`.

Snippet I'm referring to:
```js
// ...

    // If we reached this point, we need to unmount the previously
    // mounted component, mount the new one, and swap their nodes.

    // Find the old node because it will need to be replaced
    var prevNode = prevRenderedComponent.getHostNode();

    // Unmount the old child and mount a new child
    prevRenderedComponent.unmount();
    var nextRenderedComponent = instantiateComponent(nextRenderedElement);
    var nextNode = nextRenderedComponent.mount();

    // Replace the reference to the child
    this.renderedComponent = nextRenderedComponent;

    // Replace the old node with the new one
    // Note: this is renderer-specific code and
    // ideally should live outside of CompositeComponent:
    prevNode.parentNode.replaceChild(nextNode, prevNode);
```

From what I understand, we need to find a way to trigger an `unmount` on the old node like React does, or we could remove the page content div more aggressively (somehow) so that Preact itself triggers an `unmount`.

**Comment by nickytonline** [comment]
I know how to fix it @reobin. I will create an issue and put a PR up for it. We need to explicitly call `unmountComponentAtNode` in an `InstantClick.on('change', () => {})` event, like this. This is something that normally we wouldn't have to do, but because we use InstantClick, it's necessary. It also explains why I saw components repeated in the Preact dev tools.

```jsx
import { h, render } from 'preact';
import { unmountComponentAtNode } from 'preact/compat';
import { Search } from '../Search';
import 'focus-visible';

document.addEventListener('DOMContentLoaded', () => {
  const root = document.getElementById('header-search');

  render(<Search />, root);

  InstantClick.on('change', () => {
    unmountComponentAtNode(root);
  });
});
```
