### ISSUE TITLE
Search Bar for Pinning Github Repo

### ISSUE THREAD

**Issue by shadowtime2000** [forem/forem#11435]
**Is your feature request related to a problem? Please describe.**

With people (like me) who have over 20 repos it can become hard to actually find the repos you want to pin to your profile.

**Describe the solution you'd like**

A search bar above the list so you can search for the repos you want to pin.

**Describe alternatives you've considered**

A searchable dropdown bar (I don't really know how to explain this).

**Comment by cmgorton** [comment]
Hey @shadowtime2000 I talked with product a bit about this feature request. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. Since this one is very DEV specific I am going to go a head and close it here. 
If you feel strongly about this feature please visit [forem.dev](https://forem.dev/) to start a discussion around it.
