### ISSUE TITLE
Allow canonical "welcome" thread to be authored by any admin (or mascot)

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11455]
**Is your feature request related to a problem? Please describe.**
As a Forem Admin, I'd like more flexibility in setting up the canonical "Welcome" thread (that users get redirected to via `/welcome`).  Currently, that thread must be authored by the "Staff User" set in `Admin > Config > Community Content`.

**Describe the solution you'd like**
I'd like the following user "types" to be eligible authors of the thread:
- Any admin (or superadmin)
- The site mascot

**Additional context**
I _believe_ the relevant code is here:
- [`/app/models/article.rb`](https://github.com/forem/forem/blob/master/app/models/article.rb)
- [`/app/controllers/pages_controller.rb`](https://github.com/forem/forem/blob/master/app/controllers/pages_controller.rb)

I'll ensure that the [Admin Documentation](https://forem.gitbook.io/forem-admin-guide/) is improved as well.

**Comment by vaidehijoshi** [comment]
_Cross-posting from [forem.team](https://forem.team/vaidehijoshi/comment/15c) to here to maintain conversational parity:_

Stepping back for a moment, do we know if other Forem creators use the welcome thread currently? And if they do, how they use it?

I've always felt that the daily threads (like the welcome thread) to be DEV-centric, and I wonder what exactly the problem is that we are solving for. Do we want to establish an idea of all Forems having a "welcome" thread and make that a Forem-wide feature? Or do our Forem creators actually need something else to help them do the welcoming?

I do think we need to move away from the strict usage of the staff user <> welcome thread concept, but I want to raise the larger question of these daily thread concepts since they're coming up naturally in conversation.

**Comment by benhalpern** [comment]
Currently the welcome thread is widely used (it sort of has to be because we always have it in the onboarding).

<img width="671" alt="Screen Shot 2020-11-24 at 10 27 10 AM" src="https://user-images.githubusercontent.com/3102842/100114624-9dc9d680-2e3f-11eb-91bf-97e38082375a.png">

Example: https://the.community.club/community-club/welcome-thread-v2-57oj

**Comment by mstruve** [comment]
@pkfrank it looks like the attached PR will solve this issue. It needs to have the specs fixed but otherwise, it should do what you want. If @benhalpern wants to cleanup the specs and push it through that would be great otherwise I can try to take a whack at it later when I am online.
