### ISSUE TITLE
Inital Docker container setup failing

### ISSUE THREAD

**Issue by mrtnrst** [forem/forem#11512]
**Describe the bug**
When running the container setup command as described in the [docs](https://docs.forem.com/installation/containers/#installing-forem-using-containers), `bin/container-setup`, the yaml is failing to validate for Docker and errors causing an exit of the command.

**To Reproduce**
1. In your terminal run the following command:
```sh
bin/container-setup
```

**Expected behavior**
Docker containers are fully built and initial setup completes successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/1743953/99739595-1bd25a00-2a9b-11eb-84e1-bc1f4e66402b.png)

**Desktop (please complete the following information):**

- OS, version: macOS 11.0.1
- Browser, version: n/a

**Smartphone (please complete the following information):**

- Device: n/a
- OS, version: n/a
- Browser, version: n/a

**Additional context**
n/a

**Comment by mrtnrst** [comment]
Following up here, I believe this is a regression from PR #11468. Checking out the branch before that commit I am able to successfully run the command and get setup.

I can open a PR to get this fixed as I believe this line (as well as the `container-compose.yml`):
https://github.com/forem/forem/blob/a07070e8bc6685cc0c01ed810d235a5b5e5a9a13/docker-compose.yml#L4-L5

would have to be updated to:
```yml
build:
  context: .
  target: development
```

I haven't worked in docker files since v1 so someone will have to double check that.

**Comment by YJDoc2** [comment]
@mrtnrst's solution seems to work, as it successfully starts building, but my build seems to be stuck at 
`Step 40/55 : RUN chown "${APP_USER}":"${APP_USER}" -R "${APP_HOME}"` in `building rails service`
I kept this running for about 20 minutes, is it supposed to take that long? Max time for other steps on my machine was about 5-10 minutes maximum.
Platform : Linux Ubuntu 20.10
Using : docker-compose

**Comment by YJDoc2** [comment]
**Update :**
The older version , before the PR #11468  seems to build fine , in decent time.
Some Things I noticed :
* Ruby Sass is end-of-life warning
![ruby sass Eend of life message](https://user-images.githubusercontent.com/54112038/99802476-c4e18900-2b5d-11eb-88d2-2f77f9cc4a39.png)
* A LOT of warning css messages :
![css warning messages](https://user-images.githubusercontent.com/54112038/99802641-0c681500-2b5e-11eb-9f67-e9c74689ea4c.png)
These appear in Step 27 in the old build (Some steps before also emit warning or just info logs in red).

Above Both appear in old as well as new versions of build docker-compose

In new docker-compose, it splits the install of dependencies like curl, git,jemalloc etc. into ~4 steps (Which was done in a single step in old build), and after each dnf install it clears the cache, (Which I think is recommended for small build size), but because of that it also updates the fedora repository update ~4 times, which is about 92MB for single time :
![repo update info](https://user-images.githubusercontent.com/54112038/99803071-c9f30800-2b5e-11eb-9e6e-5ef73ba17fef.png)
This is done ~4 times in new version of build
I'm not sure if it is a bad thing or not, but just noticed it.

**Comment by rhymes** [comment]
Hi @YJDoc2, Rails gets stuck for me too. Thanks for the clues!

The CSS warning messages are likely going to be adressed by https://github.com/forem/forem/pull/11518

**Comment by YJDoc2** [comment]
Also, I'm not sure if it is done for some production reason , but the sleep time for containers seed and sidekiq is 1 second. Rails takes time for setup and initializing db in postgress, so they keep logging messages of rails connection refuses, sleeping for 1 second, and make it really hard to notice error messages like :
![webpacker error](https://user-images.githubusercontent.com/54112038/99805972-48ea3f80-2b63-11eb-914a-1c00e3ec9aa4.png)
And this :
![sidekiq error](https://user-images.githubusercontent.com/54112038/99807688-df1f6500-2b65-11eb-98b9-62e040eb8a25.png)
because screen is filled with messages like
![seed and sidekiq messages](https://user-images.githubusercontent.com/54112038/99806159-96ff4300-2b63-11eb-8c72-e0d25fffda68.png)

Is it possible to increase the timeout, or is it set for 1s for some specific reason? And what might be the reason for sidekiq error?

**Comment by jdoss** [comment]
Please check out #11531 and see if this fixes this problem.

**Comment by YJDoc2** [comment]
@jdoss  I'm getting these two problems :
after pulling all required images , when docker-compose up starts to run :

* Webpacker exiting with status 1 :

![webpacker error](https://user-images.githubusercontent.com/54112038/99874863-0717d280-2c11-11eb-938f-9483f402c811.png)

* bundler exiting with status 5 :

![bundler error](https://user-images.githubusercontent.com/54112038/99874878-31699000-2c11-11eb-985a-53ab181ecaa1.png)

(The exit statement is not in screenshot, as it is after few lines of elastisearch logs)

After these, sidekiq and seed keep waiting for rails app response :

seed_1           | 2020/11/21 10:16:47 Problem with request: Get http://rails:3000: dial tcp 172.19.0.7:3000: connect: connection refused. Sleeping 1s
sidekiq_1        | 2020/11/21 10:16:47 Problem with request: Get http://rails:3000: dial tcp 172.19.0.7:3000: connect: connection refused. Sleeping 1s
.
.
.

**Comment by mrtnrst** [comment]
> Please check out #11531 and see if this fixes this problem.

@jdoss thanks for the quick followup. I'm able to build the application after this change but seeing the same errors as @YJDoc2. For those issues, can we use rbenv in the container to avoid the `sudo`?

**Comment by jdoss** [comment]
@YJDoc2 Pull down https://github.com/forem/forem/pull/11531 and give it a try. It should be all fixed up now.

@mrtnrdl We use system ruby inside the container. Adding rbenv into the mix here isn't going to do much to fix the permissions problems. The real fix was to use `user: root` in the docker-compose.yml file since docker mounts volumes into containers as the root user.

**Comment by YJDoc2** [comment]
Yep, This seems to setup and run everything fine. Thanks @jdoss :smile: 

If anyone is having error that `./scripts/entrypoint-dev.sh not found` when starting containers, try docker-compose rm, and then docker-compose pull --no-parallel (without no parallel it was giving display issues for me) and then docker-compose up ,  which should make everything work.

This also closes first half for the issue #11530 , in that it sets up redis without any error, but he admin login issue is still remaining.

Can anyone confirm if the admin login issue stated at the end of #11530 is due to incorrect setup on my side or some other reason? Thanks!

**Comment by mrtnrst** [comment]
@jdoss if I remove my containers and do a fresh install there are errors from the yarn build. My initial thought was from the removal of the entry point that was above that line for bash.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/1743953/99914885-58d26280-2cce-11eb-8ca2-a0b04bdccf71.png">

**Comment by jdoss** [comment]
> @jdoss if I remove my containers and do a fresh install there are errors from the yarn build. My initial thought was from the removal of the entry point that was above that line for bash.

Repull the PR and see the commit regarding the yarn command in the compose file fixes this issue?

**Comment by mrtnrst** [comment]
@jdoss I think the image it's now pulling from quay is outdated as it's including the older `entrypoint-dev.sh` file again.

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/1743953/100003467-23904800-2d94-11eb-9797-5930766aa0e1.png">

Also, for your last commit on #11531, you forgot to add those same changes to the `docker-compose.yml`  as well.

**Comment by jdoss** [comment]
@mrtnrst I just merged my PR so the new development container will build with the needed entrypoint changes. If the yarn issue still remains or any other problems are present, I can address them in a different PR
