### ISSUE TITLE
Hide the Github account from the DEV profile, if github used as login mechanism

### ISSUE THREAD

**Issue by Arteneko** [forem/forem#11717]
Right now, if you authenticate using Github as OAuth2 provider, your github account will be publicly shown on your dev.to profile page.

As with other social media links, it should be possible to hide it away.

As an example, I mostly only keep my github account to authenticate on dev.to (and would've dropped it a while ago otherwise, but since the only two auth mechanisms are Github and Google OAuth2, I'm forced to keep a github account active for that).

I do not wish to openly display this github account, as it isn't where I work and host my projects.

**Comment by rhymes** [comment]
Agreed, right now for both GitHub and Twitter there's a coupling of purposes: 

- if a user is connected with GitHub/Twitter, we use their username to determine if we should show the icons around the website
- we also use that to determine if a user hasn't loggedin yet as well (instead of using the presence or absence of the proper authentication identity)

I wonder if this would also intersect with the work of profile generalization

**Comment by cmgorton** [comment]
Since this issue has gone stale I am going to close it. If anyone would like to still implement this feature let me know and we can turn this issue into a [discussion](https://github.com/forem/forem/discussions)
