### ISSUE TITLE
Publish/follow a series of articles

### ISSUE THREAD

**Issue by sturzl** [forem/forem#1172]
Many authors are posting series of articles. I would like to see notifications for articles in a series without having to follow everything from that author or the related tags. 

E.g. https://dev.to/shikaan/design-patterns-in-web-development---2-memento-253j

**Comment by Link2Twenty** [comment]
When you talk about manual linking for navigation what do you mean? Do you know the black navigation dots are automatic for every post in a series?

**Comment by Zhao-Andy** [comment]
This makes sense, and is related to #192.

**Comment by sturzl** [comment]
@Link2Twenty I didn't know those existed, they look like they solve the navigation issue for sure!

I updated the issue to just mention the subscription idea

**Comment by sw-yx** [comment]
the black dots dont fulfil long series with visible names like i have here

https://dev.to/swyx/supervised-learning-bayesian-learning-403l#next-in-our-series

**Comment by sw-yx** [comment]
uh oh :(

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](https://github.com/forem/forem#community) for many of these feature requests that we need more discussion around. 

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](https://forem.dev/). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
