### ISSUE TITLE
Fix 404 on "Recent Emails" via /admin/users

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11791]
**Describe the bug**
As a Forem Admin, clicking on a "recent email" via `/admin/users` is leading to a 404.

**To Reproduce**
- Be an admin with sufficient permissions
- Navigate to a user via `/admin/users`
- Click a "recent email" at the bottom of the page
- Hit a 404

**Expected behavior**

Link opens up properly, showing the relevant email

**Additional context**

This is a left-over issue stemming from the `/admin` to `/resource_admin` project.

I think the "fix" could either be:
- Update the link path to `/resource_admin` (though we're trying to keep Forem Admins out of this area in general)
- Move this email history functionality into `/admin` (bigger undertaking, probably some connected Product questions)

**Comment by fdoxyz** [comment]
https://github.com/forem/forem/pull/11792 tackles this by creating a custom view for admins to read these emails, and also removes `resource_admin` altogether.

Are there any specific features that we need from the "recent emails"? @pkfrank 

The links to the recent emails that appear in this area will be "read only", meaning that admins can't edited them, or perform any other action on them (like destroy). Unless there's something we need to explicitly support here I think this issue will be fixed with this PR.

**Comment by pkfrank** [comment]
Looks great to me @fdoxyz!

I don't think we need any extra features here — "read only" is great.

IMO, this issue can be closed once #11792 is merged.
