### ISSUE TITLE
Set up new forems with email registration enabled

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#11900]
**Is your feature request related to a problem? Please describe.**
Brand new forems are set up on a random `forem.cloud` subdomain, so they don't really need to be "invite only."

**Describe the solution you'd like**
New forems are set up with email registration enabled (and not "invite only").

**Describe alternatives you've considered**
The alternative is just to invite new Forem Admins to their Forem, but I've realized that this is sub-optimal (as sometimes people want to use different emails, invite their colleagues without extra steps, etc).

**Comment by mstruve** [comment]
Let me make sure I have this right, you would like the default for new forems to be open for everyone, correct?

This does have some security implications. I know it may seem like no one can access those forems but having the invite only on is a great way to ensure they are secure to begin with. @jdoss or @vaidehijoshi do you have any thoughts about this?

**Comment by vaidehijoshi** [comment]
> Brand new forems are set up on a random `forem.cloud` subdomain, so they don't really need to be "invite only."

> This does have some security implications. I know it may seem like no one can access those forems but having the invite only on is a great way to ensure they are secure to begin with.

I don't think it's wise for us to allow anyone to sign up with an email on a Forem instance. Signing up with email is already a potential spam vector, so allowing anyone to sign up on a Forem with any email is risky (I know you mentioned that they are set up on a random `forem.cloud` subdomain, but if anyone figures out those subdomains, they would easily be able to sign up for an account on every single Forem instance and use that account for abuse/spam purposes.

So I would vote that we _don't_ completely take this guard down (cc @mstruve).

> The alternative is just to invite new Forem Admins to their Forem, but I've realized that this is sub-optimal (as sometimes people want to use different emails, invite their colleagues without extra steps, etc).

Now, to @pkfrank's point about the pain that comes from having to invite people one-by-one. A couple ideas that come to mind:
- [ ] We allow people to add a domain so that anyone with a certain email address could sign up. This could potentially be useful when inviting colleagues; for example, I add `@forem.com` as an accepted domain, which allows _anyone_ with a `@forem.com` email address to sign up without me having to _explicitly_ send them an invite (which still is safer than allowing _anyone_ to register).
- [ ] We allow people to input a list of emails so that they can invite people en masse (rather than having to input one email at a time).

I think the problem we're trying to solve is: _"How do we make it easier for a Forem admin to invite some subset of people?"_, so I think we can try to solve for that without necessarily making email registration possible on all new Forems.

**Comment by pkfrank** [comment]
@vaidehijoshi I understand the rationale from a security perspective of keeping Forems in "Invite Only" until an admin changes that setting.  **To that end, I think we can close this issue for now.**

With that said, I do like the idea of improving invites.

- On Point 1, admins can already set an allowed domain (added via https://github.com/forem/forem/pull/11442)
- On point 2, inputting a list of emails for invitation would be a really nice improvement to `/admin/invitations/new`
    - Not sure how we'd account for the "Name" in this scenario

Additionally, my dream solution would probably be—

## Feature 1: invite token
Org Admins already have the ability to generate an "invite token" so that people can join their org.  It can be rotated for security.  I think we could have similar functionality for an invite-only Forem.

Ideally, an admin could create, rotate, and delete multiple Forem Invitation keys.  That would allow them to give different "join" keys to different cohorts which could come in handy for various reasons, instead of having just one "main" key.

## Feature 2: invite links
Similar to Feature 1 above, it would be super useful to have a simple private invitation link that allowed you to create your account on an invitation-only Forem.  Not sure if that would use a similar feature to Feature 1 under the hood.

## Feature 3: invite-as-Superadmin
Right now, we have a multi-step process for inviting someone and making them a Superadmin.

1. Invite a new user to the Forem
2. Wait until they join
3. Elevate their privileges once they join

It would be really useful if we could attach the assigned roles to an invitation to help skip a step.

**Comment by mstruve** [comment]
Thanks @vaidehijoshi for the great feedback and I think you hit the nail on the head that the invite flow needs to be improved here. 

@pkfrank how do you feel about writing up an RFC or multiple based on the features you suggested? We are close to having RFC guidelines ready and would love to get the flow tested early.

**Comment by pkfrank** [comment]
@mstruve I'll write up RFCs for these features.  In the meantime, should we close this issue?

**Comment by mstruve** [comment]
That works for me!
