### ISSUE TITLE
Github account unlinked but showing 2 Github repos still attached.

### ISSUE THREAD

**Issue by cmgorton** [forem/forem#11918]
**Describe the bug**
User has no Github account linked to their DEV account yet 2 Github repos are appearing in their profile. They have no way to unlink them from https://dev.to/settings/extensions since there is no Github account linked to this account. 

[Inês's profile](https://dev.to/ines)

![repos](https://user-images.githubusercontent.com/21039864/102263343-c80c3280-3ed9-11eb-89b1-ce2406a615b7.png)

**Expected behavior**

There should be no repos attached to the [profile](https://dev.to/ines)

**Comment by rhymes** [comment]
I can definitely reproduce this bug. I think this is due to the fact that we don't delete GitHub repositories when a person unlinks their GitHub identity from the website. I'm looking for  solution

**Comment by rhymes** [comment]
Now that I think about it this is both a bug and a behavior that depends on the fact that we have a tight coupling between the personal GitHub key and this functionality. 

We have few users that do not have a GitHub identity but have a GitHub repository linked: https://dev.to/admin/blazer/queries/306-github-repos-of-users-that-are-not-signed-in-with-github-anymore

In the past we were using the site GitHub credentials to fetch repositories, but we had issues of rate limiting (we have a max amount of calls we can make to the GitHub server per hour and we were using random keys) so we switched to using the user's GitHub key since the whole functionality is based on a person having a GitHub account linked to DEV.

The wider conversation, which is something I know @joshpuetz has been thinking about, is that we should decouple as much as possible the concept of "I'm logged in with GitHub" from "I use features related to GitHub", we had the same users requests related to people that wanted to display their GitHub URL without being signed in with GitHub, which right now you can't do.

This is the same: can the "show your GitHub repositories on your profile" feature exist outside the realm of you being signed in with GitHub? Should it?

I'm working on a PR to fix the underlying issue by removing the repositories when one unlinks GitHub and adding a script to clean up the existing data for https://dev.to/ines **but** that is going to clean up all the other repositories as well so my question is: how do we proceed? Our copy doesn't really explain that the two features are intimately connected and in the past they weren't so if we merge this PR a few users will see their repositories disappear.
