### ISSUE TITLE
DEV Community Mobile App does not surface email digest articles when clicked

### ISSUE THREAD

**Issue by SGGregory** [forem/forem#12097]
**Describe the bug**

For members with the mobile app, clicking on any of the hyperlinked articles in the email digests pulls up the app, but doesn't load the article — instead, members are simply brought to the DEV home feed.

**To Reproduce on iOS**

1. Download the DEV Community app
2. Find a previous DEV digest email
3. Click on any of the articles listed in the email digest

**Expected behavior**

Members with the DEV Community mobile app should have the article surfaced in the app when they click on any of the hyperlinked articles in the email digest 

**Screenshots**

See a screen recording of the issue [here](https://share.getcloudapp.com/E0u4mO6N)

**Smartphone (please complete the following information):**

- Device: iPhone X
- OS, version: iOS 14.2

**Comment by cmgorton** [comment]
@fdoxyz do you think this issue should be in the mobile repo or would just labeling it mobile / iOS be ok for this one?

**Comment by fdoxyz** [comment]
I think moving it to the mobile repo would be good for this one, because it relates to how the mobile app itself works. I'd leave mobile issues here (and label them with mobile tags) if they relate directly to the web app itself that runs inside the app, which is not always easy to tell though so I always appreciate the pings! 🙂

This one was reported here though https://github.com/forem/DEV-ios/issues/242

We have an app update that fixes this but we're currently blocked by Apple review at the moment. The mobile landscape should be changing a lot this year but for now as soon as we release the next update to the store this should be fixed. 

Closing and I'll follow up in that other issue when we released the fix
