### ISSUE TITLE
Onboarding Email Opt-In Not Working

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#12138]
**Describe the bug**

My opt-in to receive the newsletter + digest is not saved during onboarding. I know this because I didn't receive a welcome email, Mailchimp said I was unsubscribed, and when I visit settings/notifications, it displays that I am not opted-in to either emails. In order to subscribe to both, I need to re-select the boxes from settings/notifications and save from there.

**To Reproduce**

1. visit /onboarding on a forem
2. opt-in to emails
3. go to settings/notifications
4. observe that you are not opted-in to emails

**Expected behavior**

I expect to be subscribed to emails when I opt-in to them.

**Additional context**

This was happening to me on a non-DEV forem. 
I believe it's also happening on other forems: https://creators.forem.com/lee/mailchimp-unsubscribed-via-admin-action-2pp8

**Comment by msarit** [comment]
@jessleenyc Hi Jess! 👋🏾 

So I tried to reproduce the error described in this bug, but I couldn't. Here is a Loom video showing my experience:

https://www.loom.com/share/610c9f72e81d41cfb854d146b72b6bcb

**Comment by leewynne** [comment]
> @jessleenyc Hi Jess! 👋🏾
> 
> So I tried to reproduce the error described in this bug, but I couldn't. Here is a Loom video showing my experience:
> 
> https://www.loom.com/share/610c9f72e81d41cfb854d146b72b6bcb

Hi there, just to confirm - I also get this bug on my forem.

**Comment by jessleenyc** [comment]
@msarit so I just tried your flow on community.codenewbie.org and it is definitely still happening to me. Do you mind trying on that specific Forem? I

**Comment by benhalpern** [comment]
When I go through onboarding veeerrrryyyy slowwwwwwlyyyyyy, it works... But when I go through fast, it does not work as expected...

I'm not sure what the problem is, but I suspect there is something going on with `update_onboarding` which might cause a problem... And potentially a scenario where this response kicks something which undoes the next slide in a sort of worker race condition.

<img width="750" alt="Screen Shot 2021-01-10 at 12 44 45 PM" src="https://user-images.githubusercontent.com/3102842/104130954-a15ae380-5341-11eb-9df0-5645e0057ebf.png">

This definitely needs further exploration.

**Comment by vaidehijoshi** [comment]
Something interesting is definitely going on here 🤔  I tried this on forem.team and can confirm that it does not work when you click through unless you move at a _glacial pace_.

**Some notes from initial my investigation:**

Here's the network tab when I reproduced this on the forem.team instance
<img width="719" alt="Screen_Shot_2021-01-11_at_5_25_54_PM" src="https://user-images.githubusercontent.com/6921610/104257574-9df35500-5432-11eb-8cf1-08dc001434b6.png">

The payload looks as expected, which suggests that the issue lies somewhere between after the request is actually _sent_ from the JS side and before it is updated in the database. In other words, I don't _think_ the JS is the culprit here (...although maybe the JS is error-ing silently somehow?).

The request goes to the `UsersController#onboarding_checkbox_update` action:
https://github.com/forem/forem/blob/e7f9735354006e6f314744e3beb8c5f6d22002d8/app/controllers/users_controller.rb#L165-L176

Note that **this is different** from the rest of the onboarding requests that precede this requests, all of which go to `UsersController#onboarding_update` [action](https://github.com/forem/forem/blob/e7f9735354006e6f314744e3beb8c5f6d22002d8/app/controllers/users_controller.rb#L149-L163), except the profile update action, which seems unrelated here.

I guess what I would want to see next is what the response is from the server when it hits the `render_update_response(current_user.save)` line in the action...
https://github.com/forem/forem/blob/e7f9735354006e6f314744e3beb8c5f6d22002d8/app/controllers/users_controller.rb#L280-L286
But I'm not sure how to see that (maybe @maestromac has an idea/access?). Basically, I want to confirm if we're getting to that point or not to narrow down if we hit the line that updates the user in the database and whether we actually are properly able to `save` it or not.
