### ISSUE TITLE
Console errors while clicking on posts from homepage

### ISSUE THREAD

**Issue by ExpressGradient** [forem/forem#12146]
**Describe the bug**
Console errors that say `Uncaught SyntaxError: redeclaration of const subscribeBtn` and `POST https://api.honeybadger.io/v1/notices/js
[HTTP/1.1 429 Too Many Requests 905ms]`

I guess this isn't a bug that has an effect on users, I just noticed them in the console while opening posts.
**To Reproduce**
Just click on any random post in the home page.

**Expected behavior**
See console logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/59659961/103743982-fdacc300-5022-11eb-9822-53d2c593d2e0.png)

**Desktop**

- OS, version: Windows 10 Home
- Browser, version: Firefox Developer Edition

**Comment by nickytonline** [comment]
This error occurs because the `subscribeBtn` is defined in global. See https://github.com/forem/forem/blob/d9011f4b593469d60499900660818e8ee897c382/app/liquid_tags/user_subscription_tag.rb#L11. We should consider putting this in an [immediately invoked function expression](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) (IIFFE) instead so as to avoid polluting the global namespace. Another option would be to use `var`, but I would lean more toward the IIFE.

This is problematic for any liquid tag that includes JavaScript.

**Comment by takmar** [comment]
Can I try this?
This is likely related to https://github.com/forem/forem/issues/12545.

**Comment by nickytonline** [comment]
@takmar, thanks for your interest in this issue!

It's a little more involved than what I proposed after digging into this a little more with @jgaskins. We still need to investigate further into this issue as the IIFE will fix part of the problem, but the bigger issue is the liquid tag assumes there will only ever be one of them on a page.

**Comment by jeremyf** [comment]
In reading the partial and the liquid tag JS, there's a lot of DOM `id=` declarations.  To resolve this will require someone ready to tackle the javascript and HTML.

**Comment by aitchiss** [comment]
As a bit more context, this error was suppressed previously by changing the `const` to a `var`: https://github.com/forem/forem/pull/13694 - there's a lot of context on that PR about the remaining issues, potential fixes, etc that we need to keep in mind when looking at this

**Comment by nickytonline** [comment]
The problem is a little deeper than a JavaScript variable. There is a Slack thread somewhere about this, but the real problem is having more than one of these liquid tags embedded. `var` fixes the JS error, but what will happen is all instances of this liquid tag embedded in the same place will all reference the same `subscribeBtn`, the last one declared, i.e. the last liquid tag instance rendered. Also, even if we put this variable in a closure, there is still another problem. The button has the same `id` attribute, so when you `document.getElementById('subscribe-btn')`, it will most likely grab the first one only. The IDs should be unique.

**Comment by aitchiss** [comment]
I'm also curious how much this liquid tag is currently used or intended to be used in future - from the thread on the issue I linked:

> The user subscription liquid tag is restricted to certain roles. It was originally designed for use in CodeLand and isn't used much otherwise.

I don't recall seeing it used for CodeLand 2021, so before we go down a long rabbit hole of the issues you mention here @nickytonline I'd be keen to make sure we definitely _want_ this liquid tag

**Comment by nickytonline** [comment]
> I don't recall seeing it used for CodeLand 2021, so before we go down a long rabbit hole of the issues you mention here @nickytonline I'd be keen to make sure we definitely want this liquid tag

Sounds good! Didn't realize that was on the table. 😎

**Comment by aitchiss** [comment]
Update: yep, this is definitely an important tool for CodeLand peeps, and some other occasional uses ([see an example here](https://dev.to/devteam/how-to-claim-your-hacktoberfest-completion-badge-3l2h))
