### ISSUE TITLE
Profile generalization: Eliminating hard-coded profile fields

### ISSUE THREAD

**Issue by citizen428** [forem/forem#12157]
We [recently started ignoring columns from the `Users` table](https://github.com/forem/forem/pull/11246) which are now handled via `ProfileField`s. As a temporary workaround, we have delegation in place, but we need to stop using these fields directly/unconditionally as we can't guarantee their availability across different communities.

Each ignored column should ideally only be used in automatically generated pages like the new profile page. In cases where this isn't possible, their usage should be predicated on the availability of the field.

General note: In a previous discussion @benhalpern acknowledged that this may lead to some changes for DEV. In smaller cases this probably isn't an issue but for more substantial changes please get in touch with design and/or product.

This will be followed by https://github.com/forem/forem/issues/12159

ADDITIONAL INFO from comments:

Thesed fields are currently in the `ignored_columns` list, but there is still code using them. As an intermediate step we set up delegation from `User` to `Profile`, but we need to eliminate any direct usage of these fields (e.g. `user.education` or `user.website_url`). 

Going through the profile is not necessarily a valid alternative, as we won't be able to guarantee the existence of these fields across different communities in the future. This means that ideally they are only used on completely dynamic pages, like the new profile page.

This may have implications for DEV, so whoever works on this may need to talk to product/design occasionally before removing something that we previously had.

**Comment by mstruve** [comment]
> we need to stop using these fields directly/unconditionally as we can't guarantee their availability across different communities.

Can you be more specific about what this entails? Does this mean removing the fields from the database or is there more code that needs to be removed first?

**Comment by citizen428** [comment]
> Can you be more specific about what this entails? Does this mean removing the fields from the database or is there more code that needs to be removed first?

Thesed files are currently in the `ignored_columns` list, but there is still code using them. As an intermediate step we set up delegation from `User` to `Profile`, but we need to eliminate any direct usage of these fields (e.g. `user.education` or `user.website_url`). 

Going through the profile is not necessarily a valid alternative, as we won't be able to guarantee the existence of these fields across different communities in the future. This means that ideally they are only used on completely dynamic pages, like the new profile page.

This may have implications for DEV, so whoever works on this may need to talk to product/design occasionally before removing something that we previously had.

**Comment by vaidehijoshi** [comment]
@mstruve I removed this from "issues to review" in today's planning meeting, but we can add it back when we feel like we have enough context for someone on the team to take it on

**Comment by citizen428** [comment]
@vaidehijoshi Should we try to finally close the loop on profile generalization which started last August? If we're still missing context after the explanation I added above I'm happy to provide it, but I don't think we should leave this feature linger in a half-finished state for too long and this is quite literally the next step that needs to be taken to be able to move forward with it.

**Comment by vaidehijoshi** [comment]
> @vaidehijoshi Should we try to finally close the loop on profile generalization which started last August? If we're still missing context after the explanation I added above I'm happy to provide it, but I don't think we should leave this feature linger in a half-finished state for too long and this is quite literally the next step that needs to be taken to be able to move forward with it.

@citizen428 i absolutely agree that we should close the loop, but @mstruve had mentioned in the planning meeting that she wanted to look at this issue more closely before prioritizing it, which is why we removed it from the funnel in the meeting fo this week. I'd love the revisit and close the loop on this just as much as you :) I hope that we can discuss it in the next planning meeting

**Comment by mstruve** [comment]
@citizen428 thanks for the clarification! I added it to the description and put it back on the board to re-evaluate for the next cycle.

**Comment by vaidehijoshi** [comment]
Making a note here that once _this_ is completed, we can move https://github.com/forem/forem/issues/12159 _out_ of the blocked tasks 👍🏽

**Comment by citizen428** [comment]
One more thing that needs attention is the discussion here: https://github.com/forem/forem/pull/12015#discussion_r548349608

This PR added some constants to `Profile` that list fields that will require special treatment if they exist with exactly this name. 

```ruby

  SPECIAL_DISPLAY_ATTRIBUTES = %w[
    summary
    employment_title
    employer_name
    employer_url
    location
  ].freeze

  SPECIAL_SOCIAL_LINK_ATTRIBUTES = %w[
    twitter_url
    github_url
    facebook_url
    linkedin_url
    youtube_url
    instagram_url
    behance_url
    medium_url
    stackoverflow_url
    gitlab_url
    twitch_url
    mastodon_url
    website_url
    dribbble_url
  ].freeze


  def self.special_attributes
    SPECIAL_DISPLAY_ATTRIBUTES + SPECIAL_SOCIAL_LINK_ATTRIBUTES
  end

  def self.special_social_link_attributes
    SPECIAL_SOCIAL_LINK_ATTRIBUTES.freeze
  end
```

After sitting on this for over two months, I'm still not convinced by the approach:

1. For this to be useful, we'd have to communicate the field names in the admin guide or somewhere.
2. The `SPECIAL_SOCIAL_LINK_ATTRIBUTES` still seem pretty arbitrary/DEV-centric. If we publish this list (see #1) I'd expect we'd get more requests for other social media sites.
3. Things that have a special meaning (like `email_public`) probably should stay on `User` or go to a dedicated settings model, since `Profile` is ideally just a collection of key-value-pairs. 

I do not have a better idea for rendering profile pages as of yet, but I think we may need to come at this from a new angle. So far we only approached this starting from DEV's profile page and I feel like either we stop doing that, or we rethink how much customization (and where) we really want out of the profiles.

cc @benhalpern @forem/product

**Comment by citizen428** [comment]
I thought about this a bit more, here are two possible approaches I came up with:

1. Instead of full flexibility, we divide the profile page into "slots", something like this:
   ![Uploading 2021-03-11 10_57_00-Michael Kohl - DEV Community 👩‍💻👨‍💻 and 10 more pages - Personal - Microsoft.png…]()
    Here each red box would be a slot and we would define what can go in there, e.g. (1) any text area, (2) and (3) a text field with an optional icon, (4) a list of links (maybe we need to make a dedicated link type for profile fields), (5) A text area
    **Pro:** it keeps the page layout more consistent, also across Forems, without needing any special casing.
    **Con:** it may be hard to come up with a good admin UI for that.
2. We make the profile page very flexible, but add more validations/constraints like e.g. "no more than X text areas in the left sidebar" or "a maximum of 2 text areas in the header".
    **Pro:** More flexibility for admins while having a simpler admin UI.
    **Con:** Profile pages may look more different between Forems, potentially confusing users.
3. You tell me.

**Comment by mstruve** [comment]
I like the idea of having a couple of fields on the user like summary and location and then those exist on all profiles.

As for @citizen428's suggestions, I do think we need product to help make a decision for that. @forem/product what are your thoughts on profile display options and all of the above discussion on having some profile fields consistent across all forems?

**Comment by citizen428** [comment]
> I think we should put some of these fields on the User model

Right now we create a set of default profile fields when setting up a new Forem. But of course, these could be deleted by admins. So if we absolutely want them to always be available, we probably really should move them back to `User`.

**Comment by lisasy** [comment]
I think @citizen428's approach #1 is super sound and advocate to move forward with that so we're not continuing to be blocked here.

When it comes to anything UI/UX-related, we can *always* fix that down the line, but I think having maintaining this framework of some things are always fixed and others variable is the way to go.

**Comment by jacobherrington** [comment]
@lisasy I also think it's a really good solution.

Let's say that's our solution for the UI portion of this problem. The secondary issue we're bumping up against is the ubiquitous nature of a lot of ProfileFields in the codebase.

@citizen428 and I both (independently) attempted to remove code that was directly accessing `available_for` because (as this issue points out) if it is going to remain a ProfileField (it should), then we cannot ever assume it exists. Unfortunately, even that seemingly inconsequential field is used in some unexpected places, so removing it is somewhat difficult. There are other ProfileFields that are being accessed directly in the application that I would guess are going to be even more difficult to remove.

If this is our list of hard-coded fields to remove:
 - [ ] available_for
 - [ ] behance_url
 - [ ] bg_color_hex
 - [ ] currently_hacking_on
 - [ ] currently_learning
 - [ ] currently_streaming_on
 - [ ] dribbble_url
 - [ ] education
 - [ ] email_public
 - [ ] employer_name
 - [ ] employer_url
 - [ ] employment_title
 - [ ] facebook_url
 - [ ] gitlab_url
 - [ ] instagram_url
 - [ ] linkedin_url
 - [ ] location
 - [ ] mastodon_url
 - [ ] medium_url
 - [ ] mostly_work_with
 - [ ] stackoverflow_url
 - [ ] summary
 - [ ] text_color_hex
 - [ ] twitch_url
 - [x] twitch_username (pretty sure this one isn't being used anywhere right now)
 - [ ] website_url
 - [ ] youtube_url
 
I'm pretty sure there will be unexpected impacts to features that feel unrelated to these fields.

Breaking this up into chunks:

**Social Links** (slot 4 in Michael's graphic)
Essentially all of the ProfileFields that end in URL could be knocked out by creating a special sort of ProfileField for "social links" that either auto-detect services and apply an icon (like we do manually now, see screenshot below) or allow admins to upload an icon sized image when they define a "social link" ProfileField. This feels like a feature that could be carved out a built first by itself, my plan is to do this first if we all feel good about it. I think the first version should allow an admin to upload the icon for each link and use a default link icon in the case that an icon is not provided.
![image](https://user-images.githubusercontent.com/11466782/113356572-11a54f80-9308-11eb-992d-5ee06fba9b7a.png)

**User Settings Fields**
Some of these fields need to become User Settings (related: https://github.com/forem/forem/pull/12768). Specifically, I think bg_color_hex, email_public, and text-color_hex can go in that direction. We assume those exist in a few places in the app and therefore they aren't well suited to be ProfileFields.

**"Generic" Profile fields** (slot 5 in Michael's graphic)
I think these are things like education, currently_hacking_on, currently_learning, etc. There are some places in the code that calls to these attributes that need to be removed. Some of those things will impact other features. For example, in the instance of available_for, I'm pretty sure that's tied in to some of our search code.

**Work fields**
Right now we construct a special UI out of three of these fields (employer_name, employment_title, employer_url -- screenshot below). I think we either have to leave that behind the `dev_to?` check or get rid of it. @lisasy what do you think?
![image](https://user-images.githubusercontent.com/11466782/113357882-5b8f3500-930a-11eb-8728-475b0698351e.png)

**Others** (1, 2, and 3 in Michael's graphic, I'd suggest some of these revert to the User)
I struggle to imagine communities that won't want fields like summary and location, and we have opinions (currently) on where those fields should appear in the profile. So I'd advocate that those should exist on the User and we should feel safe assuming they exist. That's just my opinion, thoughts? @mstruve @citizen428

If there aren't any objections to starting from this point and dealing with issues as they come up, :point_up: will be my plan for building "slots" like Michael described.

**Comment by benhalpern** [comment]
@jacobherrington I was typing this up as you wrote your reply. I think it helps answers some questions. In my mind there is a path to ✂️ and simplify a bit.

To build on where we're going, here are some thoughts...

I think with regards to `SPECIAL_SOCIAL_LINK_ATTRIBUTES`...

I've become in favor of cutting the concept of social links of this fashion altogether. That would mean we keep the icons that the user has _authenticated_... (I.e. a DEV user might have their Twitter and GitHub), so it is a list of services _linked_ to the profile, but not just an arbitrary list of social accounts.

I just don't see it being very straightforward for admins to properly configure arbitrary links and have that all work out seamlessly for the end user.

We would keep the user's website URL and move it into being a sibling with location, joined date and email.

<img width="879" alt="Screen Shot 2021-04-01 at 5 37 42 PM" src="https://user-images.githubusercontent.com/3102842/113356874-f985fe00-9310-11eb-8218-98b8c7b29869.png">

In this situation, the social link fields vanish into thin air and we just keep these icons as special for _verified_ linked profiles, and this is tied to that Forem's auth (i.e. won't be as "arbitrary"). This is a breaking change for end users, but I think a valid simplification. We make the profile's website url more prominent, and that is a place where people can put whatever social links they want. We allow their website to play a bigger role. The whole _many social icons_ functionality of DEV is a nice feature, but really not what makes a Forem a Forem. If anything we want slightly slimmer, less rich profiles in this regard.

To what @jacobherrington is saying, this is a collection of attributes which generically exist across the ecosystem, and enabled by default. (But able to be disabled by admin? I could be pushed in either direction)

Then we have the _generic_ header fields... Could be _education_, _work_, _pronouns_, etc. Thinking about this, I think these attributes could allow hyperlink syntax, i.e. `Software engineer at [Forem](https://www.forem.com)`. This could allow us to migrate and preserve the "special functionality" of the `work` attribute, while allowing `education` etc. to have similar functionality.

**Comment by lisasy** [comment]
@jacobherrington @benhalpern 

Thanks for looping me into the conversation; I'm attempting to get up to date on everything with minimal context, but in some ways, I also can provide fresh eyes to this conversation :) 

An approach I took to asking myself what we could strip away to define the generic, hard-coded fields that admins cannot modify; what outcome do we want? Focusing within the "header" container, I illustrate my proposal here:

![2021-04-06_Profile-Generalization-Defaults](https://user-images.githubusercontent.com/816402/113778488-438c2c80-96e1-11eb-9ce7-bdebccb94a10.jpg)

As @jacobherrington details in this [comment](https://github.com/forem/forem/issues/12157#issuecomment-801004978), here are a few specs that I want to reiterate, and another point I want to suggest as a counter-solution:

1. This `summary` field is a fixed `textarea` that exists on the User model and is present on every Forem.
2. This `location` field is a fixed `text_input` exists on the User model and is present on every Forem. 
    - The `location` icon is fixed and not editable.
3. The `joined_at` field exists on the User model and is present on every Forem. ⚠️ A user cannot change this information; we populate it.
    - The `joined_at` icon is fixed and not editable.
4. For all of these 3 aforementioned fields, their UI is *not* configurable and exists on every User on every Forem.
5. These 3 aforementioned fields are constraint to the `display_area: header`.

As we balance setting hard defaults with customizations, I think the more choices we offer to admins around customizations for what we define as default real estate, the more confusion it could create. Keeping it pretty constrained here will make our system and lives easier. Additionally, over time, we can see what members attempt to put inside the `summary` area to observe if there are additional, more granular options we can provide to them.

**Comment by lisasy** [comment]
@jacobherrington:
> **Work fields**
> Right now we construct a special UI out of three of these fields (employer_name, employment_title, employer_url -- screenshot below). I think we either have to leave that behind the `dev_to?` check or get rid of it. @lisasy what do you think?
> ![image](https://user-images.githubusercontent.com/11466782/113357882-5b8f3500-930a-11eb-8728-475b0698351e.png)

Can you clarify what you mean when you say "leave that behind the `dev_to?` check or get rid of it"? If my recommendation is to [make default & fixed only particular fields in this header area](https://github.com/forem/forem/issues/12157#issuecomment-814446455), then I would advocate deprecating these "work fields" for all Forems in our more generalized universe. For example, I'm attaching a screenshot of how simply TikTok empowers theirs to express themselves without too many bells and whistle; I'm thinking we can adopt the same approach. 

However, what does this mean for `dev.to`, which already has this whole section? I want to ask if it is possible for us to keep it just for Dev.to and eliminate it wholly moving forward, or if that isn't possible. What are possible approaches we can take here?


![IMG_1823](https://user-images.githubusercontent.com/816402/113780470-1ab96680-96e4-11eb-955e-89922e97296c.PNG)

**Comment by citizen428** [comment]
> However, what does this mean for dev.to, which already has this whole section? I want to ask if it is possible for us to keep it just for Dev.to and eliminate it wholly moving forward, or if that isn't possible. 

It's possible, which is the `.dev_to?` check Jacob mentioned. But so far we always assumed these would be temporary, not long term solutions.

**Comment by citizen428** [comment]
@jacobherrington I"m closing this issue now, it's been open for too long. If there's any work left we can open smaller more focussed issues.
