### ISSUE TITLE
Profile generalization: custom profile fields

### ISSUE THREAD

**Issue by citizen428** [forem/forem#12160]
In the past we [merged a PR](https://github.com/forem/forem/pull/7246) that allowed users to define custom profile fields. Alas, we never added a frontend for this, so the code was essentially unused. We then removed this code in https://github.com/forem/forem/pull/9579 and added a new implementation that works in the context of our customized profiles in https://github.com/forem/forem/pull/10202.

This still doesn't have a frontend implementation, so we need to give users a way to define custom profile fields.

**Comment by mstruve** [comment]
@vaidehijoshi this will require some design work to use these custom optional fields. Do you think we want an RFC for this or should we just mention the design team here and do it that way?

**Comment by vaidehijoshi** [comment]
@mstruve let's use the RFC process since this is adding a new feature and we need to allocate design time as a prereq 👍🏽

**Comment by bnb** [comment]
Since the pronouns issue was closed, I'd like to restate my hope that pronouns be included as a first-class field regardless of how they're implemented on the backend.

Specifically, having folks have to write a key/value pair of "pronouns" and their pronouns forces a fully opt-in approach. It would be significantly more inclusive a pronouns property on profiles - implemented as custom field or not - was a default.

If impact justification is required:

- 100% of potential daily/weekly/monthly active users have pronouns.
- According to a software engineer at Adobe, [Behance has only 10m users](http://www.odbms.org/blog/2018/07/on-using-graph-database-technology-at-behance-interview-with-david-fox/). Similarly, [Dribbble has 12m users](https://techcrunch.com/2020/04/30/dribbble-a-bootstrapped-linkedin-for-designers-acquires-creative-market-grows-to-12m-users/). A year ago, it was reported that [Mastadon has 2.2m users](https://www.androidauthority.com/what-is-mastodon-1052151/).

Without considering anything else, the potential users that could meaningfully add pronouns is 100%, which is significantly higher than properties that already exist on the site.

Considering additional context, normalization of stating one's pronouns helps create a safer community for non-binary and trans folks.

**Comment by citizen428** [comment]
@bnb There's a specific reason why custom profile fields exist: once the Forem codebase has been fully generalized, the list of profile fields is completely manageable by admins. This will affect all the fields you listed as examples, they won't be created by default on new Forem instances in the future. Custom profile fields will allow users to add their pronouns to their profiles even on sites where the admins don't include the field site-wide.

As for making it a first-class field: we have to differentiate two cases here:

1. Sites run by us, like DEV: definitely, an admin can create the field and it will be there for all users.
2. Other sites: it's completely up to the respective admins which profile fields they add but users still have a chance to augment that with custom profile fields.

**Comment by bnb** [comment]
@citizen428 given that path forward, would it be safe to assume that there'll be defaults like display name, location, and bio that are turned on?

If it is, I think my request relatively stands - that it should be shipped within Forem as a default profile field (albeit a custom one that can be removed).

**Comment by citizen428** [comment]
@bnb Yes. We currently have the following list of base fields: 

* Summary (aka bio)
* Location
* Website URL
* Display email address on profile (a checkbox)

We can add more fields to this list. I brought up your request with our product team and will keep you in the loop 😃

**Comment by vaidehijoshi** [comment]
@bnb 👋🏽 Thanks for your patience here. I wanted to chime in from the product side and let you know that we agree with your recommendation that pronouns should be a first-class citizen in the form of a default profile field that comes enabled for all Forems. ❤️

**Comment by bnb** [comment]
Thanks, y'all ❤️
