### ISSUE TITLE
Check user passwords against haveibeenpwned during registration

### ISSUE THREAD

**Issue by abenettt** [forem/forem#12181]
**Is your feature request related to a problem? Please describe.**
Users can create accounts using email and password, but they might choose a passwords that is ill suited as it is either weak or has been leaked too many times. 

**Describe the solution you'd like**
When the user creates their account check their chosen password against haveibeenpwned to prevent above mentioned problems. 

**Describe alternatives you've considered**

**Additional context**
https://haveibeenpwned.com/API/v3#SearchingPwnedPasswordsByRange

**Comment by cmgorton** [comment]
Hey @abenettt Thank you for this request. I think this is definitely an interesting idea.

Moving forward we have a new RFC process internally for adding features. You can read more about it in [this post.](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4) 
Many changes to the Forem platform can be implemented and reviewed using the standard GitHub pull request workflow.

But because of the new RFC process, we would love for people to head over to [forem.dev](forem.dev) for feature requests that warrant more discussion.

If you don't mind I can create a post there for you with this request or you can create on yourself. If you would like me to post it just let me know!
