### ISSUE TITLE
Add discussion length in brackets

### ISSUE THREAD

**Issue by madzadev** [forem/forem#12324]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to get to know the discussion length for each post is to look at the post in the feed.
I usually don't pay attention to that, and even if I would, I would most likely forget that while reading some longer posts. When I reach the end of the article I would love to see how long the discussion is gonna be without the need to start scrolling.

**Describe the solution you'd like**
Add discussion length in the brackets.
Here is the requested feature I want in the image below (added in red):

![Screenshot (1)](https://user-images.githubusercontent.com/42511917/104938811-45830100-59b8-11eb-9c3b-281b06d5fbdd.png)

**Comment by ryy** [comment]
I want to work on this.
Looks like a good first effort😇

**Comment by madzadev** [comment]
@ryy yup, that's what I had in mind when I made this FR, too 😉
Suitable for beginners, should probably add 'good-first-issue' or smth 😉

**Comment by ludwiczakpawel** [comment]
@madzadev Yea, I think this is a good suggestion. I remember we had it in the past but it got removed (accidentally? not sure..). 

@ryy Awesome, I'm assigning you to this issue 👍. You can definitely follow @madzadev suggestion in terms of design: just bringing the number in brackets.

**Comment by madzadev** [comment]
Awesome guys! 👍💯

**Comment by sirius93** [comment]
Hi,
I am planning to work on this task, and have made some progress. Just wondering of a scenario like, how deleting of comments should be handled?
i.e.
![image](https://user-images.githubusercontent.com/6882879/106467637-f0b8ad80-64c2-11eb-86be-c09f5bf45558.png)

So a deleted parent, should that be counted as a comment or not? 
I am trying to get the count from article.comments_count object.

**Comment by rhymes** [comment]
@sirius93 `article.comments_count` is the number of comments for the articles, regardless of nesting. It's kept up to date automatically on the server when a comment is created or deleted. 

The only odd thing I can see here is that comments are created inline without page refresh, so that counter in the HTML could be incorrect. The easiest solution I can think of is to add 1 when the comment is created or deleted for UX purposes.

It might not be up to date though:

- I create a comment, without page refresh, the counter goes from 2 to 3, for example
- another user from their computer deletes a comment, which since it's a synchronous application
- they land back on the article page and see 2 comments
- I never refresh my page and still think there are 3 comments

This is not a huge deal in my opinion because, counter aside, it's the current behavior (comments won't disappear until I refresh the page), so the counter is actually correct.

I think by just adding `1` to the counter when the user creates a comment we're safe.

cc @forem/frontend in case there are alternative solutions for this

**Comment by ludwiczakpawel** [comment]
Agree with @rhymes re counting approach.

Also, I wanna make sure since this issue was assigned to @ryy - I hope you @sirius93 don't put too much effort into this if @ryy is already handling that. @ryy can you confirm you're currently working on this or should I reassign it to @sirius93 ?

**Comment by sirius93** [comment]
@rhymes I agree with the add 1 approach..! and I was planning to implement that, But as suggested by @ludwiczakpawel, I will wait for @ryy 's response and pick it up if needed.

**Comment by ryy** [comment]
I have not been able to tackle this issue.
Please reassign.

**Comment by nickytonline** [comment]
Assigning this to you @sirius93

**Comment by aitchiss** [comment]
Closed by #12518

**Comment by sirius93** [comment]
Thanks everyone for all the support. It was my very first open source contribution 😇😀.

**Comment by ludwiczakpawel** [comment]
@sirius93 you did great! 🚀

**Comment by rhymes** [comment]
Wow, awesome @sirius93, thank you again!

**Comment by msarit** [comment]
Awesome job, @sirius93! Thank you for enriching our project! 🙏🏾

**Comment by cmgorton** [comment]
Thank you so much for your work here @sirius93 . 🎉
