### ISSUE TITLE
Non-ASCII title makes a weird URL on Forem/dev.to

### ISSUE THREAD

**Issue by dmikurube** [forem/forem#12350]
Forem/dev.to has non-English speaking users, and they may write articles. They are expected to have an article which has a non-ASCII title. But, Forem/dev.to makes a weird URL with no slug if a title consists of non-ASCII characters.

The following article is a good example :
https://dev.to/chokri/-eg9

(This issue is a reorganization of #6942 to describe a problem here, and to propose solutions in other issues #12351 and #12352.)

**To Reproduce**

1. Start "Write a post" from dev.to
2. Fill its `title:` with non-ASCII characters (e.g. `テスト記事`)
3. Mark `published:` to `true`
4. Save changes
5. See the URL consists of only a random alphanumeric string (e.g. `/user/-eg9`)

**Expected behavior**

The article should have a meaningful URL with a meaningful slug.

**Screenshots**

The example article below (same as above) describes the issue well, instead of screenshots.
https://dev.to/chokri/-eg9

**Comment by dmikurube** [comment]
To resolve this issue, I'd propose two approaches as follows.

* #12351 
* #12352 

Both are the best, but just one of them will mitigate this issue so much.

**Comment by cmgorton** [comment]
Hey @dmikurube the Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. To propose features you should now visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏

I went a head and started a discussion post over there so that you didn't need to transfer all three issues yourself. We have had some other discussions around internationalization/localization and support for RTL languages. Opening these feature requests over there will help get our product team's eyes on the issue. Please feel free to add any comments or thoughts to the post I created. https://forem.dev/foremteam/non-ascii-title-makes-a-weird-url-on-forem-dev-to-2255
