### ISSUE TITLE
Update articles after changing a tag's style

### ISSUE THREAD

**Issue by atsmith813** [forem/forem#12486]
**Is your feature request related to a problem? Please describe.**
Whenever an admin updates the styles for a tag, those styles on the article itself does _not_ update right away. It would update once the cache expires or the article's cache is busted for another reason (i.e. the author updating it). That's because when we update a tag, we only [bust the edge cache for tags](https://github.com/forem/forem/blob/master/app/services/edge_cache/bust_tag.rb).

![Screen Shot 2021-01-29 at 10 12 14 AM](https://user-images.githubusercontent.com/15987080/106292148-8087fe80-621a-11eb-8c23-a4d9fe1bc033.png)

**Describe the solution you'd like**
When we update a tag's style, we can also bust the edge cache for the 100 most recently published articles for that tag.

**Describe alternatives you've considered**a
- Leaving it as is because the styles are updated, eventually, once the article's cache expires or is busted due to an update.
- Busting all articles under a tag (not performant).

**Additional context**
This was discovered in exploring another [issue](https://github.com/forem/forem/issues/12286#issuecomment-767828348).

**Comment by cmgorton** [comment]
@atsmith813 please correct me if I am wrong, but this is not currently being worked on by the team right? Do you have any objections to me adding the MLH fellows label to this issue and letting them work on it?

**Comment by atsmith813** [comment]
@cmgorton correct and yes, no problem!

**Comment by squarebat** [comment]
I'll take this up

**Comment by rhymes** [comment]
@squarebat @jgaskins my bad for merging it too hastily, although the code in #14298 feels like it's correct, we didn't actually solve the issue. We believe the issue was the articles edge cache but it's not. #14298 deals with the article tags under a title, which are cached server side here:

https://github.com/forem/forem/blob/71591994029d1cb861b1c82906acd0ba92c4f112/app/views/articles/show.html.erb#L121-L135

these won't change "right away" as the cache key is the list of tags, it is not cleared when a tag is updated. `Articles::BustMultipleCachesWorker` only deals with the edge caching, not the server side cache.

For this reason I'm going to reopen this and I think we should revert #14298 and change the approach.

**Comment by rhymes** [comment]
I added a PR to revert #14298 : https://github.com/forem/forem/pull/14330

**Comment by squarebat** [comment]
Whoop. Sorry that didn't work out. I'll look into how this can be solved.

**Comment by rhymes** [comment]
@squarebat I thought about two different options:

1. Doing something similar to #14298 but instead clearing the value with cache key `"main-article-tags-#{@article.cached_tag_list}"`
2. Changing the cache key to be dependent on the tags `updated_at` 

I'll let you explore what's best :) Let me/us know if you need assistance!

**Comment by squarebat** [comment]
Sure, thanks a lot! I won't be able to look into it just yet since I am working on another [issue](https://github.com/forem/forem/issues/2914), I'll let you know if I get stuck.
