### ISSUE TITLE
GitHub issue liquid tag inside `<li>` breaks markdown and rendered HTML

### ISSUE THREAD

**Issue by ludwiczakpawel** [forem/forem#12569]
**Describe the bug**

When users use github issue liquid tag inside a list item, it will break the markdown and therefore it will break rest of the page layout (since it will affect all HTML).

Please notice extra space between list items as well as _like_ and _reply_ buttons being misplaced.

**To Reproduce**

1. Write a comment or post with following markdown
    ```
    - {% github https://github.com/forem/forem/pull/12143 %}
    - something else
    - something 
    ```
2. Submit and see it breaks page layout.

**Expected behavior**

To not break a page layout.

**Screenshots**

![image](https://user-images.githubusercontent.com/108287/106880652-e540ce80-66dc-11eb-8ba2-2238789ee7af.png)

**Additional context**

I've notice this been happening only on github issue liquid tag but no other github related liquid tags.
I've also not found any _broken_ piece of html in that particular liquid tag .html.erb template (but maybe i missed something)

**Comment by vaidehijoshi** [comment]
I was able to reproduce this by putting two github liquid tags into my markdown, one after the other. This is what I had in the markdown:
```
* Plus some 15 minute fixes:
{% github https://github.com/forem/forem/pull/12877 %}
{% github https://github.com/forem/forem/pull/12919 %}
```
Which rendered this:
<img width="921" alt="Screen Shot 2021-03-08 at 5 10 52 PM" src="https://user-images.githubusercontent.com/6921610/110403282-b302f380-8031-11eb-839d-80c3bc8bb3d4.png">


But when I changed my markdown to include a line break between the liquid tags:
```
* Plus some 15 minute fixes:
{% github https://github.com/forem/forem/pull/12877 %}

{% github https://github.com/forem/forem/pull/12919 %}
```

It rendered correctly:
<img width="955" alt="Screen Shot 2021-03-08 at 5 11 37 PM" src="https://user-images.githubusercontent.com/6921610/110403391-e0e83800-8031-11eb-83f3-6126659d1476.png">


Just wanted to make a note of it here since I saw there was already an issue for it. (cc @jeferson-sb who has kindly picked this up 😄)

**Comment by ludwiczakpawel** [comment]
@aitchiss are you sure #12839 will fix it? At first glance it doesn't seem related..

**Comment by aitchiss** [comment]
@ludwiczakpawel yeah I think you're right and this issue was mistakenly referenced as closed by that PR. I've had a check this morning though and I haven't been able to reproduce this bug any more - are you still seeing it?
