### ISSUE TITLE
Request header field api-key is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by sandordargo** [forem/forem#12701]
Hello,

**Describe the bug**

I cannot connect my Angular application to the DEV API, though it works perfectly fine from Flask app and from Postman.

**To Reproduce**

```
  getStats(apiKey: string): Observable<any> {
    console.log(apiKey);
    const header = new HttpHeaders({'api-key': `${apiKey}`, 'Content-Type': 'application/json', });
    const response = this.http.get<string>(`${URL}`, {params: {page: `${1}`}, headers: header});
    console.log(response);
    return response;
}
```

With this code, I get this error:

*Access to XMLHttpRequest at 'https://dev.to/api/articles/me?page=1' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field api-key is not allowed by Access-Control-Allow-Headers in preflight response.*

**Expected behavior**

I would expect to get a normal response, just like in Postman or in Flask.
This works fine in Python:

```
import http.client
connection = http.client.HTTPSConnection("dev.to", context=ssl._create_unverified_context())
page_index = 1
connecion.request("GET", "/api/articles/me?page={}".format(page_index), headers={"api-key": api_key}, )
```

Thanks for your help. Probably more examples in the DEV API docs would be helpful.

**Comment by rhymes** [comment]
Hi @sandordargo, sorry for the delay!

We don't allow authenticated endpoints through CORS, only the public ones that don't require authentication. It's written at the top of the [API docs page](https://docs.forem.com/api/):

> All endpoints that don't require authentication are CORS enabled.

The reason is that we don't want to encourage hardcoded API keys in public frontends. My suggestion is to build a proxy: client calls server with stored API keys which calls DEV.
You can read more about this in [this issue](https://github.com/forem/forem/issues/4195).
