### ISSUE TITLE
User with no profile

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#12736]
**Describe the bug**

`NoMethodError: undefined method `decorate' for nil:NilClass`

This is the line: https://github.com/forem/forem/blob/master/app/controllers/stories_controller.rb#L238

**To Reproduce**

Visit https://dev.to/mohhamedion

**Expected behavior**

Should render a proper profile if exists.

**Additional context**

This does seem quite rare.

**Comment by citizen428** [comment]
This should not happen, from `user.rb`:

```ruby
# All new users should automatically have a profile
after_create_commit -> { Profile.create(user: self) }, unless: :_skip_creating_profile
```

That said we currently have 572,501 and 572,496 profiles. The users without profiles were created on December 5th (1), December 6th (2), December 11th (1) and January 7th (1). So it most likely wasn't something that was limited in time and fixed already, but it's exceedingly rare. We created over 50k users since December 5th and this affected 5 of them (0.01%).

**Comment by citizen428** [comment]
@Zhao-Andy I saved a query in Blazer where you can see the 5 users without profiles, I think a reasonable first step would be to manually create profiles for them:

```ruby
Profile.create(user_id: user.id)
```

**Comment by mstruve** [comment]
Updated those 5 users with profiles so I think we should be good to go with this. No new users have popped up in the last 20 days. If there is more to do let me know!
