### ISSUE TITLE
Following button can render incorrect text while data is being fetched

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#12835]
**Describe the bug**

In many (if not all!) of the places where the `Follow` button is rendered (with the class `follow-action-button`), the button _always_ renders the text `Follow` by default. Once the user's data is fetched, it then may update to `Following`. This step of fetching the data async and then updating the text _after the button and text have already rendered_ leads to a glitchy UI.

This is exacerbated further by the fact that the button itself has a different class/style depending on if the user is/is not following the organization, which makes this glitch _even more_ obvious.

**To Reproduce**

1. Follow an organization
2. Go to a post published by that organization (or to the organization's page itself)
3. Note that initially, the Follow button on the right sidebar or upper corner of the page first flashes `Follow`, and then updates to `Following`.

**Expected behavior**

I'd expect the button to render with a spinner in place of the text while the data is being fetched.

**Screenshots**

This was taken from [a post on forem.team](https://forem.team/product/balancing-flexibility-within-structured-processes-3i6o) but I've also noticed it on [organization pages](https://forem.team/product) as well; it might be happening everywhere if we are re-using the same button.

![follow button text](https://user-images.githubusercontent.com/6921610/109362697-67d22f00-7840-11eb-8fc8-87204ffaeefd.gif)

**Additional context**

We should be able to render a spinner there until we get the user data back rather than hardcoding the `Following` text that we currently do in a few places.

**Comment by citizen428** [comment]
@cmgorton Labelled this as "ready for dev" and also added "good first issue" as the bug is well described and could be fixed by a community contributor looking for a frontend task.

**Comment by cmgorton** [comment]
I have added it to the MLH project board. If they don't pick it up we can promote it more to the community. Thanks!

**Comment by sirius93** [comment]
@cmgorton @vaidehijoshi I would like to work on it, if no one has taken it up yet.

**Comment by cmgorton** [comment]
Sure @sirius93 . Thanks for helping out. I will assign it to you. 😄

**Comment by diegocasmo** [comment]
I tried replicating this issue in production and locally (adding a `sleep` call in the `follows_controller.rb` and using throttle to simulate a slow connection), but I was unable to do so 🤔.

Maybe it was unintentionally fixed already? @vaidehijoshi  do you still experience this issue? What browser are you using?

**Comment by kum9748ar** [comment]
Hi everyone, I am new to this community, can anyone guide me that how I can get started with this issue ?

**Comment by gajananpp** [comment]
Hi @kum9748ar ,

This function call loads the initial state of follow button :-
https://github.com/forem/forem/blob/96a935ffecd7cfe36bfca00aedb2feeb606daae6/app/javascript/packs/followButtons.js#L422


Since the styling for follow and following is different, maybe initially making button `display: none` in templates

https://github.com/forem/forem/blob/96a935ffecd7cfe36bfca00aedb2feeb606daae6/app/views/users/show.html.erb#L37
https://github.com/forem/forem/blob/96a935ffecd7cfe36bfca00aedb2feeb606daae6/app/views/organizations/_header.html.erb#L20-L25

and then in `initializeAllUserFollowButtons` removing `display: none` can be done or a  `.crayons-spinner` spinner can be shown in button while [`fetch`](https://github.com/forem/forem/blob/96a935ffecd7cfe36bfca00aedb2feeb606daae6/app/javascript/packs/followButtons.js#L301) completes

**Comment by Shofiya2003** [comment]
If this issue is still not resolved could you please assign it to me

**Comment by aitchiss** [comment]
@nickytonline I don't think that "Follow" text is because of caching - we used to render it with just `&nbsp` to make sure the button height didn't jump once we inserted the correct text. At some point that space disappeared and we replaced it with "Follow" to fix the CLS bug - https://github.com/forem/forem/issues/14164

I guess my question is... could the solution just be to change this back to `&nbsp` until the button initializes? The aria-label would still be present as it is now, and we could even consider making that more accessible by adding `aria-disabled="true"` while the button is still in the "uninitialized" state.

**Comment by sirius93** [comment]
Hi @nickytonline 
I am not able to spend time on it. You can assign it to someone else.

**Comment by aitchiss** [comment]
>  I think one advantage of it having the Follow text from the get go is the logged out experience since it would only ever switch to following for a logged in user.

Yeah, 100% - and I'd imagine 'Follow' is the final text in the vast majority of situations.

TBH I start to wonder how much of a problem this really is? In some ways I feel like it's _less_ distracting to have it change from Follow -> Following than it is to have the whole button suddenly appear 🤔

**Comment by nickytonline** [comment]
> > I think one advantage of it having the Follow text from the get go is the logged out experience since it would only ever switch to following for a logged in user.
> 
> Yeah, 100% - and I'd imagine 'Follow' is the final text in the vast majority of situations.
> 
> TBH I start to wonder how much of a problem this really is? In some ways I feel like it's _less_ distracting to have it change from Follow -> Following than it is to have the whole button suddenly appear 🤔

Agree that the whole button suddenly appearing is not as ideal. I wonder if we could avoid the jank still by having two buttons present (taking a11y into account) but only show the Following if logged on and following that person.

https://user-images.githubusercontent.com/833231/157489225-2f052d39-de47-4d03-aa64-ffd791e01298.mp4

**Comment by aitchiss** [comment]
>  I wonder if we could avoid the jank still by having two buttons present (taking a11y into account) but only show the Following if logged on and following that person.

I'm just not sure it's any different really than what we have at the moment? At the end of the day, we'd still be showing "Follow" which would change to "Following" with the different styles, which seems to be the the issue reported here? Maybe I'm misunderstanding something 🙃

**Comment by nickytonline** [comment]
> >  I wonder if we could avoid the jank still by having two buttons present (taking a11y into account) but only show the Following if logged on and following that person.
> 
> 
> 
> I'm just not sure it's any different really than what we have at the moment? At the end of the day, we'd still be showing "Follow" which would change to "Following" with the different styles, which seems to be the the issue reported here? Maybe I'm misunderstanding something 🙃 

I reflected on this a bit and for now I'm going to close this. 

If we get member feedback that this is still problematic , we can reopen this.
