### ISSUE TITLE
Users unable to sign up for new account with Apple ID

### ISSUE THREAD

**Issue by cmgorton** [forem/forem#12899]
**Describe the bug**
Several users have reported that they are unable to sign up for a new account with Apple ID. They 

**To Reproduce**
1) They choose to sign in with Apple ID
![Step one apple sign up](https://user-images.githubusercontent.com/21039864/109977748-c1b07a00-7cc2-11eb-80a7-f212a5c935f3.png)

2. They continue with password
![Step 2 apple sign in](https://user-images.githubusercontent.com/21039864/109976654-a2fdb380-7cc1-11eb-9fa7-90db93648c27.png)

3) When they fill in the information they are redirected back to the "Welcome to DEV Community" page and prompted to add an email and password.

4) They then see an error "Invalid Password" and are redirected back to the "Welcome to DEV Community" page. 

**Expected behavior**

Users should be able to add their Apple ID to create a new account. 

**Desktop (please complete the following information):**

Various versions. One user was on Safari. 

**Additional context**

We have had 3 reports of this so far. Each user tries to sign up with Apple and is redirected back to the "Welcome to DEV Community" and asked to create an account.

**Comment by citizen428** [comment]
@joshpuetz Can we close this now that both your PRs were merged?

**Comment by joshpuetz** [comment]
Great catch, closing now @citizen428 !

**Comment by ellativity** [comment]
Hey, I just went through the process using an incognito window and my Apple ID, taking screenshots of the entire process. Does this help at all?

![Screenshot 2021-03-09 at 16 04 10](https://user-images.githubusercontent.com/76786132/110491337-7991bd00-80f1-11eb-8cf5-1eb2f071b88c.png)
![Screenshot 2021-03-09 at 16 04 16](https://user-images.githubusercontent.com/76786132/110491339-7ac2ea00-80f1-11eb-8c9c-e7b0b38fce43.png)
![Screenshot 2021-03-09 at 16 04 26](https://user-images.githubusercontent.com/76786132/110491346-7c8cad80-80f1-11eb-9f33-35651f3f88d0.png)
![Screenshot 2021-03-09 at 16 04 50](https://user-images.githubusercontent.com/76786132/110491352-7e567100-80f1-11eb-952e-1ee796dec107.png)
![Screenshot 2021-03-09 at 16 04 59](https://user-images.githubusercontent.com/76786132/110491358-7f879e00-80f1-11eb-94f5-78ea914c82cd.png)
![Screenshot 2021-03-09 at 16 05 13](https://user-images.githubusercontent.com/76786132/110491367-81516180-80f1-11eb-9b04-fe4dd150443e.png)
![Screenshot 2021-03-09 at 16 05 22](https://user-images.githubusercontent.com/76786132/110491381-844c5200-80f1-11eb-839a-ae8f34015a9c.png)
![Screenshot 2021-03-09 at 16 05 44](https://user-images.githubusercontent.com/76786132/110491390-86aeac00-80f1-11eb-842f-07049bb9a6c2.png)
![Screenshot 2021-03-09 at 16 05 56](https://user-images.githubusercontent.com/76786132/110491395-89110600-80f1-11eb-89a9-b981a90b95e0.png)
![Screenshot 2021-03-09 at 16 06 14](https://user-images.githubusercontent.com/76786132/110491405-8b736000-80f1-11eb-81cb-755dd58eff44.png)

**Comment by fdoxyz** [comment]
I just tested this out more thoroughly (in dev.to) and there's definitely something odd going on.

| Browser (OS)  |  Works? |
| ------------- | ------------- |
| Chrome (macOS)  | ❌ |
| Firefox (macOS)  | ❌ |
| Safari (macOS)  | ✅ |
| ForemWebView (iOS)  | ✅ |
| Safari/Chome (iOS)  | ✅ |


So there has to be something weird going on in non-webkit browsers, which are **the exact browsers that have the service worker enabled** 🤔 

This is what I see for the callback from the OAuth process:

<img width="1439" alt="Screen Shot 2021-03-09 at 09 07 25" src="https://user-images.githubusercontent.com/6045239/110491479-efc4fe00-80b6-11eb-861f-07dae402a3d7.png">

So right now I think the service worker is bypassing out OAuth callback and "serving" a redirect instead of allowing the OAuth process to finish properly. I think the solution would be to bypass these endpoints from the service worker similar to how it was done in the past (there was a long list of URL paths that were excluded), in this case all `/users/auth/*` paths should not be cached.

**Comment by fdoxyz** [comment]
> @fdoxyz Do you have a good way to test this either locally or in production? I'm scared to 'hook up' my Apple ID and waste my chance at debugging 😆

I tried this out in https://community.benhalpern.com but I noticed the config there broke. I have to re-upload the configs (the `.pem` key) and I will do this soon so we can use that one for easy testing @joshpuetz

**Comment by fdoxyz** [comment]
Update: This ^ can now be tested in https://community.benhalpern.com again

**Comment by fdoxyz** [comment]
I tested this out and I believe the PR ^ fixed the issue. 

There's a chance the service worker is not being updated automatically though, so the problem could still be there for some users. I'm reopening for now and giving this some more time to see if more reports come through.

@ellativity whenever you have a minute, could you try to log in again using Apple Auth in DEV? Do you get the same result or are you now able to sign in?

**Comment by mstruve** [comment]
Given the service worker has been removed, this should no longer be an issue.
