### ISSUE TITLE
Badge is not accessible in dark mode pages

### ISSUE THREAD

**Issue by hazemalabiad** [forem/forem#12968]
When using a Dev badge in dark mode pages, it is not converting the background color to fit the existing mode (light or dark)
Badge Source Code: https://dev.to/p/badges
Type: SVG
![image](https://user-images.githubusercontent.com/16942677/110789330-ceb00900-8280-11eb-8cfd-377c49917317.png)

**Comment by cmgorton** [comment]
Hey @hazem94 where did you get the badge from. Are you using a PNG, SVG, or Font awesome?

**Comment by hazem94** [comment]
@cainwatson from [Dev.to](https://dev.to/p/badges) I am using SVG.

**Comment by hazem94** [comment]
I suggest that there could be two: one for the light theme, and another for the dark theme.

**Comment by cmgorton** [comment]
Hey @hazemalabiad . I talked to our designer and they are going to work on creating a SVG with white fill on the DEV letters and a white border so it can be used on dark themes and light themes. I'll give you a heads up when this is completed. Thanks again for reporting this.

**Comment by cmgorton** [comment]
We have updated SVG logo's from Emma to be added to the badges page. I am going to add this issue to the engineering planning funnel so the team can add the files to the page.

**Comment by cmgorton** [comment]
For anyone who works on this I have the newer SVG files that need to be added to https://dev.to/p/badges  and https://dev.to/brand

**Comment by atsmith813** [comment]
How do we want to store this asset and generate the CDN link? Or maybe we should replace the asset at this link? I don't have S3 access...

cc: @nickytonline @aitchiss @cmgorton 

[Currently, it's a CloudFront URL.](https://github.com/forem/forem/blob/fb41442d68fd33b928f9bfe5ddc10d10503e86bb/app/views/pages/badges.html.erb#L36)

**Comment by rhymes** [comment]
I would have suggested to download the badge and store it as regular SVG like https://github.com/forem/forem/blob/main/app/assets/images/instagram-logo.svg

but I also noticed another "issue". We're hardcoding the DEV logo everywhere on all Forems. If I go to https://forem.dev/p/badges I see the DEV badge, if I go to https://community.codenewbie.org/p/badges I still see the DEV logo.

Maybe we can just replace it with the actual community logo, which would be `Settings.logo_svg`, calling this helper:

https://github.com/forem/forem/blob/164525c8b6243f90bf34cf789af83054bb1f98b2/app/helpers/application_helper.rb#L158-L164


https://github.com/forem/forem/blob/main/app/assets/images/devplain.svg has transparency...

**Comment by nickytonline** [comment]
> How do we want to store this asset and generate the CDN link? Or maybe we should replace the asset at this link? I don't have S3 access...
> 
> cc: @nickytonline @aitchiss @cmgorton
> 
> [Currently, it's a CloudFront URL.](https://github.com/forem/forem/blob/fb41442d68fd33b928f9bfe5ddc10d10503e86bb/app/views/pages/badges.html.erb#L36)

If we put it in the assets folder @atsmith813, that should be good enough like @rhymes suggests.

**Comment by atsmith813** [comment]
Should we re-scope this issue?

There are several hardcoded assets on that page:
https://github.com/forem/forem/blob/main/app/views/pages/badges.html.erb

Including the `og` data.

**Comment by rhymes** [comment]
Yep, I think this issue is morphing into "use the community badge of the badges page or default to Forem badge if there's none".  We just have to make sure it's visible in dark mode, so it also solves the original bug :D 

Not sure what to do with this image that's in the headers:

![](https://thepracticaldev.s3.amazonaws.com/i/kjn1gduswyrrisc1basc.png)

Perhaps design can come up with a simpler concept that doesn't hardcode DEV's badge in the static PNG.

**Comment by aitchiss** [comment]
It looks like a few things have changed since the previous discussion on this issue - we no longer have the page `/p/badges` bundled with the app, with these DEV SVGs living now only on https://dev.to/brand which I believe is a custom page in DEV only.

In light of that, I don't think it makes sense to bundle the new SVG in with the app as discussed above, but upload it and generate the URL so that the custom page can be updated. I think both of those things can be achieved by a DEV admin.

**Comment by nickytonline** [comment]
I'm going to go ahead and close this since as @aitchiss mentioned, a DEV admin can do this now. cc: @michael-tharrington, @FounderCasey, @ellativity
