### ISSUE TITLE
When editing my  post, i see an older version of my post

### ISSUE THREAD

**Issue by glnds** [forem/forem#13331]
Blog post: https://dev.to/aws-builders/lambda-deployments-are-atomic-but-not-isolated-eph

When I click edit, the text in edit mode is NOT the latest version.
So the text in edit mode doesn't match anymore with the text displayed if you to the URL above...

**Comment by Zhao-Andy** [comment]
Hi @glnds, thanks for reporting this issue, and sorry for the late reply. I think this is because this might have happened:
1. you edited the draft on one session/device
2. on a different device/session, you picked up where you left off and saved it (maybe published it too)
3. on session/device from step 1, you went to edit your now published post
4. our auto-save feature (which is dependent on session/device) overwrite your latest published version with a previous draft state

If this is the case, I would suggest going into your browser's developer tools, then into local storage, and finally deleting the specific key value pair that might be associated to your article. It should be something like:
| key | value |
| ---- | ---- |
| editor-v2-https://dev.to/aws-builders/lambda-deployments-are-atomic-but-not-isolated-eph/edit | ...some draft metadata |

**Comment by Zhao-Andy** [comment]
Actually, closing this because I think https://github.com/forem/forem/issues/12401 is the same issue!
