### ISSUE TITLE
Add the option to share an article on pocket

### ISSUE THREAD

**Issue by yafkari** [forem/forem#1344]
**Is your feature request related to a problem? Please describe.**

I think it would be great if we can add directly in one-click an article to pocket.
Reading and listening to articles works well with dev.to

**Describe the solution you'd like**

_Simply_ add an "Save to pocket" option to the sharing options

**Additional context**

éI would like to take this opportunity to highlight that issue #150 should be open againé

**Comment by glebec** [comment]
Counterpoint: the Pocket Chrome extension toolbar button works fine for me without needing to add more content to the page.

**Comment by drazisil** [comment]
Counter, counter point. The extension isn't an option on mobile 😀

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
