### ISSUE TITLE
The twitter box no more appear when managing a post

### ISSUE THREAD

**Issue by Afif13** [forem/forem#13564]
I think the title already describe the issue. It's not related to a specific post, it happens for all my posts:

![image](https://user-images.githubusercontent.com/14073250/116435723-f7e62200-a84b-11eb-9b41-ed3b13f82f14.png)

**Comment by atsmith813** [comment]
Hey @Afif13! Are you referring to the **Suggest a Tweet** feature? If so, that was recently removed https://github.com/forem/forem/pull/13188

**Comment by Afif13** [comment]
@atsmith813  yes, it seems so. The text is a bit missleading as I understand from it that we need to write "the content of the tweet so DEV can use it" but it's not the case.

**Comment by atsmith813** [comment]
I believe the language is trying to suggest that you can write "_why you wrote the article or why people might find it interesting_" because in the past those style of Tweets has "worked". The language was updated to also say DEV may retweet you. Our team keeps an eye out for Tweets and we often retweet folks in the community. And that is all in place of the **Suggest a Tweet** feature that was removed.

I'll close this ticket out since we intentionally removed the feature. Let me know if I misunderstood or if there's another bug present - we're happy to take a look at it.

Thanks for bringing this up!
