### ISSUE TITLE
social media footer hides content in print mode

### ISSUE THREAD

**Issue by LayZeeDK** [forem/forem#13759]
**Describe the bug**

The social media footer is displayed at the bottom of every page in print mode.

**To Reproduce**

1. Go to any article on DEV Community.
2. Open the _Print_ dialog.
3. Print to PDF or watch the print preview.
4. Some content is hidden behind the social media footer at the bottom of each printed page.

**Expected behavior**

Content is displayed in full. The social media footer is hidden in print mode.

**Screenshots**

![The 7 Most Popular DEV Posts from the Past Week - DEV Community-1](https://user-images.githubusercontent.com/6364586/118184528-beacd500-b43b-11eb-965a-d15b3432d368.png)

**Desktop (please complete the following information):**

- OS, version: Windows 10 Enterprise
- Browser, version: Google Chrome 90

**Additional context**

**Comment by carlos-ds** [comment]
Hi, I'd like to pick this one up if that's ok.

My remarks/questions:

- I'm reading that a CLA should be signed in order to contribute. I don't see any links to that so I assume this can be signed from the PR itself? 
- In the images below, I've also marked other items in red that could be hidden on print (in the article view). However, this could be up for debate. But for example the moderation button can also block text (see below). 
- Since there is already a `print-hidden` class in helpers.scss, adding this class to the corresponding elements should suffice?

Does anyone have feedback on this? Thanks!

![image](https://user-images.githubusercontent.com/20499950/118362916-1eb58f80-b592-11eb-9bbb-61a8a0aea0f7.png)

![image](https://user-images.githubusercontent.com/20499950/118362932-3ab93100-b592-11eb-8554-97e5d94916ab.png)

![image](https://user-images.githubusercontent.com/20499950/118362964-61776780-b592-11eb-8eec-a2f172ce19da.png)

![image](https://user-images.githubusercontent.com/20499950/118362977-7522ce00-b592-11eb-9020-ebf3828b6f48.png)

**Comment by LayZeeDK** [comment]
Thanks, @carlos-ds!

`print-hidden` sounds like what we ant to add to the elements that should be hidden in print mode.

Consider whether any of the elements you highlighted could still make sense in a PDF printout (if they are clickable links).

**Comment by carlos-ds** [comment]
Good point, thanks for the feedback. 

Elements that need page context don't really make sense in a PDF. Hence, from the ones that I marked in the images above, I would hide following elements:

- Moderation button
- Favorite/bookmark/... bar
- "Follow" link
- Input field for new comments
- Like/reply buttons for comments
- "Subscribe" button

And leave these in:

- "More from author" links
- "Code of conduct" / "Report abuse"

**Comment by LayZeeDK** [comment]
@carlos-ds 
That's similar to what I was thinking 👍

**Comment by carlos-ds** [comment]
Alright, thanks a bunch. 
I'll try to submit a PR for this, at the latest by the end of this week.
