### ISSUE TITLE
Unpublished post shows edit link to non-author logged users

### ISSUE THREAD

**Issue by MatheusRich** [forem/forem#13795]
**Describe the bug**

**To Reproduce**

1. Log in
2. Go to a unpublished post (https://dev.to/leastbad/beast-mode-stimulusreflex-with-all-futures-4121-temp-slug-3955216?preview=0f814fe700ac64830c91c4bc686d5660272747d9e5be79f6d3e7f68b0a48e20e0e906e34ff65e51c81f166ff2a407bd10a5b9a74010c57ee7f7d8356 for example) 
3. See the banner link "Click to edit"
![image](https://user-images.githubusercontent.com/20938712/118706269-8ddbef80-b7ef-11eb-9959-5f6acc6d9030.png)
4. (optional) Click the edit link
5. The server 404s

**Expected behavior**
The banner should not include the edit link for non-author users.

**Desktop (please complete the following information):**

- OS, version: Linux Ubuntu 18.04
- Browser, version: Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)

**Additional Context:**

The banner works as expected for unlogged users.

**Comment by cmgorton** [comment]
Hey @MatheusRich I don't get a 404 when I click the edit link. I know people in organizations or sometime authors who want feedback on their writing will share a link to their unpublished articles and allow edits. I think this might be intentional functionality. Unless I am not understanding your issue correctly. 

When I am not logged in I do not have the ability to edit this post. Only while logged in.

**Comment by MatheusRich** [comment]
@cmgorton did you see the link even if you're not the author of the post? Why do non authors should see an edit link for post they didn't write?

**Comment by cmgorton** [comment]
Hey, this is because people work together sometimes to edit posts. It is something used by a lot of organisations and also coworkers on DEV and other Forems. If the author shares the link then it can be seen and edited.

**Comment by MatheusRich** [comment]
@cmgorton oh OK. I hope I didn't sound rude in my last comment! Do you think we could avoid showing this link for people that doesn't have permission to actually edit it?

**Comment by cmgorton** [comment]
> @cmgorton oh OK. I hope I didn't sound rude in my last comment! Do you think we could avoid showing this link for people that doesn't have permission to actually edit it? 

I didn't think you were rude 🙂 
We could make that a feature request so that product can weigh in on it before we make any changes. We ask contributors to put feature requests on forem.dev so the whole community can weigh in. You can see examples of feature requests in this roundup https://forem.dev/foremteam/let-s-discuss-3-a-roundup-of-feature-requests-5e2e

Also happy to create a post for you instead there if you would prefer 😀

Thanks for bringing this issue up.

**Comment by MatheusRich** [comment]
@cmgorton go ahead and create the post, please! Thank you

**Comment by cmgorton** [comment]
Post for this feature request can be found [here](https://forem.dev/coffeecraftcode/feature-request-hide-edit-link-to-anyone-without-permission-3lgi). Since we have moved this discussion over to [forem.dev](https://forem.dev/) I am going to close this issue here. Thanks.
