### ISSUE TITLE
Showing personal stats for organizations stats

### ISSUE THREAD

**Issue by surajondev** [forem/forem#13815]
**Describe the bug**

If you see, your personal stats and your organization's stats, they are the same, which is personal. 

**To Reproduce**
- Must be Admin of an Organization
- Go To Dashboard
- See Analytics
- See Analytics of your organization.
- They are same

**Expected behavior**

There should be different stats for organization and different for personal.

**Screenshots**

Personal Stats:

![surajondev](https://user-images.githubusercontent.com/67496096/118923797-c0096080-b959-11eb-9d25-34ae42e987d4.PNG)

Organization's Stats:

![basecampstats](https://user-images.githubusercontent.com/67496096/118923859-da433e80-b959-11eb-9746-c9e97bc47521.PNG)

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Comment by aitchiss** [comment]
Thanks for reporting this bug!

I had a quick investigation and I think it boils down to the way we initialize the analytics dashboard in `analyticsDashboard.js`:

```js
function initDashboard() {
  const activeOrg = document.querySelector('.organization.active');
  if (activeOrg) {
    initCharts({ organizationId: activeOrg.dataset.organizationId });
  } else {
    initCharts({ organizationId: null });
  }
}
```

The selector we're looking for ('.organization.active') doesn't exist, and I can't see anywhere in the codebase where we're attempting to add it either. The fix for this will be to make sure we accurately establish whether the organisation or user analytics are being viewed, likely by adding a data attribute in `analytics.erb`, then updating the method above to correctly pull out that org's ID.

**Comment by surajondev** [comment]
Thanks for explaining the issue in detail. 
So when I can expect the changes so that I can see my organization's stats.

Thanks

**Comment by metamoni** [comment]
While looking into whether I could fix this, I noticed that the `dashboards_controller` sets a global variable (`@organizations`) that doesn't get used in the `analytics.erb` view. So I looked into it a bit more, and it looks like the user's organizations have been removed from this view in [this PR](https://github.com/forem/forem/pull/13345/files). This is why the `analyticsDashboard` can't find the org id.

Looks like the PR was meant to make the page look better on small screens, so unless removing the orgs was an intended change, this issue can be fixed by adding the deleted code back in. The fact that `@organizations` is still present in the controller makes me think it was unintentional.

**Comment by aitchiss** [comment]
> this PR

Oh great catch! Yes that PR was only intended to be cosmetic changes, but you're right we've accidentally removed the class we were depending on for this to work properly.

It might be neater to bring this back as a data-attribute rather than adding classes "organization active", as I don't think we're using those classes for styles. Either way, as long as it brings back the functionality we're good 😄 

Are you thinking you'd like to take this one on @metamoni?

**Comment by metamoni** [comment]
Sure, happy to work on this @aitchiss!

**Comment by aitchiss** [comment]
> Sure, happy to work on this @aitchiss!

Yay! Awesome - thanks! I've assigned it to you - give me a shout if you need a hand with anything 😄

**Comment by metamoni** [comment]
I've put the code back and I'm now looking for some guidance on design. Is there a mockup for what this sub-menu should look like? It currently looks like this:

<img width="1330" alt="Screenshot 2021-06-09 at 19 57 11" src="https://user-images.githubusercontent.com/22390758/121412708-e9b41700-c95c-11eb-8781-fbd3c753438a.png">

**Comment by aitchiss** [comment]
Hey @metamoni that's awesome!

There's a mockup of this menu here: 
![image of the same dashboard section, but the links align in a column](https://user-images.githubusercontent.com/6921610/112771954-148c0180-8fe3-11eb-8a56-563e7a1f097c.png)

(taken from the original PR that introduced this work: #13156)

Looking at the old mockup, I think all that needs done is to have the links align in a column instead of a row 😄
