### ISSUE TITLE
"Skip to content" shows up erroneously on search submission

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#13876]
**Describe the bug**

When I hit "return" on desktop to make a search on the platform, I see the keyboard nav "skip to content" element show up.

**To Reproduce**

- Go to dev.to
- Make search

**Expected behavior**

This element should not become visible.

**Screenshots**

<img width="1024" alt="Screen Shot 2021-05-28 at 10 35 26 AM" src="https://user-images.githubusercontent.com/3102842/120000078-6da2f200-bfa0-11eb-9634-967843735b3f.png">

**Desktop (please complete the following information):**

- OS, version: MacOS 11.2.2
- Browser, version: Chrome 90.0.4430.212

**Comment by Link2Twenty** [comment]
If I had to guess I'd say this is related to #13828

**Comment by aitchiss** [comment]
This is an interesting one - the behaviour we want is for the skip to content link to appear/be focused when a user changes page via the keyboard... which is technically true of the search + Enter flow, although in this one case users who normally navigate with the mouse are going to be pressing Enter to get there.

I'd suggest we make an exception for the search page for now (in the `base.js.erb` `changePage` function that was changed in #13828), as a quick fix.

**Comment by benhalpern** [comment]
I'm going to re-open this because this problem seems to be occurring again.

**Comment by nickytonline** [comment]
Can confirm this is still an issue even with the new search button being present.

https://user-images.githubusercontent.com/833231/129730701-3b71afad-10b5-4b14-8ae5-01c0f6e323c2.mp4

**Comment by aitchiss** [comment]
I mentioned this in slack, but putting here for visibility - this behaviour was reintroduced (by me 😄 ) on purpose, following a discussion about https://github.com/forem/forem/issues/14001 and https://github.com/forem/forem/issues/14083 in slack.

The gist of it is, I asked if we can reintroduce the focus/visibility of the skip link on enter press if we now have a separate search submit button. I understood from the response from @anujbhavsar96 and @benhalpern that we were in agreement to do this, but it seems there has been a misunderstanding.

We can revert the commit that did this (https://github.com/forem/forem/pull/14463) if we want to, but I would like us to have a discussion about it if possible first, because we'd be sacrificing an accessibility feature.

**Comment by cmgorton** [comment]
Going to close this issue while the team discusses it further as per @aitchiss comment. Let me know if I should open it back up. Thanks :)
