### ISSUE TITLE
Clicking on Discover reloading a new page

### ISSUE THREAD

**Issue by pradeepradyumna** [forem/forem#13893]
**Describe the bug**

On the home page of forem.com, when I click navigation options like "Why Forem?", "Features", scrolls the page to the respective content without going to a new page. But when I click "Discover", it is opening a new page, instead of scrolling within the page. Not sure if it is the expected behavoiur

**To Reproduce**

1. Open forem.com
2. Go to the navigation bar on the top-right of the home screen
3. Click either "Why Forem?" or "Features", it scrolls within the same page
4. Click "Discover", instead of scrolling, it reloads the page with contents pertaining to "Discover"

**Expected behavior**

Should scroll to the Discover section on the same page

**Screenshots**

None

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome, Version 90.0.4430.212 (Official Build) (64-bit) 

**Smartphone (please complete the following information):**
Haveb't checked
- Device:
- OS, version:
- Browser, version:

**Additional context**
None

**Comment by cmgorton** [comment]
Hey @pradeepradyumna . I believe this is expected behavior. Forem discover is a separate page that will eventually list even more available Forems to explore. Because the hope is that this will eventually be a pretty big list of Forems, I believe this is intended behavior.  I'll mention this to Product/design though just so they know what the UX is like for some users. Thanks for opening this issue.
