### ISSUE TITLE
Forem app pop-up reappears

### ISSUE THREAD

**Issue by jeikabu** [forem/forem#13890]
**Describe the bug**

Forem app pop-up is undead

**To Reproduce**

1. Open any dev.to page and forem app pop-up appears
2. Close it
3. Goto 1

**Expected behavior **

It doesn't re-appear or doesn't appear at all.

**Screenshots**

![A7CAAFE5-BDC8-405E-B2A2-F2B1C27F6207](https://user-images.githubusercontent.com/5897149/120199198-a99db780-c22b-11eb-9021-d835805796e5.png)

**Smartphone (please complete the following information):**

- Device: iPhone 8
- OS, version: iOS 14.4.2
- Browser, version: Safari

**Comment by cmgorton** [comment]
@fdoxyz do you think this should be moved to mobile repo or could we keep this here? Asking before I add labels 😄

**Comment by fdoxyz** [comment]
This one is best left on this repo @cmgorton 👍 

However, I wouldn't consider this one a bug. The banner is consistently there to make sure a link to the mobile app is always available and it's only visible on iOS devices. We did our best to make this non-intrusive or too jarring of an experience (for example Reddit's or Twitter's banner for the same use case).

If there is a strong pushback against this feature we can always consider modifying the behavior, but for now I might consider this a feature request.

I want to make sure we understand your situation @jeikabu: Is there a reason you would prefer using a browser over the mobile app? Even if the only Forem you would use is DEV in this case.

**Comment by jeikabu** [comment]
Is there are reason I should prefer an app over a browser to view a website?

It's silly to install a special purpose app- that's basically just an embedded web browser- when there's already something installed that has: tabs, syncs across devices, and so on.  There's already enough websites trying to foist apps on everyone.

**Comment by fdoxyz** [comment]
> Is there a reason I should prefer an app over a browser to view a website?

The app's intention is to enhance the experience you'll have when using a general purpose browser. I'm using the word "intention" because that's what it is, I'm not claiming it will be objectively better or the choice everyone will want to use.

Here's a few things that come to mind that differentiate the app from a browser:
- You can follow many Forems from a single place
   - No need to look through existing tabs or open a new one and type the URL you're looking for
   - The above ^ refers to a situation where you're on DEV and want to check another Forem
- No tab clutter
   - Many tabs for many different Forems (+ tabs for other websites) means you have to keep on top of this
- Push Notifications
   - When logged in the Forem app you'll receive notifications. You don't get this on a browser.
   - More notifications will be added soon for different use cases. For now only replies to your Post/Comments or if subscribed to a Post.
- Background audio playback
   - If you listen to a Podcast on any Forem you'll get a native player experience.
   - If you listen to a Podcast on your mobile browser you'll most likely run into problems when you lock the screen
- Enhanced image picker in the Post editor
   - You can try for yourself uploading an image or cover image in the Post editor (native implementation)

The mobile app may not be for everyone, but it's also not _"basically just an embedded web browser"_. I have a hard time wrapping my head around what difference would it make if the app were built using purely native tech, when the browser experience seems to work well for you, other than some better performance/interactivity with the UI elements.

> There's already enough websites trying to foist apps on everyone.

That's a very fair point. You don't want an app because of this, so you're stuck with the mobile browser experience along with its limitations. We're trying an approach to a native app that leverages the same experience from the browser with the goal of improving its deficiencies. It doesn't have to perfectly fit everyone's use case for now.

There's also a bigger picture to all this: With Forem being Open Source we are doing our best to make our entire Stack available to everyone. If you already have a native app (yourself or your company) and want to create a Community around it, you could deploy Forem on your own (FOSS) and also embed the entire experience (including Push Notification delivery) directly into your app by opening "just an embedded web browser" (with a [ForemWebView](https://github.com/forem/ForemWebView-ios)). 

A few lines of code and the entire experience lives inside your app, which will be entirely up to date and without having to continuously update & go through AppStore review (at least not very often over time in order to get the latest updates from `forem/forem`).

------

I want to clarify that this is my point of view and for now we may be using this approach, but in the future we could eventually migrate to a fully native codebase. _Life is a journey, not a destination_ (excerpt from the previous app's [design ethos](https://github.com/forem/DEV-ios#design-ethos)). For now this is what makes sense to us and it doesn't have to be this way forever.

Anyways, I appreciate your feedback and will relay this sentiment internally to make sure your point of view is heard.

**Comment by jeikabu** [comment]
All that is great. It would just be nice to read an article or two without a lot of pop-ups.

**Comment by fdoxyz** [comment]
An update on this topic is that we've decided to move forward with changing the way the banner will work to avoid having it always re-appear after it was dismissed.

We're finalizing the design of the new implementation and hope to ship this update soon.

**Comment by cmgorton** [comment]
Thanks for the update Fernando!

**Comment by fdoxyz** [comment]
I missed closing this issue when it got merged last week. #14119 solves this problem. Thank you again everyone for weighing in on the topic.
