### ISSUE TITLE
Community Digest Emails Not Factoring in Anti-Follows

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#13915]
**Describe the bug**

Users are receiving links to posts on tags that they are "anti-following" — i.e. tags that they have adjusted to have a negative follow weight from https://dev.to/dashboard/following_tags.

**To Reproduce**

1. Follow a tag(s) that you want to anti-follow
2. Go to 'https://dev.to/dashboard/following_tags' and adjust this tag's follow weight to be negative
3. Ensure that you have check "Send me a periodic digest of top posts from my tags" in 'https://dev.to/settings/notifications' -->
4. Look for incongruencies in emails

**Expected behavior**

If you are anti-following a tag, you should not receive suggested posts that include these tags in your community digest.

**Additional context**

A DEV user wrote in to describe this issue.

One odd consideration, what do we do with posts that include tags the user is following, but also include tags that the user is anti-following? Do we send these posts to the user? I believe we should probably exclude these posts, but wanted to bring this up as something to keep in mind.

**Comment by cmgorton** [comment]
@michael-tharrington do you think this is an issue that could be added to the small wins project board?

**Comment by michael-tharrington** [comment]
@cmgorton I imagine so! I've tossed a few things on there, some of which may be a bit more involved than a small win. I know @Zhao-Andy is routing (and fixing!) the items that I put there, so I'm relying on him to kinda keep my suggestions in check, haha. 

I'll pop it onto that project board and, Andy, if this is something that is larger than small, ya feel free to course correct. This same advice goes to anything I pop on the small wins board that doesn't fit.

**Comment by citizen428** [comment]
I'm picking this up because it actually fits in with the mandate of the Content Experience pod.

**Comment by citizen428** [comment]
One of the problems here is that we conflate the concepts of following and "anti-following" tags: in order to not follow a tag one has to counter-intuitively follow it first and then assign it a negative score. If I had to guess this is probably because "anti-following" was retrofitted into an existing model.

My preferred approach would be to filter out tags with negative scores from `User#cached_followed_tag_names` because the user is in fact not actually following this tag and removing it from this list would also have positive effects in other areas like `Users::SuggestRecent` where we also don't seem to take the actual scores into account and therefore probably suggest wrong users too. But I'm not quite sure yet where else we are using this and want to make sure I don't break something else in the process.
