### ISSUE TITLE
RSS sync silently ignores feed entries with long titles (I think)

### ISSUE THREAD

**Issue by RangerRick** [forem/forem#13959]
**Describe the bug**

I have noticed that some of my posts to our (OpenNMS's) blog don't show up in my dashboard as draft posts.  Up until now I've just ignored it and let an entry go missing here or there.  Today I tried adding the entry manually, and found that it wouldn't let me save because my title was too long.

I suspect these entries are getting missed because the title is too long so it can't get auto-saved into my dashboard.

**To Reproduce**

1. Create an RSS feed with an entry with a very long title.
2. refresh RSS

**Expected behavior**

All RSS feed entries get draft posts.

**Desktop (please complete the following information):**

- OS, version: Mac OS X Catalina
- Browser, version: Firefox 89

**Additional context**

Our RSS feed is https://www.opennms.com/feed/

The June 7th entry _("OpenNMS On the Horizon - Documentation, Flows and Nephron, Docker Container Trust, Thresholding, Metadata, Time-Series API, Minion Health Checks")_ did not auto-import.

**Comment by djuber** [comment]
Hi @RangerRick, I can confirm this is happening, and for the reason you suspected.

When I fetched the rss feed, it contained 10 items. I only saw 7 articles created from those 10 entries, items with title lengths of up to 122 were permitted/created and entries with title lengths of 132, 143, and 144 were omitted/skipped.

## Technical investigation (skip ahead if not interested)

[Feeds::Import](https://github.com/forem/forem/blob/main/app/services/feeds/import.rb#L128-L168) handles errors in article creation by logging 

`result` here is the set of articles successfully created, `entries` is the parsed xml from the rss feed (I think there's some reverse chronological sorting between the two, one reads right to left and the other left to right, that's unimportant):

```ruby
[38] pry( <Feeds::Import>):2> result.map { |a| a.title.size }
=> [122, 114, 22, 90, 96, 114, 87]                           
[39] pry( <Feeds::Import>):2> entries.map {|e| e.title.size }
=> [144, 87, 114, 96, 143, 90, 22, 114, 122, 132]     
```

Checking the logs after I called `create_articles_from_user_feed`, I see the error message is as you suspected  (article title is too long):

```
feeds::import::error::ActiveRecord::RecordInvalid::{:feeds_import_info=>{:username=>"admin_mcadmin", :feed_url=>"https://www.opennms.com/feed/", :item_count=>10, :error=>"Feeds::Import::CreateArticleError:https://www.opennms.com/en/blog/2021-06-07-opennms-on-the-horizon-documentation-flows-and-nephron-docker-container-trust-thresholding-metadata-time-series-api-minion-health-checks/?utm_source=rss&utm_medium=rss&utm_campaign=opennms-on-the-horizon-documentation-flows-and-nephron-docker-container-trust-thresholding-metadata-time-series-api-minion-health-checks"}, :error_message=>"Validation failed: Title is too long (maximum is 128 characters)"}
```

## Take-aways and ideas (stop skipping ahead now)

I think there are a few possible solutions here to consider 
- Forem could permit longer article titles than 128 characters
- a predictable truncation/shortening could be applied to rss entries with long titles during import to fit within the existing title length limit - for example grab up to 125 initial characters, and add an ellipsis, which we currently do shorten the visible description (if the size is greater than 100 characters, we add an ellipsis '...' to the initial content)
-  add better messaging to users impacted by this during import - since you had to find this out through spot checking, and guessing about the problem, and it would be easier for us to let you know something went wrong, and what, so you can take appropriate actions. Right now we're sending that information to the logs, and not providing any notification to you. 

Putting on a "design" hat for the moment, since the article title is used in the card, exceeding a set maximum length might cause display problems. At 137 characters it wasn't a huge difference from shorter titles - at closer to 500 characters the card is noticeably larger than its peers.

![A little longer looks normal](https://user-images.githubusercontent.com/1237369/121566383-127eef80-c9e3-11eb-9866-67ca25d7b2a6.png)

![much longer becomes imbalanced](https://user-images.githubusercontent.com/1237369/121565549-26762180-c9e2-11eb-9417-ed27b0c30b61.png)

The article's page (with the body content) also starts to have display quirks, with no visible text until you scroll past the long title header. I did not explore this on mobile, where the extra screen real estate used might have a larger impact.

**Comment by rhymes** [comment]
I love the ideas of shortening the title instead of silently failing! Since we import articles as drafts, then the user can manually adapt the title if they need to
