### ISSUE TITLE
RSS feed importer truncates articles

### ISSUE THREAD

**Issue by unixorn** [forem/forem#13970]
**Describe the bug**

I connected my blog's RSS feed to my dev.to account, and the posts were ingested and added as drafts. However, everything after the `<!--more-->` line in the posts were truncated, so I still have to cut & paste from my hugo blog to dev.to.

**To Reproduce**

1. Go to settings, extensions, add a hugo-generated RSS/ATOM feed
2. Click the `Fetch feed now` button
3. View the imported draft posts and see that everything after `<!--more-->` was truncated.

**Expected behavior**

I expected the posts to have the entire text of the blog posts

**Screenshots**

**Desktop (please complete the following information):**

- OS, version: n/a
- Browser, version: n/a

**Comment by rhymes** [comment]
Hi @unixorn, could you provide us with the link to your feed and DEV account? Thank you!

**Comment by rhymes** [comment]
Is this the feed? https://unixorn.github.io/post/index.xml

From a first look I can see it doesn't contain the actual posts. Only a description. You'll probably have to change your website's configuration so that the feed contains the full post. 

You said you use Hugo, this guide should help: [Displaying the Full Content in Hugo's RSS feed](https://blog.eternalrecurrence.space/posts/displaying-the-full-content-in-hugo-rss-feed/)
