### ISSUE TITLE
Typo in FAQ page

### ISSUE THREAD

**Issue by supzi-del** [forem/forem#14004]
**Describe the bug**
It should be "Upon Sign In", rather than "Upon sign".

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/78655439/122283271-ff4fb080-cf09-11eb-9bbe-cccb3a7d76bb.png)

**Desktop (please complete the following information):**

- OS, version: Windows
- Browser, version: Chrome

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by supzi-del** [comment]
Can I work on this?

**Comment by djuber** [comment]
I think this isn't something that can be fixed with a code change - the faq page is an object in the database. 

```
forem$ bundle exec rails routes | grep faq
                                               faq GET      (/locale/:locale)/faq(.:format)                                                        pages#faq {:locale=>nil}
```

https://github.com/forem/forem/blob/main/app/controllers/pages_controller.rb#L55-L59

I think this is a valid typo but not a good candidate for a PR, someone with administrator access to dev.to would need to edit the faq page content to correct the language.

**Comment by cmgorton** [comment]
Thanks for opening this issue @supzi-del and offering to work on it! As Dan mentioned, unfortunately this will be something one of our Admins will need to fix.

**Comment by mstruve** [comment]
Fixed 💃🏻
