### ISSUE TITLE
RSS "Fetch feed now" button submits the settings instead of fetching the feed

### ISSUE THREAD

**Issue by Siderite** [forem/forem#14045]
On the dev.to website, if you go to Settings - Extensions and click on Fetch feed now the form gets submitted instead of fetching the feed. There is no onclick handler on the button either.

**Comment by rhymes** [comment]
Hi @Siderite, the submit is by design. All sections of of the profile settings submit to the server :)

I tested the functionality and it's importing the feed.

Let me know if I'm not missing something, in the case you're requesting a different behavior, that's likely a feature request and I would defer you to https://forem.dev/

Hope this helps 🙌
