### ISSUE TITLE
Mobile experience for smaller screens

### ISSUE THREAD

**Issue by Mellen** [forem/forem#14062]
**Describe the bug**

When I am creating a comment on my mobile phone quite often I can't see what I am typing because the cursor is below the heart/unicorn/read later icons or underneath the moderator button. Now, my phone is relatively old, so it might be that newer phones with higher resolution screens don't suffer from this, so this might be a niche issue. 

**To Reproduce**

Write a comment that is a few paragraphs long. 

**Expected behavior**

I expect the editing box to not be hidden by anything 

**Screenshots**

![Screenshot_20210624-090901.png](https://user-images.githubusercontent.com/127148/123228683-8f26c900-d4cd-11eb-8e66-7f558c13dc76.png)

**Smartphone (please complete the following information):**

- Device: Sony Xperia XZ 
- OS, version: android 8.0.0
- Browser, version: Firefox 89.1.1

**Additional context**

**Comment by fdoxyz** [comment]
Hello @Mellen, thank you for the report.

It seems like Firefox doesn't hide the URL bar and is also bumping up the "safe area" when the keyboard is active, which makes the reaction bar move up and appear visible. Both of these are taking up quite a bit of screen area. 

Are you on a recent Firefox version? Maybe their recent releases don't support Android 8, because I see the URL bar at the bottom of the screen and it does hide itself based on the scroll in the page. I'm on Firefox version `89.1.1` on a 
Samsung device.

We need to consider a few things before working on this, but to share an initial idea for how to improve the experience here: We could hide the mod center button & reaction bar when a comment input field is focused (ideally only for small screens).

For now my only suggestion to help you regain some screen area would be to go into https://dev.to/settings/customization and configure the Site Navbar to **Static top of page**. It's definitely not a solid solution, but it may help in the mean time we improve on this.

**Comment by Mellen** [comment]
@fdoxyz thank you for the helpful tip. I will look into that.

**Comment by benhalpern** [comment]
> We need to consider a few things before working on this, but to share an initial idea for how to improve the experience here: We could hide the mod center button & reaction bar when a comment input field is focused (ideally only for small screens).

I think this is fine.

Logic: 

- If small screen (less than 400 wide/600 tall) and it is a touch device
- On focus, hide these elements.
- On blur, show these elements again.

The functionality for detecting the focus of these elements is present on `initializeCommentsPage`, so this functionality could be added as a new function within those events, as far as handling this as an issue goes.

**Comment by keshavbiswa** [comment]
I can take this up :)

**Comment by code-reaper08** [comment]
## Hello can I take this issue (•‿•)

**Comment by citizen428** [comment]
Thanks for volunteering @code-reaper08, I assigned you the issue.
