### ISSUE TITLE
Comments/Replies don't send or they repeat.

### ISSUE THREAD

**Issue by Yuma-Tsushima07** [forem/forem#14183]
**Describe the bug**
Once you comment or reply to a person the reply/comment does not send.

**To Reproduce**

1) Go to your posts.
2) Comment / reply to a person. 
3) Try sending and wait for 1 min.
4) Refresh (Doesn't show up).

**Expected behaviour** 

Comments and replies should be sent and shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/63207324/125073238-8e885800-e0b3-11eb-8ebe-6e3e167969cb.png)
> Commented on post

![image](https://user-images.githubusercontent.com/63207324/125073318-ae1f8080-e0b3-11eb-81b0-c4cd7d021e06.png)
> Preview working 

Although submitting is not working well. 

**Desktop:**

- OS, version: Windows 10
- Browser, version: Chrome (Latest)

**Smartphone:**

- Device: Samsung Note 9
- OS, version: Dev.to App (Current Version)

**Additional context**

**POC** 

https://user-images.githubusercontent.com/63207324/125074866-c7c1c780-e0b5-11eb-9b24-35c8f4fa9cac.mp4

> Proof of Concept

**Comment by Link2Twenty** [comment]
When I try and post a comment I get this error

![error message](https://user-images.githubusercontent.com/3534427/125090285-175cbf00-e0c7-11eb-9171-3b470be4dba5.png)

But it does actually post

**Comment by Yuma-Tsushima07** [comment]
@Link2Twenty I really don't know why posts aren't working. 

To your error it seems like it's related to another post.

**Comment by Afif13** [comment]
and sometimes the comment is posted more than once. 

![Screenshot from 2021-07-09 22-12-01](https://user-images.githubusercontent.com/14073250/125131287-cd91ca00-e102-11eb-90c1-7af3d36b29dd.png)

**Comment by nickytonline** [comment]
I can replicate this. When you click submit it creates the comment, but the UI does not refresh. @Link2Twenty, the error you get is because you kit the submit button a second time. Looking in the browser console, there is no JS errors when submitting the comment, and the network request appears to submit it fine. Maybe there is some frontend functionality that regressed. 🤔

It appears to send 0 bytes for some reason, but no errors as it's pending.

![image](https://user-images.githubusercontent.com/833231/125134623-a1138900-e0d5-11eb-9e50-2aa7c3ef78de.png)

However, after a certain amount of time it produces an HTTP 503.

![image](https://user-images.githubusercontent.com/833231/125134665-ba1c3a00-e0d5-11eb-85a2-a46e4590430f.png)

Which is why I believe the UI does not refresh.

**Comment by Yuma-Tsushima07** [comment]
@nickytonline That makes sense. 
Why is there such delay in  their system?

**Comment by nickytonline** [comment]
We are currently investigating the reason for the delay @Yuma-Tsushima07.

**Comment by Yuma-Tsushima07** [comment]
> We are currently investigating the reason for the delay @Yuma-Tsushima07.

Ahh thanks for the update :)

**Comment by mstruve** [comment]
This was a backend performance issue caused by a recently introduced bug. With the above merged PR this should be fixed! Thanks for reporting it!
