### ISSUE TITLE
Mobile app push notifications

### ISSUE THREAD

**Issue by jmoney** [forem/forem#14189]
I have suddenly started receiving push notifications for posts I'm not following or have even read. Have never commented either but I've received push notifications for them letting me know of updates.

**Comment by Bas-Man** [comment]
![image](https://user-images.githubusercontent.com/6175103/125151658-cdd1aa00-e182-11eb-98a1-7c7f626e6d52.png)

![image](https://user-images.githubusercontent.com/6175103/125151709-ff4a7580-e182-11eb-9f99-bd76fd0ca229.png)

**Comment by Bas-Man** [comment]
Resolved by #14186?

**Comment by fdoxyz** [comment]
Thank you both for reporting this. We noticed the bug and it was indeed fixed by #14186. A backlog of notifications did went out by mistake, but it is now resolved. 

We sent out an email to those affected with a bit of context as well. I'm sharing it here in case it didn't reach you or anyone else (the link points to #14186):

<img width="591" alt="Screen Shot 2021-07-11 at 08 38 32" src="https://user-images.githubusercontent.com/6045239/125199537-e04ff000-e223-11eb-8d90-81df65daf55c.png">
