### ISSUE TITLE
Eager loading warning in the Dashboard when a user has posts in a series

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#14429]
**Describe the bug**

This came to light when adding Cypress tests for an unrelated PR which required a post to be added to a series. If your dashboard includes posts which belong to a series, you see this bullet warning at the bottom of the page:

![screenshot of bullet warning error stating that we are eagerly loading article collection](https://user-images.githubusercontent.com/20773163/128490621-a3ad8a52-7d8b-47dd-a8f6-f96e5885c315.png)

**To Reproduce**

- Run the app locally
- Publish an article that is part of a series
- Visit your Dashboard (e.g. via the member nav menu)
- Notice the warning that appears at the bottom left

**Expected behavior**

We shouldn't see the warning

**Screenshots**

(see above)

**Comment by rhymes** [comment]
These errors are only shown in development mode to nudge devs to make sure they load all the data they need, in order to avoid [N + 1 queries](https://semaphoreci.com/blog/2017/08/09/faster-rails-eliminating-n-plus-one-queries.html).

So yeah, it's worth investigating but I just wanted to highlight that it's not shown to end users in production :)

**Comment by aitchiss** [comment]
Yeah definitely, you have to run locally to see it. It does cause Cypress tests to fail though 🙁

**Comment by aitchiss** [comment]
Closed by #14677 - thanks @vishaldeepak!
