### ISSUE TITLE
Can tags support non-ASCII characters

### ISSUE THREAD

**Issue by krongk** [forem/forem#14422]
Tag name not support non-ASCII characters like 中文。

**Comment by djuber** [comment]
Hi @krongk - I know this was disabled intentionally at one point (see linked PR) because a url method was not sanitizing the link to the tags (at the time that resulted in an error displaying the page, rather than just a mangled tag). I believe we could revisit this since #13720 - as we no longer produce the invalid URL or the error, the original reason for the ascii only character filtering seems to have been removed.

Removing or relaxing the rules added in #9006 would be the right first step to test if this works as expected.
