### ISSUE TITLE
Given profile image is not used on email signup 

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#14432]
**Describe the bug**

When I sign up for a Forem via email, it does not take the image I use. It gives me a random default instead.

**To Reproduce**

- Visit https://www.rectangle.community/
- Create account
- Notice it does not use the image you put in the form

I am not sure if this problem is exclusive to self-host or also a problem on Forem Cloud — the way images are handled in these contexts is different, but this _seems_ like more application logic issues.

It doesn't seem to be affecting social sign up.

**Expected behavior**

The image I upload is the one used in my account. I can later fix this, but it's a bad initial experience.

**Comment by gogi2811** [comment]
I can take this up too.

**Comment by cmgorton** [comment]
Thanks @gogi2811 ! If you find working on two issues is too much just let me know. Appreciate your help🙏

**Comment by gogi2811** [comment]
I found one more issue,
via Forem ios app when I try to sing-up with the email following below steps

- Visit https://www.rectangle.community/
- Create account
I am thrown back to home page the moment I select the image for my account.
is not happening when go via web browser.

**Comment by benhalpern** [comment]
Good catch @gogi2811 — Can you create a separate issue for that bug? (And feel free to fix it if something hits, you but no pressure).

Let us know if you need help with this one.

**Comment by fdoxyz** [comment]
> I am thrown back to home page the moment I select the image for my account.
is not happening when go via web browser.

Hi @gogi2811, thanks for bringing up this situation with the iOS app. This was indeed caused by a bug in the app itself and a fix for it was just shipped to our Testflight beta releases. We hope to publish the build to the AppStore for everyone to update soon.

The original bug mentioned in the issue does seem to be a separate problem. Let us know if you need any help.
