### ISSUE TITLE
Bug with scroll down on API Doc

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#14536]
**Describe the bug**

When you scroll, you could bump to the top of the page.

**To Reproduce**
Scroll down to the [API Doc](https://docs.forem.com/api/).

1. Go to https://docs.forem.com/api/
2. Scroll down
3. You can see a lapse of time the top of the page
4. Scrolled up

**Expected behavior**

Don't scroll up. 

**Screenshots**

https://user-images.githubusercontent.com/14293805/129925047-40854620-440d-4124-9365-d5b3cecd7bf0.mp4

**Desktop (please complete the following information):**

- OS, version: Windows 10 
- Browser, version: Chrome 92.0

**Comment by cmgorton** [comment]
Hey! This is a known bug that  we have been unable to fix because the docs are built with GitDocs which unfortunately doesn't support custom styling & is no longer maintained. 

Because of this we have actually moved our docs to a new platform(Docusaurus) and repo https://github.com/forem/forem-docs that should be available soon. 
We are just finishing a few things before changing the link in our current repo to point to the new docs 😄

**Comment by thomasbnt** [comment]
Oooh okay ! Good news!

**Comment by thomasbnt** [comment]
Okay bad news, same bug with **Docusaurus** but only on Chrome *Version 92.0*.

https://user-images.githubusercontent.com/14293805/130807209-62c0b049-2174-489f-bfc0-33dbe50813a4.mp4

On Firefox *Version 91.0.2* he work.

https://user-images.githubusercontent.com/14293805/130807794-c4e3be99-7ffd-41d9-aec9-22aa4de17bb4.mp4

**Comment by thomasbnt** [comment]
Hello, this bug is always here :c
