### ISSUE TITLE
Error When Adding or Removing Tags through the Moderation Panel 

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#14554]
**Describe the bug**
When attempting to add or remove a tag through the moderation panel on a tag's page, an error pops up, making it seem like the tag was unsuccessfully added or removed. While it appears that the addition or removal of the tag fails, it actually updates as expected.

**To Reproduce**

_**When adding a tag:**_
- Visit the moderation page for a particular tag (`http://localhost:3000/mod/<tag_name>`)
- Select the post that you'd like to moderate
- Click on the "Adjust tags" dropdown and attempt to add a tag to the post:
![Screen Shot 2021-08-19 at 12 38 34 PM](https://user-images.githubusercontent.com/32834804/130126772-d0d99e97-3373-49d2-a1c5-55c13d1a4cd3.png)
- Upon clicking "Submit" observe that an error pops up:
![Screen Shot 2021-08-19 at 12 38 41 PM](https://user-images.githubusercontent.com/32834804/130126866-b4ccd5cf-2f16-4d47-934c-a6f6a1b4ff11.png)
- After clicking "OK" to close the alert, navigate to your notifications and observe that the tag appears to have been successfully added. Additionally, navigate to the post that you added the tag to and see that it also appears as expected:
![Screen Shot 2021-08-19 at 12 38 51 PM](https://user-images.githubusercontent.com/32834804/130127643-f5ddb073-9095-47ec-956d-e389b2e451ed.png)
![Screen Shot 2021-08-19 at 12 54 14 PM](https://user-images.githubusercontent.com/32834804/130127715-b5fd2d8f-a7ec-4aca-b9f8-be7c430f07db.png)

_**When removing a tag:**_
- Visit the moderation page for a particular tag (`http://localhost:3000/mod/<tag_name>`)
- Select the post that you'd like to moderate
- Click on the "Adjust tags" dropdown and attempt to remove a tag from the post:
![Screen Shot 2021-08-19 at 12 36 15 PM](https://user-images.githubusercontent.com/32834804/130128548-5b504f85-55cb-4bd8-b29b-8e99149eb61d.png)
- Upon clicking "Submit" observe that an error pops up:
![Screen Shot 2021-08-19 at 12 36 26 PM](https://user-images.githubusercontent.com/32834804/130128566-bdca6ced-dd1e-4fc4-8e89-ff98319464dc.png)
- After clicking "OK" to close the alert, navigate to your notifications and observe that the tag appears to have been successfully removed. Additionally, navigate to the post that you removed the tag to and see that it also appears as expected:
![Screen Shot 2021-08-19 at 12 36 53 PM](https://user-images.githubusercontent.com/32834804/130128636-c18563e9-fdc9-47ca-bf1e-0532badc34ec.png)
![Screen Shot 2021-08-19 at 1 00 58 PM](https://user-images.githubusercontent.com/32834804/130128660-9494c98f-a0ed-45da-b1a0-5e38d982d98f.png)

**Expected behavior**
When moderating a tag, I should be able to add and remove tags from a post without encountering an error in the form of an alert popup.

**Comment by djuber** [comment]
confirmed behavior - the POST to /tag_adjustments works (the tag is either added or removed and a success code is returned by the system) but ( js ) errors are shown. 

The error displayed in firefox for addition is _slightly_ better than chrome's (rather than only saying undefined, it tells you the variable name which was undefined):

TypeError: can't access property "appendChild", articleTagsContainer is undefined

![Screenshot from 2021-08-19 15-24-28](https://user-images.githubusercontent.com/1237369/130138869-c0e8166d-81df-4018-96b3-30277a306301.png)

This appears to be coming from that actionsPanel https://github.com/forem/forem/blob/main/app/javascript/actionsPanel/actionsPanel.js#L192-L211 (where we add the tag to the article?)

I noticed we look to the _end_ of the path, which excludes /mod/java (where java is a tag name) and falls in to the else clause of the 

```javascript
 if (top.document.location.pathname.endsWith('/mod')) {
```

I'm not sure that's the problem but this feels like the right place to look for the problem.
