### ISSUE TITLE
Forem mobile app - login with Facebook no longer supported

### ISSUE THREAD

**Issue by leewynne** [forem/forem#14681]
**Describe the bug**

When attempting to logon to facebook, error is returned by facebook stating that embedded browsers are no longer supported.

**To Reproduce**

From the Forem mobile app go to www.thismmalife.com or www.flowstate.to and attempt to login via Facebook

**Expected behavior**

Successful login

**Screenshots**

![image](https://user-images.githubusercontent.com/12694270/132395612-7a163fa8-14ca-4c8a-8514-303707a3fc6c.jpeg)

**Comment by cmgorton** [comment]
@joshpuetz @fdoxyz . Any ideas on why this might be happening?

**Comment by leewynne** [comment]
Found some more context

https://developers.facebook.com/community/threads/195638179128499/

**Comment by fdoxyz** [comment]
This feels odd because I can't replicate on iOS `14.5` & `15.0` both on device+simulator. @leewynne could you please share your device model & OS?

I remember researching about Facebook's embedded restrictions after your feedback through Testflight (thanks for that 🙏 ), and it appeared like it would only affect Android devices (based on [link 1](https://developers.facebook.com/community/threads/195638179128499/) & [link 2](https://developers.facebook.com/blog/post/2021/06/28/deprecating-support-fb-login-authentication-android-embedded-browsers/)). We [took note](https://github.com/forem/forem-android/issues/28) of this for the Android app.

This is what happens to me at the moment:

https://user-images.githubusercontent.com/6045239/132408708-1989824c-7b51-40f3-8904-714e1cc9bf14.mov

**Comment by joshpuetz** [comment]
I found a note about Facebook deprecating support for login in via embedded browsers/webviews on Android, but they don't call it out as being deprecated for iOS. There's also a comment on [this thread](https://developers.facebook.com/support/bugs/3839475259507329/) that makes it sound like it might not be supported based on user as well (I CAN replicate this bug on my device)

@fdoxyz @JennieOcken I think we're going to have to rethink our login strategy/implementation on mobile for Facebook. I suspect they want use to use their custom API.

**Comment by joshpuetz** [comment]
(Keeping this issue in the Forem repo so it's publicly visible, but it really should be in the Forem-iOS repo)

**Comment by leewynne** [comment]
Confirmed from my testing that this depends on the FB account. 1 works for me, 1 doesn't

**Comment by joshpuetz** [comment]
Thanks for verifying that @leewynne! I'm guessing we're going to have to switch over to using Facebook's native SDK for processing logins on iOS 😦

**Comment by JennieOcken** [comment]
I don't see how we have any other choice but to make this change.  I would love to understand size and any risks you see.  But if Facebook wants us to use their SDK, that is a reasonable ask.

**Comment by fdoxyz** [comment]
Given that Android (within WebView) support will be completely shut down and we are seeing intermittent (almost arbitrary) errors on iOS I also think it would be best to make the move away from the current web-based OAuth flow for Facebook.

I would say there are at least a couple of ways forward from here:

1. Use Facebook's [JS SDK](https://developers.facebook.com/docs/javascript/) to authenticate
2. Use Facebook's native SDKs [iOS](https://developers.facebook.com/docs/ios/)/[Android](https://developers.facebook.com/docs/android/) to authenticate

Option 1 makes it so that we only need to refactor this authentication method on the web app (`forem/forem`). Option 2 would need to be implemented on both iOS and Android separately.

> I would love to understand size and any risks you see

The only worry in mind for me right now is how we have standardized our social authentication code to be very reusable, based on the current OAuth standard flow.

I will personally start fiddling with Option 1 because it would likely be better for native apps not have to worry about one-off authentication in this special case, but I do welcome other's thoughts into the pro's/con's here.

**Comment by joshpuetz** [comment]
I'm curious @fdoxyz: could we switch to using FB's JS SDK for both mobile AND the full desktop experience? It would be nice if we didn't have to punch out an exception JUST for mobile login with Facebook

**Comment by fdoxyz** [comment]
> It would be nice if we didn't have to punch out an exception JUST for mobile login with Facebook

I totally agree and I'm confident it can be done that way.

I do have to experiment a bit since it's something completely different than our previous OAuth flow. So whenever I get to a working auth flow I'll share a PR so we can test it using a selfhost deployment (because I can't seem to replicate the problem myself).
