### ISSUE TITLE
Issues with feed updates

### ISSUE THREAD

**Issue by rafaelbernard** [forem/forem#14705]
**Describe the bug**

Recent posts from my website feed are not being synced at my dev.to dashboard. I try to force fetching posts from the feed, but no luck so far.

**To Reproduce**

1. Go to  'settings'
2. Click on 'Extensions'
3. In the section 'Publishing to DEV Community from RSS' click on 'Fetch feed now'
4. There is no error and last fetched info is updated

**Expected behavior**

Most recent posts from my blog are shown on the dashboard as drafts.

**Screenshots**

![image](https://user-images.githubusercontent.com/854711/133002930-c56cf59b-98e6-408b-910e-ddc3a776a00f.png)

Obs.: I manually created the last post

**Desktop (please complete the following information):**

- OS, version: Arch linux
- Browser, version: Brave 1.29.79

**Comment by djuber** [comment]
I tested this locally against https://rafael.bernard-araujo.com/feed (trying to import the articles into a development environment after setting the setting as suggested in your steps to reproduce) - it looks like the posts/articles are not created because of a  non-ascii tag (we're reading this from the category field in the rss item):

```
 :error_message=>"Validation failed: Tag \"miscelânea\" contains non-ASCII characters"
```

I assume the same error will happen when the category is Tropeçando (because of `ç`) - however the feed import stopped on the first error.

This is an open issue (https://github.com/forem/forem/issues/14422) - currently any article with a tag/category with a non-ascii character will fail to validate and then fail to be staged as a draft. Fixing the tag restriction will also overcome the issue with the rss feed.

The only work-around I can think of right now would be to remove the portuguese category/tag names that are being rejected (that's not a great suggestion).

I'll see if we can get traction on addressing the underlying/linked issue this week.

**Comment by rafaelbernard** [comment]
Thanks for the response and for trying to address it, Daniel.

It must be something introduced quite recently because I have imported other `tropeçando` tags and categories posts in the past, as you can see in my screenshot.

Best,
Rafael

**Comment by djuber** [comment]
Hi @rafaelbernard - we just deployed the [tag fix](https://github.com/forem/forem/pull/14710)  - it looks like there's up to a 4 hour delay on feed imports for any user, but I expect this will address the issue you're seeing with posts not showing up from RSS sometime today. The change definitely did result in the expected behavior of imported posts showing as  draft articles for me when testing.
