### ISSUE TITLE
Add tag autocompletion during post authoring

### ISSUE THREAD

**Issue by citizen428** [forem/forem#14751]
📖 As a content creator, I want to select tags from a dropdown of popular tags when creating my posts.

This has two parts:

* [x] A backend API for getting a list of popular tags
* [x] A frontend implementation for the dropdown

**Comment by SiddharthShyniben** [comment]
Aren't tags already autocompleted? Or do you mean an always-there list of tags which are inferred from the content?

**Comment by aitchiss** [comment]
> Aren't tags already autocompleted? Or do you mean an always-there list of tags which are inferred from the content?

Yes the idea is that before you start typing and searching, we'll auto-suggest some of the most popular tags to save people hunting for them 🙂

**Comment by amywtlin** [comment]
Post launch tracking: https://forem-team.slack.com/archives/C02B5U7N13P/p1632455709038000

The hypothesis is that people write about things that are related to the top tags. If we see people start using adding these top tags, we should see fewer # of API requests to search to add a tag, making this a good metric for us to see if we have any adoption on the new feature. We should also factor in # of articles published, to normalize the # of API requests, instead of looking at the absolute number of it.

To do:
- [ ] Get baseline numbers on (# of API requests to search for a tag) / (# of published articles), on a daily level
- [ ] Come back again 2 weeks later to observe if the number is trending down

**Comment by amywtlin** [comment]
Data dashboard set up thanks to the great @citizen428: https://app.datadoghq.com/dashboard/7di-zph-dns/content-experience-pod?from_ts=1633676856321&to_ts=1633680456321&live=true

Setting up a reminder in my calendar to check in on the stats.

**Comment by aitchiss** [comment]
closed in https://github.com/forem/forem/pull/14817
