### ISSUE TITLE
Toolbar for editor

### ISSUE THREAD

**Issue by citizen428** [forem/forem#14808]
## What this is about
Adding a toolbar to facilitate inserting markdown formatting syntaxes

## Background/Why
This is the first milestone of #14807, with the goal to make the editor easier and more intuitive. 

### Supported ways of inserting syntaxes
We are supporting 2 new ways of inserting syntaxes, besides directly typing them:
1. Clicking on a button to insert syntaxes, for example, clicking `B` button to insert `**` in the editor 
2. Hitting keyboard shortcuts to insert syntaxes, for example, hitting `ctrl/cmd+B` to  insert `**` in the editor
## Behaviors after inserting syntaxes
1. If certain text selected when inserting a syntax, using either way, the syntax should be added surrounding the text:  selecting `my selected text` => clicking  `B` from the toolbar to bold => `*my selected text*`
2. If nothing selected when inserting a syntax, then the syntax will be added where the cursor location is.
## Supported syntaxes
All existing formats are supported through the toolbar. Only a selection of keyboard shortcuts are supported, specifically those formatting selected texts. Here is a list of all formats: 
- Bold (cmd/ctrl+B)
- Italic (cmd/ctrl+I)
- Link (cmd/ctrl+K)
- Underline (cmd/ctrl+U)
- Strikethrough (cmd/ctrl+shift+X)
- Unordered list
- Ordered list
- Quote
- Code
- Code block
- H2..H4
- Line divider 
- Liquid tags
- Media uploader

## Not in scope
We are only enabling "inserting syntaxes" in this milestones. Real-time WYSIWYG rendering is not included in this one, instead is in the scope of #14794.

We are also not supporting tables at the moment as they are much more complex to handle.

## Design
Here's [working file showing visuals and some interactions](https://www.figma.com/file/FUiX2HXkQf5Y2spG25cRgA/Editor-Toolbar?node-id=0%3A1).

## Tasks

- [x] https://github.com/forem/forem/pull/14876 (basic first version of toolbar in Storybook)
- [x] https://github.com/forem/forem/issues/15263
- [x] #15294
- [x] #15114
- [x] #15115

**Comment by ludwiczakpawel** [comment]
While on this, we should also improve the "Image upload" button behavior - because right now it doesn't actually insert the syntax in the editor but shows a field to copy'n'paste it 🤷 

One could argue this should be a separate issue/rfc but behavior of this particular control (showing that extra field) will certainly impact overall toolbar structure in negative way.

**Comment by aitchiss** [comment]
> If certain text selected when inserting a syntax, using either way, the syntax should be added surrounding the text: selecting my selected text => clicking B from the toolbar to bold => *my selected text*

I wonder how this will work for all of the toolbar options - e.g. what happens if I highlight a chunk of text and click the unordered list button? Does everything highlighted become the first bullet point? Does everything with a new line become a bullet point?

Similar with links - I guess we probably want to do something intuitive like if the selected text looks like a URL, place it in the round brackets, otherwise place it in the square brackets? e.g. `[I don't look like a link]()` and `[](https://link.com)`

I think we also agreed in the chat to descope the table for now.

**Comment by ludwiczakpawel** [comment]
> I wonder how this will work for all of the toolbar options - e.g. what happens if I highlight a chunk of text and click the unordered list button? Does everything highlighted become the first bullet point? Does everything with a new line become a bullet point?

When in doubts, lets mimic Slack or GitHub.. Not like I wanna rip off other work but we should not re-invent the wheel and follow existing patterns people got used to. In this case GitHub does it pretty well - it's exactly what you described and that would be my expectation too.

**Comment by aitchiss** [comment]
Just adding for visibility - accessible authoring practices for the toolbar that we can follow: https://www.w3.org/TR/wai-aria-practices/examples/toolbar/toolbar.html

**Comment by ludwiczakpawel** [comment]
Underlin

**Comment by ludwiczakpawel** [comment]
Couple things...

### Underline

I've just noticed that markdown doesn't really support underline. I mean it support HTML and therefore you can force underline, buuut even [with HTML it's not so "obvious"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/u)... 

There are other more obvious ways for "highlighting" text. Also, underline style is used for links so this could be potentially confusing for ppl with color blindness (?).

### Overflow menu

This also brings another thing.. Current list of tools is pretty long and I'm curious about importance of these tools. There are tools that I feel could be "hidden" in the overflow menu ("three dots" button with dropdown).. In particular I'm thinking about:

1. Underline
2. Strikethrough
3. Line divider
4. Table (in future)

### `H2..H4` interaction

We said that we want to support header H2, H3 & H4. This limitation makes sense in my mind but my question is: what supposed to happen when you hit that [H] control in toolbar? 

- GitHub inserts `###` (`H3`) right away.
- Hashnode has a dropdown with 3 levels (`H1`, `H2`, `H3`) to select from.
- I've also seen solutions when clicking through [H] iterates through available headlines (clicking once inserts `H1`, clicking twice inserts `H2` and so on...

### `H2..H4` vs `H1..H3`

We want to keep good semantics (for SEO) that's why we "reserved" `H1` for post title (so something you can't edit through toolbar) therefore we ended up having `H2..H4`. But:

1. Users can still manually enter H1 in markdown...
2. I don't even know if having only one H1 element on page is still a thing (it used to be important for SEO 10 years ago).

So my question is which 3 levels of H we should keep? `H1..H3` or `H2..H4`. 
And also if we go with `H1..H3` we could still say "Headline 1, Headline 2, Headline 3" but insert markdown for `H2`, `H3` & `H4`.

### Liquid tags

What do we want to do about this UI control now? I'm pretty confident that in future we would like these to be generic embeds ([1](https://docs.google.com/document/d/1tZVdZ74E4BV1hfGeieG4N83ih7MUCREG5Jej6DBzXaY/edit#heading=h.yt9trs9bzwco) & [2](https://docs.google.com/document/d/1TDTeFCfWuFq3l0spkCUIQ9nw--BewIShnnqJ5Q_Ptlo/edit#heading=h.pfluud58zyjd)) so it should be easy then. So for now I can see three options:

1. Make "global liquid tag" a dependency for this project, meaning we would have to tackle it first to move on with 
2. Have "liquid tag" control that would open w dropdown with list of available liquid tags to pick from (clicking one would insert appropriate code) 
3. Continue work on toolbar without adding liquid tags control - we would add it when it's ready (probably the most sensible solution).

**Comment by citizen428** [comment]
> I don't even know if having only one H1 element on page is still a thing (it used to be important for SEO 10 years ago).

It is for accessibility. This is why we include the following warning if a user manually inserts an H1 tag:

![H1 tag warning in Forem editor](https://user-images.githubusercontent.com/47985/135385872-90413a2f-3edc-4bd8-9a66-c29d671abaa3.png)

**Comment by citizen428** [comment]
> Continue working on toolbar without adding liquid tags control - we would add it when it's ready (probably the most sensible solution).

This is what my vote goes to. The toolbar is something we really want, making something potentially quite complicated a dependency would delay this by quite a bit.

**Comment by aitchiss** [comment]
> Also, underline style is used for links so this could be potentially confusing for ppl with color blindness (?).

Potentially, but links have other affordances that underline text doesn't (e.g. hover/focus effect, pointer cursor) so I wouldn't worry about it too much 🙂  

> We said that we want to support header H2, H3 & H4. This limitation makes sense in my mind but my question is: what supposed to happen when you hit that [H] control in toolbar?

Yeah this is tricky I think. I like the idea of hitting the `H` more times to increase the heading level _but_ I don't think that helps users that aren't familiar with markdown. It would only be intuitive if you already knew how heading level structures work in markdown.

I think the most user-friendly is the dropdown of options... potentially more annoying for users who _are_ familiar with markdown, but there's nothing to stop those users just typing the syntax.

> So my question is which 3 levels of H we should keep? H1..H3 or H2..H4.
> And also if we go with H1..H3 we could still say "Headline 1, Headline 2, Headline 3" but insert markdown for H2, H3 & H4.

Yeah this is so tricky 😅  From an accessibility/semantics POV it would be better to not allow people to use H1... _but_ people aren't going to understand why. I don't like the idea of calling it 'h1' but inserting 'h2', purely because DEV/CodeNewbie/people who know md users are going to think it's a bug. 

Having a duplicate `h1` on the page is more like 'breaking best practice' than a hard and fast error, so on balance I think leaving inserting h1 as an option might be best for the overall experience. We have the 'accessibility suggestions' banner in the preview to encourage people to avoid it.

> Continue working on toolbar without adding liquid tags control - we would add it when it's ready (probably the most sensible solution).

Yeah, another +1 to this from me 👍

**Comment by ludwiczakpawel** [comment]
So here's my _current_ take on Headlines implementation:

1. Let's go with H2..H4 for accessibility/SEO reasons.
2. In terms of interaction, let's go with hitting [H] once inserts `##`, twice inserts `###` and 3 times inserts `####` - people familiar with markdown will less likely use toolbar anyway for headlines (or actually anything). So if they want to use H1 `#` fine, we keep prompting them about this as we do today. And people using toolbar will just have to accept it.. It's not like a big deal for them since they may not know that syntax anyway 🤷‍♂️ . 
3. We don't have to tell anywhere WHICH exactly level of headline is going to be entered - in the tooltip we will just say "Headline" - we're also not going to show generated markup (literally HTML code) anywhere...

**Comment by amywtlin** [comment]
> While on this, we should also improve the "Image upload" button behavior
I looked at the [current behavior](https://www.loom.com/share/92d24599691c436b9cc141ebca0f34f5
), and the process is like this: 
1. Click on the button "Upload Image"
2. Select a file from the file selector
3. The system will generate a string for you to copy and paste into your article

I think with the introduction of the toolbar, 
1. this "Upload Image" button should also be tucked inside the toolbar as one of the toolbar buttons. 
2. Step 2 remains the same
3. Step 3 needs to be a separated component, such as a popup or so <= This one needs explicit design support

@ludwiczakpawel Does this feel like what you have in mind?

**Comment by amywtlin** [comment]
>I wonder how this will work for all of the toolbar options - e.g. what happens if I highlight a chunk of text and click the unordered list button? Does everything highlighted become the first bullet point? Does everything with a new line become a bullet point?

I think the common behavior for ordered or unordered lists is, if you select a block of text that contains several paragraphs (detected by line breaks), the ordered/unordered syntaxes would be added in the beginning of each paragraph (yup, just [tested it as I typed here](https://www.loom.com/share/503ec80479f5445cbe678bb731ccba82))

> Similar with links - I guess we probably want to do something intuitive like if the selected text looks like a URL, place it in the round brackets, otherwise place it in the square brackets?

Yes and agree with Pawel here - when in doubts, mimic Slack or GitHub is good enough.

**Comment by amywtlin** [comment]
> I think we also agreed in the chat to descope the table for now.

@aitchiss I might be mistaken, but I thought it is rendering of tables that is tricky, not the inserting. Is that so though? If the inserting is also tricky, then we can certainly drop this one for now.

**Comment by aitchiss** [comment]
> @aitchiss I might be mistaken, but I thought it is rendering of tables that is tricky, not the inserting. Is that so though? If the inserting is also tricky, then we can certainly drop this one for now.

I think the insertion is where the main complexity lies, but it depends on how we want it to work. It would be easy enough to plop in e.g. 2 empty rows / 2 empty columns and let the user do the rest. 

What's more complicated is if the user has text highlighted and we want to do something "magic" to put that data into a table it's pretty difficult. Or if we want the user to have the ability to add additional rows and columns on a button press, that would also be pretty complex.

I still feel given the complexity vs (what I suspect) the usage rate of tables is, it would be best to leave this one to a future iteration.

**Comment by ludwiczakpawel** [comment]
> > @aitchiss I might be mistaken, but I thought it is rendering of tables that is tricky, not the inserting. Is that so though? If the inserting is also tricky, then we can certainly drop this one for now.
> 
> I think the insertion is where the main complexity lies, but it depends on how we want it to work. It would be easy enough to plop in e.g. 2 empty rows / 2 empty columns and let the user do the rest.

Agree with @aitchiss - lets just skip tables for now, for 3 reasons:
1. They are not heavily used
2. Displaying tables is complex (mobile).
3. Creating tables even with pure markdown is pretty complex. I used to use some 3rd party generators for that. I don't think the benefit from having tables in toolbar is worth the effort needed to build it.

> 3\. Step 3 needs to be a separated component, such as a popup or so <= This one needs explicit design support
> 
> @ludwiczakpawel Does this feel like what you have in mind?

@amywtlin Here's the flow for images editor: 
![image](https://user-images.githubusercontent.com/108287/135587250-96323792-9069-4fe3-baff-2b6aae65a543.png)

**Comment by ludwiczakpawel** [comment]
(I've added [figma link](https://www.figma.com/file/FUiX2HXkQf5Y2spG25cRgA/Editor-Toolbar?node-id=0%3A1) to the description of this issue)

**Comment by amywtlin** [comment]
> It would be easy enough to plop in e.g. 2 empty rows / 2 empty columns and let the user do the rest.
100% what I was thinking. No not all the magic when you select a block of text. But yea let's skip it for now. Let me update the issue.

**Comment by aitchiss** [comment]
Added a new task to fix our `KeyboardShortcuts` component so that we're not hijacking other readline keybindings on macOS
