### ISSUE TITLE
Embedding github pull request throws error

### ISSUE THREAD

**Issue by ospatil** [forem/forem#14802]
**Describe the bug**

I'm trying to embed the following gihub pull request using the Liquid Tag: `{% github https://github.com/ospatil/nats-server/pull/2 %}`

But instead of embedding, I get Github API error as can be seen in the attached screenshot.

**To Reproduce**

1. Create a new post.
2. Embed the above mentioned pull request: `{% github https://github.com/ospatil/nats-server/pull/2 %}`.

**Expected behavior**

The github pull request should be embedded and should be visible in preview and on the post.

**Screenshots**

<img width="651" alt="devto-github-embed" src="https://user-images.githubusercontent.com/1585874/134701278-23826aea-0c57-45ec-ab10-670cd347d561.png">

<img width="976" alt="devto-github-embed-error" src="https://user-images.githubusercontent.com/1585874/134701295-be8c15fc-22b4-4603-afd4-25838e227097.png">

**Desktop (please complete the following information):**

- OS, version: macOS Big Sur 11.6
- Browser, version: Chrome 94.0.4606.61, Firefox 93.0b6

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by djuber** [comment]
I get the same 422 error when trying to fetch that pull request (which is currently a draft, not sure yet if that's important) - but I can embed this issue just fine.

https://github.com/forem/forem/blob/main/app/models/github_issue.rb#L42-L44 looks like the place this is raising an error (I can fetch the issue fine, but trying to get the html body from the text fails):

```ruby
      # despite the counter intuitive name `.markdown` returns HTML rendered
      # from the original markdown
      issue.processed_html = Github::OauthClient.new.markdown(issue.issue_serialized[:body])
```

The underlying issue appears to be that the body (which we expected to be markdown from the pull request) is nil in the api response

```ruby
issue.issue_serialized = Github::OauthClient.new.issue(repo, issue_id).to_h
{ 
...
 :pull_request=>
  {:url=>"https://api.github.com/repos/ospatil/nats-server/pulls/2",
   :html_url=>"https://github.com/ospatil/nats-server/pull/2",
   :diff_url=>"https://github.com/ospatil/nats-server/pull/2.diff",
   :patch_url=>"https://github.com/ospatil/nats-server/pull/2.patch"},
 :body=>nil, 
...
}
```

The error is raising because we're posting an empty text body to github's html rendering engine (which we would use to embed the preview).

Could you add a markdown body to the PR at https://github.com/ospatil/nats-server/pull/2 and try again?

I think this is still a bug (if we get no preview for the PR there's probably _something_ we could have shown) and we should handle the situation of an empty body by _not_ requesting a markdown->html render, or show a more meaningful error message "can't embed link to PR without a description/body".

**Comment by ospatil** [comment]
@djuber Thank you for the prompt reply. It worked after I added description to the PR as you suggested.

**Comment by djuber** [comment]
Closing in favor of #14803 since it's working for you now.
