### ISSUE TITLE
Only root user is allowed to run the `bin/setup` 

### ISSUE THREAD

**Issue by rishav-singh-0** [forem/forem#14950]
**Describe the bug**

It always requires root permission for running setup(`bin/setup`)

**Expected behavior**

Should be possible to run as a normal user.

**Desktop:**

- OS, version: Ubuntu 20.04

**Additional context**

I feel the problem is that the directory `.husky/_/` is always created as `root` owners' directory.

**Comment by djuber** [comment]
I've definitely seen this happen if you ran or attempted to run the setup for docker (since there's a mounted volume back to the repo and the docker processes run as root, and created files or directories get the root ownership), but it should not be the case if you cloned the repo as an unprivileged user and ran bin/setup on the ubuntu host. I've just tested this now on a debian host and all files are owned by the user (and there's no `.husky/_/` directory present in my working tree).

If you `chown` the problematic directory then does bin/setup succeed? 

Does `find -user root .` show _other_ files (like the bundled gem sources in vendor/, for example, or files in tmp/) getting created by root? This should only happen if you've started the app as root or run the docker setup.

I would suggest setting all ownership to your normal user, something like this in the repo tree

```bash
chown -R $(whoami): ./
```

There's nothing in `bin/setup` that would change user (`sudo` for example) to root so I'm not sure `bin/setup` is causing this, and I'm trying to get more context on how you got into this situation.

**Comment by rishav-singh-0** [comment]
Yup thats exactly what the issue was.
I first ran the docker setup then after i tried to install on locally.

I removed changed the ownership of all the files using `chown -R $(whoami): ./` as suggested and now everything is fine. 🔥🔥
Sorry i didn't tried removing only `.husky/_/` directory and rerunning `bin/setup` so i cant tell what all files were generated after running docker setup and were effecting the local setup.

**Comment by djuber** [comment]
Glad to hear that worked! I'll close this issue since it's working for you now, but I think it might make sense for us to note this incompatibility between docker setups (where root owned files are created) and local setups (where files are expected to be modified by the normal user) on the installation documentation.
