### ISSUE TITLE
Can't follow an organization from an article page, but possible from their profile

### ISSUE THREAD

**Issue by ValeriaVG** [forem/forem#15001]
**Describe the bug**
When attempted to click "Follow" button from an article, a popup was shown that it was not possible to follow the user.
The button changed to following, so I needed to reload the page to try again.

Here's the failed request from dev tools:

**Request URL**: https://dev.to/follows
**Request Method**: POST
**Status Code**: 404 
**Form Data**:
```
  followable_type: organization
  followable_id: 4094
  verb_: follow
  authenticity_token: ***
```
I went to the organisation profile page and was able to successfully click the button.

Here's the successful request:
**Request URL**: https://dev.to/follows
**Request Method**: POST
**Status Code**:200
**Form Data**: 
```
 followable_type: Organization
 followable_id: 4094
 verb: follow
 authenticity_token: ***
```

Another side effect of this bug is that I still see the "follow" button on the articles of the organisation, but "following" on the profile page.

I assume that the core of the issue is in `followable_type` field, which in the first case is sent as a lowercased `organization` and the latter request sends capitalised `Organization`

**To Reproduce**
1. Go to an article written by an organization, e.g. https://dev.to/encore/distributed-tracing-made-simple-1k1f
2. Click "Follow" button on the right
3. See an error
4. Go to the organisation profile, e.g. https://dev.to/encore
5. Click "Follow" button on the right
6. See no errors

**Expected behavior**
- I expect the "Follow" button to work the same way regardless of the page it was pressed on.
- I expect the button not to change to "Following" in case of an error
- I expect to see the same "Following"/"Follow" button on organization articles and profile

**Screenshots**
<img width="529" alt="User cannot be followed due to a server error" src="https://user-images.githubusercontent.com/5821189/136683840-ed5cff0f-f097-4d6d-9574-a2e6fad79913.png">

**Desktop:**

- OS, version: MacOS BigSur 11.5.2
- Browser, version: Microsoft Edge 93.0.961.44 (Official build) (x86_64)

**Additional context**

**Comment by prayeshshah** [comment]
I'd like to work on this for hacktoberfest.

**Comment by prayeshshah** [comment]
Update: I think I might have found the issue. As @ValeriaVG rightly mentioned, the issue seems to be with the casing of the `followable_type` param.
In the follows_controller.rb#56, there is no down casing of param `followable_type`. So, when `followable_type` value is "organization" instead of "Organization", it goes into the else block setting the followable as `User` instead if `Organization`

>followable_type: organization
  followable_id: 4094
  verb: follow
  
  In this case, the code tries to create a follow record with `followable_id` as `4094` and followable_type as `User` instead of `Organization`. If no such user exists in the database, it results in a 404.
  
  I have created a PR in an attempt to fix this. It's still in draft as I'm yet to add test cases for it.
