### ISSUE TITLE
Better Liquid tag error handling 

### ISSUE THREAD

**Issue by maestromac** [forem/forem#1511]
**Is your feature request related to a problem? Please describe.**
Whenever there's an error in the liquid tag, the editor should try it's best to inform the author what went wrong and not display the dreaded `Liquid error: internal`. This has also proven to be difficult to debug in development.

**Describe the solution you'd like**
Currently, we are making our individual custom liquid tag to raise `StandardError` upon initialization if there's an... `ArgumentError`. We are doing this because any form of error that happens within `#render` will throw a `Liquid error: internal`. 

A better solution would be to let Liquid parse normally, ie `Liquid::Template.parse(sanitized_content)`, then check for errors with `Liquid.errors`. This also has the added benefit of catching multiple errors at once, letting them be added to errors to be displayed in the view.

**Describe alternatives you've considered**
There could be a better solution I've missed in [this documentation](https://github.com/Shopify/liquid).

**Additional context**
This should also account both of our editor versions.

**Comment by rhymes** [comment]
This contains useful information as well https://github.com/thepracticaldev/dev.to/issues/7898

**Comment by marcospedro97** [comment]
This issue is available? Can I give it a try?

**Comment by maestromac** [comment]
Yes @marcospedro97 . Please give it a try!

**Comment by marcospedro97** [comment]
While working in the issue I've manged to catch more errors than we have currently, the main problem I've seen on issue #7898 is that even with the problem the post was created, using the ```parsed_liquid.errors``` in the markdown parser this wouldn't happen again, but this didn't allow me to show more than a single error in the view, I've also started asking myself if giving the line were the error occurred wouldn't be a improvement since debugging that post was clearly a problem
