### ISSUE TITLE
RSS feed contains bad links

### ISSUE THREAD

**Issue by tyler36** [forem/forem#15155]
**Describe the bug**
I primary consume the [dev.io](https://dev.to/) via the RSS and view articles that I find interesting.

Starting around a month ago, I noticed a dramatic increase in article titles that felt "familiar". If I attempted to view these, I landed on a 404 page.

These articles,eg. ["10 Tips 😍 to become a great programmer🔥"](https://dev.to/codemaniaz/10-tips-to-become-a-great-programmer-3351), generally came in batches from the same user so I assumed there was a problem with their account. 

Today, there were 4 articles in the space of 10 that were all bad. In this case, it was from user `Codemania`. I tweaked the URL to see if I could view their profile page: 
https://dev.to/codemaniaz/10-tips-to-become-a-great-programmer-3351 => [https://dev.to/codemaniaz](https://dev.to/codemaniaz)
![dev io-spam](https://user-images.githubusercontent.com/7234392/138392650-bcd5f714-7639-44e2-aa4a-cf6e8e2ae11a.jpg)

So that makes sense, good job catching the spammer! But...

While the website has been cleared, the RSS feed is still littered with "bad" links. This reflects poorly on `dev.to` because most users probably won't go the extra steps to discover it was marked as spam.

**Expected behavior**
Would it be possible to purge the RSS feed of the spammer links when a user is marked as a spammer? 
Ideally this would be done at the time of marking the "spammer".  Even hourly or daily would be good.  

I currently have articles in my feed from "23 hours ago" that are 404'ing. It's even worse after a long weekend when I can have over 500+ articles dating back to a few days ago.

![dev io-spam-2](https://user-images.githubusercontent.com/7234392/138392136-92d63c98-daa2-4657-a169-e5045a59c72d.jpg)

**Screenshots**

**Comment by jeremyf** [comment]
As an RSS user, I love my feeds.  And to have these "spam" articles show up would definitely be frustrating.

@tyler36 I'm looking into this, and wondering what's the URL of the feed you're referencing?  There's some branching logic and I want to see what path to pursue.

**Comment by djuber** [comment]
A few notes and thinking points about this

- the /feed endpoints (/rss, /feed/, /feed/tag/:tagname, /feed/:username, /feed/latest) when the response is generate, only include articles that currently exist and are published. Deleted articles are not sent in the /feed/ endpoints from the server) 
  
- the /feed/ and related rss endpoints are cached for up to 10 minutes by our network (this is probably _not_ the issue you're seeing, but it's possible if you pulled the feed immediately after a user was blocked that items listed would no longer be present - that could be the 4 out of 10  sampling you pointed to in your report).

- it sounds like you may have a background process pulling the rss feed periodically (rather than just the latest 10-12 items when you check the feed at a point in time), given that you said there are hundreds of unread posts after a weekend. In that case your local feed reader is also a cache (not governed by any cache expiration policy from the http headers, the reader would effectively keep local state indefinitely - I have unread articles from May). I'm not _aware_ of a way to "cancel" previously published articles (and I'm not sure what that would look like on our end), in a way that updating the feed to pull in more articles would remove articles from your feed reader's queue that you'd already downloaded. If there were such a "remove item" directive it's unclear how long we would need to continue advertising them in the feed: while you might pull the feed hourly or daily, other users might only update weekly or less often, we don't have a good way of knowing who may or may not have seen any particular invalidation.

The latter half of the last point looks like your core question - would it be possible to purge these from the feed.

**Comment by tyler36** [comment]
RSS reader: [Feedly](https://feedly.com/)
RSS feed: https://dev.to/feed

This morning when I logged in there are 306 articles, sorted via oldest first ("Tutorial: Write Your First JavaScript Program").
Of the 10 oldest unread, 3 of them are showing as "Not found":
- https://dev.to/reactjss/40-reactjs-projects-for-beginners-easy-ideas-to-get-started-coding-beginners-advance-22i2
- https://dev.to/reactjss/get-unlimited-btc-with-this-line-of-code-4lp6
- https://dev.to/reactjss/20-projects-you-can-do-to-become-a-frontend-master-56f0

Granted, I don't usually click _every_  article, and recently I don't click on articles that _feel_ click-bait-y / familiar. This means I'm probably missing out on some great content but it's better than the disappoint of a 404. 😢 

@djuber - Thanks for in-depth explaination. It sounds like because of Feedly's "caching" approach and RSS specs, there isn't much that can be done after something hits the feed. 

Thank you again for the update.

**Comment by djuber** [comment]
I think we can close this (there doesn't seem to be a way to remediate the issue, fetched articles which are subsequently deleted will show Not Found when they are accessed).
