### ISSUE TITLE
Cannot reach the /admin page for certain users

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#15242]
**Describe the bug**

I'm unable to reach the admin page (/admin/users/###/edit) for my DEV account and at least [one other user's account](https://github.com/forem/pii/issues/93).

**To Reproduce**

1. Ensure you have admin privileges on DEV.
2. Go to my admin page 'https://dev.to/admin/users/38578/edit'
3. See spinning robot

**Expected behavior**

I'd expect to be able to navigate to any user's admin page.

**Additional context**

I need to be able to navigate to the admin page to via and edit user roles.

**Comment by djuber** [comment]
https://app.honeybadger.io/projects/66984/faults/78734892/01FKDYE0AYD57EKBCGY3F2609B

Definitely happening here - underlying error is 

NoMethodError: undefined method `path' for nil:NilClass

https://github.com/forem/forem/blob/main/app/views/admin/users/_negative_reactions.html.erb#L9 the `reaction.reactable.path` here is failing because the reaction's reactable is missing/invalid (negative reaction exists, but the referenced post or comment was deleted, and has no path to link to).
