### ISSUE TITLE
Can't view full form on sign up

### ISSUE THREAD

**Issue by markmead** [forem/forem#15279]
**Describe the bug**

I can't scroll down to the next parts of the form on the sign up modal.

**To Reproduce**

Sign up

or visit /onboarding and step through to the "Build your profile" page, happens automatically during first login

**Expected behavior**

Lemme scroll

**Screenshots**

<img width="797" alt="Screenshot 2021-11-03 at 21 18 03" src="https://user-images.githubusercontent.com/50486078/140194350-349e22d2-b2a0-405b-8e7a-584165fb040b.png">

**Desktop (please complete the following information):**

- OS, version: MacOS 12.0.1
- Browser, version: Chrome 95.0

**Comment by djuber** [comment]
@markmead as a work-around after you've continued past this step - those questions are available for update at https://dev.to/settings (on a page, not a modal) and scrolling should work fine.

I tried to replicate this locally using the same onboarding profile fields as there are in DEV, and was unable to recreate the issue. I'm using chromium on linux, so it's possible this is mac specific, but that sounds unusual (most of our team is using chrome on  mac to develop the site). I'm even more surprised because I see the scroll bar on the side in your displayed screenshot suggesting you could scroll a little but not all the way.

There is some rounded edge on the bottom of the displayed modal that makes it unclear when the scroll is complete (I'm assuming that's not what the issue was, when I scroll down fully I get to a description for the Skills/Languages in grey beneath the text input area)

![onboarding-profile-fields](https://user-images.githubusercontent.com/1237369/140198234-5fdd6fc4-3fe6-459f-b7c0-06226a6a7ce9.png)
