### ISSUE TITLE
Creator Settings: Add validation for logo

### ISSUE THREAD

**Issue by nickytonline** [forem/forem#15350]
## Description

The logo a creator uploads has to have a minimum size of 300px x 300px.

Use the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) API to validate the image  dimensions.

![image](https://user-images.githubusercontent.com/833231/141331856-fb5dd326-b3e9-4e3a-b3cf-7b351fd8de3c.png)

@anujbhavsar96 and @Ridhwana, I asked this in the Figma, but where would you like the validation message? Inline close to the input/logo preview or a dynamic flash error message?

Esitmate: 1.25 days

**Comment by nickytonline** [comment]
@anujbhavsar96 @Ridhwana, what are the expected dimensions for the logo? Looking at DEV and the CodeNewbie Community, none of the logos are square and two they are definitely smaller than 300px x 300px.

**Comment by anujbhavsar96** [comment]
@nickytonline 

**About error:**
I would prefer an error message closer to the logo/input because it looks more relevant. If we show it above the form it might look like a page-level error, which is not true.

**About dimension:**
I the case of SVG, dimensions won't matter. It can expand. 

I think we have a logo height of 40px and based on that we adjust the width to the same aspect ratio. But I agree 300x300px looks misleading. It gives you the feeling that only 1:1 ratios are accepted.  So for PNG, we can say 

**Min. size:250x80px**

Actually, we will accept any aspect ratio. But the above mention is ideal. It doesn't break UI in mobile. We will keep the implementation the same as we have right now where height will be taken 40px and adjust the width accordingly.

**Comment by Ridhwana** [comment]
I find myself having follow up questions on the dimensions:

> Actually, we will accept any aspect ratio
If we're accepting any ratio then should we still be showing an error when they upload a logo? Instead, should we maybe show a warning to let the user know that their logo is not an ideal size, but we will continue using it if they don't upload a new one. 

Initially I was under the impression that the user will not be able to proceed if they do not meet the requirements, but based on the above it sounds like they can proceed but it will not be an ideal scenario?

I want to cc @ludwiczakpawel on this conversation too, as Pawel wrote the initial RFC so maybe there is some missing context on why initially there was a call for for a minimum size of 300x300 pixels.

**Comment by Ridhwana** [comment]
@anujbhavsar96 I'm also looking at [this RFC](https://github.com/forem/rfcs/blob/anuj/unify-display-of-forem-logos-and-image-upoload-process/text/0252-unify-display-of-forem-logos-and-image-upload-process.md) which ties into the image upload process and we specify here 300px by 300px. 

It's okay if we decided that 300px is not actually the ideal dimensions but just wanted to bring mention and we can change this requirement in multiple places if it needs to be changed. 

<img width="1095" alt="Screenshot 2021-11-12 at 10 58 32" src="https://user-images.githubusercontent.com/2786819/141439724-273074b6-6154-4297-9153-39d7059dace0.png">

**Comment by anujbhavsar96** [comment]
> If we're accepting any ratio then should we still be showing an error when they upload a logo?
What I meant was that the dimensions I mentioned are not 1:1 ratio but if they are uploading in 1:1 ratio then it's fine.

I have a better idea here. Why don't we just change the copy here? 

**Recommended size: 300x300px**

Having a square logo won't break the UI in mobile _(It does in wider logos rn)_
So here we are not specifying a particular dimension only. But we are just guiding them

-----

@Ridhwana In [this RFC](https://github.com/forem/rfcs/blob/anuj/unify-display-of-forem-logos-and-image-upoload-process/text/0252-unify-display-of-forem-logos-and-image-upload-process.md)

I suggested the logo constraints to 1:1 ratio only. But that's not the case right now. Because right now we accept any dimension and scale it accordingly in implementation.

**Comment by Ridhwana** [comment]
@anujbhavsar96  Apologies, just another follow up question - is the long term plan to restrict the sizes of the logos that can be uploaded or is the long term plan to always allow for any dimensions to be uploaded but strongly encourage them to follow a dimension guide that we provide?

**Comment by anujbhavsar96** [comment]
> Restrict the sizes of the logos that can be uploaded
This is something I and Lisa came up with. Like, use the square logo only. But now it feels like that won't be the sensible solution from the kind of different creators coming on Forem.

> Allow for any dimensions to be uploaded but strongly encourage them to follow a dimension guide that we provide?
Now, this looks like a viable long-term solution. We will strongly encourage them to follow our guide for the best results. This way we are not restricting anything

**Comment by Ridhwana** [comment]
@anujbhavsar96 thank you for answering my questions so patiently. 

> We will strongly encourage them to follow our guide for the best results. This way we are not restricting anything

I like this, I think it's a very practical solution. 

Now that I have all the background information this leads to my final question. 

Do you think we need a validation check for the logo if we're allowing them to upload any sizes or will just a message under the input specifying the recommended size suffice?

And if we decide to do a validation, do we display the validation results as a warning instead of an error?

**Comment by anujbhavsar96** [comment]
> Do you think we need a validation check for the logo if we're allowing them to upload any sizes or will a description under the input specifying the recommended size suffice?

Since we are allowing any ratios/dimensions, I don't think it requires a validation check on that. We will just make the copy change here,

**Ideally SVG, but PNG will work too. Recommended size: 300x80px.**

I changed the suggested dimension here because 300x300px gives the impression of square aspect ratio only. 
And 300x80px is similar to our Forem logo.

**Comment by Ridhwana** [comment]
Thank you @anujbhavsar96. ✨ @nickytonline, in that case, we can just make the copy change for this task, no need to add validation.

**Comment by nickytonline** [comment]
We should probably still validate it because in the case of at least a PNG. If someone uploads a huge logo, we don't want that to be in the header of the site for performance reasons and it will look terrible.

One other thing to note is if they upload a PNG, they'll need to convert it to an SVG as it currently shows up as just text.

![image](https://user-images.githubusercontent.com/833231/141492151-c1598129-d6a2-4ba0-90fa-312055c907f3.png)

Probably for another issue, but we should get the image data and generate an SVG and upload that, e.g.

```html
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">

    ...
    <image
        width="100" height="100"
        xlink:href="data:image/png;base64,IMAGE_DATA"
        />
    ...
</svg>
```

**Comment by Ridhwana** [comment]
> We should probably still validate it because in the case of at least a PNG. If someone uploads a huge logo, we don't want that to be in the header of the site for performance reasons and it will look terrible.

I assumed that in the case where it wasn't the recommended size (and the logo was bigger than the container) then we were scaling the image appropriately. I realize this was a big assumption to make, but is this not the case?

> One other thing to note is if they upload a PNG, they'll need to convert it to an SVG as it currently shows up as just text.

That doesn't seem like ideal behaviour. On the admin we allow upload for both, which should ideally just be one upload process. 

<img width="916" alt="Screenshot 2021-11-15 at 12 45 05" src="https://user-images.githubusercontent.com/2786819/141768818-c1a7ff9d-895d-4171-9cf5-dcb6a74c1345.png">

Hence, on the Creator Settings Page, can we not have the upload field as is (we don't want to split them up like the admin)and then under the hood we check whether it is a png or svg and save it as either `logo_png` or `logo_svg`?

**Comment by Ridhwana** [comment]
Actually `logo_png` doesn't work as I expected it to on the admin currently. 

It seems like the logo in the top bar is determined [based on the ffg code](https://github.com/forem/forem/blob/main/app/views/layouts/_logo.html.erb): 

```
<a href="/" class="site-logo" aria-label="<%= t("views.main.aria_home") %>">
  <% if Settings::General.logo_svg.present? %>
    <%= logo_svg %>
  <% else %>
    <span class="truncate-at-2">
      <%= community_name %>
    </span>
  <% end %>
</a>
```

This doesn't make sense to me because the description of `logo_png` states that it's the fallback logo to the SVG, but the code says if `logo_svg` does not exist then we use the community name. I would have expected the code to check for `logo_svg`, if that doesn't exist then `logo_png` and if that doesn't exist then we use the `community _name`.

**Comment by anujbhavsar96** [comment]
@Ridhwana , This is confusing and I also read the [admin doc about](https://admin.forem.com/docs/advanced-customization/config/images#logo-png) `logo_png` . 

Seems like `logo_png` is not similar to the main community `logo_svg`.  `logo_png` requires square dimension according to admin doc. So going forward we can remove this field and if any place is using `logo_png`, we can replace it with favicon. I'm proposing this in my current exercise about simplify image upload process.

**Comment by Ridhwana** [comment]
Thanks @anujbhavsar96 it seems like that was intentional then based on the admin docs. We probably need to name these things more appropriately and give better descriptions in the admin 😞 . I'm sure you'll cover that in your RFC. 

@nickytonline I re-read your comment and perhaps I misinterpreted it. To clarify, can you outline what's your plan when a user uploads a `png` in the creator settings form?

**Comment by nickytonline** [comment]
> Thanks @anujbhavsar96 it seems like that was intentional then based on the admin docs. We probably need to name these things more appropriately and give better descriptions in the admin 😞 . I'm sure you'll cover that in your RFC. 
> 
> 
> 
> @nickytonline I re-read your comment and perhaps I misinterpreted it. To clarify, can you outline what's your plan when a user tries to uploads a `png` in the creator settings form?

My plan is if they upload a png, I will embed it in an SVG. That is how we've done it in the past as far as I know, but it was a manual process in the admin UI.

I'm 99.99% certain I can do this on the client-side when they select a logo for upload.

Another option is we allow for loading a PNG in the header as the logo which would be a server-side check. This would also require having a section in the config/images admin UI to load the PNG as currently we only have a textarea for the uploaded SVG.

And to tie in to that, we should probably have a logo preview in the admin UI as well, but that's me scope creeping. 😎

**Comment by Ridhwana** [comment]
@nickytonline let's implement the version with the least amount of work but also with a good user experience.

> My plan is if they upload a png, I will embed it in an SVG. That is how we've done it in the past as far as I know, but it was a manual process in the admin UI.

This seems like the least effort for now if we can get it done automatically. We shouldn't have a manual process for this.

> Another option is we allow for loading a PNG in the header as the logo which would be a server-side check. This would also require having a section in the config/images admin UI to load the PNG as currently we only have a textarea for the uploaded SVG.

This seems like the end goal and could for part of @anujbhavsar96's [RFC proposal ](https://github.com/forem/rfcs/pull/252/). 

> And to tie in to that, we should probably have a logo preview in the admin UI as well, but that's me scope creeping. 😎

This is so valuable✨, but let's add a task to our board to capture it and implement it as a small win after we've delivered on the project.

**Comment by nickytonline** [comment]
As discussed @Ridhwana, the scope of this has changed now in terms of criteria. The validation will now be allow only SVG, PNG, and JPG files. I also added the max 25MB size like we have in the editor for image uploads.

Also as discussed about image sizing, this will be handled in a separate issue as a backend task.
