### ISSUE TITLE
Error 503 when trying to change my username

### ISSUE THREAD

**Issue by benjaminrancourt** [forem/forem#15424]
**Describe the bug**

Hi,
I'm currently trying to change my DEV.to username from `ranb2002` to `benjaminrancourt`, but it doesn't work because I receive a 503 error. I'm not sure if it is generalized or if it's related only to my account. :/

**To Reproduce**
1. Go to https://dev.to/settings
2. In the *User* section, change the username from `ranb2002` to `benjaminrancourt`
3. Scroll down at the end of the page
4. Click on the *Save Profile Information*

**Expected behavior**

* My username is now `benjaminrancourt`
* All posts, comments and links inside the posts now redirect to my new username

**Screenshots**
![image](https://user-images.githubusercontent.com/7907713/142467859-8662ad28-8822-4a0e-8a46-fd78aae52253.png)

```
Error 503 backend read error
backend read error

Guru Mediation:
Details: cache-den8277-DEN 1637257747 974843738

Varnish cache server
```

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Google Chrome 95.0.4638.69

**Comment by cmgorton** [comment]
Hey @benjaminrancourt could you do me a favor and try to change your name one more time and let me know if you are still receiving the same error? 
I just tested this on my profile and successfully changed my username twice. 
If you are still getting the same error I will see if someone else on the team can try to recreate the issue. Thanks

**Comment by benjaminrancourt** [comment]
@cmgorton I've just tried it twice today and I still got the same error.

**Comment by cmgorton** [comment]
Thank you @benjaminrancourt . I'll post this issue internally and see if anyone else on the team can duplicate the bug.

**Comment by cmgorton** [comment]
Ben H. and Dan U. investigated this error more and gave this additional feedback for anyone who takes up this issue:

Ben wasn't able to replicate the error itself but 503 most likely indicates a timeout. When he went to replicate in prod, it is, in fact, very slow. He guessed it is related to some sequence of callbacks which execute synchronously which should be moved to async.

Dan mentioned: 
we see the 503 logged - not sure how much that helps (looking at the code for profiles/update, the resave_articles is async, the only thing that looks like it could take time is the transaction to save profile/user/user_settings in https://github.com/forem/forem/blob/main/app/services/users/update.rb#L66-L71 ?

error:
``` bash
at=error code=H12 desc="Request timeout" method=POST path="/profiles/175475" host=dev.to request_id=15f6c6a8-e672-42e1-967b-c14a3ffc17d0 fwd="142.116.213.26, 167.82.166.20,167.82.134.67" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
```

it timed out after 30s.

**Comment by djuber** [comment]
Hi @benjaminrancourt 

I checked the logs a little further and found out what it's doing that takes so long to complete. Because the username is part of the path to every article, there's a callback that updates all articles (loads them from the database, then saves them with the new username and path, one at a time) that happens when you change the username, that's taking longer than the 30s request limit to complete. Article updates (saving) in turn have several attached hooks to both validate formatting and uniqueness (you might notice submitting an article in the editor has a short delay) and chaining those serially exhausted the available time.

This is almost certainly something we _should_ be doing in the background, rather than holding the request open and timing out, and I think there was an intent to update articles asynchronously in the Users::Update service that's called to do this on user core fields updates.

Because the entire process is wrapped in a transaction, we're not making partial progress (the updates are all rolled back when the error shows up) and repeating the request is unlikely to succeed without our taking action on your behalf.

----

Technical solution ideas:

We probably want to either disable this article update callback from firing when the update to username is callled by  Users::Update (provided the `User#resave_articles` method correctly sets the username and path, which needs to be checked but appears to be the case from a quick reading) or disable the callback completely if this is the only path accessible to set usernames (it may be, I'm not sure, the callback to ensure the article path matches the username may predate moving the update into a service object).

Ideally any "update collection" callbacks are deferred or handled asynchronously.

**Comment by Zhao-Andy** [comment]
Hi @benjaminrancourt, I've updated your username manually for now. 🙂 

Agreed with Dan's proposal here with putting a lot of the work into a background job.

**Comment by jeremyf** [comment]
I'm interested in giving a crack at this, as I would like to learn a bit more about the callbacks of the user model.

**Comment by jeremyf** [comment]
The following method handles the update.  Note, this is called before validation. 

https://github.com/forem/forem/blob/5a5a0a723a9bec19c2e99a449ce5e1b4636c1f6e/app/models/user.rb#L593-L602

- [ ] The before validation can set the field values but should not save the articles (Consider what happens if the save is invalid but we did the article path change?)
- [ ] Create a service worker that performs the name change `after_commit on: :update`
- [ ] Refine the logic so it's replacing the path's slug (not just the username).  (Consider if the original user name is in the path twice)

Not in scope:

When a user changes their name, we're moving the articles from one path to another.  This will result in those old paths having 404s instead redirects.  That's okay for now.

**Comment by lightalloy** [comment]
A couple of notes for the last @jeremyf 's comment:

>  Create a service worker that performs the name change after_commit on: :update

I suppose we don't need to create another service worker now, the name change is now performed in `Users::Update` along with other changes.
The articles are resaved asynchronously as they used to be, the redundant synchronous resaving which caused the problem was removed.

> When a user changes their name, we're moving the articles from one path to another. This will result in those old paths having 404s instead redirects. That's okay for now.

Actually, old paths are redirected to new ones in `handle_possible_redirect`:
https://github.com/forem/forem/blob/9f688be40648a80c192983435e7628893ee83149/app/controllers/stories_controller.rb#L81-L95

We also have the corresponding specs here: https://github.com/forem/forem/blob/9f688be40648a80c192983435e7628893ee83149/spec/requests/stories_show_spec.rb#L151

Feel free to re-open if the problem persists or if you think that we need further improvements.
