### ISSUE TITLE
RSS Feed is not Imported

### ISSUE THREAD

**Issue by kaylumah** [forem/forem#15488]
I created a new post on my webpage and tried importing it to dev.to; my feed is valid according to <a href="https://validator.w3.org/feed/check.cgi?url=http%3A//kaylumah.nl/feed.xml"><img src="valid-atom.png" alt="[Valid Atom 1.0]" title="Validate my Atom 1.0 feed" /></a>

**To Reproduce**

Use https://dev.to/settings/extensions to import feed

**Expected behavior**

New feed item is imported

**Screenshots**

**Desktop (please complete the following information):**

- OS, version:
- Browser, version:

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

I've tried manipulating the rss feed items and wrapping content in CDATA makes it appear, but breaks all snippets (so that might be issue on my end)

**Comment by jeremyf** [comment]
Hi @kaylumah, I'm someone who also uses the RSS importer.  So I'm checking real quick on some triage items.

**Comment by jeremyf** [comment]
For reading notes:

```sh
❯ curl https://takeonrules.com/tags/dev-to/index.xml -I
HTTP/2 200
date: Wed, 24 Nov 2021 18:34:13 GMT
server: Apache
x-content-type-options: nosniff
last-modified: Thu, 18 Nov 2021 19:13:51 GMT
etag: "3072a-5d114f57219c0"
accept-ranges: bytes
content-length: 198442
permissions-policy: interest-cohort=()
cache-control: max-age=900, public
content-type: application/xml; charset=utf-8
via: e2s
```

```sh
❯ curl https://kaylumah.nl/feed.xml -I
HTTP/2 200
server: GitHub.com
content-type: application/xml
x-origin-cache: HIT
last-modified: Sat, 20 Nov 2021 13:04:21 GMT
access-control-allow-origin: *
etag: "6198f255-2b1b1"
expires: Wed, 24 Nov 2021 18:35:37 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: F96C:26FF:2FC04A:420689:619E83A1
accept-ranges: bytes
date: Wed, 24 Nov 2021 18:34:31 GMT
via: 1.1 varnish
age: 534
x-served-by: cache-mci5943-MCI
x-cache: HIT
x-cache-hits: 1
x-timer: S1637778871.418576,VS0,VE1
vary: Accept-Encoding
x-fastly-request-id: e3a8c082ec07f62ba4637fc5dd3f8f25d68363ff
content-length: 176561
```

Both of our sites have `content-type: application/xml` (though mine has `charset=utf-8` which I don't think is in play).

**Comment by jeremyf** [comment]
With the following code (on my local instance), I checked that we still had a valid URL: 

https://github.com/forem/forem/blob/9df5f6af497479146284818efa44d9027605235a/app/services/feeds/validate_url.rb#L1-L26

```console
❯ bundle exec rails runner "puts Feeds::ValidateUrl.call('https://kaylumah.nl/feed.xml')"
DEBUGGER[-e#4134]: Attaching after process 4112 fork to child process 4134
Running via Spring preloader in process 4134
true
```

So we have a valid URL according to our parser.

**Comment by djuber** [comment]
@kaylumah - I can reproduce this locally when pointing my dev environment at [your feed](https://kaylumah.nl/feed.xml). This looks like a problem either with the format of the feed.xml file's "alternate" link, or the code we're building articles with from it making assumptions about that content (which could be avoided). I would 

---

I'm testing this locally and see there are URI errors being raised in generating url's for image tags in [Feeds::AssembleArticleMarkdown#clean_relative_path!](https://github.com/forem/forem/blob/main/app/services/feeds/assemble_article_markdown.rb#L140-L144)  which appears to be related to an empty string being passed in as a url - which comes from the Feedjira::Parser::Atom.url method

```
[6] pry(#<Feeds::AssembleArticleMarkdown>)> @feed.url
=> ""
[7] pry(#<Feeds::AssembleArticleMarkdown>)> show-method @feed.url                                                     
From: ~src/forem/vendor/cache/ruby/3.0.0/gems/feedjira-3.2.0/lib/feedjira/parser/atom.rb:23:     


def url
  @url || (links - [feed_url]).last
end
[8] pry(#<Feeds::AssembleArticleMarkdown>)> @feed.links             
=> ["https://kaylumah.nl/feed.xml", ""]
[9] pry(#<Feeds::AssembleArticleMarkdown>)> @feed.feed_url
=> "https://kaylumah.nl/feed.xml"
```

This appears to be related to the alternate link in the feed:

```
  <link href="https://kaylumah.nl/feed.xml" rel="self" type="application/atom+xml" />
  <link href="" rel="alternate" type="text/html" />
```

Internally we're trying to use the "" URI to build image links when there are image tags with paths starting with /.

I'm not sure what the intended _meaning_ of `href=""` in the alternate link is, https://validator.w3.org/feed/docs/atom.html#link suggests that href should be a URI. However, it looks like we might be misinterpreting that (since the reasonable alternate for this feed would be https://kaylumah.nl/blog.html and we wouldn't be able to join images to that either, we expected to build images from https://kaylumah.nl/ + /path/to/image).

My assumption is that the code should be handling this by finding the item's url's b scheme + hostname and building a uri from that (and adding the path to the image/asset), rather than there being a problem with your feed formatting.

I am able to import articles successfully when I remove the second link, and able to import then when I use the posts host rather than trying to find that from the feed's `<link>` tags.

**Comment by kaylumah** [comment]
I can look into removing it on my end, but since it was not a problem for the previous 5 posts I am not sure it would help.

Also when I wrap the contents node in CData element the feed can import even with that empty link present. So perhaps something faulty in the failing/most recent article is causing this

**Comment by djuber** [comment]
On our end it is tied to building links to included images, when the image url start with `/`, something like

`<img src=/path/to/image.png>` 

If only _some_ of the articles (or the most recent one, especially) had this form of image link, that would explain the failure starting suddently.

I have a work-around (linked commit) that could fix this generally without your needing to do anything.

**Comment by kaylumah** [comment]
Did you already release this? Because i fixed the broken alternate link on my end, and now it showed up as expected
