### ISSUE TITLE
Removing community emoji results in "Internal Server Error"

### ISSUE THREAD

**Issue by q9f** [forem/forem#15722]
**Describe the bug**

Removing community emoji results in "Internal Server Error."

**To Reproduce**

1. Go to admin > customization > config > community content
2. Remove the "Community emoji"
3. Hit "Update Settings"
4. Get an _"Internal Server Error"_

**Expected behavior**

You should be able to remove the community emoji or replace it with any other symbol.

**Desktop (please complete the following information):**

* OS, version: Archlinux, kernel 5.15.6-arch2-1 x86_64 GNU/Linux
* Browser, version: Mozilla Firefox 94.0.2

**Additional context**

Setting a different symbol that is not an emoji, gives you:

> Validation failed: Community emoji contains non-emoji characters or invalid emoji

It should be possible to remove or replace emohis though. Related: https://forem.dev/afr/how-to-strip-out-all-emojis-4b7h

**Comment by djuber** [comment]
@q9f, thanks for the report. This is an issue where the emoji-only validator is called for the community emoji setting, but doesn't handle nil safely (so raised the error you saw).

https://github.com/forem/forem/blob/main/app/models/settings/community.rb#L9

```ruby
module Settings
  class Community < Base
    setting :community_emoji, type: :string, default: "🌱", validates: { emoji_only: true }
  end
end
```

https://github.com/forem/forem/blob/main/app/validators/emoji_only_validator.rb#L5

```ruby
class EmojiOnlyValidator < ActiveModel::EachValidator
  DEFAULT_MESSAGE = "contains non-emoji characters or invalid emoji".freeze

  def validate_each(record, attribute, value)
    return if value.gsub(EmojiRegex::RGIEmoji, "").blank?

    record.errors.add(attribute, options[:message] || DEFAULT_MESSAGE)
  end
end
```

This calls `nil.gsub(...)` when the emoji is cleared (and raises `NoMethodError`).

**Comment by djuber** [comment]
@q9f - I was exploring this behavior a little further. While the server error should not be happening (and I expect to have a fix for that later today or tomorrow), there's a further complication in that there's a default value used (the seedling, 🌱) when this setting is saved as a nil, (but not when it's an empty string), and the Settings::Upsert is setting blank inputs to nil when setting the value.

In order to accomplish what you're trying to do, unset the community emoji, and then also not show it on your forem site, I think there's more work required on our side besides not raising an error.

**Comment by djuber** [comment]
https://github.com/forem/forem/issues/15877 this issue was recently created to remove the community emoji completely (which is what you had set out to do) - once this is closed/complete things should be simpler.
