### ISSUE TITLE
Follow button on profile is not working json parse error

### ISSUE THREAD

**Issue by jsbaguette** [forem/forem#15916]
**Describe the bug**

When clicking on follow button is not working because of a json parse error

**To Reproduce**

1. go to https://dev.to/stack-labs?signin=true
2. notice that you have in error in the console because of a json parse error
3. click on follow
4. its not working

**Expected behavior**

We should be able to follow

**Screenshots**

<img width="725" alt="Screen Shot 2022-01-01 at 4 18 36 PM" src="https://user-images.githubusercontent.com/11556276/147860375-1902e922-d4ff-41c0-8127-1b72fff87760.png">

**Desktop (please complete the following information):**

- OS, version: macbook m1 pro max
- Browser, version: chrome latest

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

**Comment by djuber** [comment]
this is reproducible.

Checking the code for [initializeAllUserFollowButtons](https://github.com/forem/forem/blob/036d75aa6e4ca2629d46128eaeeb897260d6cea5/app/javascript/packs/followButtons.js#L325-L359)  and experimenting a little - it appears a user's data is causing an issue

```javascript
const buttons = document.querySelectorAll(
  '.follow-action-button.follow-user:not([data-fetched])',
);

Array.from(buttons, (button) => { console.log(button.dataset.info); JSON.parse(button.dataset.info);})
{"id": 383123, "className": "User", "style": "full", "name": "Chabane R."} base.js:7495:61
{"id": 383123, "className": "User", "style": "full", "name": "Chabane R."} base.js:7495:61
{"id": 399496, "className": "User", "style": "full", "name": "Λ\: Olivier Revial"} base.js:7495:61
```

Taking the raw data-info from the inspector and pasting it into node - it looks like the doubled backslash character is causing an issue... I assume when we render this we need to double that again (sending a sequence '\\\\' instead of '\\')


The capital lambda character (which has no special meaning) is not a problem, but the double backslash appears to break the handling of the user name (there are a few users with this pattern, each are unparseable and cause all follow buttons to be non-functioning).

```
> JSON.parse("{\"id\": 399496, \"className\": \"User\", \"style\": \"full\", \"name\": \"Λ\\: Olivier Revial\"}")
Uncaught SyntaxError: Unexpected token : in JSON at position 64
> JSON.parse("{\"id\": 399496, \"className\": \"User\", \"style\": \"full\", \"name\": \"\\: Olivier Revial\"}")
Uncaught SyntaxError: Unexpected token : in JSON at position 63
> JSON.parse("{\"id\": 399496, \"className\": \"User\", \"style\": \"full\", \"name\": \"\\\\: Olivier Revial\"}")
{ id: 399496, className: 'User', style: 'full', name: '\\: Olivier Revial' }
  id: 399496,
  className: 'User',
  style: 'full',
  name: '\\: Olivier Revial'
}
```

**Comment by djuber** [comment]
related https://github.com/forem/forem/issues/14704
