### ISSUE TITLE
RSS feed not fetching from dev.to to code newbie?

### ISSUE THREAD

**Issue by VickiLanger** [forem/forem#15939]
**Describe the bug**
Posts are not fetching from dev.to RSS feed to code newbie community. They were fetching in November with [this post](https://community.codenewbie.org/vickilanger/words-numbers-variables-oh-my-3jeo), but nothing from [this post](https://community.codenewbie.org/vickilanger/if-this-then-that-bim) or after. Specifically, [this post](https://dev.to/vickilanger/dry-out-with-loops-d6l) hasn't fetched properly.

**To Reproduce**
n/a?

**Expected behavior**

Posts from my dev.to RSS feed [(https://dev.to/feed/vickilanger)](https://dev.to/feed/vickilanger) will land in my [code newbie community dashboard](https://community.codenewbie.org/dashboard) as drafts
**Screenshots**
![Screen Shot of code newbie community profile extensions page showing last fetch "Last Fetched: January 3, 2:20:17 PM"](https://user-images.githubusercontent.com/46823403/147978397-5e42974b-5e1d-4cac-936b-250710ce59d1.png)

**Where:**
Tried on Chrome, Safari, Firefox, 
Tried on macOS, iPadOS, iOS

**Comment by djuber** [comment]
It looks like this is caused by a change on our end (to dev.to's caching layer) that requires a user-agent string when making requests:

```ruby
[1] pry(main)> url = "https://dev.to/feed/vickilanger"
=> "https://dev.to/feed/vickilanger"
[2] pry(main)> response = HTTParty.get(url, timeout: 10)
=> #<HTTParty::Response:0x48b98 parsed_response=nil, @response=#<Net::HTTPForbidden 403 Forbidden Bots readbody=true>, @headers={"connection"=>["close"], "content-length"=>["0"], "server"=>["Varnish"], "retry-after"=>["0"], "accept-ranges"=>["bytes"], "date"=>["Mon, 03 Jan 2022 21:07:03 GMT"], "via"=>["1.1 varnish"], "x-served-by"=>["cache-pwk4960-PWK"], "x-cache"=>["MISS"], "x-cache-hits"=>["0"], "strict-transport-security"=>["max-age=31557600"]}>
[3] pry(main)> response.code 
=> 403
[4] pry(main)> response.response
#<Net::HTTPForbidden 403 Forbidden Bots readbody=true>
```

The problem code (also on our side) is in the app/services/feeds/import.rb `fetch_feeds` method, where HTTParty.get  is sending a user agent of "Ruby", which is being rejected.

https://github.com/forem/forem/blob/main/config/fastly/snippets/bad_bot_detection.vcl#L120-L121 is the line in the fastly config to block access from "Ruby".

Either we'll need to permit feed access to Ruby the way we permit api access, something like adding `(req.url ~ ^/feed/)` to the possible matches permited (not blocked), or we'll need to update the import function to send a custom user agent string (not Ruby).

@jgaskins do you have any preference here?
