### ISSUE TITLE
Error message when attempting to post a comment

### ISSUE THREAD

**Issue by fdocr** [forem/forem#15959]
**Describe the bug**

An error related to the attempt to deliver Push Notifications to Android devices while posting a comment

**To Reproduce**

1. Post a comment on an Article where the author (or comment thread) has registered for PN delivery
2. The comment is posted but an error modal appears

Note: This was confirmed on a Forem Cloud instance and not on dev.to yet

**Expected behavior**

The comment should be posted without any errors and the PN should be scheduled for delivery

**Screenshots**

<img width="492" alt="error_message" src="https://user-images.githubusercontent.com/6045239/148221356-d0791b29-07ab-4203-b8e0-ba9d8d1d9f6d.png">

**Desktop (please complete the following information):**

- OS, version: macOS 12.1
- Browser, version: Chrome 96

**Additional context**

This is likely rooted in the Device (model) `android_notification` method or one of the `app/queries/consumer_apps` queries.

**Comment by djuber** [comment]
https://app.honeybadger.io/projects/72638/faults/83316182

```
Modis::RecordNotFound: Couldn't find Rpush::Client::Redis::Gcm::App with id=1

    app/queries/consumer_apps/rpush_app_query.rb:19 :in `call`

    def call
      if consumer_app.android?
->    android_app = Rpush::Gcm::App.where(name: app_bundle).first
        android_app || recreate_android_app!
      elsif consumer_app.ios?
app/queries/consumer_apps/rpush_app_query.rb:4 :in `call`
app/models/device.rb:55 :in `android_notification`
app/models/device.rb:21 :in `create_notification`
app/services/push_notifications/send.rb:18 :in `block in call`
app/services/push_notifications/send.rb:17 :in `call`
app/services/push_notifications/send.rb:4 :in `call`
app/services/notifications/new_mention/send.rb:40 :in `call`
```

**Comment by fdoxyz** [comment]
Thanks @djuber, I do think that one is related. I did found out [this other line](https://github.com/forem/forem/blob/main/app/models/device.rb#L55-L58) was also failing, which is also calling the `ConsumerApps::RpushAppQuery`.

> While the method call passes a name, the logged error includes id=1.

Yeah, Modis (RPush related dependency) helps store these models in Redis instead of the DB and their queries are a bit different from what we might expect from ActiveRecord.

I'm looking a bit deeper into what may have caused this problem. Things work fine with my local environment, which makes me think something went wrong (inconsistency) with the Redis models or the indexes which Modis uses to query them.

A solution I have in mind is to give all `rpush:*` KV pairs within Redis a relatively short TTL (2~4 hours maybe). We already do this (in a more conservative way) [for Notifications here](https://github.com/forem/forem/blob/main/app/workers/push_notifications/cleanup_worker.rb#L16). 

These models are meant to be ephemeral and easily recreated, so this would ensure Redis instances won't ever get to this "inconsistent state". This is just an idea for now. I'm still researching this a bit more to make sure it would solve the problem though.

**Comment by mirie** [comment]
@fdocr was this resolved by this PR you merged way back when?

**Comment by fdocr** [comment]
Yes, I see the PR was linked but didn't automatically close it (missed the `closes #XXXX` keyword). Thanks for noting this!
