### ISSUE TITLE
Feature: List users who reacted to story

### ISSUE THREAD

**Issue by RyKilleen** [forem/forem#160]
# Feature

### Request or User Story
When I see users reacted to a story, sometimes I want to see who those users are! (Who liked my brother's posts?! I'm curious.)

### Definition of Done
I'm able to see a list of users who ❤️ or 🦄 a story!

**Comment by Zhao-Andy** [comment]
Hey @RyKilleen, thanks for the feedback! We're going to put this in our backlog for now.

**Comment by RyKilleen** [comment]
Great, thanks as always for your work on the platform!

**Comment by griffinator76** [comment]
Any update on whether this was actually resolved? Just started using dev.to and it seems a bit weird that posts get "likes" but it seems there's no way to tell who liked it?

**Comment by maestromac** [comment]
Thanks for raising this @griffinator76 . This feature is not implemented yet.

**Comment by sushant12** [comment]
I can work on this feature but I cant write css

**Comment by maestromac** [comment]
Thank you for volunteering @sushant12 . We need to give this feature a bit more thought before moving forward.

**Comment by sushant12** [comment]
@maestromac  sure thing.

**Comment by arpit73** [comment]
Any updates on this issue?

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](https://github.com/forem/forem#community) for many of these feature requests that we need more discussion around. Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](https://forem.dev/). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
