### ISSUE TITLE
Allow BiDi control characters as such in article title

### ISSUE THREAD

**Issue by yheuhtozr** [forem/forem#16001]
**Describe the bug**

I just noticed #14909 was implemented, but a part of its logic that sanitizes U+202A - U+202E in the title is not desirable for i18n. Despite recent attention to an security issue, those characters are neither evil nor ornamental, but sometimes essential to natural writings in RTL languages for reasons similar to [this case](https://github.com/forem/forem/pull/15831#discussion_r772594486) (and it's not recent at all in the Unicode world, just less and less people becoming able to cast a blind eye). I think what you should do instead is either disallow "string that **only** contains BiDi controls (and whitespaces)" or "string contains **unmatched** BiDi controls".

Moreover, speaking of BiDi controls, there are more of them at:
- U+200E, U+200F
- U+2066, U+2069
- U+061C

I'll create a PR if necessary and I have time.

Note: the tag restriction may need special treatment and out of scope of this issue.

**To Reproduce**

#14909

**Expected behavior**

Explained above.

**Additional context**

- [Avoiding Source Code Spoofing](https://www.unicode.org/L2/L2022/22007-avoiding-spoof.pdf)
- [UAX #9: Unicode Bidirectional Algorithm](https://www.unicode.org/reports/tr9/)

**Comment by citizen428** [comment]
> I'll create a PR if necessary and I have time.

We don't have RTL support yet and realistically speaking we're still quite far away from that so your energy would probably be better spent elsewhere. Not saying this is not a good PR to eventually write, just giving you some context around the timing.

**Comment by ahangarha** [comment]
Hi.

My proposal is to add bidirectional text support. This makes all titles and content to get direction automatically based on their first strong character. I have done it on few other projects and I think I should be able to do it here. I know react and will know RoR soon. My native language is also Persian which is RTL so I know what the issue is.

I think I should open a new issue with titles like "add bidirectional text support" but wanted to confirm it first. It is much more than adding feature to accept unicode characters for directions (which still is a good thing to add). So I think it deserve to have a dedicated issue. Please let me know.

**Comment by ahangarha** [comment]
Thanks @maestromac

Though I suggest having better support for bidirectional text. One shouldn't need to manually add a special character to force the direction of the text. We have bidirectional text for such cases.

Should I open a new issue for bidirectional text support?
