### ISSUE TITLE
Replace listings tag selection component with new autocomplete

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#16137]
(to be tackled once https://github.com/forem/forem/pull/16025 is successfully merged)

In https://github.com/forem/forem/pull/16025, the tags selection component in the article form is replaced with a new autocomplete component. The 'create/edit' listing UI (`/listings/new`) also has a tags field, which hasn't been changed in https://github.com/forem/forem/pull/16025.

Once we see the new autocomplete component successfully live in the editor, we should also replace the current listings tag input with it. This will allow us to fix the accessibility issues in the current version, and remove the remaining 'old' tag suggestion code.

**Comment by miguelnietoa** [comment]
Hi @aitchiss, I would like to contribute to this issue 😄

**Comment by aitchiss** [comment]
Hi @miguelnietoa - that's great! Be sure to take a look at the `MultiSelectAutocomplete` component, and where we currently use it in the editor to get a feel for what needs done.

Let us know if you have any questions while looking at it 👍

**Comment by miguelnietoa** [comment]
Hello again @aitchiss , I have one question...

I have noticed that there are some additional tags for the listings depending on the category:
https://github.com/forem/forem/blob/1b337b85d9e6f7a6f1fc8e69bad3d9700739dd18/app/javascript/shared/components/tags.jsx#L35-L69 

But the `category` received in the `Tags` component (`app/javascript/shared/components/tags.jsx`) is actually an `id` ('1', '2', ...) instead of a `slug` ('jobs', 'forhire', ...)

What should I do in that case? This is the method used to get the listing categories (note that is returned the internationalized option and the `id` in an array):
https://github.com/forem/forem/blob/1b337b85d9e6f7a6f1fc8e69bad3d9700739dd18/app/helpers/listing_helper.rb#L2-L6

**Comment by aitchiss** [comment]
hey @miguelnietoa - yes those categories might need some extra handling (I think this feature is currently broken in the live app!). My initial instinct is that instead of each item being e.g. `'remote'`, they would need to be mapped to `{ name: 'remote' }`, but it might help if you could create a draft PR into our repo so that I can run what you have at the moment and reproduce the exact issue.

**Comment by miguelnietoa** [comment]
> hey @miguelnietoa - yes those categories might need some extra handling (I think this feature is currently broken in the live app!). My initial instinct is that instead of each item being e.g. `'remote'`, they would need to be mapped to `{ name: 'remote' }`, but it might help if you could create a draft PR into our repo so that I can run what you have at the moment and reproduce the exact issue.

Yes, I will create a draft PR later 👍🏻

**Comment by miguelnietoa** [comment]
Hi @aitchiss, I have created the Draft PR (https://github.com/forem/forem/pull/16855), take a look into it please 😄
