### ISSUE TITLE
Improvements to SMTP settings

### ISSUE THREAD

**Issue by JennieOcken** [forem/forem#16180]
### Discussed in https://github.com/forem/forem/discussions/16179

<div type='discussions-op-text'>

<sup>Originally posted by **JennieOcken** January 18, 2022</sup>
Allow a Creator who sets up their own SMTP settings to specify the `from email address` that will be used with that email service in the existing SMTP settings area.

In addition, update the logic of SMTP settings so cloud hosted Forems can override the SendGrid provisioned for them by us with their own SMTP settings (currently this isn't supported in the app).

```return sendgrid_settings if ENV["SENDGRID_API_KEY"].present?```</div>

- [x] Add the [ability to for a Forem Cloud Customer to use custom SMTP Settings](https://github.com/forem/forem/pull/16216/files)
- [x] Improve the [UX of the SMTP Section](https://github.com/forem/forem/pull/16223)
- [x] Add a [contact email to use in sections where the users may need to contact a Forem creator or admin](https://github.com/forem/forem/pull/16497)
- [ ] Add a [reply_to and from email address](https://github.com/forem/forem/pull/16499) on the SMTP configurations.

**Comment by Ridhwana** [comment]
Note: 
- @maestromac is tackling "update the logic of SMTP settings so cloud hosted Forems can override the SendGrid provisioned for them by us with their own SMTP settings"
- @Ridhwana is tackling "Allow a Creator who sets up their own SMTP settings to specify the from email address that will be used with that email service in the existing SMTP settings area."

**Comment by Ridhwana** [comment]
@JennieOcken here's a proposed solution for this. Let me know what you think about it.

### Forem Cloud Instances:

**Allow SMTP to override Sendgrid settings:**
We will provide the ability for Forem Cloud Instances to specify their own SMTP settings. This will be done by allowing the SENDGRID_API_KEY to be overriden with the SMTP Settings from /admin. 

**Determining the email_from and reply_to addresses for emails**
Unfortunately it seems that because all Forem Cloud instances use the same Sendgrid account, they do need to use our noreply@forem.com address. Hence, we cannot give them the ability to change their `email_from` and `reply_to` addresses like we can with self hosted forems who manage their own SMTP. If they want this control they will have to specify their own SMTP settings and in this manner they will also have control of the `email_from` and `reply_to` addresses. See below how it works for self hosters.

**Dealing with Default Email in /admin**
Across the entire codebase we specify on the UI, "if you want to contact a forem it points the contact address to use `ApplicationConfig["DEFAULT_EMAIL"]` which is `no-reply@forem.com`. 

We can rename the `Default Email Field` to something like `Forem Cloud email address`. In addition, we will add a description stating `This email cannot be changed without specifying your own SMTP settings. It is currently being used as the email_address from which your mails will be sent.` 

**Specifying the contact email address across the site**
- We'll create a new field called `contact email` with description `This email address will be used across the site in links that reference your contact email address for any queries or support.`.  This field will be pre-populated with `ApplicationConfig["DEFAULT_EMAIL"] (no-reply@forem.com)`.

### Self Host:

**Determining the email_from and reply_to addresses for emails**
The SMTP Settings will contain two new fields. An `email_from` address and a `reply_to` address. This will allow Forems to be able to specify the email that mails get sent from and an email address that users can reply to. 

These fields will auto populate based on `ApplicationConfig["DEFAULT_EMAIL"]`, which in the case of Forem Cloud instances will be no-reply@forem.com. However, a user can update this field to the addresses that they will use. 

**Dealing with Default Email in /admin**
Same as above as per Forem Cloud.

Recap: Across the entire codebase we specify on the UI, "if you want to contact a forem it points the contact address to use `ApplicationConfig["DEFAULT_EMAIL"]` which is `no-reply@forem.com`. We can rename the `Default Email Field` to something like `Forem Cloud email address`. In addition, we will add a description stating `This email cannot be changed without specifying your own SMTP settings. It is currently being used as the email_address from which your mails will be sent` 


**Specifying the contact email address across the site**
- We'll create a new field called `contact email` with description `This email address will be used across the site in links that reference your contact email address for support or to just get in touch.` This field will be pre-populated with the `no_reply` address from the SMTP settings.

### Long term goals:
I think that this UI needs to be reworked and we may need to determine upfront whether this is a forem cloud instance or self hosted and then we show the relevant options based on that. However, that seems like a longer term goal with the IA project. Hence for now this may be a step in the right direction.

**Comment by JennieOcken** [comment]
Yes, this is exactly the right direction.  I read it through a couple times and that is solving exactly the problems we discussed.

Long term, I think we don't want to allow folks to use `noreply@forem.com` but that feels pretty out of scope for right now because I don't want to think through chasing down defaults or required fields at the moment.

You bring up a really good point with the long term goals.  So... here comes my scope creep.  Do tell me if I am asking too much.  I wonder for the issue of clarity for those that are Cloud Hosted if we can add a UI element that does this...

Add a toggle to the top of the page that says "use my own email server"

If a `SendGrid_API_Key` is present, then the toggle is active and false.
If a `SendGrid_API_Key` is not present, than the toggle is inactive and true.
If the toggle is false than the SMTP settings are inactive.

I think this would allow us, with a simple UI element, to hit these scenerios (since for our Cloud hosted partners the API Key will always be present)
As a self hoster, I see that I have to use my own email server and the settings are available for me to modify.
As a cloud hoster, I see that I currently have an email server provided for me.  I have to opt to use my own email service to modify these settings.

**Comment by Ridhwana** [comment]
@JennieOcken quick demo to make sure we're on the same page https://www.loom.com/share/550048c71d144557b5dc12580ed78106

If we decide to go with all these changes, I'll make sure that the documentation is updated. Let me know your thoughts.

**Comment by JennieOcken** [comment]
I literally watched that video repeatedly saying "Yes" in a really excited voice.  Love the change in section title too.

And you already caught the "we should have more explanatory text" thought I had. 

Just to be clear, if the `SendGrid_API_Key` is not present, they box is already checked and so they wouldn't see this explanatory text on first interaction, correct?  Also, if a `SendGrid_API_Key` is not present they shouldn't be able to uncheck the box.  Or maybe if 'SendGrid_API_Key` is not present, that toggle shouldn't appear at all.  Yeah... concluding that thought out loud.  If `SendGrid_API_Key` is present, show this toggle and explanatory text.  If not, don't show toggle at all.  Which means our Cloud Hosted clients can still go back to using our server.  What would happen if they fill out the settings and then hit the toggle?  We would need to clear the settings so SendGrid would take over.

Given that logical thought, let's tweak that text to:

As a Forem Cloud client, we provide an email server managed by the Forem team.  All settings are managed by us and the from and reply email addresses are set as noreply@forem.com.  However, you can override this to use your own email server.

**Comment by Ridhwana** [comment]
@JennieOcken I had just had that [thought](https://github.com/forem/forem/pull/16216#issuecomment-1018550885) about 20 min ago and dropped it in Macs PR: 

```
What if someone is on a Forem Cloud account, and Forem has sendgrid set up for them. They then choose to override the sendgrid account with their own SMTP settings. The change that you've put into place will ensure that they can do this.

Now what happens if later they want to revert those changes, i.e. move from SMTP Settings back to Sendgrid, can they do this by just clearing out the fields? I think theres validation on the fields so that may not work.
```

We'll need to still figure out a way to implement this because right now we can't clear out the fields because of the validations. 

That aside, this is a summary for clarity. Let me know if I misunderstood anything please?

| Sendgrid API Key | Custom SMTP Settings | Show Toggle Element  | Text description                                                                                                                                                                                                                                  | Action                                                                               |
|------------------|----------------------|----------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------|
| no               | no                   | no                   | none                                                                                                                                                                                                                                              | Show the SMTP Form                                                                   |
| yes              | no                   | yes                  | As a Forem Cloud client, we provide an email server managed by the Forem team. All settings are managed by us and the from and reply email addresses are set as noreply@forem.com. . However, you can override this to use your own email server. | When the user toggles the box, the SMTP Form will show up                            |
| no               | yes                  | no                   | none                                                                                                                                                                                                                                              | Show the SMTP Form                                                                   |
| yes              | yes                  | yes                  | none                                                                                                                                                                                                                                              | A user can un toggle and it should clear out the form and revert to the sengrid key. |

**Comment by JennieOcken** [comment]
I love it when we are on the save wavelength.  Yes, that grid is 100% right and a much clearer way of thinking about it than my rambling.

**Comment by Ridhwana** [comment]
@JennieOcken you'll be receiving 2-3 demo videos, one for each of my PR. 

This one is to add a contact email, and I made some user experience changes, let me know what you think:

https://www.loom.com/share/e1615e5442d5422382edb5db603ead43

**Comment by Ridhwana** [comment]
Another video to show the user experience changes to the SMTP Section: 
https://www.loom.com/share/472c958d890140dfa13400ee3f054a10

In the last video I'll add and do a quick demo of the reply_to and contact from email address.

**Comment by JennieOcken** [comment]
This is exactly what I was hoping for.  I appreciate combining the `emails` and `email digest` sections.  Good call.

Beautiful!

**Comment by Ridhwana** [comment]
Final Video for reply to and from email addresses: https://www.loom.com/share/cdb278917765402189e38f908bb03608

**Comment by michael-tharrington** [comment]
I'm so happy we're making these changes!

I admittedly may be in the wrong spot to make this suggestion, but I wanted to point out that the Code of Conduct which ships with a Forem includes the noreply@forem.com email address in it.

For instance, if you take a look at https://www.metapunk.to/code-of-conduct, you'll see:

> Violations of the Code of Conduct may be reported by contacting the team via the [abuse report form](https://www.metapunk.to/report-abuse) or by sending an email to [noreply@forem.com](mailto:noreply@forem.com). All reports will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. Further details of specific enforcement policies may be posted separately.

I think it'd be ideal if admin could swap out noreply@forem.com with whatever email the admin has set as the Contact email. This would work similarly to how the /contact page works. 

For instance, looking back at the contact page for Meta Punk (https://www.metapunk.to/contact), you can see that they have overridden the default noreply@forem.com email address here by entering their Contact email on the admin side.
