### ISSUE TITLE
Cover image resizing logic

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#16455]
## Problem

It's very easy for authors to upload a cover image that will not look good, which isn't ideal. Let us tweak the image processing logic to make uploading a nice-looking cover image a little easier.

## Current behavior

We resize and crop the uploaded image to exactly fit our ratio of cover area. Therefore it's often blurry/pixelated.

## New behavior

1. When width of uploaded image is >= the width of the cover image area (1200px) - see B in the [figma file](https://www.figma.com/file/okQAypuj7vsDTEYt9Dr7hK/Cover-photo-resizing?node-id=0%3A1)
   1. We only resize the image to fit the full width of the cover area, without cropping - so this will NOT preserve the current ratio.
   2. We also remove the height constraint of the cover image, so the cover image area may vary in height when rendered. 
3. When width of uploaded image is < the width of the cover area (1200px) - see C in the [figma file](https://www.figma.com/file/okQAypuj7vsDTEYt9Dr7hK/Cover-photo-resizing?node-id=0%3A1)

   1. We don't stretch the image to fit width nor height of the cover area, instead, we use the image as it, centered vertically & horizontally
   2. We detect the primary color of the uploaded image, and add a background of that color to fill the rest of the cover area
3. For both cases, we also still set up a maximum height for the cover area so it wouldn't cover all the viewport, especially for portrait images. This part needs to be sorted out with @ludwiczakpawel when we start working on this issue. 
4. We also need to prevent [cumulative layout shift](https://github.com/forem/forem/issues/16455#issuecomment-1038813985) from happening. (Thank you @ludwiczakpawel for bringing this up)

## Additional info
Check out this [message thread](https://forem-team.slack.com/archives/C7GE84DEJ/p1642471159042300) where Josh uploaded an image that didn't work with the cover area, and [the discussion](https://forem-team.slack.com/archives/C7GE84DEJ/p1642734860149800) between Pawel and Amy on solutions.

**Comment by ludwiczakpawel** [comment]
The logic outlined in the description seems correct.

There's one caveat that we haven't really discussed which is IMO pretty important and we need to figure it out (likely in backend). [Cumulative Layout Shift](https://web.dev/cls/) - it's when you load the page and some elements show up with a bit delay (for example because it takes longer to load an image, like a cover photo) - in that case the entire page layout shifts a little. 

So we need to, somehow, get the cover image size before we actually load it (that's why I suggested it should be backend solution but I honestly don't know if there are alternative techniques to solve it), to avoid that Cumulative Layout Shift. Right now it's not a problem, because cover photo is ALWAYS the same height. But with new behavior, height may vary.

**Comment by amywtlin** [comment]
That's a good point. Basically you are saying that, we need to know the height of an image before it is rendered, and reserve corresponding space so the content won't be jumpy when the image finishes loading. Is that correct?

**Comment by ludwiczakpawel** [comment]
@amywtlin yes.

**Comment by amywtlin** [comment]
Thanks! I just added it to the issue so we make sure we handle it when we start working on the issue. I am not too concerned about the technicality of it, as I am sure engineers will figure out a good way to handle it 😊

**Comment by jeremyf** [comment]
Here are the constraints for [DEV.to](http://dev.to/) and our image handler:

* The image will be rendered as 1000x420
* The max upload file size is 25MB
* The maximum dimensions are 4096x4096

So, they could try a 4096 x 1720 image (4096 / 1000 * 420 == 1720).  But there may be additional image processing antics.

**Comment by amywtlin** [comment]
@ludwiczakpawel heads-up that Dwight has picked up this one!

@dwight If at some point you are unclear about the spec, feel free to ping Pawel and me!

**Comment by dscottS3** [comment]
closing this issue as the following three PRs gets us a majority of the way there. we can revisit the need of using server side resources to scale images if the implemented solution turns out to be less than ideal.

https://github.com/forem/forem/pull/17512
https://github.com/forem/forem/pull/17502
https://github.com/forem/forem/pull/17347

**Comment by amywtlin** [comment]
@dscottS3 It looks like we implemented something but not all things. Can you give me a summary of what the new expected behavior looks like? Thanks!
