### ISSUE TITLE
Admin can't delete posts on Forem

### ISSUE THREAD

**Issue by ellativity** [forem/forem#16461]
**Describe the bug**

Originally discovered on sandbox Forem but able to replicate on other Forems in the fleet.

If an Admin tries to delete a user's post (either by clicking **Delete** on the Manage page by appending `/manage` to the post URL or by clicking **Delete** on a Draft post in the User Dashboard), the `/delete_confirm` page 404s.

@michael-tharrington confirms that he's able to replicate this issue.

**To Reproduce**

When logged in as Admin:

Either
1. Open the post you want to delete
2. Append `/manage` to the post URL
3. Click **Delete** to see `/delete_confirm` page and 404 error.

Or
1. Open the post you want to delete
2. Click on the "Mod Panel" icon in the reactions bar (shield icon)
3. Click on **Unpublish post** at the bottom of the Mod Panel
4. Navigate to the User Dashboard (`/dashboard/username`)
5. Locate the freshly unpublished post in **Draft** state
6. Click **Delete** to see `/delete_confirm` page and 404 error.

**Expected behavior**

I believe we previously saw a page asking to confirm if we wanted to delete the content, but it's tricky to recall now that we don't seem to be able to access this any more. 

Ideal world behaviour: a confirmation modal appears. When confirmed, Admin is returned to User Dashboard (to visually verify the post is deleted) with a notification that matches the style of those seen by Admins when banishing/deleting users, or unpublishing all of a user's posts.

**Screenshots**

[I was recording a video tutorial when I first came across this, so here's the goofy video.](https://www.loom.com/share/b9e9ff128be2429895f838eb70aa1540) - enjoy 😆

**Comment by djuber** [comment]
The error (when using /manage to act on another user's article) is coming from [ArticlesController#delete_confirm](https://github.com/forem/forem/blob/main/app/controllers/articles_controller.rb#L152-L156), which is scoping to `@current_user.articles`. 

I'm able to reproduce the first path locally.

If I manage one of my _own_ articles (and I see manage, edit, admin buttons on the article page) this is successful, I'm prompted to confirm deletion and redirected back to the dashboard on success.

If I manage one of another user's articles, by modifying the url to end in /manage, the confirmation fails with the 404 error.

Oddly, I can _edit_ another user's articles (including unpublishing the article) but deletion is blocked by that scoped lookup.

Following the second path - after unpublishing the user's article (step 3) I'm given a 404 (because of a check `permission_denied?` in the StoriesController that fails when the article is unpublished). Continuing to the user's dashboard page is the same path as the first case (in both scenarios the problematic Not Found error is coming from the user scoped article lookup in `delete_confirm`).

**Comment by jeremyf** [comment]
This loosely relates to #16483
