### ISSUE TITLE
Podcast episodes in non-Latin Script aren't resolving properly

### ISSUE THREAD

**Issue by ellativity** [forem/forem#17168]
[Here's a little video of the bug](https://www.loom.com/share/a2c63614b24e4bb1a19d9c6965e5ba67)

**Expected behavior**

I think maybe if we can't pull an address out of the title, we create a randomized string instead? I think having random strings for all episodes would also be fine, whatever script the title is in. But I don't know enough about how this part of the codebase works to know if that's feasible or not.

**Additional context**

[This was the original post describing the issue on forem.dev](https://forem.dev/varhal/no-english-links-not-working-in-podcasts-54e7) and I've asked @Varhal to weigh in here in the comments on this bug report.

**Comment by djuber** [comment]
extracting commentary from the loom video

https://ux.pub/design_takoy is a podcast on a site using cyrillic script 
when there are some latin/ascii characters in the podcast episode title, we extract only those to make the link
when there are only cyrillic characters in the podast episode title, we are removing all of them and linking back to the same page (podcast index)

![episodes](https://user-images.githubusercontent.com/1237369/162261431-f43ef5b8-805b-4429-ae72-5c8c1ecdcb20.png)

here the first and third episodes are completely cyrillic titles, their links go back to https://ux.pub/design_takoy/ (as though a link target were built with no path after the series name)

the second and fourth episodes contain partial latin letters (the "C" in the second one, and "100" in the fourth) which are the full links, https://ux.pub/design_takoy/c and https://ux.pub/design_takoy/100

Probably the same kind of process to build urls for posts should be applied to the urls for podcasts so we get most if not all of the context from the title in the generated episode slug

**Comment by djuber** [comment]
The fix was merged into main.

@varhal if your site is a self-hosted forem, you should be able to update the latest image following the normal process, but you may need to remove and re-import the podcasts to get the full path/link from the episode titles after the update.

Something like this probably would work in a console(it will clear all existing episodes and start a process to import them again with full/usable episode links):

```ruby
# option 1 - only fix the specific Podcast "Design Takoy":

podcast = Podcast.find_by(slug: 'design_takoy')

# remove existing episodes
podcast.podcast_episodes.destroy_all

Podcasts::Feed.new(podcast).get_episodes(limit: 100, force_update: true)
```

You possibly have other Podcasts on the site that also have this issue, replace the slug and re-run (or remove all PodcastEpisodes, and use the general tool):

```ruby
# option 2 - remove all podcast episodes and recreate them
PodcastEpisode.destroy_all

# this will start one feed import per published podcast on the site, asynchronously in background jobs
Podcasts::EnqueueGetEpisodesWorker.perform_async
```

Otherwise removing the podcast through the site, and adding it again with the same information, should do the same thing (though may require more work on your side).

For hosted (by us) Forem instances this code change should be available after the usual Monday deployment.
