### ISSUE TITLE
Use latest version of jQuery

### ISSUE THREAD

**Issue by tnir** [forem/forem#17204]
### Describe the task

Use latest version of jQuery 3.6.0.

**Comment by Harmouch101** [comment]
I was about to file this issue after finding a [security report](https://snyk.io/test/npm/jquery/3.3.1) about this vulnerable version.

**Comment by tnir** [comment]
> I was about to file this issue after finding a [security report](https://snyk.io/test/npm/jquery/3.3.1) about this vulnerable version.

Actually https://security.snyk.io/vuln/SNYK-JS-JQUERY-174006 (or [CVE-2019-11358](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11358) and 
[CVE-2019-5428](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5428)) was already resolved in #17206, so you should refer https://snyk.io/test/npm/jquery/3.4.1 instead.

**Comment by Harmouch101** [comment]
> Actually https://security.snyk.io/vuln/SNYK-JS-JQUERY-174006 (or [CVE-2019-11358](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-11358) and
[CVE-2019-5428](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5428)) was already resolved in https://github.com/forem/forem/pull/17206, so you should refer https://snyk.io/test/npm/jquery/3.4.1 instead.

I meant before you opened the issue and did all the changes, the version of jquery used in production was `3.3.1`. Now, I don't see this library is used anymore. It was under the javascript libraries section:

![Screenshot from 2022-04-22 15-06-53](https://user-images.githubusercontent.com/62179149/164711534-ccac18fa-0148-4b6f-84b2-49a6ac6f1f2a.png)

That's why i was about to open this issue if it wasn't already. And i thought i would be a criminal if i didn't open this issue.

Anywho, have a great day.
