### ISSUE TITLE
Admin "Spam trigger terms" field should not accept regex

### ISSUE THREAD

**Issue by aitchiss** [forem/forem#17306]
## Background

An incident occurred where poorly formatted regex was accepted in the "Spam trigger terms" field (found in `/admin/customization/config`) and saved to the DB. As a short-term fix, [we are stripping out user-supplied regex from this field](https://github.com/forem/forem/pull/17305) at the point of usage, but in the longer-term we don't want to accept any regex in this field.

We also understand from the Community Success team that having this field as a regex is not providing value / causing an undue burden.

## Expected solution

To solve this we essentially just want to make sure that the "Spam trigger terms" field only accepts plain text, and not regex. We could choose to solve this either purely server side, or a combination of frontend and backend.

Backend: When a user enters regex in the "Spam trigger terms" field, we either:
- Inform the user of an error, or
- Strip out any regex before hits the DB

Frontend:
- We could update the text field to validate no special characters (only allowing alphanumeric + commas)
- We _could_ even move this input to using the newer `MultiSelectAutocomplete` which would similarly be able to strip out special characters

We will also need to consider the fact that the `spam_trigger_terms` for a given Forem may include regex currently.

**Comment by maestromac** [comment]
I think this could be way simpler.

With the design language we already have in place, there's not much else we need to do. In fact, we only add regex to this field is because only we ourselves know the backend is supports regex. 

Typically when a form accepts regex input, there's a clear indication. for example
![image](https://user-images.githubusercontent.com/15793250/165625531-460e6f67-2255-4d8a-9f94-8429fe3da8b7.png)

regex101 has a `/  [input goes here ] /gm` format much like other resources.

Since what we have is a normal form field, we can safely expect users not to get any crazy idea that it supports regex. We can expand the field description to ask users not to include regex. We don't even need to inform the user of any errors, because the whole input is treated as a normal string.

How does that sound? am I cutting too many corners? cc @JennieOcken

**Comment by maestromac** [comment]
After speaking with @JennieOcken and more investigation, we decided that no further action is needed.

The reason is that, with Jamie's fix in place, the form is already taking the string as is. Even if the user attempt to enter regex, the input is escaped and become a string literal. The form already provide proper description and the admin doc makes no mention of regex as a feature.
