### ISSUE TITLE
Community Wellness Badge

### ISSUE THREAD

**Issue by JennieOcken** [forem/forem#17310]
We would like to build a community wellness badge styled after the writing streak badge.  

Badge name: Community Wellness
Type: Streak of badges based on activity
Level 1: posting at least 2 constructive comments in a single week
Level: 2: posting at least 2 constructive comments per week for 2 straight weeks
Level: 3: posting at least 2 constructive comments per week for 4 straight weeks
Level: 4: posting at least 2 constructive comments per week for 8 straight weeks
Level: 5: posting at least 2 constructive comments per week for 16 straight weeks
Level: 6: posting at least 2 constructive comments per week for 32 straight weeks

“constructive” is defined as not flagged as negative by mods. The mods will be actively monitoring for productive conversation and flagging comments that aren’t constructive.

The DP team will provide graphics.

**Comment by JennieOcken** [comment]
@benhalpern Here is that issue for the community wellness badge.  Would appreciate those image files whenever you all have 'em.

Thanks!

**Comment by joshpuetz** [comment]
Some background:

There's prior art for this kind of badge with the writing streak badge: it award users a badge based on the writing streak from week to week. This awarding is done in `Badges::AwardStreak`, and it kicked off hourly by a cron job that enqueues a SideKiq job.

@jgaskins: any load related concerns on Forem (in particular Dev.to) hitting the comments table hourly in this manner to calculate badge awards?

**Comment by fdocr** [comment]
After some time diving into the queries needed for this I found out the SQL that would be required to make these checks would be pretty advanced. If we want to keep them SQL only I'd definitely need some help, as they're above my level of expertise with SQL.

I did manage to put together a [greedy algorithm](https://en.wikipedia.org/wiki/Greedy_algorithm) that I believe could be performant enough, even on DEV scale (I'll likely need some help confirming this too though 😅 ). I'd love to get some eyes on it. I shared the details [in this comment on the Draft PR](https://github.com/forem/forem/pull/17394#discussion_r855396486) as thoroughly as possible.

Also on that ^ same comment I mention there's a chance we can run this worker-service once or twice per day instead of hourly to reduce pressure on the hardware. Does that make sense?

**Comment by fdocr** [comment]
I just noticed something about the logic we're using to implement how we reward this badge. The problem:

1. User A posts two comments today
2. Badge background job runs and awards their first Community Wellness badge week
3. Mod flags one of the two comments posted hours later, but the badge is already awarded

An easy way to fix this would be to ensure comments are at least 24/48 hour old before awarding the badge, but looking for confirmation on this.

Two other things we need are the badge assets (not immediately blocking but will likely be blocking by end of the week) and [a copy review on these texts](https://github.com/forem/forem/pull/17394/files#r858857918) (entirely made up by me 😅 )

cc @JennieOcken @joshpuetz

**Comment by JennieOcken** [comment]
Making sure @SGGregory and @michael-tharrington don't have to crawl around in the code... here are the messages:

```first: Thank you for participating in constructive conversation! You posted two or more comments this week. Keep it up to continue the streak!
longest: 32 weeks! You've achieved the longest streak possible for Community Wellness badge. Amazing job engaging in the community and keep up your amazing contributions to our community!
other: Congrats on achieving a %{weeks} week streak for the Community Wellness Badge! Keep the constructive comments flowing to continue the streak!```

(I made some small edits)

**Comment by SGGregory** [comment]
Thanks @JennieOcken! Copy looks basically good but I made a few minor tweaks:

```
first: Thank you for participating in constructive conversation! You posted two or more comments this week. Keep it up to continue the streak!
longest: 32 weeks! You've achieved the longest streak possible for the Community Wellness badge. Amazing job engaging in the community and keep up your amazing contributions to our community!
other: Congrats on achieving a %{weeks} week streak for the Community Wellness Badge! Keep the constructive comments flowing to continue the streak!
```

As for the design, I mocked up something super-duper rough [here](https://www.canva.com/design/DAE_Aq-GuzE/4YKZs3nzy7VL7j4XkRCOZg/view?utm_content=DAE_Aq-GuzE&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink). If you have any gut reactions or feedback on the general direction of this, let me know. Otherwise, I'll formalize the request using this design direction for Emma and try to get you an estimated date of completion soon. Note that Emma's designs will have way, way better graphics, colors, etc!

**Comment by joshpuetz** [comment]
Pinging @emmmmmmmmmmmma for context here. @SGGregory: were does the work for Emma get tracked?

**Comment by SGGregory** [comment]
@joshpuetz team design requests of Emma are logged in Airtable. I turned this request into an issue in Airtable which I surfaced for Emma as well and will pass along updates for y'all about timing/drafts when Emma has them for me. We will discuss this during our 1:1 tomorrow and get back to you!

Feel free to continue making design requests in this exact manner which Emma and I will carry over to Airtable for team tracking and discussion 😊

**Comment by benhalpern** [comment]
@JennieOcken I just touched base with @SGGregory and we are "getting close" with the artwork.

**Comment by fdocr** [comment]
After reviewing the data from the "dry runs" (available [here](https://app.datadoghq.com/metric/explorer?from_ts=1651670416665&to_ts=1651756816665&live=true&tile_size=m&exp_metric=community_wellness_badge.award&exp_group=weeks&exp_agg=sum&exp_row_type=metric) and [also here](https://app.datadoghq.com/metric/explorer?from_ts=1651670446877&to_ts=1651756846877&live=true&tile_size=m&exp_metric=community_wellness_badge.award&exp_group=user_id&exp_agg=sum&exp_row_type=metric&exp_scope=weeks%3A4#weeks:1)) I can now see how the award would be given out to users and there are some details I think we need to clarify and likely tweak.

### What will happen the first time this executes on production (without feature flag)?

When the badge is awarded (**current logic**) we check for the "current longest streak to award" for that user. This means that if a user qualifies to be awarded with a `4 week` streak, we are only giving them that `4 week` streak. This means the user won't ever get the `1 week` and `2 week` streaks, unless they lose the current "long running streak" and start over.

1. Do we want to award them with each badge that they qualify for?
   - The side effect we would see here is that some users that already qualify for long running streaks of 8/16/32 weeks will receive many emails at once (one per each streak reward level)
2. Do we want to have the badge streak "start to count" from the moment we release the feature?
   - This means users that already qualify for long running streaks would start from the "first week" and would have to continue their streaks like everyone else, and continue their streak in order to achieve this 32 week level
   - This is an easy solution (implementation-wise) that, in other words can be read as:
      - Wellness badge streaks start to count from the moment we released this feature and aren't retroactive
3. Do we want to run a custom DataUpdateScript (DUS) to silently backfill all the Community Wellness badge streaks all users have?
   - This is the alternative that first came to mind when thinking we can go with option 1 (users will only receive their current longest running streak badge), but this backfill script would award all previous reward levels silently, a.k.a. without sending out multiple emails
      - The effect here would be: Once the feature goes into production, users with an `8 week` badge will have that badge awarded + email sent. This DUS would then award the 1, 2 and 4 week streak badges without sending the email so those users will have those badges on their profiles.

IMO I feel like option 2 is the easiest to implement. Option 3 would be my preferred alternative if we do care about sending out a few emails that are slightly redundant/spammy. Also open to hearing other alternatives though! 🙂

**Comment by SGGregory** [comment]
> @JennieOcken I just touched base with @SGGregory and we are "getting close" with the artwork.

Tada! Let us know if you have any questions or edits to this. We figured that the description could come from the site caption vs adding copy to the graphic but do let me know if you feel differently and think these need a title woven in. 
[community-wellness.zip](https://github.com/forem/forem/files/8635533/community-wellness.zip)

**Comment by joshpuetz** [comment]
Regarding https://github.com/forem/forem/issues/17310#issuecomment-1118554640: I agree that #2 sounds easiest and simplest, and I don't know that the work required for #3 would necessarily be worth the effort (or number of users it would impact).

Pinging @JennieOcken for input!

**Comment by JennieOcken** [comment]
Darn, I read all this and thought "we should do #2" and then completely failed to reply in comment form.  (silly Jennie)

We should do #2.
