### ISSUE TITLE
"Bad request" error when creating a post

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#17323]
When creating a post, a bad request page would show up first (shown below). 

![image](https://user-images.githubusercontent.com/11730007/163781255-007a3add-0e95-4122-aa4b-afcd0cc7f6ba.png)

When heading back to the feed via the URL, the post is created successfully.

**Comment by amywtlin** [comment]
Note: this showed up every time I posted something yesterday and this morning, but now it stops showing up. It is possible that this might not be reproducible.

**Comment by jeremyf** [comment]
@amywtlin as you are testing, things you'll need to provide are:

- What was the user you were logged in as
- were they an admin
- what was the state of the "Limit post creation to admins" button?

**Comment by amywtlin** [comment]
These are the two accounts that have encountered this issue, both when comment-only is on and off:

- regular user with posts: `amy_854` https://canary1.forem.wtf/admin/users/48
- super admin: `amy` https://canary1.forem.wtf/admin/users/32

I am on Chrome & MacOS.

**Comment by amywtlin** [comment]
Just tried it one more time with the 2 accounts above, not getting bad requests. 🤷‍♀️

**Comment by aitchiss** [comment]
This seems very similar to the issues I noticed previously, and [posted about in the dev slack channel](https://forem-team.slack.com/archives/C7GE84DEJ/p1648552125024769) - @ludwiczakpawel  mentioned seeing it often in the Canary Forem too.

Similar to you @amywtlin, I found it failed repeatedly and consistently... until it didn't. And then I haven't been able to reproduce since.

I'm just mentioning because it could be the same strange issue, and therefore I'm not totally sure it's related to roles & authorizations project
