### ISSUE TITLE
ticks for y-axis in Charts should be integer

### ISSUE THREAD

**Issue by tnir** [forem/forem#17433]
**Describe the bug**

ticks for y-axis in Charts should be integer.

<img src="https://user-images.githubusercontent.com/10229505/165303114-124e4f12-12a8-4884-a299-fcfb6219069d.png" width="50%">

**To Reproduce**
n/a

**Expected behavior**
As all numbers in y-axis are integer, ".0" is not required at ticks in y-axis.

**Screenshots**
See above.

This looks like a regression from #3102 for almost three years.

**Comment by juliannatetreault** [comment]
Hey, @tnir 👋 

Thanks so much for reporting this bug -- we really appreciate all the contributions that you've been making! 

I'm going to go ahead and assign the issue to you since you've already opened up a pull request for the work, but in the future, could you please first comment on the issue, expressing your interest to work on it, and allow the Forem Team some time to first triage and assign the issue to you prior to creating a pull request for the work? This will allow us to label the issue appropriately, add more context to the issue if needed, and gives other potentially interested folks an opportunity to contribute as well. 

Thank you again for all of the issues that you've logged and improvements that you've made to Forem! 🌟

**Comment by tnir** [comment]
Noted with thanks!
