### ISSUE TITLE
Sidebar Navigation Updates: Rename "Members" to "Members Manager"

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#17460]
📖 **As an Admin, I want my experience with navigating the Members Manager to be as straightforward as possible, so that I feel motivated to use Invitations, GDPR Delete Requests, and the Member Index View as a whole.**

✅ Tasks to complete:
- [ ] Rename "Members" in the sidebar to "Members Manager"

**Comment by Ridhwana** [comment]
@juliannatetreault, as soon as we [organize](https://github.com/forem/forem/issues/17461) the sidebar it covers this issue of renaming. Hence, because I've done the sub-navigation in [this PR](https://github.com/forem/forem/pull/17538), the renaming happened naturally, hence I'm just going to move this along with those changes as its impossible to work on those without this. Apologies!
