### ISSUE TITLE
Member Index View Filters: Filter by "Member Roles"

### ISSUE THREAD

**Issue by juliannatetreault** [forem/forem#17491]
📖 **As an Admin, I want my experience with filtering the Member Index View to be as pleasing and straightforward as possible, so that I feel motivated to use it.**

✅ Tasks to complete:
- [ ] Add ability to filter by "Member Roles" 
- [x] Adjust `Admin::UserQuery` to support filtering by multiple roles. (via #17919)

**Comment by aitchiss** [comment]
I've created a PR handling the basic UI functionality of showing the expandable list of roles, but I have a few questions to unblock me on the backend aspect of this.

**1. Mapping the UI "roles" to ones we can query the DB with**

I'm currently displaying all the available/filterable roles using the [SPECIAL_ROLES constant](https://github.com/forem/forem/blob/main/app/lib/constants/role.rb). However these are just 'pretty strings' that don't actually correspond to the 'real' roles we'd need to query the DB with. For example, `Resource Admin: Article` is not a role name, but `single_resource_admin` is, and would need queried with the single resource in question (articles).

I tried looking at how we handle this from the member detail view "add role" modal, and it seems to be with [this string matching function](https://github.com/forem/forem/blob/8b70e9e1f302079fda484f4c26eeb11ecef15a88/app/services/moderator/manage_activity_and_roles.rb#L57-L92).

My current thought is that I will need to write a similar string matching function to be able to query for users matching these roles - or is there a more elegant way? Would [inside UsersQuery](https://github.com/forem/forem/blob/main/app/queries/admin/users_query.rb) be the best place to add that kind of helper?

I considered a helper for the view that provided a more helpful `value` for the checkboxes, e.g. "Tech admin" -> "tech_admin", but I don't see this working with the `single_resource_admin` options mentioned above (since multiple UI options map to `single_resource_admin`)

**2. How to extract multiple of the same param**

Currently we rely on URL query params to filter the index view, e.g. `?role=admin`. The feature makes it possible to filter by _multiple_ roles, and at the moment the frontend is adding these multiple roles as separate query params, e.g. `?role=admin&role=tech_admin`. When the `UsersQuery` pulls out the `role` param, it naturally only gets the last instance in the URL string.

What's the standard way to handle "OR" params in this case? Do I need to make changes to the frontend form so it sends a single query param with an array, e.g. `?role=[admin, tech_admin]`?

**Comment by jeremyf** [comment]
**2. How to extract multiple of the same param**

From https://guides.rubyonrails.org/action_controller_overview.html#hash-and-array-parameters

> The params hash is not limited to one-dimensional keys and values. It can contain nested arrays and hashes. To send an array of values, append an empty pair of square brackets "[]" to the key name:
>
> GET /clients?ids[]=1&ids[]=2&ids[]=3

There's more about encoding.
