### ISSUE TITLE
Why is it not indicated anywhere what the latest version of FOREM is?

### ISSUE THREAD

**Issue by kseniya93** [forem/forem#17603]
Hello. Why is it not indicated anywhere what the latest version of FOREM is? Why can't I download Releases on GITHUB or on the official site in one click with information about the change (downloading via the CODE button does not count, I don't know which version I'm downloading)?

**Comment by JennieOcken** [comment]
Hi @kseniya93 ,

Thank you so much for your question.  I appreciate your request, let me give you a bit of background on what we are doing.
We have a SaaS product that we make available to self-hosters.  That means that we are constantly pushing new updates to our main line and our head of main is always very stable.  In fact, the first site we push any update to is [DEV.to](http://dev.to/).  Because we approach our product as a SaaS product, we don't bundle updates into official releases and we don't hold merges for release packages.  Instead, we merge whenever something is ready to go.  For our SaaS hosted clients, we take care of the deploys for them to keep them on regular updates and we actually do a release every Tuesday and Thursday for those Forems.

As a self-hoster, you get to choose when to update your Forem.  If you go to the forem/forem repo you can see the SHA and time/date stamp of our last release.  In your Forem, you can find the version and SHA on the bottom of the main /admin page.  Alternatively, you can find this information in the application HTML or by looking at your application’s forem directory and doing git log -1 .  We do recommend updating regularly, and as I mentioned above, we update our hosted clients twice a week.

Alternatively, we announce major features that we have released recently, or will be releasing soon, on [forem.dev](http://forem.dev/) using the #changelog tag.  This is a great way of finding out what major features have recently been created.  We have done a couple rollup posts in recent months, and will continue to do some rollup announcements, but because we release so much none of these will ever be all encompassing.  Though we do try to do something a bit more specific than "bug fixes". 😃 
 
Hope that helps.

**Comment by jeremyf** [comment]
I'm closing this issue as Jennie's answer addresses the initial request.
