### ISSUE TITLE
SPIKE: Security audit of existing API Key usage and generation in Forem

### ISSUE THREAD

**Issue by JennieOcken** [forem/forem#17648]

**Comment by fdocr** [comment]
Our existing setup:

- API Key generation
   - Relies on the `ApiSecret` model
      - `secret` is generated using `has_secure_token` ([reference](https://api.rubyonrails.org/classes/ActiveRecord/SecureToken/ClassMethods.html#method-i-has_secure_token))
      - A consideration, since we're now on Rails 7, is that we can maybe use [ActiveRecord encryption](https://guides.rubyonrails.org/active_record_encryption.html) to enhance the security here slightly
   - Generated in `ApiSecretsController` which looks solid IMO
- API Key usage
   - By users
      - This is the current main use case for API Keys
   - By organizations
      - Organizations can't create an `ApiSecret` for their use (independent of a specific user)
      - If we do want to provide this feature we'll likely have to improve the existing Organization UI in `/settings/organization` for a more thorough CRUD interface
- Web context (JavaScript on the browser) API consumption (without API Key)
   - The API has a second authentication option along with the user generated API Keys, which is a XHR (Ajax request) authenticated from a web context
   - Authentication code [here for reference](https://github.com/forem/forem/blob/main/app/controllers/api/v0/api_controller.rb#L54-L80)
   - This is an authentication option in use because different areas of the app rely on this seamless way to make requests to the API
      - Some examples of where we're fetching the API directly from the web app's JS codebase are:
         - [Paginated followers in Dashboard](https://github.com/forem/forem/blob/main/app/assets/javascripts/initializers/initScrolling.js#L154)
         - [Onboarding](https://github.com/forem/forem/blob/main/app/javascript/onboarding/components/FollowUsers.jsx#L52)
      - This seems enabled only on a subset of the API endpoints (see image below)

![Image](https://user-images.githubusercontent.com/6045239/171205338-c97c3016-a0b3-40c3-9f26-e60224c791ea.png)

Based on the above I feel like a big overhaul of the authentication implementation would be too large in scope for us right now. Options we have at hand here:
1. Include Doorkeeper gem again in our app and use it to safeguard our API v1
   - [Reference/Example here](https://github.com/doorkeeper-gem/doorkeeper/wiki/ActionController::Metal-with-doorkeeper)
   - This would allow us to expose access tokens & refresh tokens for API consumption instead of our existing implementation
   - This approach sounds good for API consumption except for the web context requests, which would require a considerable refactor to continue working (AFAICT)
   - More context (#15748): Doorkeeper was once included in our app and removed because it was no longer in use. But we considered including it again in the future (are we in that future now?)
2. Keep our authorization flows for API v1
3. Rollout another authorization
   - I feel like our existing authorization flow is secure enough to make this an inviable option (due to the effort required to refactor) but I could be wrong? Open to discussing suggestions here

In previous conversations I feel like our biggest security concerns come from how open our API is to consumption of the sites (allowing any API Key to consume almost the entirety), so authorization/scoping of access instead of authentication. Doorkeeper allows us to have a solid foundation with standards that are maintained by a well known OSS gem, but requires a bit larger refactor. Our existing auth would likely allow us to move faster without breaking that many areas of the app.

**Comment by joshpuetz** [comment]
> In previous conversations I feel like our biggest security concerns come from how open our API is to consumption of the sites (allowing any API Key to consume almost the entirety), so authorization/scoping of access instead of authentication. 

Agreed: the biggest concern was that someone can just pull down all articles (without using an API key at all!), so focusing our efforts of securing those endpoints and putting appropriates roles limits in place will go a long way. Monitoring API usage could also help.

Notably, I don't see anything here that would prevent us from pivoting to Doorkeeper in the future!
