### ISSUE TITLE
SPIKE: Logging - can we hook into some kind of existing audit trail of negative actions taken on a user

### ISSUE THREAD

**Issue by JennieOcken** [forem/forem#17652]

**Comment by fdocr** [comment]
We currently have an implementation (at least partial) here with the `AuditLog` model. I feel like in order to make this work we need to:

1. Improve the admin UI of this feature
   - Right now we have `/admin/moderation/moderator_actions` in the admin dashboard
      - This is just a list of all moderation actions ever taken
   - What are the end use-cases for this audit log? UX-wise
      - Only admin needs to see this or which roles should have access? 
      - What do they need to see? How should it look like (product-design)?
         - We might want to allow for filters and/or grouping
         - Better UI than a raw JSON data would likely be ideal
2. Extend the use of the existing `AuditLog` to track other actions
   - Within the scope of this Epic (#17668) I feel like we would want separate tracking for each of the new endpoints (see `Definition of Done`) but it would likely be beneficial to understand to what extend this is being used by creators (if they use it)

An alternative would be to replace the `AuditLog` implementation with an existing gem that solves this problem. We would still likely need to implement UI/UX for the consumption despite some of these examples have a built-in UI (not-ideal IMO):
- https://github.com/collectiveidea/audited
- https://github.com/paper-trail-gem/paper_trail
- https://github.com/rails-engine/audit-log

In order to avoid possible cumbersome data migrations I'm personally leaning more towards using our existing implementation, but as always, open to discussing more about the pros/cons of this.
