### ISSUE TITLE
Save post when user press cntrl + s

### ISSUE THREAD

**Issue by sarthology** [forem/forem#1772]
**Is your feature request related to a problem? Please describe.**
Sometimes accidentally while writing the post I press control + save. It opens the browser default save command to wonder if we can change that.

**Describe the solution you'd like**
By using this simple snippet that can be fixed

```javascript
document.addEventListener("keydown", function(e) {
  if (e.keyCode == 83 && (navigator.platform.match("Mac") ? e.metaKey : e.ctrlKey)) {
    e.preventDefault();
    // Save post instead...
  }
}, false);
```
Using this the default event can be stopped. Maybe you guys can trigger the save the post function here.

Not sure if it's a bug 🤔

**Comment by aligoren** [comment]
Or using `control + s` key article can be an autosave.

**Comment by rhymes** [comment]
@sarthology @aligoren I think this is going to be easier once the work @aspittel is doing on https://github.com/thepracticaldev/dev.to/pull/1633 is completed. She's working on amazing feature!

**Comment by aligoren** [comment]
@rhymes Thanks, I found after I commented.

**Comment by sarthology** [comment]
@rhymes oh that's cool.

**Comment by Zhao-Andy** [comment]
@sarthology now that we have auto-save, is this a feature you'd still like?

**Comment by sarthology** [comment]
Yup, As it's just a thing When you are in the zone and writing stuff, you anciently press `control + s` and that's sucks. AutoSave is cool though. But I wish, if not saving we can at least prevent the default event of saving the webpage. 🤔

**Comment by Link2Twenty** [comment]
This will be easier to implement once #10713 is merged

**Comment by cmgorton** [comment]
Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
