### ISSUE TITLE
SPIKE: What are the current API usage numbers?

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#17805]
How many users are actually using the API? How many API keys do they use?

**Comment by joshpuetz** [comment]
Key stats:

Out of 802944 users, 3525 user have created at least one API key.

**Comment by joshpuetz** [comment]
Daily we're seeing anywhere from an average of 7 to 10 million requests to the api, the vast majority of those requests are to the `api::v0::articlescontroller_show`, `api::v0::articlescontroller_me`, and `api::v0::articlescontroller_index'.

However: occasionally there are spikes in API request volume of 15-20 million requests alone centered around `api::v0::userscontroller_show`

**Comment by fdocr** [comment]
These are the endpoints in question:
1. `api::v0::articlescontroller_show`
   - Fetch (show) an article by id 
   - [reference](https://developers.forem.com/api#operation/getArticleById)
2. `api::v0::articlescontroller_me`
   - Fetch the authenticated user's articles
   - [reference](https://developers.forem.com/api#operation/getUserArticles)
3. `api::v0::articlescontroller_index`
   - Fetch all published articles on the site in reverse chronological order
   - [reference](https://developers.forem.com/api#operation/getArticles)

> We should plan on keeping the existing API endpoints operational as they are and issue a deprecation notice

I agree with this

> And help me understand what makes you feel like tat is suspicious and what the potential consequences are.

I can let Josh share his reasons, but to me it feels like the spikes aren't "organic use of the API" and is more likely someone (one or more people) making a large batch of requests to fetch a large list of posts, either for the first time or they do it from time to time to "get the latest version of them" (edits/updates on the articles maybe).

IMO with a deprecation notice we can have anyone that will be affected (with a valid use case) contact us in advance to consider their situation, in case they would no longer be able to continue doing what they're doing. However, I feel like they should still be able to do whatever is they're doing with an API Key (instead of without any authentication).

I wonder if you were thinking of something different though @joshpuetz 😄

**Comment by joshpuetz** [comment]
Agreed @fdocr: those spikes feel like a "bot hoover up a list of all Dev.to members" situation, and not something we care to support going forward.

I'll also point out none of these heavily used API endpoints are in the [list of endpoints we use in the code](https://github.com/forem/forem/issues/17809#issuecomment-1144901064)

**Comment by JennieOcken** [comment]
Thank you for the education.  100% agree with the direction here with one tweak.  It seems like to me that `api::v0::articlescontroller_me` is actually doing what I want to allow someone to do with this API (e.g. get all my posts) and with the basic security we want (API key).  Is there a reason to issue a deprecation notice on that one?


It's super interesting that the spikes are happening on `api::v0::articlescontroller_show` instead of `api::v0::articlescontroller_index`.  That seems like a pretty inefficient path to scape the site.  Unless I am missing something?

**Comment by joshpuetz** [comment]
Even though `api::v0::articlescontroller_me` has correct security, it still lives at the `/api/v0` URI that will be going away. We should let users know that **everything** at `/api/v0` will need to be fetched from `/api/v1` in the future (we will redirect these paths during the deprecation period).

> That seems like a pretty inefficient path to scape the site.

Given the alternative (writing a bot to scrap the HTML page directly at https://dev.to), it's actually pretty effective!
