### ISSUE TITLE
SPIKE: what API endpoints are current in use by the codebase?

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#17809]
The Forem codebase uses a few of the current API endpoints: which ones? Will we need to change the API Urls? Are these endpoints already using API keys?

**Comment by fdocr** [comment]
> do you know of any other API endpoints used in the code?

I can't find any other requests made to our API on our codebase at the moment. However, I do know that [listings allows for requests from the web context](https://github.com/forem/forem/blob/main/app/controllers/api/v0/listings_controller.rb#L10-L11) (API Key or current user), which is a tell that it may have been used in the past, though it seems like it isn't being actively consumed right now (from our app JS code).

> I'm thinking we're going to have to refactor most of these usages to pass along a user's API key (if possible), and should do that as part of this release. Any thoughts?

I agree that the refactor will be necessary. Though based on the comment from #17805 

> Even disregarding the suspicious high volume spike in API usage, it's clear our API is being used pretty heavily. We should plan on keeping the existing API endpoints operational as they are and issue a deprecation notice

My first thought is that we could keep these working with v0 for this transition period, and then refactor the FE code that consumes these endpoints _either_ as part of this release, or as part of removing v0 from the codebase (post deprecation period), which isn't part of this Epic's definition of done (right? 🙂 ).

In order to complete the Epic in a shorter timeframe I think the latter would be better (I guess it depends on what deprecation timeframe we are giving), unless you feel differently about this.

Also a small side note: I believe the `edge_cache` service occurrences are just endpoints that are flushed from cache (Fastly or Nginx). Meaning that a call is made to the cache provider to flush that URL, not that it's being consumed from there directly. So we shouldn't need to touch that area AFAICT.
