### ISSUE TITLE
Validate/Document rational for disabling CORS

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#18039]
We've received a few questions from the community asking why CORS is disabled on API endpoints (example: https://forem-team.slack.com/archives/CAA200SH5/p1656692658360069). We should validate and document this decision.

**Comment by fdocr** [comment]
In terms of concerns I feel like most of the resources (i.e. articles) out there, including popular Q&A sites like StackOverflow ([ex1](https://stackoverflow.com/questions/12001269/what-security-risks-exist-when-setting-access-control-allow-origin-to-accept-all), [ex2](https://medium.com/@ehayushpathak/security-risks-of-cors-e3f4a25c04d7), [ex3](https://portswigger.net/web-security/cors#:~:text=Vulnerabilities%20arising%20from%20CORS%20configuration,can%20result%20in%20exploitable%20vulnerabilities.)) are related to actions that create/modify/delete data.

Over time our API V0 has maintained an open policy for some GET resources and this hasn't been maliciously exploited. Our concerns over closing this policy on V1 were founded by the goal to restrain public access to these resources, but the side effect of this is making our (still public) API V1 only to be accessible on server side projects (that is the only environment that is secure enough to hold API keys since this isn't possible on FE environments). Given the questions/pushback received (see example in [issue description](https://github.com/forem/forem/issues/18039#issue-1294381312)) we can consider rolling back our original decision regarding CORS and openly unauthenticated requests to some of our GET resources.

For the sake of comparison, we can also consider that some popular API's exist with open CORS + unauthenticated access. To name a few (with links to their docs:
- [Soundcloud API](https://developers.soundcloud.com/docs#errors)
- [Spotify lookup API](https://developer.spotify.com/documentation/web-api/)
- [GitHub V3 API](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#cross-origin-resource-sharing)
- [Dropbox API](https://dropbox.tech/application/some-love-for-javascript-applications-2)
- Also here's [a list with other examples & resources](https://enable-cors.org/resources.html)

**Comment by joshpuetz** [comment]
This is great @fdocr! What would the effort look like to re-enable CORS on the API?

**Comment by fdocr** [comment]
I almost have it all implemented in https://github.com/forem/forem/pull/18213, so I'd say a few days to get feedback on it and then merge? Since it was all already implemented in V0 I'm going back to some of those concepts already existing there

**Comment by fdocr** [comment]
By the way, I think it's best to split that PR up. I can get the CORS-related changes in a separate PR and keep the removal of the FeatureFlag there, to be merged after that other one is in. Let me know if anyone feels like it should be approached differently. The effort there would probably be lower in terms of PR review for other core team members.
