### ISSUE TITLE
Allow viewing your hearts (❤️) and unicorns (🦄) history

### ISSUE THREAD

**Issue by j-f1** [forem/forem#1806]
**Is your feature request related to a problem? Please describe.**
I’d like to be able to mark posts with 🦄 to save them for later without having to have them in my reading list.

**Describe the solution you'd like**
It would be great to have a list of posts I’ve ❤️ed or 🦄ed so I can refer back to them later

**Describe alternatives you've considered**
Maybe a separate list I can save things to once I’ve read them?

**Additional context**
N/A

**Comment by maestromac** [comment]
Thank you for creating this feature request @j-f1 !

**Comment by keith-hall** [comment]
I would also like to see this implemented - I have been reacting with a heart to posts I have read, thinking I would be able to find them again later in case I want to re-read them. I didn't save them to my reading list, for this reason and also because I only want to keep articles I haven't read yet there, for easier discovery/filtering.
Is there any API I could use for now to find these reactions of mine please so I can put them on my reading list until this UI history is implemented? I saw that exporting my profile doesn't include this data.

**Comment by j-f1** [comment]
I don’t think this has been resolved.

**Comment by johncurcio** [comment]
How would this feature work best? 

- **Like twitter**: your :heart: and :unicorn: are on your profile and anyone can see them; (_I personally like this_)
- **Kind of like twitter**: your :heart: and :unicorn: are on your dashboard and only you can see them;
- **Completely different**: :heart: and :unicorn: as tabs in the reading list and only you can see them.

And should liked comments be included here?

**Comment by Nikla436** [comment]
Describe the solution you'd like
I often will 'heart' things I enjoyed and may want to look back on later, and would like a way to view all things I've reacted to. (hearted, unicorn, etc).

Often I'll remove things from my reading list when finished, but would like a way to get back to what I've enjoyed before.

Ex: Reddit will allow you to view your history, upvotes, downvotes, etc. That would be nice here as well.

**Comment by Link2Twenty** [comment]
Any update on this one from the team? @rhymes @jessleenyc

**Comment by cmgorton** [comment]
Hey all.  Thank you for opening this request and starting a conversation.
Since this has been open for awhile without much progress I am going to close it here. 

Features tend to be subjective and might spur some debate. The Forem core team 
now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
