### ISSUE TITLE
Composer toolbar overflow on notifications screen

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#18103]
**Describe the bug**

Toolbar overflows on narrow screen for newly-introduced comment toolbar

**To Reproduce**

- Reduce screen size too mobile width
- Go to `/notificatioins` and click "reply" to a comment
- Scroll right

**Expected behavior**

Does not overflow

**Screenshots**

<img width="455" alt="Screen Shot 2022-07-13 at 12 25 34 PM" src="https://user-images.githubusercontent.com/3102842/178783991-25a218ac-86d5-4042-bbe4-85816cfce05e.png">

**Comment by aitchiss** [comment]
For the moment I'm going to hide the toolbar completely on this page, because we don't currently show full comment functionality on `/notifications` (e.g. previously we had no templates or image upload), and so I'm not sure if it's intended to be shown here at all.

I'll check with product/design if we do want to introduce the toolbar here, and if so we can view https://github.com/forem/forem/pull/18112 as a temporary fix, and reintroduce the toolbar without these issues, and consideration of templates etc, in a later PR.
