### ISSUE TITLE
A way to jump to comment area fast while reading a post

### ISSUE THREAD

**Issue by amywtlin** [forem/forem#18127]
## Notes
This issue is blocked by #18277 -- needs to be paired up with the deployment of the removal of the unicorn reactions icon.

Adding a shortcut to jump to the comment area: I often find myself wanting to comment on something while I was still reading a post, having to scroll all the way down to the comment editor.

## To-do

We are introducing a sticky comment button:
1. Desktop version: to the left, along with reactions
   ![Image](https://user-images.githubusercontent.com/11730007/187625676-88ed9473-a3f1-4cde-9bc4-ab36d10c35b8.png)
1. Mobile: to the bottom, a sticky action toolbar
   ![Image](https://user-images.githubusercontent.com/11730007/187625207-33347479-6a45-498c-bd5e-e7d674c2ea10.png)
   See [Figma link](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=701%3A2026) for exact dimensions
   ![](https://user-images.githubusercontent.com/84626054/183574723-2bd70295-d4b7-410a-9a34-1cdb172a95ed.png)

Product point person: @amywtlin, @anujbhavsar96

**Comment by anujbhavsar96** [comment]
Right now, we don't have a comment icon in the action toolbar on the left side. Adding a comment icon will allow users to jump to the comment section.

**Interaction**
Clicking on the comment icon should take users to the comment area with the comment field focused. And clicking on the comment number should take users to the comment area only with no comment field focused.

**Desktop**

![With Comment](https://user-images.githubusercontent.com/84626054/180944621-f5125c65-35c3-484d-aaa6-38b3b9c1fc78.png)

**Mobile**

![With Comment - Mobile](https://user-images.githubusercontent.com/84626054/180944979-a312fbaa-e129-4310-ac73-0466d7e660c2.png)

**Comment by Link2Twenty** [comment]
Don't forget there might also be a mod shield in that bar.
Things start getting quite tight on mobile.

**Comment by anujbhavsar96** [comment]
@Link2Twenty Thanks for pointing this out. I'm aware of it. In that case, I would want the Shield icon to be a floating action button.

**Comment by aitchiss** [comment]
>  In that case, I would want the Shield icon to be a floating action button.

I just want to flag up that we originally had this FAB but removed it because it was frustrating users by obscuring content (e.g. https://github.com/forem/forem/issues/14062). At the time we even did a poll of mods, and they overwhelmingly agreed the button should be removed  - check out https://forem-team.slack.com/archives/C01MK34RE6P/p1635859139065700?thread_ts=1635370983.032100&cid=C01MK34RE6P

I wonder if we could instead consider adding the moderation action in the overflow menu?

> Things start getting quite tight on mobile.

I'm also a little bit concerned that very popular posts can have thousands of likes, and hundreds of comments. Perhaps one of the more extreme examples:

![DEV post with over 3000 comments, and 8000 bookmarks](https://user-images.githubusercontent.com/20773163/182845577-62a9284c-660c-4481-9481-0ff45a73c5af.png)

This post also has 226 comments, and even without the mod shield I think we would struggle to fit the count + icon into the action bar.

Do we want to consider hiding the comment count if there's insufficient space?


> Clicking on the comment icon should take users to the comment area with the comment field focused. And clicking on the comment number should take users to the comment area only with no comment field focused.

I worry a little bit that it's going to be hard on touch devices to click the option that you want - accessibility guidelines ask for a minimum of 44px x 44px touch target, and I don't think this is technically possible if we want everything in the action bar to have two touch targets (e.g. comment icon vs comment count).

I guess in this case there's not a big negative impact if you press the wrong one 🤷‍♀️

**Comment by amywtlin** [comment]
@Link2Twenty Just wanted to say that's some awesome simulation you have done there 😍

**Comment by anujbhavsar96** [comment]
> I just want to flag up that we originally had this FAB but removed it because it was frustrating users by obscuring content

Wow. That was unexpected 😂. Then, in that case, putting it inside the overflow menu should be fine. Also, we were thinking of removing the Unicorn reaction, and if we do that first, then the comment icon can replace it.

Also, some mocks around different scenarios. We are also planning to show a list of reactors so we can display the full number in that modal. But it won't be possible for the readers, though. Also not sure how important it is to display full number of likes or comments instead of 9.9k.

![Frame 98](https://user-images.githubusercontent.com/84626054/183012350-2cb5fc89-5a72-4bda-b2f8-5b3130dc05f9.png)


> I think dropping the count on bookmarks makes sense, I don't think anyone but the author really cares how many people have bookmarked it

@amywtlin 👆

**Comment by aitchiss** [comment]
> But it won't be possible for the readers, though. Also not sure how important it is to display full number of likes or comments instead of 9.9k.

I guess if we are showing a shortened number like 9.9k, then readers are still getting the core info - "hey, a lot of people liked this!". Dropping the bookmark count would also help free up space.

> Also, we were thinking of removing the Unicorn reaction, and if we do that first, then the comment icon can replace it.

That's true, it would free up exactly the right amount of space 😄 

I'm going to add the `needs product` label back on this one for now as I think we need to make some decisions around how we go about this before engineering can pick up 👍

**Comment by amywtlin** [comment]
> I think dropping the count on bookmarks makes sense, I don't think anyone but the author really cares how many people have bookmarked it

@anujbhavsar96 +1 to this. As we are also simplifying reactions, it makes sense to not show it. However, does that mean we would show it when it's the author who is reading the post vs when it's a reader?

**Comment by anujbhavsar96** [comment]
@amywtlin I'm not sure about this. This might be a question for the community. Does the bookmark number bring any value to the author? If yes, just showcasing the number enough, or do we want to show a list of who bookmarked since we are displaying a list for reactions?

IMO for the author, just a number should be enough for the bookmark to gauge the popularity of the post. No need of a list of who bookmarked.

**Comment by anujbhavsar96** [comment]
Okay, so assuming we will remove the Unicorn, and based on the [discussion here](https://github.com/forem/forem/issues/18125#issue-1305677653) about the post-reaction list, we decided not to keep interaction of modal opening in the action bar, it'll get easy to accommodate elements for mobile with enough touch area.

**Some scenarios based on the author and reader persona.**

![Comment Addition](https://user-images.githubusercontent.com/84626054/183574723-2bd70295-d4b7-410a-9a34-1cdb172a95ed.png)
[Figma link](https://www.figma.com/file/Rl50gxO5BHioRC3nUoRQ7M/Reactions-%E2%9D%A4%EF%B8%8F?node-id=775%3A1357) for exact dimensions

**Comment by joshpuetz** [comment]
@amywtlin @anujbhavsar96 I have a UX question: should the comment count in the 'jump to comments' button update when a comment is made on the page? For example, here's how I have it looking right now in my branch:

<img width="427" alt="CleanShot 2022-09-14 at 11 12 09@2x" src="https://user-images.githubusercontent.com/37842/190208783-f9f1086e-bb69-42e9-b311-e2772c13d848.png">

If the user clicks the heart, or bookmark indicators, those counts update. If the user makes a comment, should the comment count update? My gut says yes, but it does certainly add to the complexity of the page (it's easier for the reaction buttons to update their counts since the action is happening right on the button. With a comment: the comment is made in a different control than the "jump to comments" button)

**Comment by anujbhavsar96** [comment]
Yes, it should update the count if a comment is posted. 

> With a comment: the comment is made in a different control than the "jump to comments" button)

Even if the count gets updated after the refresh, that should be fine, I guess. Also, We have a comment count on the index page.

**Comment by joshpuetz** [comment]
> Even if the count gets updated after the refresh, that should be fine, I guess. Also, We have a comment count on the index page.

That part will definitely happen, it's the "live" comment count update on the page that I'm wondering about.

**Comment by anujbhavsar96** [comment]
I think it should update. I just noticed we also have a comment count above the comment input box. So if we don't update the sidebar count, it would look like a bug.
