### ISSUE TITLE
Add a way to note user and/or posts that were banned/suspected via API

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem#18121]

**Comment by fdocr** [comment]
Surfacing [what was mentioned here](https://github.com/forem/forem/pull/18043#discussion_r921587408), after some more thought I believe we can use the [AuditLog](https://github.com/forem/forem/blob/main/app/models/audit_log.rb#L1) model to encode these actions so that they are easier to revert if necessary. 

Open to discuss this and other alternatives too, so for now I updated the issue's title to reflect a more generic need of encoding these actions.
