### ISSUE TITLE
Overflow in the x direction is scrollable for smaller devices.

### ISSUE THREAD

**Issue by Sadeedpv** [forem/forem#18284]
**Describe the bug**
While I was reading a blog on my mobile device, I noticed a small bug causing an overflow in the horizontal direction of the webpage that affects the responsiveness of the website. The screenshot of the issue is given below:

**Screenshots**

![Issue](https://user-images.githubusercontent.com/96517901/183368219-e81a28c1-816d-4047-859a-45b006f50f21.png)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**

I guess it is the comment written inside the code block causing the issue. Here is the link to the [blog](https://dev.to/turinumugisha_s/the-most-awesome-trick-for-tables-mobile-responsiveness-you-will-ever-need-32cp) that caused the error. When I checked more blog posts on dev.to, I happened to see that it’s the lengthy comments written inside the code blocks that cause the error in every post.

**Comment by rt4914** [comment]
I am unable to reproduce this issue locally. Please have a look at this loom video for reference https://www.loom.com/share/786be2b43f4d4dd8a30f1cdb2a7b3598

**Comment by mirie** [comment]
@rt4914 Please check out https://canary1.forem.lol/mai_178/the-most-awesome-trick-for-tables-mobile-responsiveness-you-will-ever-need-using-html-and-css-only-416f -- I copied the title/markup of the problematic post. You can see the problem on this instance too. Perhaps if you grab the copy from the post on Canary, you'll be able to replicate locally too 🙏

**Comment by rt4914** [comment]
@mirie 

I have reproduced this error locally. Thanks.

I have come to the conclusion that the mistake is in post/article itself and not in the code.

Basically there are two `<td>` tags in the text area of article but they were not written inside `single-ticks`( ` ) as a result they were considered as html tags and therefore the entire UI issue.
If those two `<td>` tags were written in between single-ticks it would have worked correctly.

I have displayed this here too: https://www.loom.com/share/52bb171b2b4949dfa991cb9dbb7df516

In below images focus around the text of `<td>` tags.

## Edit vs Preview on current article
<img width="250" alt="Screenshot 2022-10-07 at 1 52 16 PM" src="https://user-images.githubusercontent.com/9396084/194507817-ef2e05c5-7a07-427b-a40a-534f1b52a409.png"> ... its Preview Version is ... <img width="250" alt="Screenshot 2022-10-07 at 1 52 27 PM" src="https://user-images.githubusercontent.com/9396084/194507826-a36e390d-e821-4d63-89e7-c8951e1144bb.png">


## Edit vs Preview after adding single-ticks to HTML tag
<img width="250" alt="Screenshot 2022-10-07 at 1 51 27 PM" src="https://user-images.githubusercontent.com/9396084/194508164-50f8c06d-4734-482d-bd73-e506397cbdcc.png"> ... its Preview Version is ... <img width="250" alt="Screenshot 2022-10-07 at 1 51 43 PM" src="https://user-images.githubusercontent.com/9396084/194508171-32ded731-ea1d-4223-b412-8fa635ecf550.png">


The bigger question can be: Should we proactively handle such mistakes in articles or let them be as it is? I think leave them as it is, is correct because if the user double checks there post they can easily fix such issues.

**Comment by rt4914** [comment]
@Ridhwana Any thoughts on above comment?

**Comment by mirie** [comment]
@pkfrank Is it OK for us to fix the article since this is a reported bug or should we leave it as is? If we fix and re-save the content, is there anything we need to be aware of?

**Comment by pkfrank** [comment]
@mirie this feels relatively edge case-y in terms of frequency, but it does seem like something we should fix.  We shouldn't be okay with a user-generated input that could break our styling in a way that hurts other user's experience.

**Comment by mirie** [comment]
Resolved, forgot to close issue
