### ISSUE TITLE
Consistency problem with reaction counts in local environment

### ISSUE THREAD

**Issue by fdocr** [forem/forem#18312]
**Describe the bug**

When adding likes to comments in the local environment some weird behavior comes up. It seems to be related with caching in the local environment. When caching is disabled there are inconsistencies between the comment's `public_reactions_count ` (validate the model attributes using `rails console`) and the like button that appears on-screen.

Researching the root cause of this issue will be valuable because there's a chance some of this behavior is slipping into production environments (not reproducible at the moment but worth making sure this isn't the case).

**To Reproduce**

- Ensure caching in local environment is disabled using the steps provided below
- You'll find inconsistencies (steps 8 & 9)
- Ensure caching is enabled again
- You should experience the expected behavior

**Expected behavior**

Steps including (how to enable/disable cache):
1. Stop local server
3. bundle exec rails dev:cache
4. Start local server
5. Refresh page and then browse an article
6. Submit a new comment
7. The comment should appear liked by the author of the comment (after it's submitted)
8. Clicking the like button again should remove the default like (should appear without a counter instead of "0 Likes")
9. Refresh the page and the counter should maintain its integrity

**Screenshots**

Example test flow with caching enabled (expected behavior):

https://user-images.githubusercontent.com/6045239/183705083-b1265cf8-ab23-46ed-b71c-7db676e4ec85.mov

**Desktop (please complete the following information):**

- OS, version: `MacOS 12.1`
- Browser, version: `Chrome 104`

**Additional context**

Check out the conversation [in this thread](https://github.com/forem/forem/issues/18126#issuecomment-1209151867) for more context

**Comment by amywtlin** [comment]
@fdocr moving this to `Ready for dev` on the product/eng board as it looks ready - feel free to reverse the action if not though!

**Comment by joshpuetz** [comment]
Is this related to this bug report at all? https://github.com/forem/forem/issues/18338

**Comment by fdocr** [comment]
I do think it could be related! Getting to the bottom of this might help understand the situation there too. I'll keep that in mind while debugging this 👍🏼

**Comment by Ridhwana** [comment]
We [paired](https://forem-team.slack.com/archives/CAA200SH5/p1661357179857209) on this a bit, and whilst we did find inconsistencies on this related to https://github.com/forem/forem/issues/18338, we did not replicate a caching issue :(

**Comment by fdocr** [comment]
When I started researching this a couple weeks ago [I attempted this (PR)](https://github.com/forem/forem/pull/18354) to ensure the UI displays a 1 by default and let it work its way from there... But I was still seeing some inconsistencies locally.

In case it helps, I see we're making a `/reactions` request from the FE after a comment is submitted.

<img width="1354" alt="Screen Shot 2022-08-30 at 09 42 12" src="https://user-images.githubusercontent.com/6045239/187481533-469cf689-0978-466a-b312-50d61b3b41b7.png">

I do see the like in the payload response, but this screenshot was taken on [BHC](https://community.benhalpern.com/) so the async auto-like creation might be fast ([after_commit](https://github.com/forem/forem/blob/main/app/models/comment.rb#L66) trigger a [perform_async](https://github.com/forem/forem/blob/main/app/models/comment.rb#L260) job) on production instances but slow on local environments.

<img width="1354" alt="Screen Shot 2022-08-30 at 09 42 12" src="https://user-images.githubusercontent.com/6045239/187484328-fc44b3be-91c4-4145-ac45-23327af8ce76.png">
<img width="1101" alt="Screen Shot 2022-08-30 at 09 56 14" src="https://user-images.githubusercontent.com/6045239/187484354-b3b4eb5a-c140-4cc2-9507-b291562b2107.png">


Lastly caching might have something to do with that `/reactions` endpoint, but not 100% sure on this either because my local tests were somewhat inconsistent. That may have been due to so much restarting+enabling/disabling cache of the local env, I may have made some mistakes in the manual testing process.

**Comment by mirie** [comment]
@jaw6 I see this is assigned to you, were we able to replicate this issue?

**Comment by jaw6** [comment]
Yes, I was able to replicate. I don't think the problem here is caching, per se, but background jobs & race conditions they bring in:

* Prior to https://github.com/forem/forem/pull/11283, we had special treatment for a newly created comment that would assume it had 1 like, by the current user.
* Now that this starts at zero, the first time a user interacts with a like (manually self-liking), because like-ing is toggle-ing, the initial like would be removed, thus the count is deprecated in JS, and we might see a [negative like](https://github.com/forem/forem/issues/18338).
* However, because we are creating the initial self-like in a background job, if we restore the UI assumptions (https://github.com/forem/forem/pull/18354 for example), there's still a race condition, where if the user interacts with the like before the background task finishes, if there is not _yet_ an initial like, we will often wind up creating **2 likes** for the user.
* @fdocr is [also correct](https://github.com/forem/forem/issues/18312#issuecomment-1231864379), we have a separate javascript that "polls" to update all comments for [reaction count updates](https://github.com/forem/forem/blob/main/app/assets/javascripts/initializers/initializeCommentsPage.js.erb#L17-L200). This then introduces a second race condition: if the poll polls before the background initial like finishes creating, it can reset the initial 1 like to 0. (It's not technically polling, it's triggered by the user, but the trigger is subtle and indirect and "feels like" background polling. There also seems to be a bit of a buggy inconsistency between the way the polling JS and the post-Ajax JS render 0 likes, but compared to everything else, this is very minor.)
* We do have a `public_reactions_count` on `comment` that _does_ cache the count -- however, this isn't used in the post-Ajax handler at all, only in the polling JS, so it's a factor in the various race-conditions, but I think this is more about the race between the various background behaviours more than the fact that we cache the count, per se.

I suspect we often see this more as a "local environment" issue because the timing of front-end and back-end background work in the dev environment is more tightly coupled (it's all happening on the same CPU) and not especially optimized.

From my perspective, it seems like the probable solution here would be to actually create the initial like in the same request where we create the comment. That would have us swimming a bit upstream (typically we want to move more things to background work), but given the way these overlap asynchronously, I think it's the only way to have the UI work consistently the way we want it to work. 

I'm currently working on that, but it's proving a bit thorny, mostly because of all the ways creating a comment can go wrong (rate-limit throttling, moderation authorization, etc.)

**Comment by jaw6** [comment]
Should be fixed by https://github.com/forem/forem/pull/18438
