### ISSUE TITLE
Error when Admin click on "Verify email address" of Invited users

### ISSUE THREAD

**Issue by devops-school** [forem/forem#18323]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="827" alt="image" src="https://user-images.githubusercontent.com/44023974/183899585-c197e61f-2dbf-4e2a-b9cd-aff2f71c97e3.png">

<img width="590" alt="image" src="https://user-images.githubusercontent.com/44023974/183899661-c65aaf79-ba39-4243-a7fd-95b4f23b5786.png">

**Desktop (please complete the following information):**

- OS, version: Desktop
- Browser, version: Windows

**Smartphone (please complete the following information):**

- Device: 
- OS, version: 
- Browser, version: 

**Additional context**

**Comment by Ridhwana** [comment]
Hi @devops-school, I tried replicating this issue but I am unable to. 

Can you please provide more information on this bug report? Since this is an admin page I'm assuming that you are an admin of a particular Forem? Can you also double check that you have SMTP settings setup so that the emails can be sent?

**Comment by mirie** [comment]
Closing for now because cannot replicate
