### ISSUE TITLE
There is no way to delete a series name

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#18351]
**Describe the bug**

Currently, if you create a series title, there's no way to remove it.

**To Reproduce**

1. Go to https://dev.to/new
2. Click on the gear icon beside "save draft"
3. Give your series a title and hit done
4. Save draft
5. Try to figure out how to delete the series title (I couldn't see how to do so from the editor nor the dashboard)

**Expected behavior**

There should be a clear way to delete a series title. 

Perhaps a series should have to be completely unpublished in order to remove the title from the list. Also thinking that maybe there should be a way to delete/rename/manage posts under a series from dashboard > series (i.e. https://dev.to/michaeltharrington/series for me)

**Additional context**

Here's a loom video of me trying to figure out how to remove an unused series name from my list:

https://www.loom.com/share/382b40e78e6f4ac9a341482710be3151

**Comment by Link2Twenty** [comment]
Even though the `stuff` series was missing from selection page it's still accessible with the url

https://dev.to/michaeltharrington/series/19380

**Comment by michael-tharrington** [comment]
Oooo interesting! Thanks for adding that angle @Link2Twenty!

**Comment by fdocr** [comment]
I feel like this would be fixed by ensuring empty series (a check for this triggered by saving a post) are actually being deleted instead of lingering around. Once a series is empty (without published/unpublished posts) users can always just type out the series name to recreate it, which is also triggered by post save action (as-is today).

**Comment by fdocr** [comment]
> Also thinking that maybe there should be a way to delete/rename/manage posts under a series from dashboard > series (i.e. https://dev.to/michaeltharrington/series for me)

We don't have edit/delete actions for series, and from a "bugfix approach" we don't quite need them [if the above is ensured/fixed](https://github.com/forem/forem/issues/18351#issuecomment-1244193793).

I'm thinking this because a user can always create a new series and migrate the posts to that new one with the updated name. That's a cumbersome flow though, specially when considering series with many posts (personally more than 5 posts becomes a hassle). This is feels like an edge case that wouldn't see much usage in real life though, so maybe we want to consider this a feature to work on or rather punt on it for now?

cc @amywtlin @anujbhavsar96 @mirie for your thoughts on this, because we would need some design mocks for this if that's the route we want to take
