### ISSUE TITLE
:bug:  "Commentable is not valid on" on a Post in Draft status

### ISSUE THREAD

**Issue by adriens** [forem/forem#18386]
# :footprints: Steps to reproduce

1. Create a post
2. Save it in draft status (ie. do not publish it)
3. Comment on it
4. Get the "Your comment could not be posted due to an error: Commentable is not valid. " message

![image](https://user-images.githubusercontent.com/5235127/187024402-6ff89dff-3b6d-4b7c-a5b9-33aaaa231f49.png)

# :pray: Expected behavior

Two options : 

:+1:  Ideally : be able to save the comment event on an unpublished post (which is quite useful in some cases for editor experience)
:-1:  Do not allow to comment... and then fix the bug

**Comment by adriens** [comment]
> Thanks for the issue, we will take it into consideration!

UR welcome :smile_cat: 

> Our team of engineers is busy working on many types of features, please give us time to get back to you.

:pray: :heart_eyes: :clap:

**Comment by ChaelCodes** [comment]
Hey! I'd like to pick this one up. After perusing the code, it looks like being unable to comment on draft articles is intentional. Only published articles are commentable. That said, the error message and UX here is pretty painful.

I plan to:
- improve the error message so it's clear why the comment is invalid
- disable the comment input when a comment wouldn't be valid
