### ISSUE TITLE
Remove "sponsors" code

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#18486]
## Context

- We have a lot of coded related to the explicit concept of “sponsors” and “sponsorships” built into the application
    - https://dev.to/sponsors
    - https://forem.dev/sponsors
- This functionality is not being used **on any Forem**
- This has been “soft deprecated” for long enough to move forward right away.
- This is entirely being replaced by the more flexible “Display Ads” concepts, and can be removed.

## Desired Outcome

- We pull out the code related to serving and supporting the “sponsorships” concept
- This will touch a lot of files, but will ultimately be a removal that simplifies the application. Most code removal will be fairly straightforward display logic here and there.
- There is no need to redirect any pages or maintain any compatibility, it has been long enough since this was last used.

## Additional Context

- This task will be similar in nature to the PR that removed Events (https://github.com/forem/forem/pull/15062)
- This is *only* related specifically to “Sponsors”, and does not include “Credits” or other related concepts. If you run into any complications, just ask.

**Comment by Ridhwana** [comment]
Just a note that I double checked that we don't have any live sponsorships running - https://dev.to/admin/blazer/queries/884-live-sponsorships

**Comment by benhalpern** [comment]
I have shipped the forem.dev "heads up" post for this project.

https://forem.dev/ben/the-hardcoded-concept-of-sponsorships-is-being-removed-36jn

**Comment by Ridhwana** [comment]
<img width="1511" alt="Screenshot 2022-09-30 at 10 16 10" src="https://user-images.githubusercontent.com/2786819/193224834-89bde2cf-7125-4008-8e55-34a838ce1dc1.png">

- Display Sponsors actually refers to showing Display Ads, not sure if it's worth considering changing the wording of this section?
- It seems like we don't use permit_adjacent_sponsors setting anywhere in the code. Are we planning on using it or should we consider removing it.

**Comment by benhalpern** [comment]
@Ridhwana we're looking to preserve credits where possible _in general_ to ensure we properly let people use and spend credits they have earned.

In the case of sponsorships, it's such an outdated notion, that anywhere we need to remove or modify credit data _specifically related to sponsors_, we can go ahead and do that.

We will manually make record of all credit data related to sponsors in case we need to issue a refund later, and can do that ahead of this merging.

Is that helpful in allowing you to make a decision around creating a workaround to remove the need for sponsors to exist in this logic?

**We are preserving credits for now _in general_** but sponsor-related data and logic is allowed to be carefully removed.

Anyway, really happy you're working on this, because this highly inter-tangled and co-dependent specialized relationship some of our objects have is really untenable. The future is much brighter with more flexible building blocks. 😄

**Comment by mirie** [comment]
Closing this issue -- didn't realize it was still open! (the work has been completed/is done)
