### ISSUE TITLE
Re-Implementing Reactions (Backend ONLY)

### ISSUE THREAD

**Issue by mirie** [forem/forem#18521]
## Problem Statement

BACKEND ONLY

We are prioritizing this work because it is part of building a more engaging and flexible experience. We have been stagnant on improving the interactivity of our most traffick’ed view, and this will provide admins with a ton of creativity and members with a lot of fun. We have biased towards action on getting this project started, so we want to finish it and have it be *the most fun feature we have ever shipped*.

This is **the backend portion** of re-implementing reactions (to replace the hard-coded Unicorn), which was announced [here](https://dev.to/devteam/our-dear-unicorn-friend-is-going-on-vacation-idm/). We will start with the backend portion, before building out the Frontend (which has some in-progress [Design Exploration](https://www.notion.so/forem/Exploration-Adding-playful-multi-reaction-picker-7d09111c76be4db5b61d888fe581c065)).

Once this change is fully live, a user will be able to “react” up to 7x on a single post:

- Like (not configurable - appears in reactions panel)
- Reading List (not configurable - appears in reactions panel)
- 5 Creator-set reactions (configurable with fallback defaults)

All existing APIs for reactions will be capable of accepting these dynamic reactions just like the hardcoded ones could have.

### Requirements
This feature will ultimately create a new model concept similar in nature to `NavigationLinks` or `Badges` (different from `BadgeAchievements`, which is the instance of a badge). Since we already define a `Reaction` by `category`, this new object should be named: `ReactionCategory`.

A `ReactionCategory` should have a data structure similar to navigation links and badges with possible contextual differences
    - SVG Image
    - Slug (i.e. `reading_list`)
    - Name (or title?) (i.e. `Reading List`)
    - Position
    - Published boolean
    - Color hex

- We will enforce exactly 6 custom reactions be published in addition to the hardcoded reactions still in place. This number should be a constant, but could change on account of future product decisions. Can be thought of as `N` because 6 is a magic number.
    - We will specify 6 new hardcoded default reactions — which will act as defaults when admins have not created custom Reaction Categories. 
    - If there are not 6 published custom reactions categories, these hardcoded default reactions will be displayed by a hardcoded position value. These are subject to change, but the placeholders will be: `unicorn`,`hands_up`, `fire`, `laughing`, `shocked`, with proper SVGs to be supplied
- Reaction Categories can all be **unpublished** (and a fallback default reaction will go into place if fewer than 6) 
- Reaction Categories can only be deleted if there are no reactions associated with it

Note: This will change the code from constants to needing to be dynamically generated in a number of places, but the application logic and APIs should all be able to be modified to be abstract vs hardcoded.

## Product Point Person
@benhalpern 

### Supporting documentation
- https://www.notion.so/forem/Re-Implementing-Reactions-Backend-5e4497391f8a4395bd6d725237557017
- [Draft PR](https://github.com/forem/forem/pull/18410) to remove hard coded unicorn reaction

**Comment by jaw6** [comment]
Questions:

* How should custom reactions impact score calculations?
* Moderator actions use the "reaction system" (eg, "vomit", "thumbsup", "thumbsdown") -- these aren't mentioned here, but I assume we want to leave these as is?

**Comment by benhalpern** [comment]
@jaw6 good questions, here are the answers:

- How should custom reactions impact score calculations?

Let's make this a custom float field called something like `score_calc`, and default it to `1.0`. The hardcoded ones can stay hardcoded as `1.0`.

- Moderator actions use the "reaction system" (eg, "vomit", "thumbsup", "thumbsdown") -- these aren't mentioned here, but I assume we want to leave these as is?

Yes, leave these as is as the other _hardcoded_ values.

***

We should have all the answers here as needed, but if anything else seems unaccounted for, please don't hesitate to ask!

**Comment by jaw6** [comment]
I started out as prescribed here -- creating a new database-backed model -- but almost immediately, there were a ton of decisions to make around persistence:

* How do we "link" a reaction to a `ReactionCategory`? All of the connectivity *now* runs on the raw string (`slug`). Conventionally, we'd add a `reaction_category_id` on the `reactions` table, but that's expensive (migration & update) to run on all of our historical reactions. 
* Would we *actually* want to join `reactions` to get `reaction_category`? At write time, we do some gating against a reaction that's *about to happen*, so in practice, most of our lookups are by `slug` anyway.
* Pre-fetching `reaction_categories` might be necessary when we get to the front-end parts of this -- which might be a strong argument in favor of a foreign-key?
* How would we handle a category being deleted or changed to non-public? Maybe we'd rather "soft delete", because we'd still have areas like score calculation where we might need to access the category data.
* Are fields like position or slug unique against other published categories or all categories? 
* Should "load bearing" categories be persisted (and un-editable?) or should we have a "hybrid" model, merging structures?
* What should happen if someone created a public-facing "vomit" category?
* When and how do we "back-fill" categories with defaults?

I'm sure there are more issues -- I think I've only begun to scratch the surface.

As I understand our goals, I think we want to encourage engagement, by letting users react in more/other ways with our content. Sorting all of those things out would ultimately delay us getting the "meat" of this feature (as I understand it) in front of our users. This issue is prioritizing getting the "backend" issues sorted out before tackling front-end, but if we can tolerate a period where "editable" means "edit a yml file" (certainly not an ideal format) I think we can get to the user-facing parts of this sooner than if we work out all the persistence kinks.

@benhalpern @pkfrank @mirie if I'm barking up the wrong tree, I'll close https://github.com/forem/forem/pull/18540 and open a PR against [the modeling branch](https://github.com/forem/forem/compare/main...jaw6/_reaction_category_modeling) -- but if I'm on the right track, should we update this issue or open an entirely different one?

**Comment by benhalpern** [comment]
> This issue is prioritizing getting the "backend" issues sorted out before tackling front-end, but if we can tolerate a period where "editable" means "edit a yml file" (certainly not an ideal format) I think we can get to the user-facing parts of this sooner than if we work out all the persistence kinks.

@jaw6 I really do like that idea. We're trying to _prioritize_ this, but not necessarily _rush_ it, because we don't want to be stuck with an unideal situation.

If you feel like this would be a useful first step to get to the new interface ready to go, I think we could accept that as an iteration while we methodically work through the data considerations.

_Ultimately_ I think we may ultimately will want the `reaction_category_id` to exist to make this useful and scalable — but caching _all_ the ReactionCategory data in Redis or something might also be fine because this will not be much data (5 published categories, maybe a few dozen unpublished depending on admin activity).

> How would we handle a category being deleted or changed to non-public? Maybe we'd rather "soft delete", because we'd still have areas like score calculation where we might need to access the category data.

I think we're on the same page, this is from the original spec trying to account for this:

> Reaction Categories can only be deleted if there are no reactions associated with it

I think simply not allowing a delete of any kind is more communicative than even soft delete.

> Are fields like position or slug unique against other published categories or all categories?

Slug is unique against all published _and_ unpublished. You can only have one `unicorn` category.

Position should be unique in that if I set something as `1`, whatever is currently occupying that position should be pushed to 2. I imagine there will likely need to be a "re-sorting" step to always have positions 1,2,3,4,5 available.

> Should "load bearing" categories be persisted (and un-editable?) or should we have a "hybrid" model, merging structures?

I'm not totally sure what you mean by this.

> What should happen if someone created a public-facing "vomit" category?

We should disallow the creation of any categories that would conflict with existing categories. The uniqueness validation can include the hardcoded ones.

All in all I think you are aligned with how we'd been thinking through this, and the iterations make sense. So we should keep checking in on any nuance, but I think your steps so far are spot on.

**Comment by jaw6** [comment]
> > Should "load bearing" categories be persisted (and un-editable?) or should we have a "hybrid" model, merging structures?
> 
> I'm not totally sure what you mean by this.

So, yeah, let me unpack a bit. Last week, I wasn't sure if we would want the **uneditable** reaction categories -- the ones that have significance, like "thumbsup" or "vomit" -- to even persist in the database alongside the user-editable categories. I was imagining it might be possible (awful, messy, but *possible*) to have some of the significant categories live entirely in code, and have to deal with both kinds of category internally. I really didn't want to do that, and I don't really think there's any _good_ reason to, but there were some types of problems I was concerned about that we could avoid if we took that route.

Maybe I forget, maybe I'm rested up post-vacation and thinking about it differently, but this week I really can't see a reason we'd do that.

**Comment by anujbhavsar96** [comment]
I discussed the same with @benhalpern, and we decided to implement this iteratively. Here is how we are thinking about it,

**V1:** 4-5 hardcoded reactions and can't be changed by admins.
**V2:** Provide a few sets of reactions and enable them based on preference
**V3:** Configure any reaction - Upload icons and name them etc. The whole system of configuring reaction _(Kind of similar to navigation links)_

I'm meeting Ben today to discuss this further, but in the meantime, if you need a rough concept/mock to understand this, let me know. Then, I can have a basic sketch for **V2** and **V3**.

**Comment by benhalpern** [comment]
@jaw6 just to follow up on the @anujbhavsar96 point, this should be very much in line with our direction of starting with the `yml` file and progressing from there. Let me know if this is confusing at all. I think this is working on concert with the backend choices.

One new decision in the design process that _will_ need a backend choice: We will need each reaction to have a _color hex_. This is functionally equivalent to how we ask admins to define a color hex for tags. I am adding this to the above guideline now.

We are still finalizing the choices of which our default reactions will be, and _how many_ we will ultimately want to display once the design is complete. I imagine these are not material changes in the backend decision process, but let me know otherwise.

**Comment by mirie** [comment]
@jaw6 You have this open PR https://github.com/forem/forem/pull/18540 -- it looks like you've been getting feedback which is great. Who would be good to get another review from?

**Comment by mirie** [comment]
@jaw6 , checking on this one -- can you share next steps? I see that you have approvals for your open PR.@benhalpern took a look as well and doesn't have any additional feedback to add.

**Comment by jaw6** [comment]
@mirie The PR is currently blocked by a CI status check, but I'm not sure why -- I'll check in Slack and see if there's a good way to nudge that forward, I believe it's otherwise ready to merge.
