### ISSUE TITLE
Add Post Sidebar placement option for display ads

### ISSUE THREAD

**Issue by mirie** [forem/forem#18638]
## User Story (Who / What / Why)

As an admin, I want to be able to add a Display Ad unit to the post sidebar in order to be able to more effectively target messaging to readers.

## Definition of Done

- [ ] New placement area added to dropdown in `/admin/customization/display_ads/new`
- [ ] Placement area should be titled: “Post sidebar”
- [ ] Placement area should be under existing content in the right sidebar
- [ ] Display unit should be “sticky” when the user scrolls (see below)
- [ ] Creation, Rendering, Tracking, Targeting, etc. should be consistent with other display ad units
- [ ] Sidebar unit should not be visible or take up space on single-column screen width (i.e. `display: none`), and not trigger an impression in this scenario.
## Additional Context

GIF showing the interaction.

![Image](https://user-images.githubusercontent.com/9434801/197679004-d651df4c-deed-4cb2-82e1-a71e02a37c1d.gif)

Display Ad Event tracking example (rendering under comments):
- https://github.com/forem/forem/blob/98077a8df64d2fea1da17077d3fd4bd92fe44a0c/app/views/articles/show.html.erb#L197
- Recent work to improve our display add tracking: https://github.com/forem/forem/pull/18460

**Comment by Ridhwana** [comment]
Questions that I have: 

1. Is this a completely new post placement option on the post page? Hence will we still be keeping "post_comments" that appear under the comments as well?
2. Should we account for the [displaying targeted tags for this placement option](https://github.com/forem/forem/issues/18519) as well?


An aside question that does not necessarily relate to this issue but rather Display Ads as a whole, should placement area be a multi-select option in the future instead of only being able to select a single placement area for the ad. I can see folks in the future might want the ad to appear on both the post page and the home page. I'm curious to hear what thoughts there are on this?

**Comment by pkfrank** [comment]
Hi @Ridhwana 

> Is this a completely new post placement option on the post page? Hence will we still be keeping "post_comments" that appear under the comments as well?

Yes, this is a new post placement.  We'll keep the current "under the comments" location as well.

> Should we account for the https://github.com/forem/forem/issues/18519 as well?

Yes, definitely.  Thanks for mentioning that consideration.

> should placement area be a multi-select option in the future instead of only being able to select a single placement area for the ad.

This is a great question.

We've talked about this and want keep it brutally simple for now, but we will likely want to revisit a few considerations like this in the future as we collectively deepen our understanding and alignment on how we'll be using Display Ads going forward.

**Comment by rt4914** [comment]
👍

**Comment by benhalpern** [comment]
@jaw6 It wasn't totally clear whether [this PR](https://github.com/forem/forem/pull/18686) is ready, so ignore me if you were already on your way here, but I see it isn't yet accounting for `Display unit should be “sticky” when the user scrolls (see below)`. Let me know if you have any confusion about what the ask there is. "Sticky" here refers to the `position:sticky` behavior here moving away from the current elements and instead is applied to this new elements, so it behaves like the gif.

**Comment by jaw6** [comment]
@benhalpern Thanks for clarifying, I had misunderstood the `sticky` requirement as applying to the whole sidebar.

What's the intent for how this should work with `permit_adjacent_sponsors` ?

**Comment by jaw6** [comment]
Ah, nevermind - `:last-child` to the rescue (though, I note there's a minor inconsistency with top padding/position, I'm not sure it's a showstopper?)

![Screen Recording 2022-11-10 at 09 22 27](https://user-images.githubusercontent.com/2077/201039210-6fb17c00-4354-4b38-8b09-81f3f180f4ea.gif)

![Screen Recording 2022-11-10 at 09 27 03](https://user-images.githubusercontent.com/2077/201039763-fa821667-f998-4143-9e8b-2a6e27d7e2a6.gif)

**Comment by jaw6** [comment]
@benhalpern @pkfrank 

I want to add though, even just browsing around in lorem-ipsum land, this feels **bad** to me, as a reader. The requested sticky ad behavior is just, like, visually very unpredictable, it makes the whole sidebar feel weird when browsing. Maybe the ad I made for Dev is _particularly_ uninspiring, but pages with an ad feel really bland -- especially pages that would have otherwise shown related articles (a series, say) in the sidebar.

I think it's not a great choice to have "new ad placement" impact the *whole* page design in this way. Also -- I don't know if self-reported eye-tracking has any value -- but it feels like the sidebar ad generates _less_ attention this way.

Speaking of this inconsistency, I'll also note that this whole sidebar behaves **very** differently on mobile -- that is to say: `post-sidebar` ads work more like `post-comments` ads when one is on mobile. 

![IMG_0159](https://user-images.githubusercontent.com/2077/201042939-851500d0-e939-4968-a9f0-00aab66fc070.png)
![IMG_0160](https://user-images.githubusercontent.com/2077/201042975-66ab28dc-c7b4-44bb-9121-87eb85ffab33.png)

(There is no ad here, screenshots are from DEV, I haven't poked enough holes to connect my mobile to my local dev environment yet, this is a visual reminder that any ad would appear below the author profile.)

Currently, display ad impression tracking won't track an ad that isn't visible on screen, so the statistical noise should be minimal-ish, but the way we select and serve ads makes no distinction for the user's device or screensize or mode, our targeting has all been focused on our end of the telescope, so far. The net effect here is that a `post-sidebar` ad is kind of _de facto_ invisible on mobile.

**Comment by Ridhwana** [comment]
> I think it's not a great choice to have "new ad placement" impact the whole page design in this way. Also -- I don't know if self-reported eye-tracking has any value -- but it feels like the sidebar ad generates less attention this way.

My 2c here as I've been following along 😅 Looking at the video above I agree and have similar thoughts about the sticky behaviour. It feels very jarring to stop the sidebar at the ad like that, and I'm wondering if there are other ways we can draw attention to the ad without impacting the whole page design.

**Comment by benhalpern** [comment]
Let's definitely have this conversation as an opportunity to rethink any part of this approach at this stage. It's definitely good to bring up these concerns.

As an important part of the conversation, I think it's necessary to note that the same, or similar behavior, is quite common — even standard — across platforms with a similar structure to ours.

https://user-images.githubusercontent.com/3102842/201112701-1fcadaad-f4c6-4391-b21b-0d1b47533821.mov

https://user-images.githubusercontent.com/3102842/201112740-a129e838-6a34-4465-b392-7e14dc2dd25d.mov

https://user-images.githubusercontent.com/3102842/201113345-9883fbc7-f8e2-4c00-8496-678d0555ac15.mov

I do think with launching this, we need to be abundantly prepared with _relevant_ use of this space — ensuring the content is value-add when we do. I _wonder_ if any amount of the jarring feeling is how different it is, and how generally that is unappealing in and of itself a lot of the time. How we manage the rollout will be important, given that.

We'll consider every factor that can make this successful given this uneasiness, but I'm curious if these comparisons and context help us think through the issue?

(Let's talk about the mobile stuff after we resolve this first concern)

**Comment by jaw6** [comment]
> I'm curious if these comparisons and context help us think through the issue?

My immediate, top-of-mind observation is that the third example seems the closest to our content model (an article vs a stream) and is pretty much "whole sidebar sticky".

**Comment by benhalpern** [comment]
@jaw6 — you're right. It's _sort of_ a hybrid.

That might be a better approach. I'll touch base with @pkfrank and @anujbhavsar96 and we'll re-examine the possibilities here.

We need to solve the current issue where _fully sticky_ doesn't allow for variation in window size and content in a way that's already problematic for existing content, but is basically a non-starter for adding new content to the sidebar.

The current proposal is _precisely_ the same pattern as the LinkedIn example, but we very well could be better off with the Medium model. Thank you for the feedback, we will turn around and consider our options.

**Comment by anujbhavsar96** [comment]
I feel LinkedIn wants to emphasize more on an ad after scrolling; that's why it's just a sticky ad. On the other hand, the Medium/Twitter wants to emphasize all content on the sidebar, which makes them have different scrolling behavior. 

Though I feel Medium/Twitter scrolling behavior is more expected where you keep the bottom content sticky at the bottom and scroll only till the bottom content is visible entirely. 

But since it's a bottom position, it's easy to miss if Medium/Twitter behavior is used. 

Why not change the placement of the Ad to the below profile card? The only cons I see there are it feels like a personal space to the user, and it might feel like we are forcing them to ads. But the same thing we are doing for the home page's right sidebar, we have the option to display ads at the top.

If we implement ads below the user profile card, we must be careful about what kind of display ads we promote, so it doesn't look like spam.

--

About mobile

I think we can't do anything. Usually, sidebars are secondary information; that's why they go at the bottom in responsive designs.

**Comment by mirie** [comment]
I have changed the status to `Next` as we are working through the requirements and is no longer work that is ready for PR review / deploy.

**Comment by benhalpern** [comment]
Okay, follow up here. @jaw6 @anujbhavsar96 @mirie 

After discussing this with @pkfrank and evaluating the different tradeoffs, we are going to proceed with the original design. In order to ensure we don't roll out a jarring experience, we are going to limit the use of this functionality to a small experimental subset of targeting on tags which are limited our own use, and then expand only for non-signed in users, and ultimately expand further only when we have developed appropriate visual guidelines for our use of this functionality.

With that said, we do still feel like the original behavior is the most straightforward and provides some flexibility at the margins for further iteration.

**With regards to mobile:**

I am going to update the original issue to request that the ad be _hidden_ via styling on mobile and not trigger an impression when in that state. Given that we have _the other_ location above it in the mobile context, this placement makes less sense in that context. We could re-evaluate this decision later, but for now this is the appropriate way to not add an extra unit here where it's not needed.
