### ISSUE TITLE
Add API Endpoints for Display Ads

### ISSUE THREAD

**Issue by mirie** [forem/forem#18642]
## User Story (Who / What / Why)

As an admin, I'd like the ability to CRUD (Create, Read, Update, Delete) display ads via API, to help me create and manage my display ads by leveraging external tools.

## Definition of Done

**Create / Update / Delete**
- [ ] Admin is able to create, update, and delete the following Display Ads fields 
    - [ ] approved | boolean
    - [ ] body_markdown | text
    - [ ] display_to | integer
    - [ ] name | character varying
    - [ ] organization_id | bigint
    - [ ] placement_area | character varying
    - [ ] published | boolean
    - [ ] targeted_tags (as soon as it is stable and in production, not a blocker) 
    - [ ] type (as soon as it is stable and in production, not a blocker) 

**Read**
- [ ] Admin is able to read all relevant fields:
    - [ ] approved | boolean
    - [ ] body_markdown | text
    - [ ] clicks_count | integer
    - [ ] created_at | timestamp without time zone
    - [ ] display_to | integer
    - [ ] id | bigint
    - [ ] impressions_count | integer
    - [ ] name | character varying
    - [ ] organization_id | bigint
    - [ ] placement_area | character varying
    - [ ] processed_html | text
    - [ ] published | boolean
    - [ ] success_rate | double precision
    - [ ] targeted_tags (as soon as it is stable and in production, not a blocker) 
    - [ ] type (as soon as it is stable and in production, not a blocker) 

* Note: `Admin` access should be the same level as what we set up for Forem Shield and the Reactions API.

API Documentation:
- [ ] V1 API documentation is updated accordingly _(No need to worry about V0 docs)_
 
_* Just as an FYI (nothing actionable for this issue): We might rename Display Ads to something else in the future -- this means we might need to alias the name for this resource in the future_

## Additional Context

Some fields (such as "success rate") should only be available via the Read endpoint, as those are tabulated based on actions, and should not be editable by an admin.

If `targeted_tags` and/or `type` are not ready to be folded into this issue during time of implementation, please create a followup (and linked) separate issue for completing this work.

To answer the question of how the API will be used, see https://forem.team/ben/where-is-the-display-ad-project-going-2lle. Other examples are spoken about in the refinement meeting recording, some examples to pull out: 
- Unpublish a display ad after a certain # of days or certain # of impressions _(just examples)_

**Comment by Ridhwana** [comment]
Should we account for the [targeted tags](https://github.com/forem/forem/issues/18519) in this issue? We've already got some of the backend hooked in, I just need to optimize.

**Comment by Ridhwana** [comment]
I also noticed that adding "processed html" is not an option on the UI, do we want to allow that at the moment through the API?

**Comment by benhalpern** [comment]
Great call on both points @Ridhwana.

Yes... `processed_html` is a _derived field_ and should be excluded from the `write` actions. And targeted tags should be included.

Since we want all of our APIs to be open to extension, but closed for modification, it's _okay_ to ship without targeted tags and add that as soon as available — but as it's coming down the pike it should definitely be included.

I'm going to change the original issue comment to reflect this convo.

**Comment by jaw6** [comment]
:link: This also needs to coordinate with [#18640 - Add 'type' to DisplayAd](https://github.com/forem/forem/issues/18640).

**Comment by rt4914** [comment]
👍

**Comment by jaw6** [comment]
> to help me create and manage my display ads by leveraging external tools.

I'm having trouble understanding how this API would be used. What sort of external tools would be used to create/manage DisplayAds?

**Comment by mirie** [comment]
Surfacing from estimation exercise: We should include API documentation as part of the work / definition of done.

**Comment by benhalpern** [comment]
@Ridhwana @jaw6 I'm working on integrating with these write endpoints. Looks like this endpoint allows `:tags` as an attribute for _writing_, and am not totally sure on things.

```
      def permitted_params
        params.permit :approved, :body_markdown, :display_to, :name,
                      :organization_id, :placement_area, :published, :tags
      end
```

When I send tags _as a string_, I get a `500` error. But when I send it as an array, I get nothing updated.

There could definitely be some confusion around how this was initially implemented because acts-as-taggable-on has so much read/write magic with `tags`, `tag_list`, `cached_tag_list`, etc.

Any help getting me unstuck is helpful!
