### ISSUE TITLE
[Feature Request] autogenerated table of contents

### ISSUE THREAD

**Issue by sw-yx** [forem/forem#1868]
**Is your feature request related to a problem? Please describe.**

Markdown header tags now have anchor tags, so we can generate tables of contents for the articles. 

this encourages more browsable longer form content on dev.to.

optionally, we can make the TOC float in a sidebar.

**Describe the solution you'd like**

possibly use a TOC generator like https://ecotrust-canada.github.io/markdown-toc/

**Describe alternatives you've considered**

not doing anything

**Additional context**

i last filed this request here https://github.com/thepracticaldev/dev.to/issues/183 at my old job's github account. a prerequesite was adding id's on every header, which was done in Nov. its time to revisit this idea!

**Comment by Link2Twenty** [comment]
Headers are anchors. It's the header text lowercase with spaces replaced with dashes.
https://dev.to/swyx/supervised-learning-support-vector-machines-3mgk#svms-and-boosting

Though, having an auto-generated TOC might be something to look at, thoughts @benhalpern ?

**Comment by sw-yx** [comment]
i actually meant to change that text, i'm going to edit my text now to make it less confusing

**Comment by sw-yx** [comment]
uh oh :(

**Comment by robertcoopercode** [comment]
One idea is to make the table of contents added by using a liquid tag such as `{% tableOfContents %}` so that the articles that want a table of contents can have one. I wrote a fairly long article (https://dev.to/robertcoopercode/docker-guide-118i) in which is would have been nice to have a table of contents to let users get a good overview of the article and be able to jump around more easily.
