### ISSUE TITLE
Publication Date Doesn't Update After Draft

### ISSUE THREAD

**Issue by stevewhitmore** [forem/forem#18725]
There's an issue where if you start writing a post and save it to draft the publication date is captured as that date. 

For example; if you start writing an article but don't publish and just save the draft on 4/6/2021, then finally get around to publishing on 11/11/2022, the publication date will show as 4/6/2021. 

This was the case for me with my post https://dev.to/stevewhitmore/python-powered-pipelines-preposterous-4316. I reached out to your team via Twitter and they updated the date for me: https://twitter.com/ThePracticalDev/status/1591086282570338308?s=20&t=JvkdjZq1o9W9IAovNrHQgQ

**Comment by erinb223** [comment]
I revised the date via post > admin a few minutes before the timestamp on the tweet in case that helps with problem solving here. Reach out to me if you need more details. Thanks, team!

**Comment by lightalloy** [comment]
Hey, @stevewhitmore , thanks for sharing. Is it possible that you had published your post at some point in the past (e.g. on creating), and then unpublished it?
I have checked for this issue for a new post (creating a draft), and it doesn't save the publication date if not set explicitly. Similar situation is possible if a user creates a drafts and set a future publication date (to schedule a post), then returns to the post later, but the publication date is already in the past and is non-editable. We don't allow editing publication dates if they are in the past because that would allow users to bump a publication date of an old post by unpublishing and republishing. But this shouldn't apply to your situation because we didn't have the scheduling feature back then.
