### ISSUE TITLE
Adjust space between the author + org logo and post title in embeds

### ISSUE THREAD

**Issue by mirie** [forem/forem#18734]
**Describe the bug**

When embedding a link to another Post and the author of the post is publishing under the umbrella of an organization, the icon for the author is too close to the Post title. 

https://www.loom.com/share/c87616bc11c84cfcbc328523a8b39b67

It is a little more obvious with the dark theme because there is a black box surround the organization logo.

<img width="747" alt="Screen Shot 2022-11-15 at 4 38 50 PM" src="https://user-images.githubusercontent.com/896728/202032479-fa015cb0-0fde-4aa8-a810-82d884fb1774.png">

You can see the difference when comparing an author and author + organization logo:
<img width="752" alt="Screen Shot 2022-11-15 at 4 51 09 PM" src="https://user-images.githubusercontent.com/896728/202032859-2cf38aa2-755a-4735-a2f5-fddfa2877f92.png">

Example page: https://dev.to/devteam/the-7-most-popular-dev-posts-from-the-past-week-59ba

**To Reproduce**

1. Create a Post and embed posts from an author posting for an organization
2. Save post and view the display of image to the left of the post title in the embed

**Expected behavior**
We want the same spacing between author and Post title (even if there's an org logo underneath the author profile pic).

**Comment by benhalpern** [comment]
Thanks for writing this up @mirie!

@rt4914 — let's note that we _can't_ change HTML in embeds without complicated re-saving mechanisms (Fixing this problem is a bigger project in the near future). So these fixes have to be done purely in CSS....

And with that being said, I think we could make a bunch of small fixes across other embeds we currently have live in an initial step to make things more consistent and uniform _as a stopgap ahead of a bigger overall refactor_. So as you take this on, please keep in mind that we may add a task in the near future to make some of these pure CSS improvements, and then ultimately follow up with a more complicated ultimate solution. So even though this is a small item, please feel free to reach out and discuss anything, because this could be a chance to kick off a bunch of super useful small fixes as we prepare for some bigger longterm improvements.

All that is to say... Let's not over-complicate this issue by adding to it, but when you're in this part of the code, take stock of it because this could be the first domino of a lot of improvements here. 😄

**Comment by rt4914** [comment]
@benhalpern Thanks for the heads-up. Will first try to fix the issue and then improve on the solution.

**Comment by mrpaulishaili** [comment]
The reason this may be happening can be possible that the image is not relative to it's size of the container, which of course can be a deal in figuring and refactoring through other possible areas that may be impacted by the fix.
