### ISSUE TITLE
Last line in edit mode not visible after switching from preview mode

### ISSUE THREAD

**Issue by TanishqSingla** [forem/forem#18833]
**Describe the bug**
When switching from preview mode to edit mode, the last line is not visible when scrolled to bottom. 

**To Reproduce**

1. Go to create post.
2. Add dummy text to body, and make sure no empty line is left behind.
3. Switch to preview mode, scroll down to check what was the last line.
4. Switch to edit mode, scroll down to last line.

**Expected behavior**
When switching back to edit mode and scrolling to end, the last line should be visible.

**Screenshots**
**Preview mode**
![image](https://user-images.githubusercontent.com/26207583/206900803-342226c8-1535-4ba8-b19c-e95e980f366b.png)
**Edit Mode**
![image](https://user-images.githubusercontent.com/26207583/206900822-1516d940-932e-4073-81e6-e909ebeb0418.png)

**Desktop (please complete the following information):**

- OS - version: Windows 10 21H2, x64-based processor
- Browser, version: Brave, Version 1.46.140 Chromium (Official Build)(64-bit) and Firefox 107.0.1 (64-bit)

**Smartphone (please complete the following information):**

- Device:
- OS, version:
- Browser, version:

**Additional context**
Notice the last line in edit mode and preview mode in screenshots, the scroll is fully at bottom in both.

**Comment by michael-tharrington** [comment]
Thanks so much for reporting this one!

I can confirm that I hit this one pretty regularly, so much so that it's become normal to me and I've forgotten about it. But, just this past week someone else pointed it out to me separately from this issue. While it's not a hugely disruptive bug in that you can relatively easily click in and scroll to the true bottom of the post, I do think it is affecting a lot of folks and is confusing for folks who are uninitiated with our editor.

**Comment by ktmouk** [comment]
I looked into the issue, and I probably identified the reason.

The [useTextAreaAutoResize](https://github.com/forem/forem/blob/75d6e60a957b4296dd9eddbf8f0628781dc5cd56/app/javascript/utilities/textAreaUtils.js#L269) hook calculates the editor height using [a hidden text area](https://github.com/forem/forem/blob/6f057fc8ceb154a4bde53fa0a72ef931d9b523e6/app/javascript/utilities/calculateTextAreaHeight.js#L44-L45) and applies it to the `max-height` of the editor element. However, this calculation probably doesn't consider the width of a scroll bar, so the hook cannot calculate the height accurately.

If the OS is macOS and the user is not using a mouse, this issue will not occur because the scroll bar will not be visible.

So I think one of the simplest solutions is to change the `overflow-y` value from `auto` to `scroll` to show a scroll bar always.
https://github.com/forem/forem/blob/caec27c3001e46fed87633db889abf6cb2f083f2/app/assets/stylesheets/views/article-form.scss#L75

**Comment by receter** [comment]
I just stumbled upon this issue when trying to edit an older article. For me it was a quite frustrating experience because I first thought that it might be an older version from local storage an I didn’t want to loose anything. So I deleted localStorage keys, switched browser etc. After some time I found that I can scroll down further using the down key.

For me this happens when I click edit and it is not just the last line but the last 7 lines, I guess @ktmouk is right and it is because of the scrollbars.

There is a library that does this very well, as far as I remember this one is also used by Wordpress under the hood:
https://github.com/jackmoore/autosize
