### ISSUE TITLE
Adjust optimization Billboard logic

### ISSUE THREAD

**Issue by mirie** [forem/forem#18870]
## User Story (Who / What / Why)

*Note: This is a request for specific small adjustments to underlying mechanics in a specific way to aid current behavior.*

As an admin, I’d like the Billboard optimization strategy to allow for a bit more experimentation (vs. optimizing for the most successful ads), in order to ensure that new entrants get more attempts at establishing themselves.

As an admin, I may be inhibited by  the fixed “limit 15” with the current logic, I’d like to see that number scale relative to the total number of Billboards created.

## Definition of Done

- [ ]  Adjust logic so that new units show up slightly more often than normal until they reach 100 impressions, or similar logic
- [ ]  Adjust the current optimization hardcoded “limit” of 15 to instead be *approximately* half of qualifying billboards

## Additional Context

Below are some proposed options for accomplishing this which are acceptable for product team, but alternative solutions are welcome here.

### Technical considerations

A proposed option is to calculate `success_rate` a minimum `0.1` if impression count is less than 100.

We also want to adjust the hardcoded 15 to be a count of *half* of the number of qualifying billboards. This can be an *approximate* count, which is a speedier check vs a strict number.

*Something like this*

`relation.limit(rand(1..relations.estimated_count)).sample`

Both of these asks should slot within the existing mechanics without structural changes — though maybe this is a good chance to break out the logic to more isolated areas. 🙂

**Comment by jaw6** [comment]
I believe this is referring to this [`DisplayAd.for_display` method](https://github.com/forem/forem/blob/38d95857c59a2a9227a1a7921012cc14e1522440/app/models/display_ad.rb#L59-L64), which selects a pool of ads sorted by `success_rate`, then (after possibly further winnowing the list by tags or user targets) selects one at full random one-in-eight times, or one of the top 15 the other 7/8 times. 

For what it's worth, I am _slightly_ nervous about the idea of adjusting `success_rate` artificially for low-impression ads, but I wouldn't have any problem with scoping that to this specific query, if that's possible. (Maybe we have two queries, one that sorted by `success_rate` and another that's scoped to sub 100 impressions and sorted by new, then mix before sampling?) That said, I am _more_ nervous that this query becomes more complex (harder and harder to index for, let alone understand/`explain` a query plan) at the same time we are also relaxing our approach to caching `DisplayAds`, without a lot of tracking how these changes, in aggregate, are impacting page performance.

**Comment by benhalpern** [comment]
Adjusted the original ask based on convo. As noted, additional changes here could have a performance impact we will want to establish some baselines for and pay attention to impact.

**Comment by mirie** [comment]
@benhalpern 

In today's refinement discussion, Engineering advocated for a separate field to hold this information, versus changing the meaning of `success_rate` and keeping the same label.

Some options brainstormed in the meeting for the name of this new field: `rank`, `trending`. What are your thoughts on this?

**Comment by benhalpern** [comment]
Yup, I'm all for having a separate field, and adjusting the logic here however needed. 👍 

Any number with any appropriately communicative name works here, and we don't need to ever expose this value to any UI per se — it's just internal logic.

So I'm good with all of this.

***

One additional thought about all of this since it was first brought up: I'd been thinking that we might actually want to dictate this type of "new billboards should get a boost" logic entirely from outside the core low level logic — meaning we make the "new billboard adjustment" entirely "manual" — but by manual it means delegating to the API user.

So that would mean exposing something like a `ranking_adjustment` number and have the final `rank` number be a summation `success_rate` and `ranking_adjustment` — so by default it is _only_ success rate, but the optional `ranking_adjustment` allows the controller application to adjust as is needed for business logic purposes — so we entirely allow the third party controller the option to mess with rankings as needed, and we reduce the amount of "rules" that need to live in the core application.

That thinking could apply to both bullet points of this task, but I feel like the `Adjust the current optimization hardcoded “limit” of 15 to instead be approximately half of qualifying billboards` one strikes me as a little weird to force third party logic on to.

All that is to say — I think the above idea about creating a different internal attribute for storing ranking logic is totally the right approach and seems great — but given some time to think about this, I think just delegating this "adjustment" to the API is the cleanest way to ensure we get the ongoing flexibility we might want/need here.

@pkfrank I think this speaks to the direction of keeping our billboard logic low level and embracing the opportunity to provide an API for more intricate business logic wherever possible. I think that was always a direction we were going, but I think it's clarifying that we really seek to use that pattern everywhere we can.
