### ISSUE TITLE
Discrepancy between the reaction calculation on post preview versus post sidebar

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#19086]
**Describe the bug**

The reaction calculation that is visible within a post is different from what is visible on a post's preview card in the feed.

**To Reproduce**

1. Go to 'https://dev.to/top/infinity`
2. Look at the reaction count for the top post on the post's preview card
3. Click on the post
3. Read the reaction count in the sidebar of the post
4. See the discrepancy

**Expected behavior**

The number of reactions on the post preview should be the same as the number of reactions visible in the sidebar of the post.

We should probably not roll the # of post saves/bookmarks into the reaction count. Perhaps we could visualize saves/bookmarks separately.

But also, even if you add the bookmarks and reactions together, there is still a discrepancy between that number and what's on the preview page.

**Screenshots**

<img width="547" alt="Screen Shot 2023-02-08 at 3 20 33 PM" src="https://user-images.githubusercontent.com/16007075/217645693-c55981b8-78bf-4771-ac62-574586ef2866.png">

<img width="742" alt="Screen Shot 2023-02-08 at 3 31 07 PM" src="https://user-images.githubusercontent.com/16007075/217645751-274f1f0c-bb84-489c-a018-10d65c1c3486.png">

**Additional context**

Shout out to @Afif13 for reporting this discovery to us [here](https://dev.to/afif/comment/24k9f).

**Comment by pkfrank** [comment]
This discrepancy is caused by the (temporary) [removal of the Unicorn reaction](https://dev.to/devteam/our-dear-unicorn-friend-is-going-on-vacation-idm), as the Reactions Count on the index view still takes those reactions into account.  Once the Unicorn is re-introduced, everything will line up.

One additional note: the "bookmarks" also factor into the total.

**Comment by michael-tharrington** [comment]
Gotcha! Thanks a bunch.

**Comment by Afif13** [comment]
> But also, even if you add the bookmarks and reactions together, there is still a discrepancy between that number and what's on the preview page.

I think this is because we removed the licorne reaction. I remember The team said that the total will remain unchanged even if the reaction is removed.

Also I think we should keep the sum of likes and favorites. At least this was the default behavior but for some posts it's not the case.

Mine just dropped from around 5000 to only 2061 https://dev.to/afif/i-made-100-css-loaders-for-your-next-project-4eje .. I was the second in the CSS top but not anymore: https://dev.to/t/css/top/infinity

**Comment by Afif13** [comment]
> This discrepancy is caused by the (temporary) [removal of the Unicorn reaction](https://dev.to/devteam/our-dear-unicorn-friend-is-going-on-vacation-idm), as the Reactions Count on the index view still takes those reactions into account. Once the Unicorn is re-introduced, everything will line up.
> 
> One additional note: the "bookmarks" also factor into the total.

I probably wasn't clear on my exchange with @michael-tharrington but the issue is that some posts aren't counting the "bookmark" in their total. Some posts are only showing the "heart" count.

**Comment by pkfrank** [comment]
@Afif13 moving this over here: https://github.com/forem/forem/issues/19088

Thanks for raising this!

**Comment by jmau111** [comment]
> One additional note: the "bookmarks" also factor into the total.

hello @pkfrank, just post a comment https://github.com/forem/forem/issues/19088#issuecomment-1429890862. I think it's debatable.
