### ISSUE TITLE
[honeybadger] TypeError: undefined is not an object (evaluating 'window.Forem.Runtime')

### ISSUE THREAD

**Issue by maestromac** [forem/forem#19248]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/67192/faults/89477500)

**Comment by maestromac** [comment]
So i'm finding out that this is an exception alert from a code that no longer exist :unamused: 

I'm quite confused by how this is possible. It _has_ to be caching, and must be browser cache, but what part of our codebase is making this happen?

**Comment by mirie** [comment]
@filleduchaos can you add the notes from Slack? My understanding from our 1:1 conversation is that this is a won't fix unless there's specific articles to bust cache...but how long are things cached for?

**Comment by filleduchaos** [comment]
Sure! My conclusion @maestromac :

- We've already fixed the actual error in #19007 , so there isn't much else we can do product-engineering-wise.
- These errors are coming from visitors who are somehow still on versions of the frontend from before that PR/deployment. To reduce noise, we could simply throttle or outright surpress all errors coming from a Honeybadger client that isn't the current version we depend on
- Nice-to-have: if Fastly provides request logs that we can review, it should be possible to check those logs to see if we actually are still serving outdated versions of the frontend (from the `base.{contenthash}.js` request logs), in which case we might have a cache of articles we need to bust. If not the "traffic" is likely external (offline readers, proxies with their own caches?) and not something we can do anything about

But the main thing is that this is safe to ignore! 🙂 I'll send this back to Platform because of the Fastly thing, but feel free to close

**Comment by maestromac** [comment]
This has gone stale and we are now dealing with a different issue.
