### ISSUE TITLE
Fix small styling bug on GitHub liquid tag in Billboard context

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19359]
Fix small styling bug on GitHub liquid tag in Billboard context

## Describe the bug

The GitHub repo liquid tag has a styling bug in the context of Billboards / Display Ads.

## To Reproduce

1. Set up a new `display_ad` (Billboard) that uses this GitHub repo liquid tag
    1. `{% embed https://github.com/forem/forem %}`
2. Observe the “CI” badge is not properly styled

## Expected behavior

The liquid tag should render the same way in the Billboard context as it does in the post context.

## Screenshots

Note the far left “badge” in the liquid tag.  Billboard context on top, post context below.

![two examples top and bottom](https://p-DgFRWr8y.t2.n0.cdn.getcloudapp.com/items/L1uD8blg/4f3fba11-b335-48ac-ab85-626293351bb9.jpg?v=ce1a2b462c7e585c632c28e8bb5bcff1)

## Additional context

While this isn’t a guaranteed solution, you can go to a DEV article, scroll to the bottom (below comments), and refresh a few times.  You may get lucky in that this live example will show up for you.

**Comment by mirie** [comment]
@jaw6 assigning this one to you as I'm hopeful this is a small one / can be addressed prior to your OOO

**Comment by jaw6** [comment]
So, I initially wasn't able to replicate this on `localhost`, but [a version of it](https://canary1.forem.lol/images/66U7YQNKLK4Lz4-u9nDVbT_QT_M1iahl-lhVqZxCGZ8/w:775/mb:500000/ar:1/aHR0cHM6Ly9naXRo/dWIuY29tL2ZvcmVt/L2ZvcmVtL2FjdGlv/bnMvd29ya2Zsb3dz/L2NpLWNkLnltbC9i/YWRnZS5zdmc) is visible on `canary1`. 

This _appears_ to be a problem with `prefix_images` — which is somewhat unique to DisplayAds — which has an opt-out for `camo.githubusercontent.com`, but that isn't the host serving CI badges, so the image handler attempts to "localize" the badge, with ... inconsistent output.

The fix is probably to extend the carve-out to cover (at least?) these badges. I'm not confident I'll get this wrapped up before 🌴 though.

`cc` @lightalloy & :link: #19091

**Comment by mirie** [comment]
Q: @jaw6 did you add the `blocked` flag because you can't replicate on `localhost`? What would recommend to be the next step to unblocking?

**Comment by jaw6** [comment]
@mirie 
> Q: did you add the blocked flag because you can't replicate on localhost? What would recommend to be the next step to unblocking?

I'm honestly a bit stumped here, thus the `blocked` label.

**Comment by mirie** [comment]
This convo happened in Slack but I realized I should note on this issue: I asked for @maestromac to deploy the latest to a Canary instance when he has a moment since the code is a bit outdated.
