### ISSUE TITLE
Add filter for organizations in /search

### ISSUE THREAD

**Issue by pkfrank** [forem/forem#19364]
## Is this feature related to a problem?  Please describe.

As a user, I want to be able to search for organizations in `/search`.

## Describe the solution you’d like

On `/search`, I’m already able to use filters for…

* Posts
* Podcasts
* People
* Tags
* Comments
* My posts only

The feature request here is to add a filter for **organizations**.

The organizations should be returned visually in essentially the similar style as we use for users. 

**Information to display:**
* Profile image
* Name
* Username
* Tagline

![Frame 1](https://user-images.githubusercontent.com/84626054/234759964-6e2b9ba4-1b7b-4855-b11a-0b304cc74a75.png)

**[Figma Designs](https://www.figma.com/file/9UfSjNYJs745w3Q8JCUqsL/Small-Wins---%E2%80%A8Core-Experience-%E2%9A%A1%EF%B8%8F?type=design&node-id=1833-6318&t=x090sTWmIUcXwR9V-4)**

## Definition of Done

- [ ] A filter for organizations has been added to the `/search` page
- [ ] Search uses supplied keyword and searches across `organizations.name` (will likely need to create an index)
- [ ] Organizations are returned visually in their appropriate style (square logo) with the Follow button

## Additional Context

This should follow existing patterns for search functionality, so check out how it is done with some of the other resources we have, and copy those. Files such as `app/services/search` are a good place to start looking.

**Comment by anujbhavsar96** [comment]
I would like to suggest some minor design improvements here. Maybe we can extend this to the user's card as well later.

If you see on the left side, the user's card looks blank and needs to utilize space better. And we display the username first in the textual hierarchy, which is a bit weird because the actual name should be at the top because that's the easiest and accurate way to recognize anything in a search. We can also add a tagline/summary/bio to give more context about the searched element.

Thoughts @pkfrank ?

<img width="1607" alt="Screenshot 2023-04-25 at 11 38 51 AM" src="https://user-images.githubusercontent.com/84626054/234189124-9b48a7f2-f04c-442e-ac4f-f9360ec8fde2.png">

**Comment by mirie** [comment]
@anujbhavsar96 This looks nice! So it looks like these fields:
- Name
- Profile image
- Tag line

**Comment by anujbhavsar96** [comment]
Yes @mirie we are adding the `Tagline` new and adjusting the reading hierarchy.

**Comment by pkfrank** [comment]
@anujbhavsar96 this looks great, let's proceed with these designs.  Agreed that it makes sense to implement this for Organizations first, and then we can circle back and improve the designs for the other search result views.

**Comment by anujbhavsar96** [comment]
Updated the issue with new design and Figma link @mirie and  @pkfrank

**Comment by mirie** [comment]
Found a bug so re-opening. The search should return only matching organizations. Example:

1. https://dev.to/search?q=AWS&filters=class_name:Organization(https://forem-team.slack.com/archives/D0478SFDB7G/p1683644718673309)
2. First result in search is not an organization

![Screenshot 2023-05-09 at 11 00 20 AM](https://github.com/forem/forem/assets/896728/2f5e80ef-6c00-4ccf-a39b-fee32e900ba3)
