### ISSUE TITLE
Scroll To Top

### ISSUE THREAD

**Issue by maheshhost** [forem/forem#1952]
Please add scroll to top button . I read tech blogs daily from dev.to and some blogs are so lengthy so in the end we need to scroll to the top again so if there would be a scroll to top button it would be great for the readers to get to the top easily.

Thankyou

**Comment by jessleenyc** [comment]
Thanks for the feature request. @benhalpern let's take this into consideration on future design overhauls.

**Comment by mkrl** [comment]
Please consider using [this](http://tholman.com/elevator.js/) as a part of a possible implementation

**Comment by twhite96** [comment]
>Please consider using [this](http://tholman.com/elevator.js/) as a part of a possible implementation 

@mkrl I think you can do this with just plain JavaScript. I have this on my blog but with React and React Spring. It shouldn't be too difficult to implement this in vanilla js.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rhymes** [comment]
@mkrl the music is terrible though :D I like the effect especially because I see it can be made a little bit faster...

@twhite96 it's implemented in vanilla JS: https://github.com/tholman/elevator.js/blob/master/elevator.js - it's 1.77kb minified, removing the audio stuff should make it even shorter :D

**Comment by mkrl** [comment]
Jokes aside, I don't think you need any kind of JS for a simple "scroll to the top" button.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
