### ISSUE TITLE
Spike: Target billboards by country/region as edge caching allows

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#19597]
## Is this feature related to a problem? Please describe.

As a billboard creator, I’d like to restrict billboard displays to a particular region where it is most relevant — or perhaps the only area it is relevant, for use cases such as promoting local events and conferences, or generally restricting messaging to a locality where the message would be more relevant.

This is both important for billboard creators, and for users who don’t want to see irrelevant billboards.

As a platform we want to provide this service without tracking users across the web via cookies processing or storing personal data for anonymous browsing — that is to say, offering some reasonable high level filtering while constraining the functionality such that it cannot be used for fingerprinting or storing of information where personal identity could be derived.

City-level targeting would also not be considered PII in the way we do it, and we could consider adding it in the future, but would do so in a forward compatible way. This task is strictly country/region specific.

## Describe the solution you’d like

We should use regional geolocation information which can be passed through from the edge to regional filtering.

We should implement this to work *with FASTLY*, i.e. the edge network that DEV uses, but projects that this could be compatible with other edges in the future.

For the time being, we will make this compatible with the way DEV uses Fastly.

https://developer.fastly.com/reference/vcl/variables/geolocation/client-geo-region-ascii/

As per Fastly docs, we can set an HTTP header to be passed with VCL along these lines

```
set req.http.client-geo-country = client.geo.country_code;
Set.req.http.client-geo-region = client.geo.region
```

Or perhaps instead we concatenate and pass a single value such as:

```
set req.http.client-geo = combination_of_both (i.e. “US-CA”)
```

These would wind up on our server as a part of `request.env`, similar to how we have access to `request.env["HTTP_FASTLY_CLIENT_IP"]` as needed for rate limiting.

Fastly uses standard ISO 3166-2 codes to reference regions. For example, the regions in the USA correspond to states, i.e. US-CA or US-NY.

For other countries, regions vary in terms of how the nation is divided by county or other areas, but the good thing is that the idea of “region” is reasonably standard.

We will allow billboard creators to input a comma-separated string which corresponds to a list of country codes or country+region codes.

Example: “FR, DR, US-CA, US-FL” would allow a billboard to target France, Germany, California (USA), or Florida (USA).

This would be approximately the same logic as what we provide for tags — where a list of various locations corresponds to an OR query, and leaving this field blank corresponds to no restrictions (i.e. targeting all).

The request would receive a value such as `request.env["HTTP_CLIENT_GEO"]` and then we would need to find the various matches, whether country or country + region.

This logically creates a more complex match than the way we match on tags due to the possibility of partial matches (i.e. a request coming from Florida would match whether `US` or `US-FL` is included in the list). However, this should be achievable via regex matching in a similarly efficient way, just with a bit more complexity.

Similar to `cached_tag_list` new field should have a We need a GIN index on `cached_tag_list` to speed up `LIKE` queries — https://www.postgresql.org/docs/11/pgtrgm.html#id-1.11.7.40.7

Finally, the logic to pass the appropriate header should be added as a VCL snippet, similar to the existing snippets we have such as `config/fastly/snippets/check_for_remember_user_token_in_cookie_to_set_header.vcl`.

While this will only match this functionality to a context where this Fastly parameter is passed, if the parameter does not exist or is not passed through as expected, all the remaining functionality will continue to work without geo targeting.

### Development environment

In the development environment and/or staging (i.e. Uffizzi), the “client geo” headers we pass through will not be present. Therefore we should also add a way to test this functionality in development in a way that is intuitive.

Therefore we could allow the functionality to be set in *either* a CLIENT HTTP HEADER as proposed _or_ a URL parameter, i.e. ?client_geo=US-CA

There will always be a component of this functionality which is environment-specific, but the simpler we can make it to manually test the deeper parts of this functionality through manual PRs, the better.

Alternative ideas to make development simpler.

## Definition of Done

- [ ] New geo field is added to `display_ads`
- [ ] VCL is added to pass geo data as header to server
- [ ] Geo field is added to admin area
- [ ] Geo field is added to API
- [ ] FilteredAdsQuery is modified to accept geo filtering
- [ ] Add development environment parameters or similar solution

## Additional Context

If full or partial support of this can be added to Forem Cloud nginx config, this is worth exploring, but is a nice-to-have for this deliverable.

**Comment by Ridhwana** [comment]
After reading this issue more I'm not sure that it can be broken into _many_ smaller tasks. However there is potential to achieve more certainty prior to implementation. Certainty can be achieved with researching/answering the following questions: 

- How do we best pass the country code and region within our app. Should we set up as different fields, do we concatenate etc. and why? 
- How do we setup the development environment to ensure that we can test locally ? ( I like the proposal of the CLIENT HTTP HEADER but we can validate if it makes most sense)
- Do we store as a string (like cached tag list) or as an array and if so what are the tradeoffs? 

I think allocating out a day or two for research on this may be useful. The time could also be used to crank out an MVP that we could use or throwaway. 

cc @benhalpern @mirie

**Comment by mirie** [comment]
Okay based on that feedback I'm giving the overall issue a estimate of 10 but want to say that we'll need to have iterable deliverables within this time period versus all at the end. I agree that limiting to a day of research and a day for feedback / adjustment of proposal sounds reasonable.

**Comment by Ridhwana** [comment]
@filleduchaos this issue has been identified as one that could potentially take longer than expected, hence let's try to be as communicative on any blockers or questions and keep feedback loop open in general. 

When you start working on the issue let us allocate out about 2 days for initial research to answer some of these [questions](https://github.com/forem/forem/issues/19597#issuecomment-1621460712) and thereafter communicate the findings, provide a more informed estimation, and see if things can be broken up further.

**Comment by filleduchaos** [comment]
Some important context from the exploration I have done so far:

The ISO 3166-2 standard provides a list of countries mapped to 2-letter codes, along with a sub-list for each country of what are called "subdivisions" since they vary from country to country.

Some countries have a simple standard for subdivisions (such as [Canada](https://en.wikipedia.org/wiki/ISO_3166-2:CA), whose subdivision list is just the 10 provinces and 3 territories, all of which are on the same hierarchical level so to speak). This makes handling targeting fairly easy, because if we get an incoming request from someone in `CA-NL` (Newfoundland, Canada), it is fairly straightforward to craft a query that includes any billboards targeting `CA` (the whole of Canada) or `CA-NL` specifically, but excludes those targeting `CA-QC` (Quebec, Canada) or `US-CA` (California, United States) using pattern or even just string matching

However, others use the subdivisions code list for multiple different levels of geographical subdivisions, some of which are _contained_ in each other. [France](https://en.wikipedia.org/wiki/ISO_3166-2:FR) for example has subdivision list which includes both "metropolitan regions" (such as `FR-ARA` (Auvergne-Rhône-Alpes)) _and_ "metropolitan departments" which make up those regions (such as `FR-01` (Ain, a department in Auvergne-Rhône-Alpes)). [Per Fastly's docs](https://developer.fastly.com/reference/vcl/variables/geolocation/client-geo-region-ascii/), we would be getting the most specific subdivision/"region" possible, so a user in Ain would show up as `FR-01`, not as `FR-ARA`. But they _should_ be getting matched with any billboards targeting `FR-ARA`, much like they should be matched with billboards targeting all of `FR`.

My proposed eventual solution to this is to internally expand the hierarchy so that `FR-01` would internally become a path/representation like `FR-ARA-01`. Then we'd be able to safely match only billboards targeting `FR`, `FR-ARA`, or `FR-ARA-01` (the syntax for this is a bit more pleasant with an ltree array column than with regex matching. This is a bit complicated though because while the Ruby gem (`countries`) I'm prototyping with provides a lot that will be useful (such as localized names for the UI), it doesn't seem to include the relationships between subdivisions. But I was able to find [this Debian-maintained subdivision code dataset](https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/data/iso_3166-2.json) that does include the "parent" relationship, which we could use to extend the gem with the ability to expand subdivision hierarchy.

I put a hold on implementing that though because in the short term, we could start by only allowing billboards to target whole countries (or limiting the initial countries-with-regions launch to the US and Canada while we plan what we're going to do with non-uniform subdivisions).

**Comment by Ridhwana** [comment]
@filleduchaos I didn't get a chance to look through this PR today but I'll look at it on Monday morning.

**Comment by mirie** [comment]
@filleduchaos does it make sense to close this issue in favor of the smaller ones you've created?

**Comment by Ridhwana** [comment]
@filleduchaos I've edited the title of this task with "Spike". I think that since you've created the smaller issues, we can close this one in favor of those. 

For reference in this task, I've added the links to the other issues: 

- [Support filtering billboards by target location #19790](https://github.com/forem/forem/issues/19790)
- [Update Fastly config to include client country and region as a header #19792](https://github.com/forem/forem/issues/19792)
- [Update billboard displays to only show billboards targeting the user's location #19793](https://github.com/forem/forem/issues/19793)
- [Basic admin UI for targeting billboards by location #19794](https://github.com/forem/forem/issues/19794)
- [Add support for target geolocation to the billboards API #19798](https://github.com/forem/forem/issues/19798)
- [Enhanced admin UI for targeting billboards by location #19795](https://github.com/forem/forem/issues/19795)
