### ISSUE TITLE
Return a 404 for public unauthenticated access to banished or empty suspended accounts

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19732]
## Is this feature related to a problem? Please describe.

As a Forem admin, I want to reduce the impact of spam accounts on the platform's reputation and SEO performance.

## Describe the solution you’d like

- For public, unauthenticated (i.e., not logged in) access to a user's profile page, we should return a 404/not found response when the target user's profile is either:
  - Banished, or
  - Suspended **and** has no published, accessible articles or comments.

## Definition of Done

- [ ] Return a 404 when a non-authenticated user accesses a banished user's profile page
- [x] Return a 404 when a non-authenticated user accesses a suspended user's profile page when the suspended user has no visible comments or no published accessible articles.

## Additional Context

- This work is a low-effort, medium-impact means of reducing the impact of spam accounts that exist purely to direct traffic to their profile (or are effectively suspended before they have time to interact).
- Admins might suspend a user for instances of bad behavior but want to retain their content on the platform.
- This only refers to unauthenticated access; access for members of the community should be retained.
- Articles which are published but scheduled for the future are not accessible, and thus suspended users' profiles with these articles should still return a 404.
- From refinement discussion, we determined it would be best to move this functionality out of the view (which we feel is a a bit hacky) to the controller

**Comment by benhalpern** [comment]
We already add `no-index` in some contexts, so this would be a matter of essentially modifying the existing logic to something like this:

```
<%= content_for :page_meta do %>
  <%= render "users/meta" %>
  <% if @user.score.negative? || @user.suspended? %>
    <meta name="robots" content="noindex">
    <meta name="robots" content="nofollow">
    <% if no_content? && !user_signed_in? %>
      <% not_found %>
    <% end %>
  <% end %>
<% end %>
```

That would be if we tacked on to the existing view area — but this is best handled in the controller.

**Comment by Hanaffi** [comment]
@PhilipHow Shall I work on this please?

**Comment by Hanaffi** [comment]
@benhalpern @PhilipHow Can you assign this to me please?

**Comment by PhilipHow** [comment]
@Hanaffi Thanks for getting involved. Unfortunately, this issue is labeled `Forem team` which means it's reserved for our internal team members. Feel free to look over the issues that are `ready for dev` which are open to external contributors and make your request there. Make sure you've read the [contributor's guide](https://developers.forem.com/contributing-guide/forem).

**Comment by Hanaffi** [comment]
@PhilipHow Thanks for explaining.
Can you assign me some backend task please?

**Comment by Ridhwana** [comment]
There's a little bit to dive into on this task. Before diving into the details, I want to provide some of the observations from exploring the codebase within this context: 

### Observations

#### Banishing a user:

1. We can banish a user from http://localhost:3000/admin/member_manager/users/72. In order to banish a user, [the following requirements are important](https://github.com/forem/forem/blob/main/app/controllers/admin/users_controller.rb#L413-L416):
      -  user has not commented in the last 100 days 
      - the user was created in the last 100 days 
      - the current user who will banish is a super_admin or a support_admin

        def set_banishable_user
              @banishable_user = (@user.comments.where("created_at < ?", 100.days.ago).empty? &&
                @user.created_at < 100.days.ago) || current_user.super_admin? || current_user.support_admin?
          end

2. When we banish a user we call a worker that contains a [service that does the following](https://github.com/forem/forem/blob/main/app/services/moderator/banish_user.rb)
        - Move it to a BanishedUser table where we track banished users
        - Remove the email from mailchimp newsletters
        - Remove the Profile Information
        - Change the user status to suspended
        - Delete user activity
        - Delete comments
        - Delete articles
        - Delete user podcasts
        - We update the username to be "spam_#{rand(1_000_000)}"
        - Delete vomit reactions


#### Checking if a user is banished

3. As part of the authorizer we check if a user is banished by calling [`<user>.banished?` where the username starts with `spam`](https://github.com/forem/forem/blob/main/app/policies/authorizer.rb#L66-L68)

          def banished?
              user.username.starts_with?("spam_")
           end
         

4. We've created a user decorator to determine if a user is [`fully_banished?` ](https://github.com/forem/forem/blob/main/app/decorators/user_decorator.rb#L117-L120) by checking if the user has been suspended and has no content. 

          # returns true if the user has been suspended and has no content
          def fully_banished?
            articles_count.zero? && comments_count.zero? && suspended?
          end

#### Using the banished helpers

5. We currently use the  [`fully_banished?` ](https://github.com/forem/forem/blob/main/app/decorators/user_decorator.rb#L117-L120) decorator (mentioned in point 4) in the stories_controller whereby we show a 404 on the profile page /<:username> if the username includes `spam_` and the user is `fully_banished?` as per the definition function above. We do this whether the current user is authenticated or not.

        not_found if @user.username.include?("spam_") && @user.decorate.fully_banished?

6. We [do not award users badges if users are banished,](https://github.com/forem/forem/blob/main/app/services/badges/award.rb#L1) we check this using `user.banished?`

#### Unrelated but related
7. When a username is changed then [we validate that the initial username of the user does not exist in the Banished Table](https://github.com/forem/forem/blob/main/app/models/user.rb#L501-L503):
    ```
    def non_banished_username
        errors.add(:username, I18n.t("models.user.has_been_banished")) if BanishedUser.exists?(username: username)
      end
    ```

### How does this information relate to the issue at hand

From the above, it seems like there are two ways that we tell if a user is banished or not, using two methods:

          def banished?
              user.username.starts_with?("spam_")
           end

and 

          # returns true if the user has been suspended and has no content
          def fully_banished?
            articles_count.zero? && comments_count.zero? && suspended?
          end

However, from my understanding there is no difference in whether a user is `banished?` or `fully_banished?`. There doesn't seem to be a concept of banished and fully banished. By deduction a banished user is a user that meets all the following criteria: 
- They have `_spam` in their username 
- They have been suspended
- They have no articles or comments i.e. `articles_count.zero? && comments_count.zero?`

The two requirements in this [issue](https://github.com/forem/forem/issues/19732) 
```
1. Return a 404 when a non-authenticated user accesses a banished user's profile page
2. Return a 404 when a non-authenticated user accesses a suspended user's profile page when the suspended user has no visible comments or no published accessible articles 
```
seem only be one requirement - i.e. show a 404 when a user is banished. Point 2 seems to be the definition of a banished user according to the `fully_banished` method that currently exists (_with a tweak that  we want to use an accessible_article_counts which I think we can add to `fully_banished?`)._  

**_@PhilipHow is point 2 actually a different requirement to a `fully_banished_user`? and do we want to instead keep them separate:_** 

_for point (1)  a banished user which meets the requirements of `articles_count.zero? && comments_count.zero? && suspended?`
for point (2) a user which meets the requirements of `accessible_article_count.zero? && comments_count.zero? && suspended?`_


If it turns out that the above is actually one requirement and we actually want to just handle the case of a banished user  then in a PR I can update `fully_banished?` to use `accessible_article_counts` instead of `articles_count` and I can update the [current line that handle banished users for the user_profile](https://github.com/forem/forem/blob/main/app/controllers/stories_controller.rb#L185-L186)
```
    not_found if @user.username.include?("spam_") && @user.decorate.fully_banished?
```
to read 
```
unless current_user
   not_found if @user.banished? && @user.decorate.fully_banished?
end
```
Currently, if the user is `fully_banished` we are always showing a 404 page to authenticated and unauthenticated users. 

_**I guess my action item here is for @PhilipHow to confirm that both those points do actually seem like one requirement instead of two.**_ 

Thereafter I can go ahead and create a PR as per the steps that I've outlined above. 

## A follow up cleanup issue

Based on all the information above on the surface it _seems_ like we could consolidate `fully_banished` and `banished` into one method that we call `banished?` which will maintain all the requirements ( `_spam` in the username , suspended,  no _accessible_ article_counts or comments) that indicate a banished user. We could delete `fully_banished?`and only maintain one method. 

But perhaps I'm missing some context and there is a reason why we have a `banished?` method and a `fully_banished?` one?

## Long Term possible alternative?

An alternate solution for banished users could be that when we banish a user through the [BanishUser service](https://github.com/forem/forem/blob/main/app/services/moderator/banish_user.rb), in addition to keeping track of the old_username, we could keep track of the new_username of the user (i.e. spam_<random>). Hence, if we want to check if a username is banished we could check if that old_username exists in the BanishUser table which seems like it could be more reliable. In this scenario we would need to update the table for historic data. 

I'm looking for feedback from possibly @benhalpern on the  "follow up cleanup issue" and "Long Term possible alternative" section.

**Comment by PhilipHow** [comment]
Thanks, @Ridhwana, for the detailed explanation of what is going on here. My head is spinning, so this must have taken some time to put together.

It's clear `banished` is a bit of a mess at the moment - rather than drag a fix into this issue, I suggest we separate out the concerns and only focus on `suspended` users for now and revisit `banished` separately.

I think that means we focus on (2) of the matters you've referred to above and implement the change specifically for suspended users with no accessible content, irrespective of the `banished` state.

See example [spam account here](https://dev.to/pk88io01) where the user has been suspended and an article unpublished. We're incorrectly showing the number of articles as 1, so I think `accessible_article_count` should be mindful of this unpublishing behavior.

This increases the power of the `suspend` + `unpublish` combination as an alternative to the destructive `banish` that adds hesitation to its use.

I would like to explore a proper non-destructive `banish` soon, and it's likely we can tidy the existing `banish` helper functions as part of that work.

**Comment by Ridhwana** [comment]
Thanks so much for your feedback here ✨

> I think that means we focus on (2) of the matters you've referred to above and implement the change specifically for suspended users with no accessible content, irrespective of the banished state.

Okay this sounds good, I'll send out a change to only tackle (2).

> See example [spam account here](https://dev.to/pk88io01) where the user has been suspended and an article unpublished. We're incorrectly showing the number of articles as 1, so I think accessible_article_count should be mindful of this unpublishing behavior.

In this case, we are actually only [calculating posts that have been published already](https://github.com/forem/forem/blob/Ridhwana/404-banished-user/app/views/users/_sidebar.html.erb#L54)
```
<%= t "views.users.side.post.text", count: @user.articles.published.size %>
```
So the value is correct, however we are caching that section and off the top of my head it seems like the cache is not being refreshed. I'd need to give this a bit more thought but we can add it as a separate issue and fix it if that makes sense?

**Comment by PhilipHow** [comment]
>So the value is correct, however we are caching that section and off the top of my head it seems like the cache is not being refreshed. I'd need to give this a bit more thought but we can add it as a separate issue and fix it if that makes sense?

Yes - I will log a separate issue for that.
