### ISSUE TITLE
Allow organization admins to add organization members as co-authors to posts

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19828]
## Is this feature related to a problem? Please describe.

- As an organization admin, I want to add co-authors to posts created under the organization when they were involved in the authoring of the post to be able to credit them properly.
- As an organization admin, I have the property authority to be able to do this unilaterally, as I can currently change the author for any organization posts to any organization member.

## Describe the solution you’d like

- Organization admins should be able to add other organization members as co-authors to organization posts.

**Designs** - [Figma link](https://www.figma.com/file/9UfSjNYJs745w3Q8JCUqsL/Small-Wins---%E2%80%A8Core-Experience-%E2%9A%A1%EF%B8%8F?type=design&node-id=2574-565&mode=design&t=OkJzVzvo9wK495Mc-4)

![Frame 626048](https://github.com/forem/forem/assets/84626054/64f72bc2-8e09-40ed-8150-0a5b51c4f39d)

## Definition of Done

- [ ] Organization admins will now be able to set the "Co-authors" for a post in the "Additional settings menu" in the Dashboard on any organization post, for the organizations they are an admin for.
- [ ] Organizations admins will be able to set up to 4 additional co-authors to each post.
- [ ] Organization admins will be able to remove individual co-authors from the post.

## Additional Context

- No changes to how co-authored posts are displayed or behave are required as part of this.
- Users added as co-authors will not be notified
- The additional settings menu is shown on the dashboard when the ellipses button is pressed for a post:
![image](https://github.com/forem/forem/assets/1628871/d5852ce8-68fb-425c-9105-f5e3090c769d)
- Co-authors should be added in the database, in the same manner co-authors can be added to existing posts by admins, accessible through the content manager in `/admin`:
![image](https://github.com/forem/forem/assets/1628871/5f88b623-847d-41c9-a057-7f4fa0640c01)
- We are limiting this to organization posts as we then are not required to build any notion of a user consenting to being added to a co-authored post, as they naturally have given consent to this as being part of the organization. Any issues of this being abused and the clean-up needed when a user leaves an organization (whether to remove the co-authorship, or not) will be handled manually for the time being.

**Comment by Ridhwana** [comment]
>  Once clicked, they will be able to select an Organization member as the additional co-author.
>  Organizations admins will be able to set up to 4 additional co-authors to each post.


I'm wondering what the user experience of this looks like: 

Based on a [query](https://forem.metabaseapp.com/question/827-organization-memberships-count-grouped-by-sorted-by-count-descending) one of our organizations has 1000+ members in their organization. Other organizations are mostly 150 and below. However, this makes me think about how we plan to add these members?

On the admin, we just use user_ids to populate co-authors which is probably want we want to avoid. However, we could as an MVP have a comma separated list of usernames as co-authors?

The more user friendly alternative would be to perhaps get a count and if its a small number of users, we just populate it in a dropdown and have a search in place. 

For longer lists maybe we want some sort of search input where a username can be typed and after the first three characters we maybe autocomplete it? I don't think we'd want to load all 1000+ users at once, hence we may want to treat the dropdown in this case as a search rather than a list. 

What are your thoughts from a product perspective

**Comment by mirie** [comment]
Team, for estimation, let's estimate the version that has an autocomplete user search option that is limited to post's selected organization users.

**Comment by anujbhavsar96** [comment]
@Ridhwana here is the [loom video](https://www.loom.com/share/b5a34b6386814d47b9778c48279d7ec4) explaining my approach, which is similar to what you have suggested but in the modal. Because I think autocomplete dropdowns in the dropdown itself would become very complex.

Do let me know what you think about it. Here is the [Figma link](https://www.figma.com/file/9UfSjNYJs745w3Q8JCUqsL/Small-Wins---%E2%80%A8Core-Experience-%E2%9A%A1%EF%B8%8F?type=design&node-id=2548-7509&mode=design&t=rDggEuha7UtCzPgX-4) _(I'll clean up designs based on feedback later)_

**Comment by PhilipHow** [comment]
I'd rather keep this as simple as possible. Handling organizations with a large number of users is an edge case in itself.

**Comment by mirie** [comment]
@anujbhavsar96 / @PhilipHow - watched the Loom and yeah, this autocomplete that you showed (similar to what happens when tagging in an Article is what I was imagining). Even if we don't solve for the 1000+ user org, if we have organizations that have 30 or 40+ members, having a scrolling list to select from will be less than ideal.

I feel like if we are OK with a less than ideal UX, then we should just go with comma separated user ids or usernames that are validated upon form submit to check if that user is part of the org. 

Otherwise I think we should opt to a better UX -- depends on who might immediately use it and how flexible they might be with a less than ideal UX/how we want to prioritize a better user experience.

**Comment by PhilipHow** [comment]
I'm less keen on a comma-separated list of usernames as:
  - People are less familiar with usernames, as opposed to a user's `name`.
  - There will need to be some on-screen validation of the username, to check if it is valid, and if the user belongs to the same organization.

If there is a simple means of adding an autocomplete search to the dropdown (e.g., a library we use and are familiar with, then I'm happy to include it. We could use [datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) instead, which seems like a good option, but I'm unaware of our browser support and accessibility requirement.

**Comment by Ridhwana** [comment]
If we're going some sort of autocomplete dropdown then I like @anujbhavsar96's proposal. 

@anujbhavsar96 it seems like what you are suggesting is sort of re-using the [Mention Autocomplete area](https://storybook.forem.com/?path=/story/app-components-mention-autocomplete-textarea--default) but we'd potentially extend it or re-use it in some way to handle the comma separated values.

Another option that I'd like to throw out there is to re-use [the tag multi-select component](https://storybook.forem.com/?path=/story/app-components-multiselectautocomplete--default) of which we have most of the functionality built already. 

cc @anujbhavsar96

**Comment by anujbhavsar96** [comment]
> Another option that I'd like to throw out there is to re-use [the tag multi-select component](https://storybook.forem.com/?path=/story/app-components-multiselectautocomplete--default) of which we have most of the functionality built already.

This component can work. Also, have a limit of four selections. Just a quick mock of how it would look.

![Section 4](https://github.com/forem/forem/assets/84626054/004bf57a-b07d-4b06-9b2a-7b5458af76ca)

**Comment by Ridhwana** [comment]
> This component can work. Also, have a limit of four selections. Just a quick mock of how it would look.

I think this looks good. Which do you think we should go with? 

In terms of engineering work required it might be more efficient/quick to re-use [the tag multi-select component](https://storybook.forem.com/?path=/story/app-components-multiselectautocomplete--default) because I had updated it to allow it to be re-used on the [Billboards Targeted tags feature](https://github.com/forem/forem/pull/18560). Hence, we _may_ just be able to pass the information to the component instead of making changes to the component itself. 

Some context on the engineering side for engineers, we use the component through React and it looks something like this, we'd configure this component to accept username suggestions and provide the necessary callbacks. 
```
<MultiSelectAutocomplete
      defaultValue={defaultSelections}
      fetchSuggestions={fetchSuggestions}
      staticSuggestions={topTags}
      staticSuggestionsHeading={
        <h2 className="c-autocomplete--multi__top-tags-heading">Top tags</h2>
      }
      border
      showLabel
      labelText="Targeted Tag(s)"
      placeholder="Add up to 10 tags..."
      maxSelections={10}
      SuggestionTemplate={TagAutocompleteOption}
      SelectionTemplate={TagAutocompleteSelection}
      onSelectionsChanged={syncSelections}
      onFocus={switchHelpContext}
      inputId="display-ad-targeted-tags"
      allowUserDefinedSelections={true}
    />
```

**Comment by PhilipHow** [comment]
Agreed to use the component @Ridhwana has suggested before.

If we could search by user's `name` as opposed to `username`, I think this would help the UX.

**Comment by mirie** [comment]
@jaw6 I believe you've been focusing on the other higher priority issue (user status visibility), but figured I should ask! For the draft PR you have going for this work -- it looks like the recent focus has been on test coverage -- anything off/unexpected that you're bumping into there?

**Comment by jaw6** [comment]
> anything off/unexpected that you're bumping into there?

I'm not sure what's going on, but it seems like the code coverage tool is wrong, or I am. [I am already asking the team for help over here.](https://forem-team.slack.com/archives/C7GE84DEJ/p1694079600471419)
