### ISSUE TITLE
Allow tag moderators to override other tag moderators actions

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19824]
## Is this feature related to a problem? Please describe.

- As a tag moderator, I want the ability to override other tag moderators' actions so that tag moderators can come to a consensus on the right course of action for an article.

## Describe the solution you’d like

- Tag moderators will be able to override other tag moderators' actions (relating to the same tag, where both tag moderators moderate the same tag) and re-add a tag to a post that had been removed, and vice versa.
- Tag moderators will not be able to override admin actions and will be shown when an admin has added or removed a tag
- Admins will be able to override all actions, including other admins, and add or remove any tag.

## Designs 

- See [full designs on Figma](https://www.figma.com/file/yhg9HTZDFIeWuvBt9ygrss/Moderation?type=design&node-id=1895-4729&mode=design&t=pRLL1b6DLuptuDYe-4)

![image](https://github.com/forem/forem/assets/1628871/4947a732-017b-4c1d-856e-0826ae6a0da9)

## Definition of Done

- [x] Remove the restriction that prevents tag moderators from adding or removing a tag that was added or removed by another tag moderator.
- [x] Remove the restriction that prevents admins from adding or removing a tag that was added or removed by another admin
- [ ] The tag moderation history should be appended in all cases, preserving the order and history in which tags were added or removed.
- [x] ~When a tag moderator attempts to add or remove a tag that was added or removed by an admin, the tag moderation panel should show a warning that can be dismissed, stating, "Tag has been {added/removed} by Admin. You can't {add/remove} it now. If you feel that's a mistake, please contact us at {support_email}".~ However, after chatting with Phil we will proactively show a message "Tag has been {added/removed} by Admin. You can't {add/remove} it now. If you feel that's a mistake, please contact us at {support_email}" when a tag moderator is moderating a tag that has already been updated by an admin or super moderator.

## Additional Context
Some of the policy code related to this lives [here](https://github.com/forem/forem/blob/main/app/policies/article_policy.rb#L171-L188).

- Additional issues being undertaken:
  - https://github.com/forem/forem/issues/19822
  - https://github.com/forem/forem/issues/19823

**Comment by michael-tharrington** [comment]
Just to be super clear, currently, a tag moderator can't even override/undo their own actions. 

For example, if a tag mod removes a tag from a post, they cannot add the tag back. I think this proposed fix accounts for that scenario, but I just wanted to be super clear.

**Comment by mirie** [comment]
@filleduchaos has a branch they can push; taking this off their plate as they have multiple high priority issues in progress/in review

**Comment by filleduchaos** [comment]
@Ridhwana here is [the branch in question](https://github.com/forem/forem/compare/filleduchaos/tag-moderation-access-policy-update) - I've rebased it on main so really what's left is attaching the error messages to the UI that Rajat worked on. I also remember being dissatisfied with the way I was checking for adjustments made by admins, if you want to take a second look at that as well

**Comment by Ridhwana** [comment]
@anujbhavsar96 just a heads up that after chatting with Phil we decided that instead of having a moderator click on the add/remove button for a tag (that was previously added by an admin) and then receive an error message, we will instead proactively show the message "Tag has been {added/removed} by Admin. You can't {add/remove} it now. If you feel that's a mistake, please contact us at {support_email}" when a tag moderator is moderating a tag that has already been updated by an admin or super moderator.

**Comment by Ridhwana** [comment]
@PhilipHow just confirming that this

> The tag moderation history should be appended in all cases, preserving the order and history in which tags were added or removed.

belongs in https://github.com/forem/forem/issues/19823?

**Comment by PhilipHow** [comment]
@Ridhwana This was intended to mean "don't roll-up the changes" i.e. if one person removes a tag and one person adds one, there are 2 entries, not 1 or 0.

**Comment by anujbhavsar96** [comment]
@Ridhwana @PhilipHow If we want to display this up front, maybe we should reduce the notice length. Because, let's say, as tag moderator, I'm moderating two tags or more, and admin has adjusted all of them, this would look very weird in such a small space. That's why I decided to display notice one step inside. 

And anyway, I feel this is kind of an edge case, so we don't have to worry about displaying this notice upfront.

<img width="394" alt="Screenshot 2023-09-13 at 11 39 52 AM" src="https://github.com/forem/forem/assets/84626054/3d63c412-5855-486e-aa90-19b3a4407a36">

**Comment by Ridhwana** [comment]
Let me know if you'd like me to make any changes here @anujbhavsar96

**Comment by anujbhavsar96** [comment]
@Ridhwana I've discussed the above issue with Phil, and I'm okay with it. 

Just one small change: as you can see in the above screenshot, the `#go` tag is in the middle of two unadjustable tags. Can you do something so that the adjustable tag always stays on top and below that the unadjustable tags?

The same goes for the tag removal area.

**Comment by Ridhwana** [comment]
Sorry I mistakenly closed it, this is still in review.
