### ISSUE TITLE
Filter out tags with user-assigned negative weights from the "Relevant" feed

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19829]
## Is this feature related to a problem? Please describe.

- As a feed-consuming user, I want a simple means of hiding content I do not want to see in the feed. For example, if I am uninterested in javascript content, I can hide the `#javascript` tag.

## Describe the solution you’d like

- To coincide with the [UI work to hide tag weights and add a "hidden tags" section](https://github.com/forem/forem/issues/19675), changes to the "Relevant" feed logic are required to exclude articles with any tags the user has set to a negative (< 0) weight. (i.e. if I have hidden `#javascript` and a post has been tagged `#javascript`, I should not see that post in my feed.)

## Definition of Done

- [ ] Change the "Relevant" feed logic so posts with tags that the user has hidden (assigned a negative weight to) are filtered out of the feed
- [ ] When no user is signed in (or when a logged-in user has no tags hidden), feed appearance and behavior should not be affected
- [ ] Specs exist / have been added or fortified, to ensure that when a user manually searches for a tag they've hidden, or accesses it directly, the user is still able to see and interact with the tag. *Hiding a tag should only affect how the user scrolls their feed, not a user's later decision to peek at the tag's contents*
- [ ]  A change made to how the Relevant feed loads a queried set of posts should not result in changes to how the query retrieves posts for other contexts. 

## Additional Context

- This should only impact the "Relevant" feed. We should prioritize supporting this on DEV before any additional work is required to support it more widely.
- The initial async load of posts in `/stories/feed` should hide the same posts based on hidden tags as the paginated posts loaded via `/search/feed_content?` while scrolling.
- Searching for a tag or accessing a tag directly shouldn't be affected by this change. Tags will not be removed entirely.
- Ideally, searching for an article would be unaffected by this, but if this is prohibitively complex, then we can leave it in for now.
- The `Homepage::ArticlesQuery` and its private `filter` method is used both in the initial article fetch as well as within `Search::Article.search_documents.` It's possible that with a new query param differentiating a typed search from a scroll init search, a conditional filtering step added to Homepage::ArticlesQuery#filter could handle filtering out hidden tags without doing that filtering every time the query is called on.
- We have tried to reduce the effort required to ship this work - we want to test the impact this makes on improving the perceived quality of the feed. We currently have a low number of users with negative weights set, and feed variants still show some posts with negatively attached weights. The approach here should minimize the work before we commit to a more permanent solution (which may not use tag weights at all).
- Feed variant logic [already queries and scores](https://github.com/forem/forem/blob/3493c12ad2ac787b70724d689105b84b1035a9aa/config/feed-variants/20230511-variant-a.json#L58C16-L58C16) intersecting negative tag weights. We could simply update the in-use variants to zero out the scores here. e.g.
```
"matching_negative_tags_intersection_count": {
      "cases": [
        [0, 1],
        [1, 0],
        [2, 0],
        [3, 0],
        [4, 0]
      ],
      "fallback": 0
    },
```
- Alternatively, we could look at [adding the logic to this method](https://github.com/forem/forem/blob/d7b2f2e10f750ea53e45cc4e857d074453386759/app/services/articles/feeds/variant_query.rb#L257), to accept a list of `omit_tags" and build the where clauses to filter them out. The calling method should then be modified to pass in the list of the user's negatively weighted tags.
- See comments [[1](https://github.com/forem/forem/issues/19829#issuecomment-1653424770),[2](https://github.com/forem/forem/issues/19829#issuecomment-1655642703)] from @Ridhwana for more information about the technical implementation

**Comment by Ridhwana** [comment]
There are multiple considerations for this issue because the feed renders in many different ways.

Some background on rendering the feed:  We render the logged out feed asynchronously. We render the first page of the logged in feed through an endpoint `stories/feed....` which I describe later. When we scroll through the feed, we continue rendering the rest of the feed through an endpoint `search/feed_content`. 

We would not need to worry about the logged out feed in this case since a logged out user will not follow any tags, however when working on this task its important to make sure that the overlapping queries that we use for the logged in and logged out views are able to gracefully work when there is no hidden tags to remove from the feed. 

You will need to consider: 
- The (logged in) async rendering of the feed `stories/feed....`
- The scrolling behaviour which populates more feed items `search/feed_content`.  
- Each of the timeframes for the feed. The default is Relevant, then there is Latest, and Top. 

### The async rendering of first page of the feed: 
- In the Feed.jsx you will find a call to to render the feed `/stories/feed/${timeframe}? page=${page}` which is rendered by the `Stories::FeedController`.

The below queries will need to be amended, each of which help render the feed: 

- The feed that is filtered by a timeframe /top/<week | month | year | infinity> `Articles::Feeds::Timeframe.call(<some params>)`
- The feed that is filtered by a timeframe /latest `Articles::Feeds::Latest.call(<some params>)`
- For the default/Relevant Feed
  - if the feed strategy is "basic" `Articles::Feeds::Basic.new(<some params>)` 
  - if the feed strategy is not "basic"  `Articles::Feeds.feed_for(<some params>)` which uses the variant query for the feed `Articles::Feeds::VariantQuery.
            

### Further scrolling/pagination of the feed: 
- In the `searchParams.js` you will find a call to to render the feed `search/feed_content` which is rendered by the `SearchController`.            

To view the behaviour when you scroll down after the first page you will see a call to  
`http://localhost:3000/search/feed_content?per_page=15&page=3&sort_by=hotness_score&sort_direction=desc&approved=&class_name=Article`]. 

The query `Homepage::ArticlesQuery` would need to be amended in this case.
    
Some other considerations/questions: 
 - What happens if you search by a tag that is “hidden”? We need to make sure that the feed does not break in this case and that we render the articles for the "hidden tags".
 - Do searches show articles with "hidden tags"? If they do continue showing articles with "hidden_tags" then we would need to consider this in the `search/feed_content` path.
- None of our score calculations (like tag_score) will be changing, as we still maintain the tags `points` as is.

**Comment by PhilipHow** [comment]
@Ridhwana Thanks for the detailed explanation for this.

I really want to minimize the impact of this work, to be able to ship something sooner rather than later. We can take an incremental approach. We're not totally hiding a tag from everything - we can experiment with some copy changes later if this needs clarification.

- I think we could safely reduce this scope of this to only impact the "Relevant" feed for the time being.
- Searching for a tag or accessing a tag directly shouldn't be affected by this change. Tags will not be removed entirely.
- Ideally, searching for an article would be unaffected by this, but if this is prohibitively complex then we can leave it in for now.

**Comment by Ridhwana** [comment]
Okay so it seems if we want to only tackle Relevant then we need to amend the query that does the initial load of 50 items through `stories/feed` and the query that gets called through `https://dev.to/search/feed_content?` as we scroll and it loads 15 items at a time.

> For the default/Relevant Feed:
> - if the feed strategy is "basic" Articles::Feeds::Basic.new(<some params>)
> - if the feed strategy is not "basic" Articles::Feeds.feed_for(<some params>) which uses the variant query for the feed `Articles::Feeds::VariantQuery.

> Further scrolling/pagination of the feed:
> - In the searchParams.js you will find a call to to render the feed search/feed_content which is rendered by the SearchController.
> - To view the behaviour when you scroll down after the first page you will see a call to
> http://localhost:3000/search/feed_content?per_page=15&page=3&sort_by=hotness_score&sort_direction=desc&approved=&class_name=Article].

> - The query Homepage::ArticlesQuery would need to be amended in this case.

The engineer working on the task will need to careful to not unintentionally amend queries that are being used in multiple places, especially since the search query amendment can affect the actual search. Based on the above by @PhilipHow it seems like we do not want the results of any search on the home feed to be affected. We seem to have some test coverage but we'll need to ensure that we update those thoroughly.

**Comment by dukegreene** [comment]
Top-tier context collecting here, thanks so much for this @Ridhwana! Gives me a better idea of the surface area especially of where changes might have unintended impacts eg search

**Comment by filleduchaos** [comment]
Some (hopefully helpful) context for whoever picks this up: loading "feed content" is already routed separately to `Homepage::ArticlesQuery` for the home/relevant feed page and to `Search::Article.search_documents` for article searches. So when testing it may be useful to ensure that the changes to the former don't affect the latter

**Comment by PhilipHow** [comment]
Blocked for #19867
