### ISSUE TITLE
Add or remove `limited` role via API

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19893]
## Is this feature related to a problem? Please describe.

As an API consumer, I want to set a user's status to or from `limited`, so that I can programmatically determine whether a user is a suspected spam account and set the user's status accordingly.

## Describe the solution you’d like

- We need a means of add or removing the  `limited` user role, added in #19891, via the API, similar to the [suspend user endpoint](https://developers.forem.com/api/v1#tag/users/operation/suspendUser).
- This should be accomplished via an explicit API route for the limited status (eg. `/api/users/ID/limited`) where the role is added (via a `POST`) or removed (via a `DELETE`).
- This action should be limited to accounts with the `admin` or `moderator` role.

## Definition of Done

- [ ] Create an API endpoint that allows API consumers to add or remove the `limited` role.
- [ ] The API endpoints should only respond to accounts with the `admin` or `moderator` role.

## Additional Context

- An external service (likely part of Forem Tools) will consume this API to verify new user accounts before clearing their status back to Good Standing.

**Comment by Ridhwana** [comment]
> This could be accomplished through explicit endpoints for each action (e.g. "Limit a user's account", and "Clear a user's status/Set user to Good Standing"), or through a new "Set status" endpoint where the status is supplied in the request.

Even though we currently have a suspend `https://dev.to/api/api/users/{id}/suspend` I feel hesitant to create a bunch of endpoints that can set statuses and so I'm in favour of rather creating a single endpoint (unless there's a strong reason we shouldn't?) where we can set a user role (the permissions of role setting should be the same as we have in the application) with a note. If we set the status through an endpoint then it should call [`self.handle_user_roles(admin:, user:, user_params:)`](https://github.com/forem/forem/blob/b6b64c5d5b2abb1ad4d3a7168bd0ba9f76daac79/app/services/moderator/manage_activity_and_roles.rb#L5-L7) and go through [`handle_user_status`](https://github.com/forem/forem/blob/b6b64c5d5b2abb1ad4d3a7168bd0ba9f76daac79/app/services/moderator/manage_activity_and_roles.rb#L61-L97) like it would in the application. When we set a status/role, it should remove the appropriate negative roles etc. 

@philip based on the above I think I know the answer to this but I'd like to be explicit and so we need to determine how `limited` impacts the other roles:
- Is `limited` a negative role, hence, when we admin a privileged role to a user should it remove `limited` like it [would remove negative roles like `suspended`, `warned` or `comment_suspended`](https://github.com/forem/forem/blob/b6b64c5d5b2abb1ad4d3a7168bd0ba9f76daac79/app/services/moderator/manage_activity_and_roles.rb#L129-L134)?
- and the flip side of that, is that when we add `limited` to a role, should[ we remove privileged roles like `moderator`, `trusted` ](https://github.com/forem/forem/blob/b6b64c5d5b2abb1ad4d3a7168bd0ba9f76daac79/app/services/moderator/manage_activity_and_roles.rb#L31-L35)etc. 

> Create an API endpoint that allows API consumers to clear a user's status, setting them to "Good Standing".
We can probably create a DELET endpoint for a user role here. 


Let's chat a bit more about what the exact endpoint url is in the refinement: 
- We ideally want to pass through the username and the role (maybe a note param - should this be optional or mandatory?). 
- We need to handle error cases where the username or the role does not exist.

**Comment by PhilipHow** [comment]
Yes I think `limited` is a negative role that should clear positive statuses when applied and vice versa.

**Comment by jaw6** [comment]
> Create an API endpoint that allows API consumers to clear a user's status, setting them to "Good Standing".

I think this is maybe a "words thing" but I also think it would be good to clarify this particular point. Specifically, it often seems to me that we have implemented a *role-based system*, but we tend to describe our "wants" — like this one — in ways that more closely resemble a *status-based system*. 

It seems like the way we "want" to use `limited` will deepen this tendency.

So, here, specifically, we can't really "clear a user's status", because they don't have a "status", they have any number of "roles", which might include "limited", and we want to "remove the limited role", *possibly* **implicitly** putting them to "good standing", but possibly not. That distinction might matter?

We've also generally _**not**_ done a lot with roles in our API before — with the exception of `suspended`, I think? (Searching for `role` and related words in `app/controllers/concerns/api` comes up with just that one endpoint.) We don't even currently expose "roles" in the API at all, as far as I can tell.

In a universe where we were "thoroughly role-based" (for want of a better term), we might have a "roles" attribute in the `users` API with an array of values, something like:

```json
{
    "type_of": "user",
    "id": 11,
    "username": "admin_mcadmin",
    "roles": [
      "admin"
    ]
}
```

We might have an endpoint like `/api/users/ID/roles` that we POST or PATCH to set or change a user's roles, or we might — conceivably — embed them in the user, using `PATCH /api/users/ID` to add/edit/update the user's roles.

In a universe where we were "quite entirely status-based" (again, terms are hard), we might have a bunch of statuses instead:

```json
{
    "type_of": "user",
    "id": 11,
    "username": "admin_mcadmin",
    "admin": true
    "limited": false
}
```

And we'd need to `PATCH /api/users/ID.json` to alter these statuses.

To be clear, I don't think there are "problems" with either sort of modeling, it's just that, because we are _in fact_ role-based, but _in practice_ sort of status-based, we necessarily wind up with a bit of a blurry abstraction. 

(Of course, our API does not _necessarily_ need to reflect our implementation — we can adapt data in or out of nearly any conceivable structure — we do this _all the time_ with `tags`. I _do_ think we actually _ought_ to have an issue, somewhere, to add `roles` to the users API, though, as otherwise I don't believe there's any way to "read" this info now.)

I am sort of thinking-out-loud here, trying to ground my thought process... but I actually think our situation might make more sense if we think about this more in terms of "verbs" than "nouns".

We want to "make a user 'unlimited'" (against, my kingdom for better words). We _probably_ want this to be idempotent-ish (so: a user that's _already_ "become unlimited" isn't an error, but a no-op).

REST-ish principles would suggest we can move the verb into the HTTP verb pattern, so we potentially have URLs like `/api/users/ID/ROLE` and we POST or DELETE them to set or unset them, in an idempotent-ish way.

I realize that I am maybe _leaning_ in the opposite direction as @Ridhwana here.

(I sort of think we're also likely to want an endpoint where we *swap* roles around. I think it's still conceptual, but this issue seems a bit happy-path focused; our theoretical `tools`-type application _might_ remove "limited" in favor of a not-good-standing role like "suspended" or something?)

Too long summary: I tend to think we'd want to focus on a simple-ish implementation for now, which I think might mean POST / DELETE to `/api/users/ID/limited` to add or remove the "limited" role? (With the idea that this _could_ but not necessarily _would_ allow for other role-changing in the future?)

**Comment by jaw6** [comment]
One other note:

> The API endpoints should only respond to accounts with the admin or moderator role.

So far, I believe our `tools`-type consumer has still only ever used one API token, identifying itself as "a/the admin user", but having some kind of internal authorization system that's entirely separate from `core`'s. 

I haven't exactly big a "fan" of this, but making this new endpoint _also_ work for `moderator` would be a significant divergence from our pattern up-to-now, and I'm skeptical that this is entirely intended?

**Comment by PhilipHow** [comment]
@jaw6 Thanks for your thoughtful response to this - it's helped me learn a lot.

I think we want to continue thinking of our system as a _role_-based system, just with inherent logic that means the addition of one role can mean the automatic addition or removal of another role. I agree for a subset of these valid role combinations, we think (and display them in the UI) as _statuses_ but I don't think this should change our approach. We are trading current and future flexibility here for more complex business logic - which as long as we properly maintain, I think is a good tradeoff.

For that reason, I think we should try to match up with the UI, in we're adding or removing a role (when adding or removing the `limited` status), and some central logic handles the downstream actions from that (adding or removing other roles). This logic should be centralized and used by both the UI and the API if not already. This means API consumers don't need to know valid combinations and can keep their concerns to what action they're trying to do.

I quite like your suggestion for a REST-ish approach, having `/api/users/ID/ROLE` and API consumers POST or DELETE them - that seems to match the UI in the most elegant way.

> I haven't exactly big a "fan" of this, but making this new endpoint also work for moderator would be a significant divergence from our pattern up-to-now, and I'm skeptical that this is entirely intended?

To be honest, I just copied this from the  existing [API documentation for suspend](https://developers.forem.com/api/v1#tag/users/operation/suspendUser) here. I think this is referring to the "super moderator" role, [implemented here](https://github.com/forem/forem/blob/e0a3ff9cbd823199d371be6305ec2c000b0eca5c/app/controllers/concerns/api/users_controller.rb#L26).

**Comment by jaw6** [comment]
> > I haven't exactly big a "fan" of this, but making this new endpoint also work for moderator would be a significant divergence from our pattern up-to-now, and I'm skeptical that this is entirely intended?
> 
> To be honest, I just copied this from the existing [API documentation for suspend](https://developers.forem.com/api/v1#tag/users/operation/suspendUser) here. I think this is referring to the "super moderator" role, [implemented here](https://github.com/forem/forem/blob/e0a3ff9cbd823199d371be6305ec2c000b0eca5c/app/controllers/concerns/api/users_controller.rb#L26).

Ah, you're right. I had been thinking of the _parts_ of the API that we've specifically created for the `forem-tools` service, where we've been [requiring admin](https://github.com/forem/forem/blob/4a8dc9abf6c34d8cebf2b32f79d8ab79900a7a3a/app/controllers/api/v1/billboards_controller.rb#L5), but the user suspension API — which is, in effect, ported over from the old v0 API — does allow an ["elevated user"](https://github.com/forem/forem/blob/e0a3ff9cbd823199d371be6305ec2c000b0eca5c/app/policies/user_policy.rb#L92-L97) to manage `suspended`, and is a closer pattern match for this new endpoint.

:+1:
