### ISSUE TITLE
Custom newsletter onboarding content

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#19987]
## Is this feature related to a problem? Please describe.

- As a new user, I want the option to opt-in to a custom newsletter authored by the Forem operator so I can stay up-to-date with what is happening in the community
- As a Forem operator, I want to maximize my subscribe rates to my newsletter for new users to create new opportunities to keep community members engaged

## Describe the solution you'd like

- After removing the digest opt-in from this onboarding step, we are free to dedicate this step to the custom newsletter opt-in.
- This step will be configurable using Markdown to give ultimate flexibility to the Forem operator.
- The wording on the opt-in checkbox will also be configurable.
- Move the final "Finish" navigation button to the main section of the modal and make it a full-width button.

## Designs

- [Desktop Designs](https://www.figma.com/file/u7VcNG4pjbn7K01V8JrFWo/Member-Onboarding-Process?type=design&node-id=2846-27293&mode=design)
- [Mobile Designs](https://www.figma.com/file/u7VcNG4pjbn7K01V8JrFWo/Member-Onboarding-Process?type=design&node-id=2951-6752&mode=dev)

## Definition of Done

- [ ] Add the following new fields to the configuration in the "Onboarding" section of `/admin/customization/config` for:
  - [ ] "Newsletter onboarding step content", which will be a markdown field that should ideally use an existing markdown processor, but should at least support the following:
    - Headings
    - Paragraphs
    - Images (no need to support image upload)
    - Links
    - Font decoration (bold, italics, underline)
  - There will be no preview for the markdown field.
  -  [ ] "Newsletter opt-in heading" and "Newsletter opt-in subheading", which will be plain text fields
- [ ] On the newsletter onboarding step (the final onboarding step):
    - [ ] Render the configured "Newsletter onboarding step content" markdown, using the full-width of the modal.
    - [ ] Render the configured "Newsletter opt-in heading" in bold at the top of the checkbox opt-in (see designs) and the subheading beneath it.
      - Clicking anywhere on opt-in should activate the checkbox.
    - [ ] Move the finish / continue button to below opt-in
        - When the opt-in is not checked (default), the button text should be "Finish"
        - When the opt-in is checked, the button text should be "Subscribe and Finish"

## Additional Context

* For deployment, we could feature the flag the new onboarding layout to give time to set the configuration.
* For DEV, we hope to configure something similar to the designs using markdown.

**Comment by jaw6** [comment]
@PhilipHow @anujbhavsar96 

Draft PR, using feature flag, focusing on getting the backend of this working right now.

<img width="881" alt="image" src="https://github.com/forem/forem/assets/2077/97918c9c-265a-4bbc-8af7-2799542eb7fd">

It's not _super_ clear where `heading` and `subheading` _actually go_?

---

Now that I am digging around in the code, we are going to have some **issues** with the `Finish` button. There are some assumptions in that "nav" panel that tie the back-arrow, step dots, and that button altogether. Splitting these out into separate areas is likely going to be a _lot_ more work than we anticipated.

Any chance we can focus the scope here on the "custom" part and follow-up later with button design/layout? (Given that we are likely keeping this feature flagged until the custom content is "ready", there's a chance we wouldn't see much _overall_ delay — as those two experiments could potentially even run in parallel?)

**Comment by PhilipHow** [comment]
<img width="708" alt="Screenshot 2023-09-14 at 21 43 30" src="https://github.com/forem/forem/assets/1628871/2d23dc64-7dbb-49a4-b520-2ac02d3c01df">

@jaw6 I've updated the figma to add this. Looking at it "sub-heading" doesn't quite describe the secondary text - but it also doesn't look like body content? Happy for a sensible name to be given.

**Comment by anujbhavsar96** [comment]
@PhilipHow how about we make some change of input field label like below,

_Newsletter onboarding step content_  -> `Newsletter step heading`
It would be good to have description as well with input field just like `Suggested tags`
Description -> `Use this field to set the title and subtitle for your newsletter offering step. Keep it concise.`
 

_Newsletter opt-in heading_ -> `Newsletter checkbox heading`
_Newsletter opt-in subheading_  -> `Newsletter checkbox subheading`

In future, having a preview of this configuration would be good addition.

> I'm happy to descope the button for the time being

I'm also happy with that. Not a dealbreaker.

**Comment by jaw6** [comment]
Settings:
<img width="843" alt="image" src="https://github.com/forem/forem/assets/2077/27d26d87-38f4-4e51-a89c-8ddb378122c9">


Onboarding — the fonts in here feel off to me, but I'm not sure why? Seems like the line-height is weirdly inconsistent or something? Like it's too high for `p` and too short for `h`? @anujbhavsar96 

<img width="809" alt="image" src="https://github.com/forem/forem/assets/2077/eaf8b3a2-df8a-4b1b-b20d-f40179672d0c">


Maybe I've just been staring at it for too long, but something about the copy & design here, it feels like we're pushing the newsletter pretty _hard_? Like, I want to say "calm _down_, onboarding, you don't need to shout at me".

**Comment by anujbhavsar96** [comment]
@jaw6 setting can go like this in the below order,
![Frame 4](https://github.com/forem/forem/assets/84626054/35f4b6e7-e6be-4515-93e7-3dfa6db5dd5c)

> the fonts in here feel off to me, but I'm not sure why? Seems like the line-height is weirdly inconsistent or something? Like it's too high for p and too short for h?

Yes, we will have to alter the line-height here; we can not use the same style as the previous steps here since this is a manual configuration. 

> it feels like we're pushing the newsletter pretty hard?

I think it's because of the line-height and some padding issues.

**Comment by jaw6** [comment]
> except for one thing when there is no configuration from the admin side - the default view should look something like this.

@anujbhavsar96 @mirie We very likely need to change how we approach the design with this component. Compared to most of our content, this is _extremely_ dynamic content. That is to say:

* With a feature flag and a default, there are _at least_ three "modes" this panel can take (enabled & configured, enabled & not-configured, not-enabled).
* With the ability to freely enter markdown, there are _infinite_ "modes" the content of this panel can take. We can't style targets like `h1` or `h2` or whatever — I mean, I _can_ do it, but we can't _rely_ on that _working_ — because there's **zero guarantee** that those nodes will appear in the content.

Specifically, the "rectangle checkbox" is a rather complicated bit of styling, because of the "three modes" and unpredictable contents. (It gets _even more complicated_ if we introduce "half-configured" modes.) Trying to make this component "look right" whether or not there's a "heading" and/or "subheading" is a tricky balancing act.

(We probably _should_ build a "proper component" version of these "rectangle checkboxes", because as Anuj points out, this really _should_ resemble the one [over here](https://github.com/forem/forem/pull/20133), but this is prohibitively difficult at this stage. That other panel is fully preact-rendered, and depends on react mechanisms to work as a checkbox; this panel has a mix of server-side and client-side rendering — because feature-flag is still _only_ accessible server-side — so we can't use those react mechanisms for behaviour.)

I'm trying to get this as close to the designs as we can for now, but it really feels like the way we're going here is a bit backwards. Especially because we're making the content here _extremely configurable_, the better approach for this would be to style _the content_ not the panel.

<img width="837" alt="image" src="https://github.com/forem/forem/assets/2077/62b5ca76-fb08-45d0-88c2-027f297a89ae">

<img width="832" alt="image" src="https://github.com/forem/forem/assets/2077/61c426a0-a43a-4535-8862-aea070de01b9">

**Comment by anujbhavsar96** [comment]
@jaw6, we are super close😌. I tried experimenting myself with CSS and got the expected results _(Not sure if that's the right way, though)_. I hope this [Loom video helps](https://www.loom.com/share/3b29a564b0214886855d34517ed03a43?sid=07d40d86-8704-4408-8d08-82de44413520).

**Comment by jaw6** [comment]
In the Loom, you are mostly editing the definitions of the utility classes — which would have far-ranging consequences that are probably _not_ what you intend — but in this case, it mostly works to change the utility classes being used.

<img width="828" alt="image" src="https://github.com/forem/forem/assets/2077/77f55e46-3ba1-4416-bd38-f316ff80525f">

I think it even works "okay" with unexpected content:

<img width="805" alt="image" src="https://github.com/forem/forem/assets/2077/6ca93bcc-2848-4fe8-a0d8-61f7ffd590f8">

However, there are some issues with "default mode". If I style the one label as you have styled our "heading":

<img width="732" alt="image" src="https://github.com/forem/forem/assets/2077/e6dbffa1-8fc7-40d7-b00b-ed452023ba79">

Without _any_ styling, it's ... weird:

<img width="709" alt="image" src="https://github.com/forem/forem/assets/2077/f975fbcc-ae35-43da-8e5d-d483dbc46f22">

I think it looks okay with _just_ the padding & margins copied over:

<img width="712" alt="image" src="https://github.com/forem/forem/assets/2077/76358199-d4e7-4bcf-9a9d-4aabbecd7baf">

But it's a little better if I style it as a "subheading":

<img width="721" alt="image" src="https://github.com/forem/forem/assets/2077/b4d7b697-457d-4a92-b688-25a633b8089d">

**Comment by anujbhavsar96** [comment]
> In the Loom, you are mostly editing the definitions of the utility classes — which would have far-ranging consequences that are probably not what you intend — but in this case, it mostly works to change the utility classes being used.

I hope it doesn't break anything, but the above changes look great @jaw6 ✨

About the default state - I tried this with the flexbox property and tried to align to the center after removing the top padding for the checkbox. [Checkout this Loom](https://www.loom.com/share/581fbe79235340fb94ccf0432739e31c?sid=98c5f689-2eaf-458e-88e7-edfa8a5c7b63)

> I think it looks okay with just the padding & margins copied over:

This also looks great just that we need to adjust padding-left for that and make `font-weight:600`

**Comment by mirie** [comment]
I took at look at the current state of things on the current PR. Makes sense about fully configured vs not as the two states to support (and not supporting a partially configured state for now). Can we timebox this CSS update for the default state on **this PR** to an hour? I think we can separate any additional styling tweaks and have the bulk of this work merged.

**Comment by anujbhavsar96** [comment]
Sounds good @mirie . Functionality-wise, this is working as expected, and also, from the design-wise, we are super close ✨

You can take a call based on technical feasibility here.
