### ISSUE TITLE
Add hide tag button to `/t/{{tag}}` page

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20022]
## Is this feature related to a problem? Please describe.

You have to go to the `/tags` page to hide a tag at the moment, when you should also be able to hide a tag on the `/t/{{tag}}` page

## Definition of Done

- [ ] Add the hide tag button to the `/t/{{tag}}` page. It should work in the same manner as the button on each of the tags on the `/tags` page

## Additional Context
- Rough mockup: ![image](https://github.com/forem/forem/assets/1628871/0808a84f-bd1e-4888-9f09-4c3ca99453c0)

**Comment by prabal-goyal** [comment]
Is the issue still open? I can give it a try :)

**Comment by PhilipHow** [comment]
@prabal-goyal This issue is marked with `Forem team` meaning this is intended for our internal team to tackle!

Please read through our [contributors guide](https://developers.forem.com/contributing-guide/forem) and look for issues with `Ready for dev` that are available to wider contributors!

**Comment by Ridhwana** [comment]
I think rather than try to implement this through `followButtons.js` it may be useful to further abstract/enhance the [Tag.jsx](https://github.com/forem/forem/blob/10841795795ec79f599a95be6d0a73b196245579/app/javascript/tags/Tag.jsx#L79) preact component to be able to handle a single grouped follow and hide button. 

Ideally in the long run it seems like we could remove the manual DOM manipulation in `followButtons.js` and use Preacts built in state management to manage those States.

**Comment by Ridhwana** [comment]
@dukegreene just wanted to let you know that if you run into any issues on this, I'm happy to pair on it with you.
