### ISSUE TITLE
Sidebar not displayed when we are on /locale/{}

### ISSUE THREAD

**Issue by thomasbnt** [forem/forem#20028]
**Describe the bug**
We can't see the sidebar on https://dev.to/locale/{} 

**To Reproduce**

1. Go to https://dev.to/locale/fr (also work with /en)
2. See the sidebar isn't here

**Expected behavior**

**Screenshots**
![image](https://github.com/forem/forem/assets/14293805/3d534a37-34b1-4ac0-ac57-b85f36af8e53)

**Desktop (please complete the following information):**

- OS, version: Windows 10
- Browser, version: Chrome 116

**Additional context**

**Comment by ktmouk** [comment]
The sidebar probably can be shown by fixing this line, I'm going to fix this.
https://github.com/forem/forem/blob/89b3b8127e7a2ebe23547e8fd6f2be7b9987504d/app/javascript/packs/homePage.jsx#L73

**Comment by dukegreene** [comment]
Thanks for raising this @thomasbnt! Thank for working on a fix, @ktmouk! I appreciate the care and effort taken.

Is this bug still happening on your end? I am currently able to see the right hand sidebar at `/locale/fr` and `/locale/en` when I visit dev.to in Chrome, Safari, and Firefox.

Wondering if you are able to replicate this issue @rt4914, as we are both tagged as reviewers on the linked fix above.

**Comment by ktmouk** [comment]
I've noticed this issue happens only when you are logged-in because when you are not logged-in, the sidebar will be rendered via this erb file below and `renderSidebar` function will not be called due to this [line](https://github.com/forem/forem/blob/89b3b8127e7a2ebe23547e8fd6f2be7b9987504d/app/javascript/packs/homePage.jsx#L94).
https://github.com/forem/forem/blob/18877f6f1b21ff0ceec546695fd7aec9f0d6e4b7/app/views/articles/_sidebar_additional.html.erb

so I think you are able to replicate this issue by accessing a page after logging-in. 😃
