### ISSUE TITLE
Markdown code formatting error

### ISSUE THREAD

**Issue by xaberue** [forem/forem#20369]
**Describe the bug**

Code snippets are wrongly formated,

**To Reproduce**

1. Go to https://dev.to/xaberue/private-fields-with-or-without-underscore-5pl
2. Look at the different code snippets, all of them wrongly formatted.

I have checked the syntax numerous times, also checked in external editors and the markdown seems correct.

**Expected behavior**

That the snippet is correctly formatted, as in other posts.

**Screenshots**
Markdown:
![1](https://github.com/forem/forem/assets/55638917/f7885850-ccf5-44cd-9b6b-bf93ba7126fb)
Formatted:
![2](https://github.com/forem/forem/assets/55638917/f06a0cdf-af91-4e87-825b-97ccda648b32)
Formatted in a different markdown editor (Visual Studio 2022)
![3](https://github.com/forem/forem/assets/55638917/5e617c7c-505e-49cf-8054-d13252290eb1)

The problem is visible both in desktop and mobile.

**Comment by dancristianb** [comment]
Hey @xaberue ! 👋 

I checked the markdown (nice article!) and I think the formatting is broken due to this extra _\`_ character in _i`t's just a ..._

<img width="919" alt="Screenshot 2023-11-27 at 13 39 42" src="https://github.com/forem/forem/assets/32739319/24d1bbb5-9c60-4119-89cc-dc1d5875f4cc">

Can you please try removing that and see if it helps? Thanks!

**Comment by xaberue** [comment]
Hi @dancristianb !!

Many thanks for your support. 

Effectively you are right! This was indeed breaking the formatting.

It's something that you can completely oversee, and the fact of seeing it properly in other tools created me more confusion.

Many thanks!
