### ISSUE TITLE
Improve assigning tag moderators (for admins)

### ISSUE THREAD

**Issue by lightalloy** [forem/forem#20405]
There are a couple of issues related to the users search in /admin.
E.g. when adding a tag moderator on `/admin/content_manager/tags/{id}/edit` page.

1) We are currently searching by the specified string in username, name and email with `ILIKE %string%` (see `Admin::UsersQuery.search_relation`) which often can lead to a large number of search results (e.g. when we search for a short  or popular name/word). We also limit the results to 10, so the actual user we search for may not appear in the results at all.

There is an [additional filtering](https://github.com/forem/forem/blob/473594f1920966cc40d749141d7ca44b740eea78/app/javascript/shared/components/UserStore.js#L27C26-L41) on the frontend which is slightly different (e.g. it's case sensitive, and the search on the backend is case-sensitive), that's why we get less that 10 results.

**Possible solution:**
- make search "stricter", use case-sensitive search and/or use strict matching, not just inclusion of the search string
- search only by username (the label says "enter the username")
- remove filtering on the frontend or change it so that it wouldn't contradict the backend one

**Concern:**

The same code is used in other places: users list (search) in member manager and `/admin/invitations`, so if we make changes we need to make sure that search in those places keeps working as intended.

2) It's not clear what user we select from the search, because we show users `name`, not `username` in the search results. It may be misleading because names are not unique. It may lead to assigning wrong users as tag moderators.

**Solution:** show both names and usernames (or only unuque username) in the search results dropdown.

**Comment by lightalloy** [comment]
I wanted to fix this more or less quickly by making the search "stricter", at least for searching mods, but it seems like the frontend requires more time, especially [`convertUserIdsToUsernameInputs`](https://github.com/forem/forem/blob/473594f1920966cc40d749141d7ca44b740eea78/app/javascript/packs/admin/convertUserIdsToUsernameInputs.js#L4):
- we're loading users on page load (I suppose we don't need it as we do search for autocomplete when admin inputs)
- a lot of "co-authors" references which are not relevant for this file (probably were copy-pasted from `convertCoauthorIdsToUsernameInputs`)
- also, we don't actually convert ids to usernames anymore (?) but rather searching for users (at least in case of searching for users to assign tag mods), so the code needs attention (rewrite/remove unnecessary logic)

**Comment by michael-tharrington** [comment]
Thanks for all this context @lightalloy! 

I just wanted to drop a few thoughts that might be handy...

1. I'd like to link up [a relevant convo we were having in Slack](https://forem-team.slack.com/archives/CAA200SH5/p1708032941720569). I think most of this is covered in your assessment above, but it's a practical example of me trying to add a tag mod and not being able to find them in the list by their username. I do think strict username match would be a good solution. 

2. Notably, when you look at a user's admin page (e.g. https://dev.to/admin/member_manager/users/38578) there are some short directions for adding a user as a tag mod. These incorrectly state that you will need to copy the user's id number. Not really a big deal because I remember the quirks, but ideally this message should be updated. (See pic)

![Screen Shot 2024-02-16 at 9 52 30 AM](https://github.com/forem/forem/assets/16007075/4e689b71-3176-4057-8f58-526b677d5cdb)

3. Lastly, here's [a link to an alternative solution for adding tag mods](https://github.com/forem/forem/discussions/20306) this would happen from the user's admin page & would allow admin to add tags directly to the user vs going to each individual tag page and adding the user's name. I think it would make things much speedier.

**Comment by lightalloy** [comment]
@michael-tharrington 
Yeah, p.2 is outdated (( Unfortunately there is also leftover naming/functionality in the code which makes it harder to modify 😬

So, what I would implement (from what I got from the discussion):

- [ ] quick fix: remove autocomplete/user search from the tag page, instead of it do "input username => assign tag mod role to the user"
- [ ] update the outdated message ("adding tags for moderation is currently only possible") on the user's admin page according to the existing functionality
- [ ] feature: make it possible to assign tag moderator roles on the user's admin page (input tags => assign corresponding roles)

**Comment by michael-tharrington** [comment]
@lightalloy All good on p.2 — I'm nitpicking here, haha. Honestly, it's not been a hassle, I just wanted to mention it because it's connected!

On p.2, the language update I'd suggest would be:
> You can also add tag moderators from [Content Manager > Tags](https://dev.to/admin/content_manager/tags). Search for the tag, click to view it, and you'll see the option to add a moderator by entering their username.

With this updated language, I'm assuming that p3 will be coming somewhat soon and I'm accounting for that update in this language — this is why I say "also"! I'd just collocate this language near the mechanism for adding/removing tags to a user.

I think you've nailed it with your checklist! That said, you could always change the outdated message last if you'd prefer.
