### ISSUE TITLE
Make articles from a user with `spam` role inaccessible

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20452]
## Describe the solution you’d like

- Articles authored by users with the `spam` role, should return in a 404 and not be accessible, when navigated to directly.
  - If quicker to implement, we should prioritize initially making them inaccessible to logged out users (but I assume this provides no implementation efficiency).
  - If quick to implement, it would still be handy if users with the role of `admin` and above, were still able to access these articles (directly only), but this could be handled separately.
- Articles authored by users with the `spam` role, should not show in the feed.
- Articles authored by users with the `spam` role, should not appear in the search.
- Articles authored by users with the `spam` role, should not appear in the digest emails.
- Articles (scheduled ahead of time) by users with the `spam` role,  should not trigger notifications.

## Additional Context

- If we need to take an incremental approach to this issue - then please let me know and we can split these out to seperate issues.
- If there is a way in which we can centralize some of this logic to make downstream effects of hiding spam articles easier, then we should invest in this.

**Comment by lightalloy** [comment]
I did a bit more research on the issue and given that some work was done in #20498 (assign negative score on spammer'a articles). So, I suppose that I'm going to rely on `score` and make sure that articles with negative score don't appear in feeds and search. There are checks like `.where("score >= 0") ` or `with_at_least_home_feed_minimum_score` in some places, but we need to make sure that articles with negative score don't appear somewhere.

I considered unpublishing, but it will make unsuspending harder, and in general seems like misusing `published` field.
Filtering my the author's role explicitly will be inefficient in feeds/search, so is not an optimal solution as well.

**Comment by benhalpern** [comment]
@lightalloy yeah, on a place-by-place basis, sometimes 0 should be the threshold and sometimes minimum feed score. I think it depends on the place.

I actually think we're reasonably well covered in "feed" contexts, but we can seek to find more.

In order to make articles and users with spam role less accessible, I think one move would be to `404` the landing pages (at least for signed out) — this would ensure that.

In general I think we should avoid using _unpublishing_, and instead modify score and call `not_found` on the landing page themselves. Therefore if we need to remove the `spam` role things effectively go back to where they were without having to manage a bunch of complicated state — we try and make everything flow down-hill from the `spam` role being present.

Maybe it makes sense to add downstream logic little by little in small PRs so that you can make a judgment call as needed and we can evaluate a change in the PR itself?

**Comment by PhilipHow** [comment]
@lightalloy I think creating the PR for the 404 is the right next step. In general we want to minimize the chance of someone clicking a link elsewhere in the product to get a 404 page, but I think we're likely covered here and would only have edge cases remaining.

**Comment by lightalloy** [comment]
So, I found out that articles with negative score can be displayed on pages like top by timeframe (`/top/week`, `/top/month`) and tag pages by timeframe: (`/t/tagname/top/year`). 
It's not very likely for them to appear on dev.to because of the large number of articles, though possible, especially on tag pages with less popular tags. 
So I would add a threshold there. Latest has a `-20` threshold https://github.com/forem/forem/blob/1c25171cc693e67612bc22e704bc66b6daf8e1ef/app/controllers/stories/tagged_articles_controller.rb#L86 (other timeframes don't have one).
So, we could use -20 (or zero) as a threshold for those pages.

**Comment by benhalpern** [comment]
Yeah @lightalloy that makes sense
