### ISSUE TITLE
Embed GitHub Code

### ISSUE THREAD

**Issue by johnpapa** [forem/forem#2046]
I tried to embed a few lines of code in a post from github. It did not work, but would be cool if it did.

This would be the expected format, I think

{% github https://github.com/johnpapa/vscode-peacock/blob/master/.vscodeignore#L12-L17 %}

**Comment by rhymes** [comment]
Yeah, currently the GitHub tag only supports issues, pull requests and the readme, not arbitrary code: https://github.com/thepracticaldev/dev.to/blob/be8e139e3e744779a161d3ac48e343a6f9569458/app/liquid_tags/github_tag.rb#L18-L27

**Comment by colorfusion** [comment]
May I work on this? This seems like a very helpful feature to have for the page.

**Comment by rhymes** [comment]
@colorfusion sure, go ahead and thanks!

**Comment by colorfusion** [comment]
Just checking, I have to write the rendering of the code in html from scratch right?
I assume there is no way to piggy back existing markdown triple back tick code snippet, to recreate something similar to github's way of rendering code snippet.

**Comment by rhymes** [comment]
@colorfusion if you look at the existing github liquid tag code you'll see the rendering is done with HTML re-creating the look and feel:

https://github.com/thepracticaldev/dev.to/blob/master/app/views/liquids/_github_issue.html.erb
https://github.com/thepracticaldev/dev.to/blob/master/app/assets/stylesheets/ltags/GithubTag.scss

https://github.com/thepracticaldev/dev.to/blob/master/app/views/liquids/_github_readme.html.erb
https://github.com/thepracticaldev/dev.to/blob/master/app/assets/stylesheets/ltags/GithubReadmeTag.scss

I'm pinging @Zhao-Andy because he's more familiar than I am with liquid tags but I believe there's no magic to it all right now

**Comment by colorfusion** [comment]
Those are great reference for me to start off from, thanks!
It's okay if I split the feature into sub-tasks and have PRs for each of them right?
I plan to get the code rendering up first, before I take a look at syntax highlighting.

**Comment by Zhao-Andy** [comment]
> It's okay if I split the feature into sub-tasks and have PRs for each of them right?

That works! We'll need an MVP that works of course, but I think extra features like syntax highlighting can go in a different version / PR.

Our codeblocks have syntax highlighting via the [Rouge gem](https://github.com/rouge-ruby/rouge), so if you wanted to borrow those styles and render that, then render it like so:
https://github.com/thepracticaldev/dev.to/blob/e0287a574c3a07a9bc65fa39e08f587443202a56/app/labor/markdown_parser.rb#L13

**Comment by colorfusion** [comment]
Will do. Thanks a lot! 🎉

**Comment by colorfusion** [comment]
@rhymes Sorry for taking so long with this feature. I'm done with the PR, so could you take a look at it?

**Comment by henrikwirth** [comment]
This feature would be super helpful. Also It would be great to be able to show the whole file like:

{% github https://github.com/johnpapa/vscode-peacock/blob/master/.vscodeignore %}

There is already this issue: #4757

I'm just wondering if it would make sense to implement that in the same PR.

**Comment by colorfusion** [comment]
@henrikwirth Yeah, I agree, showing the whole file does sound like a great idea. it is probably easy for me to implement that into the PR as well, since the code retrieves the whole file to begin with. My only concerns so far with the proposal are the following:
- File types that can / cannot be embed, what's a good way to determine them, without too much code maintenance (some form of whitelist maybe?).
- Handling files that has a large number of lines (truncate / wrap around an internal frame if it exceeds a predefined number of lines?)

**Comment by henrikwirth** [comment]
> - File types that can / cannot be embed, what's a good way to determine them, without too much code maintenance (some form of whitelist maybe?). 
> - Handling files that has a large number of lines (truncate / wrap around an internal frame if it exceeds a predefined number of lines?)

Shouldn't it be the same for gist embeds, which are implemented already?

Also one thing that would be nice, is to pass down the code highlighting. So the default highlighting could derive from the file-ending like `.js`, but sometimes you would rather want highlighting to be for `jsx` instead.

**Comment by colorfusion** [comment]
I believe that the two features work differently. The gist embeds basically takes in the link and generates a `<script>` tag link based on github's embed gist, which will run the script to generate the gist correctly. This PR reads the file from the github repo using the API, and displays a small snippet of it based on the line number input. 

Adding custom code highlighting sounds like a great idea too, to be able to define the highlighting in some situations. That can probably be in another PR, if this one takes off.

**Comment by cmgorton** [comment]
We support gist now:

_GitHub Gist Embed
All you need is the gist link:

{% gist https://gist.github.com/CristinaSolana/1885435 %}
Single File Embed
You can choose to embed a single gist file.
{% gist https://gist.github.com/CristinaSolana/1885435 file=gistfile1.md %}

Specific Version Embed
You can choose to embed a specific version of a gist file. All you need the link and the commit hash for that specific version.
The format is {% gist [gist-link]/[commit-hash] %}
e.g.
{% gist https://gist.github.com/suntong/3a31faf8129d3d7a380122d5a6d48ff6/f77d01e82defbf736ebf4879a812cf9c916a9252 %}

Specific Version File Embed
You can choose to embed a specific version of a gist file. All you need the link, the filename and the commit hash for that specific version .
The format is {% gist [gist-link]/[commit-hash] file=[filename] %}
e.g.
{% gist https://gist.github.com/suntong/3a31faf8129d3d7a380122d5a6d48ff6/f77d01e82defbf736ebf4879a812cf9c916a9252 file=Images.tmpl %}_
