### ISSUE TITLE
Make comments from a user with `spam` role inaccessible

### ISSUE THREAD

**Issue by PhilipHow** [forem/forem#20472]
## Describe the solution you’d like

- Comments from users with the `spam` role, should not be visible on the article page.
  - If a comment from a user with a `spam` role has no replies, then the comment itself will not be visible.
  - If a comment from a user with `spam` role has replies, the comment itself will appear as it has been deleted (using the existing UI element).

**Comment by lightalloy** [comment]
Spammers' commens are currently assigned a low score (implemented in #20498) . I assume that we can hide comments based on their score (even if the score was assigned not by adding `spam` role to the author).

Currently we have message "Comment marked as low quality/non-constructive by the community. "  for such comments. Is it ok to replace this with "deleted" (in case the comment has children)? Or should we distinguish "low score comments" and "low score comments by spammers" (for me it doesn't make much sense). But maybe we should decide whether to hide or not based on a comment's score (e.g -100..0 => display "marked as low quality", `< 100` => hide).

**Comment by benhalpern** [comment]
Hey! I jumped on a small adjustment because we were seeing an uptick in spam commentary the past day:

https://github.com/forem/forem/pull/20534

But @lightalloy I think a good additional visibility indicator would be what you are sort of proposing.

Currently comments which are negative, we hide _from logged out_, but what about adjusting that logic so we still hide all negative when logged out, but additionally hide comments below `-50` _for all users_, including _signed in_. Does that work?

**Comment by PhilipHow** [comment]
> @PhilipHow Should we also 404 if visiting a low score comment page directly (if there are no children)? 

Yup, we should definitely do this.

**Comment by lightalloy** [comment]
If we keep `-75` there will be no purpose of "low quality marker" because we hide such comments anyway, so it won't be displayed. If we use `-50`, "low quality marker" will be displayed for comments with score from `-50` to `-75` , but that complicates logic + there shouldn't be many comments in this range. So I would either keep `-75` and remove "low quality marker" or widen the range for comments with the marker. @benhalpern what are your thoughts?

**Comment by lightalloy** [comment]
I have impelemented hiding comments on articles pages with score below `-75`. We also need to implement:
- 404 on direct comment path (or "deleted" if it has children)
- hide comments below threshold on articles comments page
- hide comments on user profile page

**Comment by lightalloy** [comment]
Closing as done, adjustments in separate issues.
