### ISSUE TITLE
adding a "read" button to notification

### ISSUE THREAD

**Issue by erikyuzwa** [forem/forem#2048]
**Is your feature request related to a problem? Please describe.**
It's not "frustrating", but I don't know how to remove a notification in my list. I only see the heart and the "save" button. Clicking on the article doesn't remove it from the notification list either (at least for me).

**Describe the solution you'd like**
It would be nice to have an "x" or a "read" button to just acknowledge the notification and make it disappear.

**Describe alternatives you've considered**
I've refreshed the page while on the notifications, and I've read an article linked from a notification. Both actions don't remove any notification.

**Additional context**

**Comment by jessleenyc** [comment]
Thanks for the request. Right now new notifications are highlighted in a different color while older notifications are not highlighted. I know Twitter also follows this pattern but there are certainly other platforms that give you the option to clear your notification list completely. We'll give this some thought.

**Comment by erikyuzwa** [comment]
thanks @jessleenyc - I realize it's likely quite a low priority, but much appreciated 🙇

**Comment by cmgorton** [comment]
Hello! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
