### ISSUE TITLE
Changing the title of an article leads me to a search page

### ISSUE THREAD

**Issue by kay-is** [forem/forem#2068]
**Describe the bug**
I created a new article and saved it. Then I wanted to change the title and it got me to a page with the title "Search Results - Dev Community" that showed users, while **the URL still includes the old title**.

**To Reproduce**

1. Create a new article
2. Save it
3. Change the title
4. Save it
5. End up at the search results page

**Expected behavior**
To get a new URL and end up in the editor again.

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser: Firefox
- Version: 65.0.1 (64-Bit)

**Comment by rhymes** [comment]
I think this is due to the fact that the slug is created only once and never updated (which in theory makes sense):

https://github.com/thepracticaldev/dev.to/blob/f93af16fbe99a83d5fd3e74bd7ffa3a2532ae6b4/app/models/article.rb#L49

which calls

https://github.com/thepracticaldev/dev.to/blob/f93af16fbe99a83d5fd3e74bd7ffa3a2532ae6b4/app/models/article.rb#L511-L517

which calls the following two methods in order

https://github.com/thepracticaldev/dev.to/blob/f93af16fbe99a83d5fd3e74bd7ffa3a2532ae6b4/app/models/article.rb#L519-L522

https://github.com/thepracticaldev/dev.to/blob/f93af16fbe99a83d5fd3e74bd7ffa3a2532ae6b4/app/models/article.rb#L559-L561

**Comment by edisonywh** [comment]
@rhymes slightly unrelated, but I noticed that when my friend shared me a draft post, it generated a non-final slug (it includes `temp-slug`), and when he finally publishes the post, the old link does not work anymore.

Now looking at the code you just posted it is apparent that this is probably intended, but I'm curious if there's a reason behind that? Why is the `temp-slug` _needed_?

**Comment by rhymes** [comment]
> @rhymes slightly unrelated, but I noticed that when my friend shared me a draft post, it generated a non-final slug (it includes `temp-slug`), and when he finally publishes the post, the old link does not work anymore.
> 
> Now looking at the code you just posted it is apparent that this is probably intended, but I'm curious if there's a reason behind that? Why is the `temp-slug` _needed_?

I don't know the exact reason, probably @benhalpern knows the details. If I were to guess I'd say it's to obfuscate the temporary URL

**Comment by Zhao-Andy** [comment]
Hey @kay-is, could you email yo@dev.to with a link to the post that's giving you this issue?

Also, it might be related to this client side error I've had: https://github.com/thepracticaldev/dev.to/issues/1206

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
