### ISSUE TITLE
Feature Request: Access my posts via ssh&git

### ISSUE THREAD

**Issue by c33s** [forem/forem#220]
# _TASK or Feature_
### Request or User Story
i fear that this is out of scope of this awesome community, but maybe you like the idea. on gitlab you can every repo can have a wiki, the wiki can be edited via the normal webinterface but the wiki is a normal git repo so you also can simply clone the wiki repo locally and edit it, push it back or somewhere else.

it would be soooo awesome if i would be able to access my posts like ths. it also would make #219 obsolete

**Comment by Zhao-Andy** [comment]
Hey @c33s, thanks for the feature request! Also backlogging this for now.

**Comment by bennypowers** [comment]
One possible implementation could have a user post a git repo url (with access token in the case of private repos on gitlab, github, or bitbucket), which would either periodically sync, or use webhooks to fetch commits on push.

Alternatively, dev.to could host a remote, which users could push to from their own repos.

```bash
git push dev.to master
```

which, I have to say, would be *wicked cool*

dev.to could either host the repos on its own servers, or set up a self-hosted gitlab cluster that uses a combination of dev.to endpoints and gitlab webhooks to handle synchronization.

**Comment by bennypowers** [comment]
Is this still on the radar? I'd like to hear some thoughts from the maintainers on feature design WRT the backend

**Comment by benhalpern** [comment]
We're making progress on this via the API

**Comment by c33s** [comment]
unstale

@benhalpern well this request is not really about accessing posts via api but via git

**Comment by abraham** [comment]
This sounds like a fun feature but a huge amount of work to implement with a lot of dangerous areas. E.g. what happens if a user has 1000 posts, rebases and force pushes.

**Comment by c33s** [comment]
@abraham  then all posts are gone. compare it with "what happens if i have a production repo of a very important source code, rebase and force push" or "what happens if i do `rm -rf /`"

**Comment by abraham** [comment]
I'm not talking about the loss of data, I'm talking about the impact to the DEV service. There are huge potential side effects that could bring down the entire site.

**Comment by rhymes** [comment]
@c33s on a technical side of things, how would you retrieve posts via git? The data is inside a DB. Would this mean embedding a git server as a sidecar of the webserver? Would it mean synchronizing the DB somehow with a git repo?

It really sounds complicated and it would probably be easier if it were something built on top of the API when is published. 

`DEV API <=== GIT SERVER <===> client`

Would this be something like you envision? A git client pulling/pushing to a git server that uses the API to operate on the user's articles? Not sure this is easy either...

**Comment by suntong** [comment]
> a huge amount of work to implement with a lot of dangerous areas

then maybe we should simplify the whole thing just like what codesandbox is doing, or even simpler than that -- 

- blog has a back end git. 
- each post is a file in git. 
- use can do whatever edit they like on dev.to, when they are satisfied, they can make a commit to the back end git. via provided interface from web GUI, just like what codesandbox is doing.

> The data is inside a DB... Would it mean synchronizing the DB somehow with a git repo?

- when user making a commit to the back end git. via provided interface from web GUI,
- regenerate/dump those posts from DB that last modification time is later than last git push time. 
- git add, commit & push. 

I think it's pretty straightforward. Maybe I've missed something. 

Further, since dev.to has already authenticated via github, using github git repo would be a natural choice, and not asking too much from the users, if they opt-in for it.

**Comment by suntong** [comment]
Until then (when dev.to posts are backed up to git), I'm not feeling comfortable start using it...

**Comment by jeikabu** [comment]
Not to resurrect a dead horse, but some variation of this would be good.

As it is, it's easy to publish to Github Pages (or Gitlab, or whatever) and then update/correct content with a simple push.  When using "Publishing from RSS" there's no sane way to update content on dev.to; posts are simply out of date.  There's obvious caveats, particularly the fact that dev.to and other sites might use different libraries to render markdown.  But, I have more faith in my ability to maintain git branches and propagate changes than my ability to manually make changes via web interfaces.

**Comment by cmgorton** [comment]
Hey all! This post originally had some good traction but seems to have a lot of pieces to it that would benefit from more discussion. 

Since this one stale for a while I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!

**Comment by c33s** [comment]
think it is really uncool to close all the issues here and move the discussion to forem.dev. if you prefer to also have a discussion on forem.dev at least crosslink it and don't close everything on github.

**Comment by cmgorton** [comment]
Hey Julian. I’m sorry for the inconvenience. This issue is currently over 2 years old. Because we had over 800 open issues, I have been closing older issues that have had little traction for a few months now to maintain the health of the project here. 

 One hard thing about feature requests is it is usually a yes or no and because it is an issue as a maintainer you have to close it. With over 700 issues currently in the project older feature requests are often lost or forgotten.  

To help with this, the team wanted to have a place for the community to discuss their issues or feature requests if they still felt they were useful. That way we could give them more visibility and highlight them to potential contributors.  We can still link this issue to any post in form.dev and if someone wants to contribute to it we can reopen the issue here. 
Thanks again for your contributions here. I am happy to discuss any other concerns you have.

**Comment by c33s** [comment]
@cmgorton only because nobody implemented a feature the feature request is still valid. from UX view i only can give you the feedback it is not a good UX. 

if you keep the issues here it is simpe: "i stayed subscibed here until it is done or get fully rejected". 

if you would migrate all the issues to forem.dev (where i personally don't see any benefit) the UX would not be as good as if it stayed here but at least i would have a direct link to the new discussion area (don't really understand what there is to discuss. allow to access my content on dev.to via git/ssh is quite clear). 

to close it without even a link where the discussion is ongoing is, for me personally, not a good way to go. btw your link is broken https://github.com/forem/forem/issues/forem.dev

with your move you force the persons who are subscribed here to create an account on forem.dev and configure it to follow a simply thing - when the feature is implemented.

communities like github and gitlab are made for developers. git access to the repos and to the wiki (gitlab, don't know about github), full api access, good header in emails (like X-GitHub-Sender: ..., X-GitHub-Recipient: c33s, X-GitHub-Reason: push) to easily filter and folder them. you take that all away just for... hmm for what exactly? yes i am a pro-decentralized internet and i really disliked that microsoft bought github. also against staying here speaks this article: https://karl-voit.at/2020/10/23/avoid-web-forums/)

but still i think closing legit issues just to discuss it in a forum is the wrong move, especially when the new forum doesn't have the same features as github. 

your move to close the issues here is really sad.

**Comment by c33s** [comment]
the linked post does not make it any better. if you want to bring tech and non tech people together, my suggestion would be to sync the comments between github and the forum and not to kill easy tech communication on github (like commenting via emai) without providing at least a subset of the existing featureset (you can't even simply vote on features as it is still not possible to see who gives you a heart, what i requested in a different issue here).

but well i give up. i even think about dropping dev.to (i know nobody would care, i just share my thoughts), because i thought dev.to was made for developers. i have choosen dev.to because i was looking for a blog system made for developers (markdown first, easy access via cli, api). some of the features i was looking for where already there, other features like this one where missing. 
 with the move you show that many tech things i would love to see in dev.to wont happen. so maybe gitlab or github pages are the better location for a tech blog :(
