### ISSUE TITLE
Inline code with double backslash becomes single if it is part of nested bullet list

### ISSUE THREAD

**Issue by learnbyexample** [forem/forem#2288]
**Describe the bug**

Double backslash inside code blocks in nested listing results in single backslash instead of two.

**To Reproduce**

From any post/comment, try these non-nested and nested bullet lists:

```
* foo
* use `\\1`, `\\2`, etc

---

* foo
    * baz
* use `\\1`, `\\2`, etc
```

**Expected behavior**

Double backslash shouldn't become single, as shown below for GitHub markdown rendering:

* foo
    * baz
* use `\\1`, `\\2`, etc

**Screenshots**

Screenshot for above non-nested (correctly rendering) and nested list (incorrect):

![nested_bullet_double_backslash](https://user-images.githubusercontent.com/17766317/55397518-088c1700-5564-11e9-8203-50386f196e05.png)

Not sure if this is related to: https://github.com/thepracticaldev/dev.to/issues/960

**Comment by danascheider** [comment]
I'm happy to pick issue up if it's still one the maintainers want done.

**Comment by rhymes** [comment]
@danascheider please go ahead and thank you! I'm going to assign the issue to you

**Comment by danascheider** [comment]
It appears this bug is in the Redcarpet gem, not in dev.to code. I've submitted an issue report against Redcarpet to ask if they'd accept a PR. Unfortunately, the last commit merged on Redcarpet was almost a year ago, and the last time a maintainer responded to an issue report or merged a PR was in January of 2019. The most recent commit to the repository was when version 3.5.0 was released back in July. So basically, there's nothing more I can do with this issue on this codebase unless either (1) the maintainers of Redcarpet accept a PR and release a new version or (2) we want to switch to a different library. Point (2) would probably not be a bad idea if the library we're using isn't being actively maintained anymore, especially since properly escaping HTML is pretty important for security.

So that's where we're at with this - please just let me know how you'd like me to proceed. I'm happy to make a Redcarpet PR in the unlikely event the maintainers respond to my issue report soon, and I could also take on at least some of the work if you want to instead switch to a different library.

**Comment by cmgorton** [comment]
Thanks for taking this up and investigating Dana. As this issue looks like it will be blocked for some time I am going to go a head and close it. If the Redcarpet maintainers address the issue in their gem we can open this back up!
