### ISSUE TITLE
Landing pages for series

### ISSUE THREAD

**Issue by desirottman** [forem/forem#2424]
**Describe the solution you'd like**
It would be cool if series posts could have a landing page where all posts in the series displayed. It could look like the main feed, with just those series posts, and the [individual posts themselves](https://dev.to/aspittel/moving-past-tutorials-receiving-a-problem-to-solve-2hf8) could have the series name clickable - in that example, the **Part of "moving past tutorials" series** text would link to the feed of series posts.

**Comment by davefollett** [comment]
I really like this feature request.  I kinda did this on accident by inventing my own tag (I did this before the series feature was added):

https://dev.to/t/anewvueonjs30

But I think your suggestion is a much better option because the landing page could have more features to it.  Perhaps cover art for each post or other things.

**Comment by jessleenyc** [comment]
Hey! Just want to leave a comment here that we've updated the design of series where you can see more info on the other posts within the series in each post. Here's an example of it in action: https://dev.to/devteam/daily-challenge-43-boardgame-fight-resolver-53e3

**Comment by jessleenyc** [comment]
Some additional notes/thoughts on a series landing page: https://github.com/thepracticaldev/dev.to/issues/3772

**Comment by benhalpern** [comment]
I think the route for this could be `dev.to/ben/series/:slug`

The "series" thing is actually a `collection` in the application (with the idea that there could be different "types" of collections, that may or may not ever happen).

But I think creating a landing page with the same format as tags and other index views should be fairly straightforward.

`CollectionsController` `show` is probably the place to put this, and then follow similar view structure as tags, etc.

**Comment by michaellee** [comment]
Hey everyone! I think it would be cool if we could also "follow" or "subscribe" to a series. I could see this happening on either the new series UI that show up on posts or if the series page gets pushed out, a button showing up on there.

This way when new series are published they can pop up in notifications.

**Comment by AlbertoPdRF** [comment]
I would be interested in working on this feature if the plan is still to have it!

**Comment by seangwright** [comment]
@AlbertoPdRF, that would be awesome!

My blog post series is at 25 posts now 🤣 and I'd love a landing page for it to promote it on social media!

**Comment by rhymes** [comment]
@AlbertoPdRF please go ahead! :D Do you have a plan? 

I'd imagine we need the following parts:

- routes and controllers to access each series
- a index and a show page, the index page lists the user's series(es ahaha) and the show page lists the article's belonging to such page
- a link to the series overview from the single article page
- a UI

I don't think we need edit/update as they'll eventually be managed in the dashboard.

It'll then be linked from the dashboard when https://github.com/thepracticaldev/dev.to/issues/6938 is completed

cc @ludwiczakpawel @lisasy in case they have ideas on how this should/can look like or if we're missing some features in the plan

**Comment by AlbertoPdRF** [comment]
I don't have a plan yet, but what you said sounds good to me :smiley: Based on that, I'll try to come up with something and then we can discuss it more in depth.

**Comment by ludwiczakpawel** [comment]
I'm happy to jump in and help with UI and frontend whenever the backend part is ready :) Just let me know!

**Comment by AlbertoPdRF** [comment]
I have a few questions/issues/comments:

1. Right now, collections are created with only the slug (which is actually more like a title, more on this on point 2) and the user. I think that it would be very useful for this feature to fill more attributes on creation, which could be inherited from the first article of the collection until a way to directly create and/or edit collections exists. What do you think?
2. As with articles, probably having a `path` attribute on the collections table is the way to go in order to provide links for them, but one problem is that the slug that collections have right now actually look like titles (i.e. `A series` instead of `a-series-andSomeRandomChars`). Converting current slugs to "real" slugs shouldn't be so difficult, but the problem is to not break all the functionality that already exists. How would you recommend approaching this?
3. This one is probably a dumb question, but I can't really get what's wrong: if I create an action on a controller (e.g. `index` on the `CollectionsController`) and a route for it (e.g. `/series`), why do I get the not found error page when navigating to the route? In other words, what am I missing? :slightly_smiling_face:
4. Is it ok to create only very simple `.html.erb` pages for this feature on the first iteration?

I think that's all for now :stuck_out_tongue:

**Comment by rhymes** [comment]
Hi @AlbertoPdRF!

1. I think we should add attributes as needed, unless we come up with attributes we actually need now I think we should postpone this
2. we could use [parameterize](https://api.rubyonrails.org/classes/String.html#method-i-parameterize) to create a slug:

```ruby
[7] pry(main)> cx.slug
=> "A series"
[8] pry(main)> cx.slug.parameterize
=> "a-series"
```

this way the path could be something like `/series/rhymes/a-series` I think

3. can you share some code? Or a draft PR?

4. Definitely, I don't think we need JS much :D

**Comment by AlbertoPdRF** [comment]
Thanks for the clarifications, @rhymes!

1. Gotcha!
2. I didn't know that method, it's neat!
3. It was a mistake on my side 😅
4. Perfect!
