### ISSUE TITLE
Incorrect date on post

### ISSUE THREAD

**Issue by shindakun** [forem/forem#2433]
**Describe the bug**

I ended up posting a bit later in the date then I usually do and noticed that even though it's 7:26 PM Saturday, April 13, 2019 (PDT) the date on my new post is April 14th. Timezones are a pain and *I think this ruins my posting streak*. :( (Let's a switch to Swatch internet time!). 

**To Reproduce**

1. Create a post after 7 PM PST.
2. Note that it is listed as the following day.

![Screen Shot 2019-04-13 at 7 18 06 PM](https://user-images.githubusercontent.com/319128/56087477-26d5fa80-5e21-11e9-94ff-91549c29b72b.png)

**Expected behavior**

I haven't looked into the code but I suppose saving new posts in UTC and displaying in the browsers local time would be a solution but that would need moment.js or something so.

**Screenshots**

![clock punch](https://media.giphy.com/media/Lo7XJ4DjHjkOs/giphy.gif)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 73.0.3683.75 (Official Build) (64-bit)

**Comment by rhymes** [comment]
Good idea @shindakun, I just now realized that this can happen also on comments.

With https://github.com/thepracticaldev/dev.to/pull/1970 a verbose timestamp localized for the user has been added when the user hovers the date in comments, but the actual "Apr 13" / "Apr 14" can still happen as you described. So the feature is not complete. I'm going to open a ticket for that too :D

Both, localizing the short date and displaying a full localized datetime on hover, should be taken into consideration for implementation for posts.

**Comment by Zhao-Andy** [comment]
Thanks for flagging this!

**Comment by benhalpern** [comment]
I think having the UTC timezone across the site is a better outcome than if we do some localized, some not.

Let's remember that we cache whole pages, so the initial render being localized date is a bit easier said than done. So when we do stuff like that right now it needs to be done on the client side. In terms of how we could localize _on initial page load_ instead of via JavaScript:

Fastly provides some tools for some of this stuff:

https://docs.fastly.com/vcl/date-and-time/

It's less clear how you go about doing the HTML swap at the edge, it would have something to do with ESI:

https://docs.fastly.com/guides/performance-tuning/using-edge-side-includes

Of course, doing it in JS might be best as well, if we were consistent about it. That's how we're doing themes right now, for example.

**Comment by rhymes** [comment]
@benhalpern what do you think about this approach? it's only on comments, not on posts because it was easier to test but if it's deemed valid we could do something similar for article dates https://github.com/thepracticaldev/dev.to/pull/2437

**Comment by danisaza** [comment]
Hi folks 👋🏽

I experienced this same issue last night. Here's a description and screenshot.

At risk of stating the obvious, this did not have a big negative impact on my experience using the site.

---

Last night (March 30th), I opened dev.to at around 10:45pm and noticed that one of the posts in my feed said that it had been written in the future (March 31st).

It was about 10:45pm CT on March 30th for me. (I'm based out of Chicago)

I was using Chrome and was not browsing with a VPN turned on.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/6345764/78038135-179dd480-7332-11ea-8b79-6c7a893ab75d.png)

**Comment by mstruve** [comment]
In #9285 we recently added a local_date helper to ensure that article published timestamps were shown in locale time and not server time. I then also applied this to our article partials https://github.com/forem/forem/pull/11028. Between the 2 PRs I believe this solves our timezone issues so I am going to close this out. 

@shindakun and @danisaza please let us know if you continue to see this behavior and reopen this issue! Thank you for being a part of the Forem community!!!
