### ISSUE TITLE
Add developer documentation about the JavaScript frontend

### ISSUE THREAD

**Issue by rhymes** [forem/forem#2507]
**Is your feature request related to a problem? Please describe.**

On the heels of [Thoughts on migrating to TypeScript and improving the overall quality of the frontend DEV codebase](https://dev.to/ben/thoughts-on-migrating-to-typescript-and-improving-the-overall-quality-of-the-frontend-dev-codebase-1121), [DEV Notes: Don't Forget To Clear Cache!](https://dev.to/jess/dev-notes-don-t-forget-to-clear-cache-962) and https://github.com/thepracticaldev/dev.to/issues/2499 I thought it'd be nice and useful if there was some kind of overview of how the frontend pieces (especially the JavaScript layer) all fit together.

I know there are two sets of JS code bases, the "legacy" in [app/assets/javascripts](https://github.com/thepracticaldev/dev.to/tree/master/app/assets/javascripts) managed by Rails's sprockets and the one in [app/javascript](https://github.com/thepracticaldev/dev.to/tree/master/app/javascript) managed by webpack.

Other than that I'm not sure how everything works (I admit I haven't spent much time in the frontend, other than the occasional bug fix or small feature). 

A few questions that a `docs/frontend/javascript.md` might answer:

* How does initialization work?
* Is the Preact layer totally ignorant of the vanilla JS layer?
* Do the two JS code bases interact with/call each other?
* How are they attached to the template pages? Does each webpage serves two sets of packed/minified JS files? 
* What does the service worker do in the context of dev.to? Is it registered on the whole page? Is there more than one?
* How does edge caching fit in all of this? 
* How does instant click fit in all of this?

Plus anything else deemed important. It doesn't have to be super in depth, just a treasure map to know what does what and how everything fits together. 

**Describe the solution you'd like**

A documentation file that contains a description of how the JS frontend works

**Describe alternatives you've considered**

I haven't considered alternatives TBH, the status quo is okay, it's just going to be easier for contributors if there's some onboarding documentation about the code base, especially if the goal is to refactor it, modernize it or even adapt with TypeScript or other solutions.

**Comment by rhymes** [comment]
I'm pinging @Link2Twenty, @nickytonline and @venarius because I'm sure they'll have, being more familiar with the frontend than I, POVs to contribute. I'm not pinging anyone directly from the core team because, well... they'll see the ticket anyway :D 

LET'S DOCUMENT ALL THE THINGS 😂

**Comment by nickytonline** [comment]
@rhymes, I'll write something up maybe tonight, but definitely this week.

**Comment by venarius** [comment]
Documentation sounds great! I could add some more infos to the documentation from @nickytonline when he adds it and theres something to add. But I currently don't know that much about the frontend parts as I am currently just starting to get into it 🙂

**Comment by maestromac** [comment]
Nice write up @rhymes ! We could take this time to also review our thought process on the use of our various JS codes.

**Comment by jessleenyc** [comment]
@aspittel and I were just talking about this! Thanks for the issue @rhymes!!

**Comment by nickytonline** [comment]
I've started writing a post about this because it'll help me do a brain barf, but also, I'm hoping people can fill in holes as I'm not on the core team and also hopefully have community members ask questions. I'll try to answer most of your questions @rhymes in the post to the best of my knowledge.

**Comment by omenking** [comment]
I have found afterwards documentation did exist for some things but being able to discover that information was more work than me just coding in workarounds. The main README needs some formatting love.


Maybe already answered but just writing out what I recall looking at the codebase

### How does initialization work?

`app/assets/javascripts/initializers` look straight forward in that `initializePage.js` is included likely in the `application.js` via the `//= require_tree .`

When the dom is considered ready it just loads the initializers files linearly.

### Is the Preact layer totally ignorant of the vanilla JS layer?

#### Webpacker and Preact

As far as I can tell yes. Preact uses webpacker and generates out its own pack. Each pack is then included within erb partials when the functionality is required.

#### Sprockets and VanillaJS

The vanilla js appears to be being delivered by sprockets.


### Do the two JS code bases interact with/call each other?

This appears a repeat of the question above, I would say no, they do not talk to each other.

### How are they attached to the template pages? Does each webpage serves two sets of packed/minified JS files?

One is delivered through sprockets so, and the other is packaged by webpacker.
I would expect sprockets bundled js to be included in the layouts, the webpacker packs appear to be included conditionally when needed within partials.

### What does the service worker do in the context of dev.to? Is it registered on the whole page? Is there more than one?

 I'm guessing this is referring to what we normally see in react-like apps and this would be for `Progressive Web App (PWA)` functionality.

This chunk of code could imply notifications, I see things in the service worker to pre-cache emoji and other assets.
```
self.addEventListener('install', onInstall);
self.addEventListener('activate', onActivate);
self.addEventListener('fetch', onFetch);
self.addEventListener('push', onPush);
self.addEventListener('notificationclick', onNotificationClick)
```

### How does edge caching fit in all of this?

I'm thinking this has to do with Fastly the CDN being utilized. 

### How does instant click fit in all of this?

InstantClick uses javascript to determine the intent to look at the next page and start loading it so that if a user clicks through that page will load faster.

**Comment by omenking** [comment]
I installed the gitdocs gem with a bit of pain due to native extensions and it wasn't loading gitdocs as expected, maybe its using the node library `gitdocs` so will give that a go.

**Comment by rhymes** [comment]
> Maybe already answered but just writing out what I recall looking at the codebase

Hey @omenking thanks for the answers, my questions were more a brain dump of possible starting points to write an overview documentation than anything else. I'm sure there's stuff I forgot to "ask" 

BTW @nickytonline also contributed some info that could become part of the "how the frontend works" docs: https://dev.to/nickytonline/dev-to-s-frontend-a-brain-dump-in-one-act-7mg

> I installed the gitdocs gem

What's gitdocs?

**Comment by omenking** [comment]
Getting GitDocs organized today:

<img width="284" alt="Screen Shot 2019-04-28 at 11 36 53 AM" src="https://user-images.githubusercontent.com/7776/56866674-f73efa80-69a9-11e9-83c3-2a91e5379956.png">

@rhymes  https://github.com/timberio/gitdocs

**Comment by omenking** [comment]
Its coming along
<img width="321" alt="Screen Shot 2019-04-28 at 12 44 44 PM" src="https://user-images.githubusercontent.com/7776/56867464-6ec55780-69b3-11e9-8738-f03646b5c0cb.png">

**Comment by nickytonline** [comment]
The only other main thing I can think about in the frontend for documentation would be our usage of service workers. I will add this once I've done some of the service worker stuff I've been tasked with. After that, this is probably good to close.

**Comment by mstruve** [comment]
@nickytonline looks like we talk a bit about service workers in `docs/backend/internationalization.md` but I am thinking it might be worth it to close this and add a separate issue just to document service workers. Might be more approachable for a contributor to pickup.
