### ISSUE TITLE
Classified listings UI: add color coding of listing titles and selector buttons

### ISSUE THREAD

**Issue by rhymes** [forem/forem#2586]
**Is your feature request related to a problem? Please describe.**

I was thinking that it would be nice and easier to scan if the various classified listings were color coded and maybe even their relative "category" button had the same color.

Mine it's obviously an example, I'm not advocating for this color scheme, just the general idea of using a color coded system

**Describe the solution you'd like**

Something like this:

![Screenshot_2019-04-27 Listings(1)](https://user-images.githubusercontent.com/146201/56840491-1e051000-6888-11e9-93b1-ae5ef0e0f6f1.png)

**Comment by jessleenyc** [comment]
I really like this idea!

**Comment by rhymes** [comment]
> I really like this idea!

Maybe something in tune with the color scheme of the [offline page](https://dev.to/offline) ?

![Screenshot_2019-04-30 Looks like you've lost your Internet connection](https://user-images.githubusercontent.com/146201/56947908-d358f180-6b2e-11e9-9d3a-2c57b2952ed4.png)

**Comment by rhymes** [comment]
@benhalpern cool :-)

ps. I don't know how you did it but you commented from the future 😂

![Screenshot_2019-05-08 Classified listings UI add color coding of listing titles and selector buttons · Issue #2586 · thepra](https://user-images.githubusercontent.com/146201/57383581-5a513e00-71af-11e9-9858-7aa548fea901.png)

**Comment by benhalpern** [comment]
Nice!!

I think we should sit on this a bit, in terms of the final details and implications, but big yes. This is great. Let's finalize something next week.

**Comment by rhymes** [comment]
not stale (?)

**Comment by lisasy** [comment]
@rhymes I'd love to have you reframe this proposal of the user problem it is attempting to solve, and why you think this type of solution is most appropriate for it :) 

If I were to work backwards, I imagine the framing being something along the lines of:

### User problem 
People currently find it difficult to easy scan and sort through the times of listings they see. 

### Proposed solution
Sort the listings based on color in the listings + with the tag filters.

---

My thoughts:
1. I think that with the recent update to the Listings page overall with Crayons, we've attempted to improve the scannability altogether with updating the layout (left sidebar nav + 2 column content).
2. The solution to categorize by color might be a bit distracting, and another approach/question I have is: do we have _too_ many different types of filters in the menu? What if condensing these text labels and having fewer, more intentional filters help with organizing this view?

**Comment by rhymes** [comment]
@lisasy I agree with you. Actually my proposal was to add colors just for visual eye candy. It also doesn't hold up with the recent restructure of listings as you mentioned.

I'm closing this and I thank you for taking the time to think about this!
