### ISSUE TITLE
More easily reachable night mode button

### ISSUE THREAD

**Issue by itsjzt** [forem/forem#2961]
**Is your feature request related to a problem? Please describe.**
I frequently shift between Night mode and normal mode, and I need to go through 3 pages to just change this setting

**Describe the solution you'd like**
It would be nice if we can have a night mode toggle in the top navbar

**Describe alternatives you've considered**
Alternatively I mostly switch between dark mode in evenings and night, so we can also think of an automatic mode that changes according to time, like twitter's

**Additional context**

**Comment by cmgorton** [comment]
Hey @itsjzt thanks for the feature request. 
There is a current active discussion around this topic on issue [#5431](https://github.com/forem/forem/issues/5431). Since the discussion is active there and this appears to cover the same topic I am going to go ahead and close this issue. Thanks again for starting this discussion and feel free to add any more thoughts you have on this feature in the above linked issue.
