### ISSUE TITLE
Add i18n to support other languages

### ISSUE THREAD

**Issue by mikaoelitiana** [forem/forem#304]
### Description
dev.to is a great community for developer but today it's only available to english speaking users as far as I know. It would be great to have i18n and be able to deploy a dev.to version for other language speaking communities. 

### Definition of Done
Users can deploy a non english version of dev.top

**Comment by benhalpern** [comment]
I agree. We've been a little paralyzed by the implementation details, and how this would be done with regards to our CDN-driven approach.

Basically, most content is delivered cached at the edge, as opposed to re-computed from the origin, so we need to make sure i18n plays nicely. I know it's not that hard, but we need to make sure we do this in a way that plays nicely with our architecture.

So let's start the conversation!

**Comment by joeberetta** [comment]
@benhalpern I propose to introduce certain rules of translation, [as did the Microsoft development team](https://github.com/Microsoft/Localization/wiki/How-to-Contribute-to-docs.microsoft.com), for example

**Comment by chrisvasqm** [comment]
I can help with the spanish translations 🤓

**Comment by MatheusRV** [comment]
How about implement https://github.com/projectfluent/fluent to i18n? I could help implement that.

**Comment by jessleenyc** [comment]
@benhalpern bumping this for you. What do you think of fluent?

**Comment by finkiki** [comment]
Could be nice to support other languages. I can help with french.

**Comment by murtezayesil** [comment]
I would like to help with the Turkish translation :smiley:

**Comment by champi-dev** [comment]
I'd love to implement the translations using an i18n library,
injecting those strings into the views/components,
we may find ways to do cool things with translations.

**Comment by rabbishuki** [comment]
I'd be happy to help with the hebrew translations

**Comment by 0xC000005** [comment]
I would like to help with the Mandarin translation.  😉

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](https://github.com/forem/forem#community) for many of these feature requests that we need more discussion around. Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](https://forem.dev/). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
