### ISSUE TITLE
Editing content should be consistent throughout the site

### ISSUE THREAD

**Issue by rylandg** [forem/forem#3152]
**Is your feature request related to a problem? Please describe.**
Both posts and comments on posts are editable, but direct messages between users are not. Regardless of preference (twitter style of no editing or slack of edit everything), the UX should be consistent throughout the site.

**Describe the solution you'd like**
Make direct messages editable (keep history if worried about abuse).

**Describe alternatives you've considered**
Technically you could make comments uneditable because it would be consistent. Please don't do that though.

**Comment by Zhao-Andy** [comment]
Thanks for the issue @rylandg. We'll discuss this as a team and come back to this.

**Comment by rylandg** [comment]
@Zhao-Andy Of course, thanks for taking the time to think it over!

**Comment by cmgorton** [comment]
Thanks for the feature request.  It looks like DMs are editable now. 
![Showing edit button on DMs](https://user-images.githubusercontent.com/21039864/100759338-1d165780-33b6-11eb-9d66-58f270df245c.png)

Since we are working on cleaning up stale issues and I think this one is actually fixed I am going to go a head and close this.
