### ISSUE TITLE
ActivityPub support

### ISSUE THREAD

**Issue by rugk** [forem/forem#317]
### User Story / Description

As a user of Dev.io/Mastodon/Peertube/…, I want a federated web, where I can follow anyone on any instance of a "social network" (or similar), because it is what the web is like/should be and is a usability improvement.

For this to work, you should try to add ActivityPub support, as this is the new standardized federation protocol. See:
* https://activitypub.rocks/
* https://en.wikipedia.org/wiki/ActivityPub
* https://blog.joinmastodon.org/2018/06/why-activitypub-is-the-future/

### Definition of Done

* ActivityPub support implemented
* Sharing stuff to other networks work.
* You can follow other user's on other instances.
* Maybe more(?).

**Comment by michaelgv** [comment]
It would be nice, as the posts could be synced over to fediverse, but it begs the question, if someone interacts on the fediverse, should Dev's platform automatically insert that reaction, or should it leave that door closed? If we go with the former, it's a tad bit of work to get it properly implemented, and effectively it's "shadow" accounts; syncing could be become a very bad nightmare quickly.

**Comment by benhalpern** [comment]
I'm in favor of this sort of thing. In the past I've looked into this but didn't come away with specific product inspiration. @michaelgv's questions are definitely where my head goes. We'd have to do this the right way.

So I'm very excited by this and I think it could be really fun to work out as a community, but I think there are a lot of conceptual details to hammer out.

So let's commit to this as an ongoing discussion.

**Comment by ortegacmanuel** [comment]
@benhalpern thanks for your reply. Recently [Write.as added support to ActivityPub](https://discuss.write.as/t/activitypub-support/64). They added a basic implementation as described in the next list 

- Finding Write.as blogs by name from within Mastodon, e.g. @blog@write.as for write.as/blog/ or blog.writeas.com 4
- Following Write.as blogs
- Getting blog posts in your home stream / on your instance’s federated timeline
- Favoriting posts (nothing happens on our end – we consider it a private bookmark)
- Boosting posts

I think that it as a good first step foward on adding support to ActivityPub, just enabling broadcasting of Dev.to content across Federated Web using ActivityPub.

I'm now exploring the Deb.to codebase in order to see how this could be easily added and happy to be part of that ongoing discussion.

**Comment by rugk** [comment]
No bot, keep it open. :smiley:

**Comment by zcdunn** [comment]
[Prismo](https://prismo.news) is a link-sharing application (think reddit, hacker news, lobsters) that federates over ActivityPub. It's also written in Ruby and the developer is working on extracting the AP support into a library. Anybody interested in this issue could jump over to [his repo](https://gitlab.com/prismosuite/activitypub-rails/) and help out there to provide an easy path for dev.to to integrate AP

**Comment by maestromac** [comment]
not stale

**Comment by aschrijver** [comment]
**FYI**: I just [described a vision](https://meta.discourse.org/t/132624/40?u=aschrijver) for Discourse as-if it were built from the ground up with federation support, called **"Community has no boundary"** and which turn Discourse from a stand-alone product into Discourse-as-a-Fabric. It may be inspiring to **forem** to consider these possibilities too. Also adopting a compatible federation design would allow `forem <----> discourse` community integration.

**Comment by resynth1943** [comment]
Thanks, A! :heart: I put out a [post](https://mastodon.tedomum.net/@resynth1943/105467385328376766) on my Mastodon, so hopefully this gets picked up soon. Would love for dev.to to interact with an interconnected network of over 4 million people. This would do *wonders* for the JS community on Mastodon, too :heart: 

Will be keeping my Eagle Eye :tm: on this issue.
