### ISSUE TITLE
Addition of dev.to tags in meta tag

### ISSUE THREAD

**Issue by Bhupesh-V** [forem/forem#3181]
**Additional context**

Including `article:tag` in the meta information will be a good idea for SEO
I have seen that dev.to has already a `og:type` tag.
```html
<meta property="og:type" content="article">
``` 
So adding to this could be a good idea.
freecodecamp also has a `article:tag`
```html
<meta property="article:tag" content="Angular">
```
Taking it further `article:author` could also be added.

**Comment by Bhupesh-V** [comment]
I would like to contribute, can someone point me towards the required files.
I checked [docs.dev.to](https://docs.dev.to), not much info there

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
