### ISSUE TITLE
Feature request: List added tag guidelines in the editor

### ISSUE THREAD

**Issue by Avalander** [forem/forem#3216]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I've noticed that some tags get misused a lot. Especially the `discuss` tag seems to be used as a wildcard for all sorts of topics. Since the guidelines are only visible in the tag page, I suspect a lot of users don't even know that they exist.

**Describe the solution you'd like**
Maybe it would be good to display the guidelines for the tags added to the post in the editor view, with a warning that tags not adhering to the guidelines may be removed.

**Describe alternatives you've considered**

**Additional context**
![Screenshot_20190618_104322](https://user-images.githubusercontent.com/9766906/59666840-ef375600-91b5-11e9-9c71-e7e7eb0c739e.png)

**Comment by jessleenyc** [comment]
I really like this idea but if someone is adding four tags, the area could get really cluttered with instructions. I do think a note that your tag could be removed would be nice to have on the editor, maybe it could link out to more specific information on how to check tag rules.

**Comment by Avalander** [comment]
You make a good point! What if the guidelines where collapsed by default and could be expanded? Although maybe that would make too much clutter anyway.

**Comment by maestromac** [comment]
What if the guideline's content change based on user's cursor?

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
