### ISSUE TITLE
Reported "recent reactions" don't make sense

### ISSUE THREAD

**Issue by rylandg** [forem/forem#3225]
**Describe the bug**
My notification window will sometimes say "90" people recently reacted, only to then see "70" people recently reacted a few minutes later. This is very confusing and doesn't add value to the experience.

**To Reproduce**
Get a lot of reactions on a post. Watch updates in notification window.

**Expected behavior**
I'm assuming this is implemented with a rolling window for the notification metrics. That's completely valid but maybe the notification window could show the timeframe of the recent reactions.

"70 people reacted in the last X minutes" OR just show total reactions!

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome

**Comment by Zhao-Andy** [comment]
Thanks for the report. I think the reaction notifications could use another look in general.

**Comment by mstruve** [comment]
Hey @rylandg! We have recently overhauled our notification setup and design. Given this is an older issue and has not been reported since I am going to assume it has been fixed and close this out. If you see this problem again, please do not hesitate to open this back up!!! Thank you so much for being a part of the Forem community!
