### ISSUE TITLE
Image upload elements get lost at certain browser scales

### ISSUE THREAD

**Issue by rylandg** [forem/forem#3226]
**Describe the bug**
When the horizontal size of the Dev.to window is scaled down, the "image" buttons can get lost and the window must be resized to recover them.

**To Reproduce**
1. Edit a post.
2. Narrow your browser window horizontally while watching the image button in the editor pane
3. Wait until it disappears

**Expected behavior**
Buttons don't go on spiritual journeys outside of the browser.

**Screenshots**
Before

<img width="757" alt="Screen Shot 2019-06-18 at 9 24 45 AM" src="https://user-images.githubusercontent.com/27736122/59701673-f9a02280-91aa-11e9-8d11-9c9a839734de.png">

After

<img width="664" alt="Screen Shot 2019-06-18 at 9 23 26 AM" src="https://user-images.githubusercontent.com/27736122/59701585-cb224780-91aa-11e9-8997-46abd95f1111.png">

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome
- Version: 74.0.3729.169

**Comment by mazentouati** [comment]
On smaller screen sizes they jump to the button of the editor to give space. Are they gone there too ?

**Comment by rylandg** [comment]
@mazentouati you found them! I still think it should be addressed because I would have never found that myself + it's still impractical.

**Comment by mazentouati** [comment]
@rylandg Indeed, it's not intuitive. This may be an issue for users who never used the version 1 of the editor. Probably, it has been made that way because you usually add images as you write your article. However, it's not very practical when editing like your case.
I think it's impractical on both mobile & desktop versions, desktop users have to scroll up each time they need to upload an image while mobile users have to scroll down for that goal 🤷‍♂️

**Comment by rylandg** [comment]
Perfectly summarized +1

**Comment by ludwiczakpawel** [comment]
Fixed.
