### ISSUE TITLE
Profile overflowing issue

### ISSUE THREAD

**Issue by K-Sato1995** [forem/forem#3253]
**Describe the bug**

When a user puts too much info in his/her profile, it gets covered up. It should be scrollable or something.

Kind of hard to explain with words but I think it's easy to understand what I'm trying to say from the screenshot.

**To Reproduce**

1. Check her profile 

https://dev.to/mollynem

**Expected behavior**
All the info should be readable.

**Screenshots**

![image](https://user-images.githubusercontent.com/32632542/59889471-81826880-9407-11e9-9634-2f1e70c707a6.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by maestromac** [comment]
Thank you for this issue @K-Sato1995 . That happens when user max out their infos. A more responsive CSS could fix the issue but if it doesn't, we'll have to further limit character count for those fields.

**Comment by michaellee** [comment]
I saw this issue as well. @maestromac are there any design decisions regarding keeping the height limited and overflow hidden on desktop? On mobile width, it seems the height restriction is removed and all the content is viewable. Just wasn't sure if this was intentional?

Would love to contribute to patching this up, just would like some context in seeing if the solution I have in mind is the correct fix.

**Comment by uyouthe** [comment]
same here

**Comment by theomelo** [comment]
Is there work left here? From the discussions on the PR merged, it seems that it was agreed that the original issue was fixed?
