### ISSUE TITLE
Gold star for comments

### ISSUE THREAD

**Issue by zeddotes** [forem/forem#3380]
Why
- It's good to reward someone for an awesome comment.
- Filtering by gold sometimes makes it easier to find a solution faster.
- Revenue could be used for charitable causes.

Alternate
Maybe not "gold" per say, but some way to reward to a comment would be a nice feature to have.

**Comment by Glennmen** [comment]
How would this be different than giving a "heart"?

**Comment by edisonywh** [comment]
I think OP is suggesting to actually sell Gold, just like Reddit does?

**Comment by jessleenyc** [comment]
@zeddotes can you clarify what you mean here?

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
