### ISSUE TITLE
Easy way to include tags in dev.to posts

### ISSUE THREAD

**Issue by suntong** [forem/forem#3393]
**Is your feature request related to a problem? Please describe.**

With dev.to trying to incorporate other media into its own, including gist, twitter, or even youtube, is there any easy way to link to its own tags in dev.to posts? Like for #question and #help, etc, we still need to go the whole nine-yard to use the md syntac for links, right? 

    [#question](https://dev.to/t/question)

**Describe the solution you'd like**

The same approach we links to youtube or comments in dev.to (`{% devcomment cl50 %}
`), e.g., 

    {% devtag question %}

**Describe alternatives you've considered**

This request is different from that of, 

    {% tag question %}

which shows up as a pop-out block. I just want a inline link, where I can say, for e.g.

    You can use either {% devtag question %} or {% devtag help %} tags to ask questions.

Or anything else, as long as we don't need to spell out it twice like this:

    [#question](https://dev.to/t/question)

**Comment by cmgorton** [comment]
Hey thanks so much for opening this issue. We have been doing a lot of work on keyboard shortcuts and think this kind of feature would be better served as a shortcut rather than a new liquid tag when we have finalized some of the shortcuts. Since that is the case I am going to go a head and close this issue.

**Comment by suntong** [comment]
Would it be possible for you quickly summarize the proposed solution to the issue please @cmgorton?

**Comment by rhymes** [comment]
@suntong we're currently working on overhauling the keyboard shortcuts management system, this will allow us to attach shortcuts and keyboard combinations more easily around the website and eventually get to a keyboard shorcut modal. We think this would be better addressed by a shortcut that adds `[#question](https://dev.to/t/question)` inline instead of a dedicated liquid tag.

For reference on the work that's being done: https://github.com/forem/forem/pull/10468, https://github.com/forem/forem/pull/10713, https://github.com/forem/forem/issues/5023, https://github.com/forem/forem/pull/11017, https://github.com/forem/forem/pull/11014 and related conversations
