### ISSUE TITLE
GitLab URL does not allow self-hosted GitLab instances

### ISSUE THREAD

**Issue by TekGadgt** [forem/forem#3418]
**Is your feature request related to a problem? Please describe.**
In setting up my account, I realized that the GitLab URL field does not allow anything outside of gitlab.com URLs.  I have a self-hosted installation alongside my portfolio (which takes up my Website url field) and so cannot link to it on my profile.

**Describe the solution you'd like**
Either remove URL validation tied specifically to gitlab.com for the field, or find a new way to validate the URL (GitLab API call?)

**Describe alternatives you've considered**
The two above are the only options I can think of to allow other URLs outside of gitlab.com, the second being the only option that could validate a URL as being associated with GitLab.

**Additional context**
GitLab CE can be installed manually or through systems like the DigitalOcean Marketplace and, while not heavily used for personal scenarios, is definitely a viable option.  I might even suggest changing the field to something like "Alternative Git Management System", "Alternative Repo Management System", or similar, and allow URLs for Gitea installations to be linked as well.

**Comment by TekGadgt** [comment]
**What Happens**
![What Happens](https://user-images.githubusercontent.com/3054491/60841447-d95af680-a19f-11e9-8cc5-1c91192abc27.png)
![What Happens 2](https://user-images.githubusercontent.com/3054491/60841585-29d25400-a1a0-11e9-9897-a0101bc49dbb.png)

**Comment by TekGadgt** [comment]
I have looked further into using API for install validation.  Unfortunately, GitLab does not even allow a version API request without authentication, however Gitea does, as can be seen here: https://try.gitea.io/api/v1/version.  Just more to think about.

**Comment by jessleenyc** [comment]
We ran into a similar issue with Mastodon URLs and ended up removing the validation altogether. It would be ideal if we could create a general tool that could validate links. We welcome any additional thoughts here..hesitant about removing the validation here because we don't want arbitrary links.

**Comment by TekGadgt** [comment]
Could require base level authentication for people that want to share their self-hosted GitLab.  Enough to access the API version call.  Could be temp stored for initial validation.  Just a thought, looking through GitLab API docs, doesn't look like their is much available to the public.

**Comment by TekGadgt** [comment]
So, it's hacky, but could be a place to start.  GITLABURL/api/v4/projects will return any public projects that are there to anyone that calls it.  This could technically be used for validation, but I could see issues arise if someone has no public projects.  Could require an OAUTH token to be made and submitted alongside the URL in order to ping /api/v4/version, but not sure what other security risks might be involved for the owner of the GitLab install.  Perhaps if, as mentioned above, an OAUTH token is generated for initial validation, stored until validation completes, then wipes, that would work.  Then self-hosted GitLab and Gitea could be distinguished by whether or not an OAUTH token was submitted as well (since, as mentioned above Gitea's /api/v1/version responds without auth).

Sorry if that was all over the place.  Was writing as I was reading.  Basically the options I have found:
*Either keep a single field with a dropdown to specify GitLab/Gitea   OR
*Two separate fields, one for each, for those odd cases where someone has both.

*For validation of GitLab, either ping /api/v4/projects (potentially problematic, e.g. no public projects or an extremely large number of projects) or require an OAUTH token to be submitted alongside the URL in order to ping /api/v4/version.
*For validation of Gitea, simply ping /api/v1/version.

**Comment by victorbordo** [comment]
Solid approach to handle Mastodon link validation with a domain whitelist. I'm thinking through different ways to handle self-hosted GitLab and other arbitrary links. 

> It would be ideal if we could create a general tool that could validate links.

What types of generic validations do you see as useful here @jessleenyc?

**Comment by tcg** [comment]
I was a little curious about a related issue, and found myself here. Offering perhaps an alternative solution...? 

If a person is self-hosting GitLab, it *might* be *conceivable* that Dev.to wouldn't consider that "a GitLab URL", but rather something like "Your Code Repo URL" -- which could be a generic, unvalidated URL similar to the "Your Website" URL. 

Why? 

- Why make the assumption to limit folks to point to repos at Github/Gitlab? 
- It allows them to have a "website" and a "place where my public code lives", that are arbitrary. 
- It removes any development obligation (and code rot) to keeping up with the validity of a given URL for a specific service. 

Downsides? 

- If it is a Github, Gitlab, etc, URL it's harder to associate a nice little icon with that. (However, other services do this by inspecting the URL on render, and having a list of icons that match URL patterns, so that's an idea). 
- Some folks will want multiple. But if folks aren't complaining about not having multiple "website" URLs, maybe they won't complain about not getting multiple repo URLs. (I'm *not* advocating removing the Gitlab/Github ones tho, so maybe that covers a large case). 
- Others I'm sure. 

--- 

In my case, I thought it was really weird that I couldn't add a GitHub link, since the site supported Sign In With GitHub. I discovered that if I used that, it would *implicitly* add that link. But that seemed strange to me. 🤷‍♂

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
