### ISSUE TITLE
Customize the page layout through admin panel

### ISSUE THREAD

**Issue by damechen** [forem/forem#3457]
**Is your feature request related to a problem? Please describe.**
Right now, the page layout is hardcoded. Let's say if I want to add a new tag in the right side bar, I have to change the code. Instead, can we do so through the admin panel?

**Describe the solution you'd like**
Customize the page layout in admin panel.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by jessleenyc** [comment]
This makes sense to me, similarly to how we have an admin tool for the sidebar when we want to put up doodles.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
