### ISSUE TITLE
Make liquid tags a ruby gem

### ISSUE THREAD

**Issue by deepu105** [forem/forem#3491]
**Is your feature request related to a problem? Please describe.**

I'm planning to set up a Jekyll blog and crosspost everything to Dev.to, I currently wrote some stubs for the Dev.to custom Liquid tags. But it would be nice if those tags are published as a ruby gem that can be used in any Jekyll project. It would help a lot of people who are crossposting to Dev from Jekyll blogs

**Describe the solution you'd like**
Extract the custom tags into a separate OSS repo and publish as a ruby gem

**Describe alternatives you've considered**
Creating my own stubs, but they are not a scalable solution

**Comment by shushugah** [comment]
I'd be happy to work on this, but am having trouble finding an example of existing liquid plugins used with rails. There are a few dependencies of this gem, namely it works with `rails`, `liquid` and `nokogiri`.  See my open PR's below

**Comment by rhymes** [comment]
Hi @deepu105 - I think it's a good idea in general, but I'm not 100% sure that in the current state it could be easily done, in part for what @shushugah noticed (they are coupled with the Rails app and some of them even use models and data inside the DEV app) and also because they should be subject to review to make sure there are no security or data leaks.

Anyhow, there's a discussion somewhere to be had before the code :)

If I were to test the feasibility of this idea I'd start a new [gem project](https://guides.rubygems.org/make-your-own-gem/), choose a tag that doesn't depend from DEV data layer, add the dependencies that are required and then find a way to make it configurable, so that if it's imported in any app there's an easy way to do that. 

Some ideas: errors should be customized, it should play well with existing Rails apps, you'd have to decide a minimum supported Rails version, find a way to specify any potentially needed API keys and so on. Some depends on JavaScript scripts included in the HTML and some even with JS injected at runtime I guess.

Only at the end one could change dev.to's source code by adding the gem (which now contains one functioning tag), removing the externalized tag and see that everything works. Then repeat from there.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
