### ISSUE TITLE
Live Streaming / Self serve broadcasting for Orgs

### ISSUE THREAD

**Issue by spboyer** [forem/forem#3538]
See: https://github.com/thepracticaldev/dev.to/pull/2591

Would like to have the live stream/self serve abilities for organizations as well.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
