### ISSUE TITLE
Embedding SVG does not work. Neither attaching SVG file ("unsupported format")

### ISSUE THREAD

**Issue by alex-jitbit** [forem/forem#3574]
**Describe the bug**

Embedding `<svg>` tag does not work, the markdown engine does not see it as HTML.

Attaching (uploading) as external .svg file does not work either, it complains about "invalid format".

**To Reproduce**

Paste some `<svg>` code into V1 editor.

**Comment by jessleenyc** [comment]
We don't currently support SVGs because of security concerns. We could potentially support the upload of SVGs if we converted them to another format or if we could serve them through Cloudinary in a safe way.

**Comment by pavelloz** [comment]
What is the security concern?

**Comment by pavelloz** [comment]
I was just thinking... embedding SVG is a security concern, how about `<img src="x.svg" />` ?

Like this:

![My SVG](https://uploads.prod01.oregon.platform-os.com/instances/1/assets/images/use-cases/recording-terminal/pos-cli.svg?updated=1585304029)


If github does it, i presume it is not especially dangerous.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
