### ISSUE TITLE
Logic for Reading Podcast RSS Occasionally May Miss New Episodes

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#3580]
**Describe the bug**

A podcast host recently reported that their podcast on DEV wasn't updating with the newest episodes.

After a deeper look, we realized the episodes in their RSS are sorted from oldest to newest ones, so the latest are at the bottom. Our current logic is to fetch all the episodes when a podcast is created and then check the "latest" 5 every hour. We assume the latest podcasts to be the top ones (as it generally is this way for most of the podcasts).

Thus, our logic isn't accounting for times when a user's RSS may be ordered differently.

**Expected behavior**

A show's episodes should stay up to date regardless of how articles are ordered in the RSS.

**Additional context**

This user mentioned possibly using the date tags to sort this out.

**Comment by mynar7** [comment]
Hi, I'm the podcast host that originally reported this issue.

Here's a link to our [feed](https://techjr.dev/rss.xml) (We're currently working on listing items latest-first)

We generate our RSS through markdown files that eventually get parsed through this [RSS npm package](https://www.npmjs.com/package/rss).

We haven't had issues with any other podcast platforms that consume our feed. [Spotify](https://open.spotify.com/show/4jFt5Yjfs1jmimj52S2Wve), [google](https://playmusic.app.goo.gl/?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&apn=com.google.android.music&link=https://play.google.com/music/m/Iqm76lldc555i6v2taar7d4fd3a?t%3DTech_Jr%26pcampaignid%3DMKT-na-all-co-pr-mu-pod-16), and [iTunes](https://podcasts.apple.com/us/podcast/tech-jr/id1465115096) all list new episodes from our feed.

However on dev.to, no additional episodes beyond episode 6 were being listed. After speaking with @michael-tharrington, we determined that because my feed listed items out of order, Dev's algorithm for checking feeds was not detecting new episodes.

Internally in our build process, there was no sorting mechanism in place for ordering the items in the RSS feed, despite other popular RSS providers like libsyn sorting items chronologically. I've made some PRs to the npm package we use to generate our feed to correctly sort based on date.

However, I have not been able to find any spec or standard for RSS that states feed items must be chronological or latest-first. I assume that the major aggregators check the feeds for `pubDate` and `guid` tags to determine if there are new items present.

**Comment by vaidehijoshi** [comment]
@cmgorton As we discussed in our recent planning meeting, this one product issue is a good one for someone in the community and/or our MLH fellow; leaving a note of it here!

**Comment by cmgorton** [comment]
I added it to their project board. Thanks.

**Comment by Miguel-Enrique13** [comment]
@cmgorton - Could you assign me to this issue
