### ISSUE TITLE
Ability to quickly save posts that appear in "More from ..." or "Trending on DEV" side panels

### ISSUE THREAD

**Issue by msarit** [forem/forem#3590]
**Is your feature request related to a problem? Please describe.**
While browsing Dev.To, I would like to be able to quickly save articles that appear under _"More from @author"_ or _"Trending on DEV"_ side panels. Currently, to do this, I need to actually click on the article first - but I'd rather not leave the article I'm reading.

**Describe the solution you'd like**
I propose having a "Save" icon appear on the margin of the article card, maybe after I've hovered on it for a second or so. This icon would disappear if I stop hovering on the article card. Clicking on this icon would save that article.

**Describe alternatives you've considered**
Maybe have an excerpt of the article pop up in a modal, with the save icon present in the modal? This approach seems a bit intrusive to me though.

**Additional context**
Here is a visual representation of my proposed solution:

![my-devto-issue](https://user-images.githubusercontent.com/32520970/62228151-225f2e80-b38b-11e9-91af-cbfb4df0e508.png)

**Comment by cmgorton** [comment]
Hey! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
