### ISSUE TITLE
When we change theme, we have to refresh the page to update

### ISSUE THREAD

**Issue by mbackermann** [forem/forem#3613]
**Describe the bug**

When we go to settings and change the theme options and save it, we have to refresh the page so the changes can take place.

**To Reproduce**

Go to settings -> change the theme and save

**Expected behavior**

When we save and the page get refreshed, it should already update your preferences

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome 
- Version: 75.0

**Comment by Link2Twenty** [comment]
This will be a lot easier to fix when #2154 is done.

It should just be a bit of JS changing all the css variables.
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties#Values_in_JavaScript

**Comment by shilpi230** [comment]
@rhymes I would like to take this up. Thanks!

**Comment by rhymes** [comment]
@shilpi230 yes, thank you!

**Comment by citizen428** [comment]
@shilpi230 When you fix this, please also take a look at `UsersController#update`, where we specifically set a flash message telling the user to reload the page after the updated their theme:

```ruby
      if config_changed?
        notice = "Your config has been updated. Refresh to see all changes."
      end
```

The `config_changed?` method doesn't have the best name and can be found in the same file:

```ruby
  def config_changed?
    params[:user].include?(:config_theme)
  end
```

If manual refreshes after theme changes are no longer necessary, both the check and the predicate method can be removed.

**Comment by shilpi230** [comment]
Sure @citizen428 Thanks!

**Comment by shilpi230** [comment]
@citizen428 @rhymes The issue over here right now is, to load the user's selected theme we are getting it from localStorage. Which resets when we refresh the page. To solve this we will need to reset the localStorage explicitly.

**Comment by cmgorton** [comment]
Thank you for opening this request.
Since this has been open for awhile without much progress lately I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
