### ISSUE TITLE
Reward for lots of followers

### ISSUE THREAD

**Issue by axtens** [forem/forem#3639]
I must confess I was not expecting to pick up many followers. The fact that I have over 1000 now is mind-boggling. 

How about a badge for follower-milestones? And not just for me -- make sure to backdate them for everyone. 1000, 2500, 5000, 10000 followers etc. 

Play on writers' desire for significance and fame. ;)

**Comment by jessleenyc** [comment]
Hey! Thanks for the request. We don't show your follower/following count on profiles so I'm not sure we'd want a badge like this. Happy to keep the issue open to invite more discussion.

**Comment by Clarity-89** [comment]
Hi @jessleenyc was just wondering about this. Do you hide the followers count on profiles intentionally? What was the reasoning for it? Not turning dev.to into a popularity contest is my first guess, not sure if I'm right tho :)

**Comment by jessleenyc** [comment]
@Clarity-89 exactly -- we don't really want people to feel judged for how many followers they do/do not have here.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
