### ISSUE TITLE
Replace randomized calls with distributed throttling

### ISSUE THREAD

**Issue by rhymes** [forem/forem#3649]
**Is your feature request related to a problem? Please describe.**

Across the code base we use [Kernel#rand](https://rubyapi.org/2.6/o/kernel#method-i-rand) to limit some function calls that we don't need to execute on every single invocation of the logic they are in.

Examples where we use `rand()` to limit calls:

- updating analytics
- updating ads data
- updating page views
- updating reaction counts
- sending notification emails
- force fetching RSS feeds

The issue with using `rand()` is twofold:

- rand runs inside a single thread, which means that the sampling doesn't take into account any other parallel paths (other threads in the same process, other processes on the same server or other instances of the web server)
- rand makes the code hard to test and potentially makes parallel testing harder

**Describe the solution you'd like**

If you look closely at what `rand()` accomplishes you'll notice that it's effectively a rate limiter. We are used to think of rate limiting as limiting the amount of calls a networked client can make to a server but limiting function calls inside a single process is effectively the same thing: perform only M amount of calls instead of all N of them. This particular kind of rate limiting is called throttling.

My proposal is the following: replace `rand()` calls with throttling backed by Redis.

This way it's possible to accomplish the following things:

- have a distributed limit, which means that if we want to update something 10 times per day, we'll know we'll update it 10 times per day across all nodes, instead of "probably 10 times but maybe more"
- potentially being able to change limits by changing the value in a Redis key, without having to deploy
- make testing far easier

**Comment by rhymes** [comment]
NOTE: the biggest drawbcak to this approach is networking latency. If the cost of asking Redis from the web server about the limit is higher than the cost of the entire operation that's being rate limited, then the roundtrip is not worth it.  This will have to be measured, also because not all instances of rate limiting need to take into account a distributed memory across all processes and threads, the rest might be store in the dyno's own RAM.

**Comment by mstruve** [comment]
Added to the SRE board since I also noticed this recently and would love to get it optimized.

**Comment by mstruve** [comment]
For whoever picks this up, breaking this into separate PRs for each different `rand()` or grouping only a couple at a time would be ideal and make reviewing much easier.

**Comment by citizen428** [comment]
@rhymes Now that I picked up this issue, I have some questions:

* Your post mentions requests per day: however, the current `rand` implementations have no notion of "X calls within timeframe", but instead perform each call with a certain probability (though the numbers may not quite work out as intended in certain cases). It doesn't really matter if an operation gets attempted 300 or 3000000 times a day, we'd attempt to e.g. perform it 10% of the time. If we set daily limits, the values may not scale well across Forems. The probability approach also negates the point about concurrency issues, since each invocation constitutes an independent event with the same chance of happening.
* If we go with time-limited calls, what constitutes a day? Do we have a worker which manually resets counts at e.g. midnight UTC each day? Or is it 24h from the first call, e.g. with a key TTL in Redis?
* Did you envision two Redis keys per call, one for the limit, one for the current count? Or was it one key, e.g. counting down from the daily limit until we reach 0? If the former, this would require an atomic operation consisting of the limit check (first roundtrip), performing the operation, incrementing current count (second roundtrip), correct? If the latter, where are the limits stored so we can reset the daily count?

Do you think this issue may actually require an RFC to answer these questions? Are you even still in favor of this proposed solution, or would you be open to using the unique worker pattern @fdoxyz introduced [in this spike PR](https://github.com/forem/forem/pull/12419) and which I then used [here](https://github.com/forem/forem/pull/12686)? This would also be a time-based vs. probability-based approach, but instead of introducing a whole new abstraction build on top of something we already heavily use, i.e. background workers.

**Comment by mstruve** [comment]
> however, the current rand implementations have no notion of "X calls within timeframe", but instead perform each call with a certain probability

I think the point of this issue is that we want to move away from probability-based throttling and move towards something more explicit such as time based throttling so that we can test it more easily and it can be more predictable.

> with a key TTL in Redis? Did you envision two Redis keys per call, one for the limit, one for the current count?  

The way I envisioned this working was when something is updated, say analytics, we set a key in Redis with a TTL. On each call to update the analytics, we first check if that key is present. If that key is present we skip the update. If that key is not present we update the analytics and set the key with a new TTL. This means we would update analytics say every 2 minutes or something

With all of that said ☝️  I am not fully aware of ALL the places we use `rand` which is why I suggested replacing a few of the `rand` calls with a time-based throttling mechanism and then seeing what use pattern emerges that we can continue to apply throughout the code. This approach worked extremely well for our database Rate Limiting that we set up and we have a nice reusable pattern because of it. In an effort to try and not put the cart before the horse I suggested taking that same approach hoping it would work well here too.

**Comment by rhymes** [comment]
Thanks for the detailed analysis @citizen428. It really depends on how we want to restructure the code.

I was reading a few resources on "distributed rate limiting" to be able to answer your questions and:

> Your post mentions requests per day: however, the current rand implementations have no notion of "X calls within timeframe", but instead perform each call with a certain probability (though the numbers may not quite work out as intended in certain cases). 

That's the key point we need to explore I think. Are we using probability to lessen the load or because we actually need the algorithm to be based on probability? Can we separate the two cases? Let's say we have both cases in the code, we might need two different solutions. Use distributed rate limiting based on "per second" or "per minute" or "per hour" and we keep probability for the other use cases

> If we go with time-limited calls, what constitutes a day? Do we have a worker which manually resets counts at e.g. midnight UTC each day? Or is it 24h from the first call, e.g. with a key TTL in Redis?
> Did you envision two Redis keys per call, one for the limit, one for the current count? Or was it one key, e.g. counting down from the daily limit until we reach 0? If the former, this would require an atomic operation consisting of the limit check (first roundtrip), performing the operation, incrementing current count (second roundtrip), correct? If the latter, where are the limits stored so we can reset the daily count?

I found these interesting:

- [Redis Labs: Basic Rate Limiting](https://redislabs.com/redis-best-practices/basic-rate-limiting/), seems a simple algorithm (per minute o per hour), without a rolling window
- [Better Rate Limiting With Redis Sorted Sets](https://engineering.classdojo.com/blog/2015/02/06/rolling-rate-limiter/), uses a rolling window

> Do you think this issue may actually require an RFC to answer these questions? 

Maybe? 

> Are you even still in favor of this proposed solution, or would you be open to using the unique worker pattern @fdoxyz introduced in this spike PR and which I then used here? This would also be a time-based vs. probability-based approach, but instead of introducing a whole new abstraction build on top of something we already heavily use, i.e. background workers.

Could the unique worker pattern be too heavy on the Sidekiq queue (imagine the traffic on a popular's article page views on DEV) ?

Perhaps we need a spike on this too :-D Depends how complex our needs are.

**Comment by citizen428** [comment]
> The way I envisioned this working was when something is updated, say analytics, we set a key in Redis with a TTL. 

A time-based sentinel value, that makes sense and should be easy to build. I guess I was overthinking it this morning.

**Comment by mstruve** [comment]
> Are we using probability to lessen the load or because we actually need the algorithm to be based on probability?

Confirmed with Ben that all the `rand` calls were put in place to decrease load, nothing more complex is going on.

**Comment by citizen428** [comment]
I thought about this a bit more last night before going to sleep: the reason I hadn't considered a purely time-based sentinel was that it doesn't allow us to do this:

> potentially being able to change limits by changing the value in a Redis key, without having to deploy

But it's ok, I guess we don't need that for a first step.

Thanks for double-checking with Ben, @mstruve. I was reasonably certain that this was the case but good to be sure. In a way, I like the probabilistic approach, as it theoretically automatically adapts to different Forem sizes (though that is only really true if the hardware specs are reflective of Forem usage). 

Anyway, I think I have a decent idea know what we want to accomplish with this "spike", I'll get to it once I wrap up a few things.
