### ISSUE TITLE
Articles API: filtering by tags

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#3654]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
In response to #3509, we want to allow the API endpoint to filter by tags and include an 'anti-tag' list.

**Comment by bdbch** [comment]
Awesome, thanks a lot!

**Comment by cdvillard** [comment]
Closed #3668 after @rhymes pointed out that it basically mirrored this. Simply having an additional optional flag for the query string of something like `nottagged=` would be great, given that `#discuss` articles are still of type `article`. There might be an argument, though, to do some heavy lifting now and just create a type `discussion`, should that grow into its own, but I don't have a deeper understanding of dev.to's architecture, so I'll digress to stay on topic.

**Comment by caseyrollins** [comment]
Hi all, taking a stab at this issue! Does anyone have a preference on the name for the filter (`anti_tag` v. `not_tagged`)? @rhymes?

**Comment by rhymes** [comment]
@caseyrollins since the initial request is talking about filtering by multiple tags I would probably consider introducing two new parameters:

`tags` which takes a comma separated list of tags to _include_
`tags_exclude` which takes a comma separated list of tags to _exclude_

(right now we have only `tag`, we could consider extending this to support multiple tags but due to the naming I'm inclined to leave it alone and use two more explicit parameters)

If they both appear they'd have to be applied in and (pseudo SQL: `WHERE tags in (a,b,c) AND tags not in (d,e,f)`)

Not 100% sure if multiple tags in each list should be in `AND` (I want articles that are tagged both `discuss` and `python` but not articles that are tagged both `react` and `javascript`) or using `OR` (I want articles that are tagged either `discuss` or `python` but not articles that are tagged either `react` and `javascript`)

I think `OR` inside one list and obviously `AND` between the two lists is the most logical but it could be up for debate. It's also the closest to how the single parameter `tag` works right now (It doesn't return articles that are only tagged `python`, but articles that have `python` in their tag list).

What do you all think? Should we introduce 2 new params or just extend `tag` plus the param for exclusion? Should we use `AND` or `OR` to join multiple tags in each list?

**Comment by caseyrollins** [comment]
@rhymes, I completely agree that `tags` and `tags_exclude` should take comma separated lists. I would also say that `tags` and `tags_exclude` should be an `AND` between each other and the tags within each list should be `OR`. It feels the most intuitive and resembles what I've seen in other APIs. 

Do you think `tags` should be a new parameter (along with `exclude_tags`), or should `tag` be removed and replaced with `tags`? Does the API have a deprecation policy?

**Comment by rhymes** [comment]
@caseyrollins thanks!

> Does the API have a deprecation policy?

No, not really, we've been operating with the assumption that we're just going to add things and trying not to break anything even though it's a v0
