### ISSUE TITLE
Chat - Push Notifications To Chrome Browser

### ISSUE THREAD

**Issue by omenking** [forem/forem#3683]
**Is your feature request related to a problem? Please describe.**

Modern Browsers allow you to push notifications so you can see activity on a website with chat functionality. 

**Describe the solution you'd like**

- [ ] When someone messages me in Chat it pushes notification to the browser's Notification functionality

**Describe alternatives you've considered**

**Additional context**

**Comment by jessleenyc** [comment]
Yep, that would be awesome.

**Comment by cmgorton** [comment]
Hey Andrew! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
