### ISSUE TITLE
Chat - Send Email Summary When Idle

### ISSUE THREAD

**Issue by omenking** [forem/forem#3685]
**Is your feature request related to a problem? Please describe.**

When I'm away someone might message me but I won't know until the next time I log into DEV.to

**Describe the solution you'd like**

- [ ] When the user is inactive and they have unread chat messages, deliver a summarized email of unread chat messages

**Describe alternatives you've considered**

**Additional context**

**Comment by jessleenyc** [comment]
Hey @omenking, just a heads up that we *do* send an email after a certain period of time. I believe the logic is in `app/models/message.rb`!  I do agree that it would be a better experience if those messages were consolidated into a summary though.

**Comment by cmgorton** [comment]
I also think this would be a good one to surface in [forem.dev](forem.dev) if you think this feature is still useful!

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
