### ISSUE TITLE
Periodically auto-delete 'orphaned' image files

### ISSUE THREAD

**Issue by AninditaBasu** [forem/forem#3709]
**I can't delete images I don't need**

Recently, while drafting a post on the dev.to website, I used an image that I later deleted from the final post.
I could not figure out any way to delete that image from the server itself. I wanted it gone just to reduce the space I take up on the server.

**Possible to give us a _Delete_ option for uploaded images?**

It reduces our footprint, is all.

**Or maybe run an auto-delete script periodically for 'orphan' image files?**

If there's any way to 'tie' images to posts, maybe a script could identify orphan image files and delete them?

**Comment by jessleenyc** [comment]
Hey @AninditaBasu. Thanks for bringing this up -- something good for us to think about. I just updated the issue title to reflect the route we'd consider most.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
