### ISSUE TITLE
Link for latest blog post directly

### ISSUE THREAD

**Issue by BassemMohamed** [forem/forem#3741]
**Is your feature request related to a problem? Please describe.**

It would be much easier if there was a URL that always maps to the latest article published by a certain user.

**Describe the solution you'd like**

Right now, we only have for example: https://dev.to/bassemmohamed.
What I am suggesting is we have something like: https://dev.to/bassemmohamed/latest to get to the latest blog post quickly.

**Comment by nickytonline** [comment]
Just in case you weren't aware, you can now pin posts to your profile. See https://dev.to/devteam/changelog-pin-posts-you-want-to-feature-to-the-top-of-your-profile-feed-1ki4

**Comment by BassemMohamed** [comment]
@nickytonline, I had no idea. Thanks!! 👍

**Comment by nickytonline** [comment]
Yeah, I know it wasn't the same thing, but thought it might be good enough in terms of what you're looking for. Carry on 😉

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
