### ISSUE TITLE
Hide Comments initially on 'Daily Challenge' posts

### ISSUE THREAD

**Issue by msarit** [forem/forem#3785]
**Is your feature request related to a problem? Please describe.**

For the 'Daily Challenge' posts, it sometimes bothers me that a careless scroll to the Comments could reveal solutions to the problem before I'm ready to view them, since many comments contain solved challenges

**Describe the solution you'd like**

For 'Daily Challenge' posts, I propose hiding the Comments section at first, and including a 'Show Comments' button (and maybe a short explanation) that reveals the comments when clicked. Of course, creating a comment without clicking the 'Show Comments' button would reveal the comments as well.

**Describe alternatives you've considered**

I tried to come up with some, but nada.

**Additional context**

Here's a screenshot with a depiction of what I had in mind 😄 

<img width="1680" alt="Hide Daily Comments section" src="https://user-images.githubusercontent.com/32520970/63449416-186e9f80-c40e-11e9-92d5-b0c112d69b6b.png">

**Comment by cmgorton** [comment]
Not sure this is something we do on DEV anymore. 

Since this issue has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
