### ISSUE TITLE
historical stats

### ISSUE THREAD

**Issue by awwsmm** [forem/forem#3830]
__How it works now:__

Users can see their follower count, post likes, and post views on the `dashboard` page.

__How it could work:__

Users should be able to see historical follower count, post likes, and post views. This would require (at least) daily totals of each of these numbers to be recorded for each user. This could be expanded into a "stats summary" page, showing performance over time, maybe with a timeline with markers for posts, so users can better see the impact their work has had.

**Comment by jessleenyc** [comment]
Hey @awwsmm , this functionality will be available soon. We’re rolling out advanced stats as part of a pro feature which will go live within the next few weeks.

We’re starting with pro because we’d rather fully support this for users who want it most rather than trying to water it down for the need to scale to the entire userbase. If we get to the point where it’s comfortably scaling it will go to general availability.

**Comment by awwsmm** [comment]
You mean "Pro" will go live in the next few weeks? Any details available on that? Or are you waiting for a big unveiling?

**Comment by jessleenyc** [comment]
Err here's some info that is totally subject to change 😅 : https://dev.to/pro

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.
We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
