### ISSUE TITLE
Show notifications with :hover property! 

### ISSUE THREAD

**Issue by ochoadev** [forem/forem#3852]
**Is your feature request related to a problem? Please describe.**

This feature request isn't related to a problem, but it does to a feature on the website itself. 

**Describe the solution you'd like**

I'd like to see my latest notifications from the current page or blog post I'm reading without going to the /notifications path. 

This could be done with a :hover effect on the notification icon and adding there the latest 4-5 notifications, just like the effect when you are :hover the your profile picture.

**Comment by ayushmxn** [comment]
I'd like to add to this feature by having the option to click on the notification icon and have a popup open which does not interfere with the feed on a PC display (on mobile the popup will temporarily have to take up the whole screen). A lot of the times I just want to quickly scroll through my notifications and go back to reading an article.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
