### ISSUE TITLE
Tag Inbox for Mod

### ISSUE THREAD

**Issue by omenking** [forem/forem#3955]
Ben mentioned this functionality during the Moderator Zoom call.
I think the goal of this feature is a shared inbox that all moderators to talk to users but as one identified as the mod?

@benhalpern could you help clarify?

**Comment by cmgorton** [comment]
Hey Andrew! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
