### ISSUE TITLE
Dashboard should remember article sort order between devices

### ISSUE THREAD

**Issue by jacobherrington** [forem/forem#3982]
**Is your feature request related to a problem? Please describe.**

I'd like the sorting of my dashboard to persist when I change devices or log out. It's a little disorienting to me because I'd really prefer drafts and articles to be sorted by publish date by default as opposed to the creation date.

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/11466782/64539336-ef8e4b80-d2e3-11e9-9182-8770dcd4cdf0.png)
I'd like this sort order to persist between devices and logs - I imagine it would need to live in the same place as most user settings.

**Describe alternatives you've considered**

**Additional context**

**Comment by cmgorton** [comment]
Hey! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
