### ISSUE TITLE
Kotlin snippets support

### ISSUE THREAD

**Issue by jmfayard** [forem/forem#4011]
**Describe the bug**

I contributed the feature #3776 `Support for runnable kotlin snippets` 

The one thing that prevents to be usable is bad iframe height. 

**To Reproduce**

Open my article https://dev.to/jmfayard/with-configobject-language-kotlin-issparkingjoy-ic4

Scroll down to the runnable snippet and press **Run ▶️**

**Expected behavior**

I should see this:

![image](https://user-images.githubusercontent.com/459464/64924762-3a2e2d00-d7e8-11e9-8c8e-19a7de7281c0.png)

**Actual behavior**

It seems that pressing **Run ▶️** did nothing:

![image](https://user-images.githubusercontent.com/459464/64924747-fe936300-d7e7-11e9-924b-413e52a4a17a.png)

You have to scroll down the iframe to see it:

![image](https://user-images.githubusercontent.com/459464/64924565-72cd0700-d7e6-11e9-9950-5202ac482c4d.png)

**Solution ?**

I asked for advice on this to the Kotlin Playground guys and got this answer:

> @jmfayard  Do you know dev.to has API for iframe resizing? I can send some events on editor changes.
> For examples, emdedly platform provides resizing for the Medium : 

References:

https://docs.embed.ly/v1.0/docs/provider-height-resizing

https://github.com/JetBrains/kotlin-playground/issues/64

**Comment by Zhao-Andy** [comment]
Hmm interesting, I wonder how Stripe's Runkit embed handles this. Worth looking into though. Thanks for the issue!

**Comment by princefishthrower** [comment]
@jmfayard , @Zhao-Andy - Hacktoberfest lurker here 😄 , I think I'd like to give this one a shot, but I'd like to hear both of your thoughts. 

As @jmfayard referenced, if we used the embedly kotlin, it seems that we just need to pass a height via a postMessage (I looked at @jmfayard's post showing the original issue - from it seems the default height from embedly (?) is 150px - thought at the moment I guess we are using the pure iframe and not embedly. But if we had embedly that would be a possibility.

Then I think it would be a matter of adding that post variable to the liquid tags file:

https://github.com/thepracticaldev/dev.to/blob/master/app/liquid_tags/kotlin_tag.rb

(and of course updating the spec and test files correspondingly). The main challenge then I suppose would only be 
1. determining which height to send (before AND after click 'run') (or as an initial version, let them be user specified in their markup)

However, there could be an alternative:

The resizing functionality comes out of the box from including the javascript as referenced from JetBrains:

https://blog.jetbrains.com/kotlin/2018/04/embedding-kotlin-playground/

But I saw that's essentially the equivalent of what @jmfayard suggested in the original feature (the npm package):

https://github.com/thepracticaldev/dev.to/issues/3776 

and that @Zhao-Andy favors the iframe as apposed to the heavier weighing javascript - the js file is indeed 426KB (the npm bundle equivalent nearly the same) - but perhaps its something we could dynamically load only for the posts which have kotlin embeds in them? - I don't know enough about the dev.to internals yet to know how much work that would be 🙈 

Finally, I looked into a Javascript/CSS solution to dynamically size the frame, but that's not possible, because of cross-origin issues.

Hmmmm... this is a tough one 👍

**Comment by jmfayard** [comment]
My thought was that the npm package would be the best solution by far **if** the heavy JavaScript could be lazily loaded only for articles tagged with `#kotlin`. It's that possible @Zhao-Andy ?

**Comment by jmfayard** [comment]
The big advantage from a writer point of view is that you don't need to maintain code snippets in another website. It's just a markdown code block with `run-Kotlin` instead of `Kotlin`

**Comment by jmfayard** [comment]
@Zhao-Andy can you help us unstuck this issue?

Recap: the problem is that the iframe of the Kotlin Playground has a wrong height, both on creation and after you run it, making a very useful feature not really usable.

The open question:

Which one of those solutions would be acceptable

1) Lazily load the [npm package `kotlin-playground` ](https://jetbrains.github.io/kotlin-playground/examples/) only on dev.to articles that are tagged with `#kotlin`. If there is no big performance problem associated with it, that would be the simplest solution (it comes out of the box), and the most comfortable from a writer point of view (no need to maintain separate snippets)

2) @AlexanderPrendota from JetBrains told me that if dev.to has an API for iframe resizing, they can send events on editor changes. It's in this issue https://github.com/JetBrains/kotlin-playground/issues/64

3) or using embedly like medium.com

cc @princefishthrower

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  I am going to close this issue.  We have a new process moving forward to address feature requests and especially those that have been in our repo for 1+ years without much traction.  
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](forem.dev).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
