### ISSUE TITLE
Text highlighting within blog posts

### ISSUE THREAD

**Issue by brittany-johnson** [forem/forem#4026]
**Is your feature request related to a problem? Please describe.**

This feature request is not related to a problem. When reading articles on [medium](https://medium.com/), I love to highlight text that I find interesting or useful and would like to reference in the future. I would find this feature super useful and I'm wondering if other people feel the same? 

**Describe the solution you'd like**

When reading a blog post on the site, I would like to highlight text. When I open the article in the future, the highlighted text is still present. This request does not include the grouping of saved highlighted text across a user's saved blog posts. 

**Describe alternatives you've considered**

N/A

**Additional context**

An example of highlighting on medium.com 
<img width="1605" alt="Screen Shot 2019-09-14 at 9 39 44 AM" src="https://user-images.githubusercontent.com/24909007/64909572-acf9b400-d6d3-11e9-915c-42f9e3870ce8.png">

**Comment by maestromac** [comment]
That's definitely a useful feature! 

I've never use that feature myself but I've seen "Top highlight" appearing here and there. Is this something that is only reserved to the reader and not the author?

**Comment by brittany-johnson** [comment]
Yep! The highlighting feature is reserved for the reader. On my Medium profile, I can also see all of my highlights. Not sure if other users can see my highlights when visiting my profile. I don't find this part very useful though.  
<img width="1792" alt="Screen Shot 2019-09-19 at 12 34 27 PM" src="https://user-images.githubusercontent.com/24909007/65267116-feda7980-dad9-11e9-907a-64462a63fb14.png">

**Comment by cmgorton** [comment]
Hey! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
