### ISSUE TITLE
Feature request: Bulk image upload or drag and drop upload or IA writer integration

### ISSUE THREAD

**Issue by discdiver** [forem/forem#4126]
I write blog posts in my IA Writer markdown editor and then want to upload or copy/paste into Dev. Uploading images one at a time and copying and pasting the URL provided is slow.

I would like to be able to upload images in bulk and easily copy the urls or have some other mechanism to quickly add images to posts. Directly dropping the images into the blog post and having Dev substitute the URL into the post might be ideal. That would save a lot of copy/pasting.

IA Writer has an integration with Medium, so it's quick to get articles into Medium. I have tried importing my articles directly from Medium into Dev, but Toward Data Science cuts off the article after the first paragraph, so that's not an option. If IA Writer and Dev had an integration, that would make life easier.

There's currently a good bit of friction in port an article from my local markdown writer (AI Writer)

Thanks for considering!

**Comment by rhymes** [comment]
Hi @discdiver, you can select and upload multiple images already, it's a recent feature but it's in production since August 18, see https://github.com/thepracticaldev/dev.to/pull/3599

Basically when you open the modal to upload images, you can select more than one and then upload them, the editor will display the tags and the direct urls you can use in your article.

Drag and drop would be nice, I use it all the time on GitHub.

Integration with IA Writer though should probably come from their side, DEV has a [beta API](https://docs.dev.to/api/) to create and publish articles...

**Comment by discdiver** [comment]
Thanks  Hmm. I got an error and no uploads when I tried to bulk upload.
Guess that was a bug and not a lack of a feature then.

**Comment by rhymes** [comment]
What sort of error? Can you check the browser's console? Thanks

**Comment by bharatdwarkani** [comment]
I suggest a GitHub comment editor like drag and drop file/image upload user experience. Pasting an image or dragging and dropping a file uploads image automatically and adds the image/file where the cursor is at present.

![image](https://user-images.githubusercontent.com/12810605/67080702-65bf8100-f1b3-11e9-8ec1-a8e964a70aa9.png)
