### ISSUE TITLE
Suggest a tag for Moderate Post

### ISSUE THREAD

**Issue by Defman21** [forem/forem#4207]
**Is your feature request related to a problem? Please describe.**

Sometime authors do not set tags (e.g. an article about Node.JS GraphQL server lacks the `node` tag).

**Describe the solution you'd like**

Allow trusted members/mods to suggest/change tags for an article. For example, if I suggest the `node` tag for the article, moderators of the tag should receive a notification about that to either accept my suggestion or deny it, providing a reason I'd see.

**Comment by jessleenyc** [comment]
I think the approval process is probably up for debate. I personally think it makes sense for mods to be able to add/change the tags directly as long as the user gets and email and on-site notification about it.

**Comment by Defman21** [comment]
@cmgorton could you explain why you've closed the issue?

**Comment by cmgorton** [comment]
Hey @Defman21 this was a useful feature request but we have a new process for feature requests.
To help the team internally, our contributors, and to help the health of our repository, I am working on closing out older requests that have been open for more than a year without much traction. 
You can read about the new process [here](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).

**Comment by Defman21** [comment]
So should I post it on forem.dev or... ?

**Comment by cmgorton** [comment]
Yes you can post it on forem.dev for discussion. [Here is an example](https://forem.dev/foremteam/forem-following-system-b9f) of an issue I recently posted there for discussion. 
In the future we shouldn't have to link to the original issue since the discussions should start there before being issues but for know if you want to add more context you can link to this issue on forem.dev like I did in that example post.
