### ISSUE TITLE
Inconsistent editor versions between posts

### ISSUE THREAD

**Issue by msfjarvis** [forem/forem#4219]
**Describe the bug**

I have two posts on DEV that were supposed to be in a series, [#TeachingKotlin Part 1](https://dev.to/msfjarvis/teachingkotlin-part-1-classes-and-objects-and-everything-in-between-5bn0) and [#TeachingKotlin Part 2](https://dev.to/msfjarvis/teachingkotlin-part-2-variables-2api). I have been trying to use the editor to add Part 2 to the series but no matter what I choose as my editor version, that particular post always opens in frontmatter view while Part 1 opens up in editor v2, the choice I made in settings.

**To Reproduce**

There appears to be no pattern to it at all. I've linked all my posts so far in chronological order along with the versions of the editor I am shown.

- [Post 1](https://dev.to/msfjarvis/how-to-get-involved-with-open-source-4h42): v2
- [Post 2](https://dev.to/msfjarvis/understanding-and-resolving-selinux-denials-on-android-2588): v1
- [Post 3](https://dev.to/msfjarvis/what-is-your-housekeeping-programming-task-4lce): v2
- [Post 4](https://dev.to/msfjarvis/how-do-i-regain-my-sense-of-purpose-after-quitting-my-job-1e4k): v2
- [Post 5](https://dev.to/msfjarvis/tools-for-effective-rust-development-3mb4): v1
- [Post 6](https://dev.to/msfjarvis/teachingkotlin-kotlin-for-android-java-developers-1fo3): v1
- [Post 7](https://dev.to/msfjarvis/teachingkotlin-part-1-classes-and-objects-and-everything-in-between-5bn0): v2
- [Post 8](https://dev.to/msfjarvis/teachingkotlin-part-2-variables-2api): v1

**Expected behavior**

Every post opens with the same version of the editor

**Screenshots**

<details>
<summary>Editor v1 and v2</summary>

![Screenshot from 2019-10-03 20-39-15](https://user-images.githubusercontent.com/13348378/66139354-e9a73400-e61d-11e9-8bec-6e99bf7f2885.png)

![Screenshot from 2019-10-03 20-39-10](https://user-images.githubusercontent.com/13348378/66139355-e9a73400-e61d-11e9-9be9-6eaa87bc598a.png)

</details>

**Desktop (please complete the following information):**

- OS: Linux Mint 19.4
- Browser: Google Chrome
- Version: 77.0.3865.90

**Smartphone (please complete the following information):**

- Device: Google Pixel 2
- OS: Android 10
- Browser: Google Chrome
- Version: 77.0.3865.92

**Additional context**

None that I can immediately think of.

**Comment by jessleenyc** [comment]
Strange. Thanks for reporting. Whoever grabs this, look into the logic that's determining which editor to show?

**Comment by alebruck** [comment]
The current logic for Article Edit chooses the editor based on the content of the article, as you can see [here](https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/articles_controller.rb#L77) and [here](https://github.com/thepracticaldev/dev.to/blob/757b1a8b57906d5ad987cb75be8b671758a3e036/app/models/article.rb#L330).

If it finds a `title` on the front matter block it will render the V1 editor(frontmatter Jekyll style), otherwise, it will always use V2(markdown), the user preferences have no effect. The assumption seems to be that an Article should be always edited with the editor that can parse its content format.

@jessleenyc My question is, should the User Editor Preference be used for edit even if the article has content in a different format? I would say no, but maybe it would be better to have a way to switch between editors from the Article Edit Page(Switch to v1/v2 Button).

@msfjarvis quick fix for you would be to edit the v1 article, delete the title from the [YAML front matter block](https://jekyllrb.com/docs/front-matter/) and save it. The next time you open it should use the v2 editor.

**Comment by msfjarvis** [comment]
> @msfjarvis quick fix for you would be to edit the v1 article, delete the title from the [YAML front matter block](https://jekyllrb.com/docs/front-matter/) and save it. The next time you open it should use the v2 editor.

That did the job! Definitely going to keep this in mind for the future, lost way too many hours fumbling around...
