### ISSUE TITLE
# reactions per view

### ISSUE THREAD

**Issue by Almenon** [forem/forem#4252]
**Is your feature request related to a problem? Please describe.**

My problem: I have to calculate manually the number of reactions per view. I use this score as a rough indication of how good an article is. An article that gets 100 hearts for 1000 views is probably better than a article that got 500 hearts for 2000 views. There's other factors at play too, of course, but the score serves as a rough indicator.

**Describe the solution you'd like**

The engagement score (reactions/comments per view) to be visible in the dashboard or in a stats page if that is eventually deveoped.

`engagement score: 4.6%`

**Describe alternatives you've considered**

`reactions per view: 1 reaction per 21.5 views`

**Additional context**

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
