### ISSUE TITLE
Negative following count on Dashboard

### ISSUE THREAD

**Issue by technoplato** [forem/forem#4263]
**Describe the bug**

I have negative followers.

**To Reproduce**

Unsure how to reproduce...

**Expected behavior**

Followers count is equal to number of people oI follow

**Screenshots**

![image](https://user-images.githubusercontent.com/6922904/66272529-dd4af300-e838-11e9-8371-83bef56292e0.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by ludamillion** [comment]
Possibly related issue logged in CounterCulture repo https://github.com/magnusvk/counter_culture/issues/187

**Comment by mstruve** [comment]
@technoplato  thank you so much for reporting this! Since being reported we have updated a lot of our following code logic and I have not been able to reproduce this with the new code so I am going to close this issue. If you can still reproduce this please let us know and we will look further into it! Thanks for being a part of the Forem community!
