### ISSUE TITLE
API: get user by its github username

### ISSUE THREAD

**Issue by technoplato** [forem/forem#4266]
**Is your feature request related to a problem? Please describe.**

I'm developing an "Edit on Github" "plugin" for posts for Dev.to and I want to automatically accredit users in a list at the bottom of an article if they submit an edit, along with maybe something like line count changed. I want to automate this, so I'd need a way to search for Dev.to users by github username. 

Is this currently possible?

**Describe the solution you'd like**

https://dev.to/api/users/by_github?url=technoplato

**Describe alternatives you've considered**

Having the user provide their Dev.to username manually.

**Additional context**

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
