### ISSUE TITLE
Personal image gallery

### ISSUE THREAD

**Issue by half-nirvana** [forem/forem#4268]
**Is your feature request related to a problem? Please describe.**

Once I upload an image for an post, I have to use it immediately or at least keep the copy of link otherwise it gets lost. Ideally I should be able to add, delete, use the content I upload.

**Describe the solution you'd like**

I should have a personal gallery of images which I have uploaded and I should be able to use it in any of my posts.

**Describe alternatives you've considered**

No

**Additional context**

Noting to add

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
