### ISSUE TITLE
End to end encrypted private messages

### ISSUE THREAD

**Issue by abenerd** [forem/forem#4328]
**Is your feature request related to a problem? Please describe.**
No problem, you're doing great!

**Describe the solution you'd like**
DEV supports private messages and I think it would be awesome if these could be end to end encrypted between the participants.

**Describe alternatives you've considered**
Alternatively the messages could simply be encrypted by the platform so that there are still no plain messages in the database. 

**Additional context**
https://signal.org/docs might be a place where one could start, although I unfortunately don't have the knowledge and understanding to implement this feature myself.

**Comment by rhymes** [comment]
Hi @abenettt, thanks for this request and for starting this conversation! 

A bit of information about the status quo:

Right now we use [Pusher](pusher_channels) to push messages to all recipients, and messages are also [stored in the DB in the clear](https://github.com/thepracticaldev/dev.to/blob/master/app/models/message.rb).

Pusher does support [e2e encrypted channels](https://blog.pusher.com/end-to-end-encryption-beta-channels/) apparently since March 2019 (here's a [Node tutorial](https://pusher.com/tutorials/end-to-end-encryption-node) and a [Go tutorial](https://pusher.com/tutorials/encryption-go-channels)).

I think the main reason for the messages to have been in the clear until now (aside from the fact that this is a relatively new feature) is moderation of possible abuse.

**Comment by benhalpern** [comment]
I agree with this feature big time.

> I think the main reason for the messages to have been in the clear until now (aside from the fact that this is a relatively new feature) is moderation of possible abuse.

@rhymes yes abuse reports is a component here, but the way we deal with privacy (through strict internal permissions) is something I'd love if we could move off of. With regard to the abuse, I think we could work out a mechanism so that when someone reported abuse, they initiate an encryption transaction similar to how they were doing e2e in the first place. They have access to the conversation. They could send this to admins in a new encrypted transaction. But admins couldn't go in the other direction.

The biggest reason it is not this way is because we sort of dropped it as _necessary for launch_ and haven't gotten to it yet.

The only reason this non-encrypted situation is justifiable IMO is that it's common enough on other platforms to operate how we've been thus far. But I 10000% want to move to e2e.

And in thinking about this, even though Pusher has been great for us so far, if we're thinking about big infra changes, I'd love to move in a more open source direction (e.g. ActionCable for Rails) so that we have one fewer proprietary dependency.

**Comment by abenettt** [comment]
I don't know many connections pusher is serving right now, but maybe using something like [Mercure](https://github.com/dunglas/mercure) instead of ActionCable will allow for independent scaling, and it is still open source. The platform would still be responsible for the encryption.

**Comment by rhymes** [comment]
I haven't studied the issue enough to know if we should migrate away from Pusher (or any other SaaS offering) and do encryption ourselves through some framework/library/server but in any case I agree with Ben, we definitely need e2e encryption.

Mercure seems interesting, a possible alternative to ActionCable which is compatible with it and that's popular in the Rails community is AnyCable: https://anycable.io/

I agree that the web app and the chat should scale independently, we need to determine a few things though:

- what's the support for e2e encryption for these various tools
- if the tradeoff of leaving a SaaS service is worth it
- how more complicated the deployment of the DEV app becomes (well, this is a tradeoff)

:-)

**Comment by rhymes** [comment]
The main blocker here is that [Pusher end-to-end encrypted private channels](https://pusher.com/docs/channels/using_channels/encrypted-channels) don't work with the Ruby client :-(

**Comment by abenettt** [comment]
That is true but, correct me if I'm wrong, but I think I remember a discussion on whether to stay with pusher or using an (open source) alternative. I think this issue could be shelved until the decision on whether to use pusher is resolved.

**Comment by rhymes** [comment]
@abenettt yeah, I don't think any of the alternatives listed in that conversation supports e2e though. I'm not surprised as it's not an easy thing to tackle within the context of an open source project

**Comment by cmgorton** [comment]
Since our connect feature is being depreciated I am going to close this issue.
