### ISSUE TITLE
Gitlab / *-based project showcase

### ISSUE THREAD

**Issue by Arteneko** [forem/forem#4332]
We can put in front some of our Github-based projects, but nothing else.

I'm mainly a Gitlab user, and have a few projects I'd like to showcase on my profile, and I sadly can't do that unless I mirror my real repository with a mirror on Github, which is pretty impractical and adds some indirection.

Wouldn't it be possible to also load Gitlab-based projects? Or pretty much any git-based project? (Including self-hosted gitlab, gitea, gogs, etc.)

**Comment by rhymes** [comment]
Hi @Arteneko, thanks for starting the discussion! 

It's probably doable for repositories hosted by Gitlab and possibly with self hosted options that have the API enabled. All the other services are probably conditioned as well on availability of an API.

What do you think?

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
