### ISSUE TITLE
The lifetime of Tutorials vs Posts vs Tricks vs Hot Stuff

### ISSUE THREAD

**Issue by joetex** [forem/forem#4386]
**Is your feature request related to a problem? Please describe.**

dev.to receives many different categories of write ups, and they all have the same lifetime, or time-based promotion.   Unless a write-up is promoted outside of dev.to, its lifetime is anywhere between 1 hour and 5 days.    All write-ups are being equated to a meme or news articles with short engagements, but most write-ups are reference materials that should have longer lifetimes based on their popularity.  

This causes 2 problems:

1. Quality write-ups (4+ min reads) for tutorials, tricks and hot stuff have to compete with short (1 min) generic posts.

2.  Quality write-ups are missed completely by the very people who would have helped bump the write-up in popularity (reactions/follows).  

**Describe the solution you'd like**

For starters, the types of posts need to be separated, some examples to split apart:
1. Categorize the posts as Tutorial, Tricks, Hot Stuff, or Post.
2. Let readers filter by read time range.  (i.e. Show only write-ups that are 3+ minute read time)

Next, each reaction, view, comment, or follow that a write-up receives should allow it a % chance to make it back into the circulation of a user's feed at a later date for users who have not read it. 

Of course, there are too many write-ups per day, so there should be some limitations:
1. Any interaction increases % chance of repost for X amount of time with diminishing return.
2. Limited only to readers who have not read.  Heuristics will be needed to prevent spamming the same articles too much to the same user.  
3. Maybe have a "Popular" feed view where this formula is enabled.

**Describe alternatives you've considered**

none

**Additional context**

Some write-ups deserve to live for up to a month or more, but its not possible with the current algorithm, as those deserving write-ups may fall through the cracks before they gain traction.

**Comment by cmgorton** [comment]
Hey I think this is a great feature request!
Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
