### ISSUE TITLE
Redirect user to origin after sign up

### ISSUE THREAD

**Issue by abenettt** [forem/forem#4389]
**Is your feature request related to a problem? Please describe.**
When being prompted to sign in before commenting on an article, after completing the onboarding after creating a new account one is being redirected to the landing page / start page of dev.to. Instead of the article one wanted to comment on.

**Describe the solution you'd like**
I think being one should be redirected to the place where one has been prompted to sign in, so they can continue with what they wanted to do without further disruption. 

**Describe alternatives you've considered**

**Additional context**

**Comment by jessleenyc** [comment]
@abenettt thanks for raising this. We have a few variants of onboarding and you might have hit a flow where it doesn't redirect back to your original action. Totally agree that it's awkward here and I think we should update to make sure all variants return people to what they were trying to accomplish to begin with.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
