### ISSUE TITLE
Add support for native methods in Android app.

### ISSUE THREAD

**Issue by VarunBarad** [forem/forem#4399]
**Is your feature request related to a problem? Please describe.**

To add more functionalities in Android app while we keep using the web-view in there, a bridge needs to be added in the Android app. I have added the bridge in Android app but now need the website to start taking advantage of that bridge.

I have followed [this tutorial](http://rapidprogrammer.com/android-how-to-call-native-java-methods-from-webview-javascript) and ensured that the method outlined in it works in a private small test application.

For reference, I have named the bridge object `androidWebViewBridge` so that will be the name you need to use in JS.

**Additional context**

This issue is just a starting point to discuss what things do the team plan to start natively including in the Android app, because a bit of shim code will need to be added to the website side for every native functionality added on Android.

**Comment by VarunBarad** [comment]
I am willing to add those shims to the website (though it will take me a couple of days to set up a local dev environment for the website) if it is acceptable.

**Comment by maestromac** [comment]
Thank you for this issue and creating a PR on android side @VarunBarad !

This will definitely make our android app more interesting. I don't have any immediate idea to try out this use case yet but we're open to suggestion.

**Comment by VarunBarad** [comment]
@maestromac I have seen a couple of issues regarding post-sharing (and link-copying) causing problems due to the website being loaded inside a web-view. That might be a small-enough initial target to test this integration.
I will look tomorrow into how those things are currently implemented and what needs to be done.

**Comment by cmgorton** [comment]
Hey! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
