### ISSUE TITLE
Editor: more info about local "new changes"

### ISSUE THREAD

**Issue by kay-is** [forem/forem#4409]
**Is your feature request related to a problem? Please describe.**

I wrote an article on multiple devices over the course of a week.

I finished it on one device and wanted to publish it on another after the weekend.

When I opened the article on the other device, it showed me an incomplete version of the article with the hint that this version has "new changes".

I freaked out and drove home to see if I had the complete version as local "new changes" on one of my other devices.

Turns out, the article was saved to the backend complete and some of my devices had old versions which they sold me as "new changes".

Long story short, it cost me 5€ and a 1h subway ride to find out everything was okay and I could simply have "clear"ed the "new changes".

**Describe the solution you'd like**

The nice dev-style solution would be a Git(Hub-style) diff of the local version and my remote version, haha. Because it's nice to see what's old and whats new, but it's nicer to see if the old stuff includes some things missing in the new stuff.

**Describe alternatives you've considered**

A simple solution would be some dates and times.

    Local version  15:12:11 15.10.2019 - old
    Remote version 12:11:00 16.10.2019 - new

**Additional context**

5€!!! 💩

**Comment by benhalpern** [comment]
Sending over the timestamp of the most recent saved change and then only showing the local changes if they are newer than the recent changes in the server side article makes sense. The diff functionality makes sense but is possibly not needed because the problem would be improved by only showing local changes if they are more recent than the ones sent by the server.

I'll mark this as approved for help in that capacity and we'll get to this if nobody from the community scoops it up.

In the future we could possibly sync "unsaved changes" as a column on the article and then sync those across clients—we could also do live changes and storing all the diffs over time, but that seems like a bridge we can cross later.

Sorry for the panic K.

**Comment by rhymes** [comment]
Adding a note for the discussion: receiving the timestamp from the client might also entail handling conflicts (worst case scenario is the client not having an aligned clock)

**Comment by cmgorton** [comment]
Since this is an older issue at this point I am going to close it in favor of #12401 and add it to our engineer planning funnel to get more visibility on it. Hopefully that will help get this issue fixed sooner.
