### ISSUE TITLE
Detect image height and width in markdown parser

### ISSUE THREAD

**Issue by benhalpern** [forem/forem#4616]
As per [this video](https://www.youtube.com/watch?v=4-d_SoCHeWE), browsers will begin laying out images based on `height` and `width` attributes so they don't "jump" on load.

Of course, with user-generated content, we can't always know the height and width of an image, but we _could_.

We do various forms of image manipulation in the `markdown_parser`, i.e.

```ruby
    html = prefix_all_images(html)
    html = wrap_all_images_in_links(html)
```

And in that process we set some attributes such as `img["loading"] = "lazy"`. In that area we could also set `img["height"]` and `img["width"]`.

In terms of "how" to do this, the library [FastImage](https://github.com/sdsykes/fastimage) looks like a good one to me, but I didn't do an extensive search. I'd think we'd want to create a method which Rails caches the output of the image we fetch, so we don't need to make this network fetch every time we hit "preview" or re-save an article. `FastImage` also lets us set a timeout, which we should definitely make use of because this is not critical behavior we'd want to cause a major slowdown with. 

Anyway, if we can make this work without making things meaningfully more fragile or slow, I think we should do this. Having awareness of aspect ratios seems generally useful.

**Comment by welenofsky** [comment]
I am going to start looking into this one.

**Comment by welenofsky** [comment]
I tried to take a crack at this. It was the first time I worked on any rails code outside of tutorials. Let me know if I can improve this any way. Thank you.

**Comment by rhymes** [comment]
I would like to understand this issue better and what the current situation in the code is and if we can get there in steps.

If I'm not mistaken, right now we have two types of images: those that are uploaded to DEV (and hence we can know their aspect ratio, which is the most important part of the new feature if I understood correctly the video) and those that people link from third parties.

The uploaded images can be analyzed and the width, height and aspect ratio can be found. Since they are served by Cloudinary that's also a given for their algorithms.

Third party images though are a different story because we don't know in advance their sizes or aspect ratios. I'm not convinced preview should take that into account (it would also not work in the case of articles sent by the API and it would slow down the preview). If we want to build an automated system we should probably do something about that after the post is saved/updated, where images can be retrieved by Fastimage et similia and analyzed.

We need to find the right balance in any case, I don't know how common "image heavy" posts are but if I have a tutorial post that's image heavy and I post it with the API we might not want a library downloading 10 never seen before images and adding the sizes while the client is waiting for the article to be created.

The [benchmarks for Fastimage](https://github.com/sdsykes/fastimage#benchmark) talk about 100 milliseconds for a clearly well cached image (wikimedia), those add up if you have 10 images and maybe not all of them fast at responding :)

I'm also dubious about storing metadata of every single image on the website in the cache. 

We should have a discussion about _how to do it correctly_ as @benhalpern mentioned, aside from which gem to employ.

We also need to check how do we have the CSS setup for images.

**Comment by benhalpern** [comment]
@rhymes how do you feel about all of this now that https://github.com/forem/forem/blob/main/app/services/articles/detect_animated_images.rb exists?

My thought is that we could repurpose that service to be a _general_ async image inspection manipulation step? Seems like now that we are going through the trouble of inspecting images in this way we could take the next step to add this functionality?

Re-opening this and making that mod seems like pretty high value unless I'm mistaking something here.

**Comment by rhymes** [comment]
@benhalpern, great idea! The functionality is currently behind a feature flag because we're having some troubles on DEV we need to debug, so I'm leaning towards transforming this to a RFC 0 but we should definitely do it. Having the width and height will make such a difference to the UX and browsers will be happier.

**Comment by benhalpern** [comment]
@rhymes that all sounds good to me!
