### ISSUE TITLE
Spelling/Grammar Correction Feature

### ISSUE THREAD

**Issue by jessleenyc** [forem/forem#464]
### User Story / Description
This came through the state of the web survey: a request for spelling/grammar check on articles. I think this would be useful for a lot of people, especially because we have such an international community where english is not native for all. Things to consider: design, which service to use. 

### Definition of Done
A ticket w/ more actionable next steps? Or I can update this as the conversation evolves.

**Comment by gytdau** [comment]
Hmm, adding Grammarly sounds like it would conflict with the entire open source philosophy in some way. I haven't experienced these issues myself, but what about a Stackoverflow-esque style of editing, where other people can suggest edits on the article for the author to review and publish? This could also be good if the information should be corrected in some minor way. I can see this infringing on the entire concept of an article having one author though.

**Comment by alextakitani** [comment]
I was about to open an issue about it.

As a non-native English speaker, I get intimidated writing posts/comments that will show for a huge audience.

Many times I've written a huge text and erased because I feel that I was not able to properly translate what I was thinking.

I think that more than an automatic way of checking spell and grammar, the help from native speakers would help A LOT. Sometimes we non-native have problems on the correct translation, to make the idea clear from our language to English.

I agree with @gytdau idea that a stackoverflow like editing would help, but I also suggest that we have a way to flag our posts/comments for help.

Maybe also mark those as drafts, to be "approved" when our english experts think they are ok.

That would open a way for english native beginners to help the community, and for foreigners to grow on English.

**Comment by rhymes** [comment]
@alextakitani as a non native speaker myself I see where you're coming from

> Maybe also mark those as drafts, to be "approved" when our english experts think they are ok.

Keeping a post in draft and waiting for approval for an english expert might ease one's mind but it also means that someone has to bear the work and responsibility of going through your post (if not tens of posts if they sign up for the "job"), in their spare time, to correct our typos or mistakes. Essentially they would become proof readers.

I think an opt-in system would be better. Where a reader, that's already reading your post in the first place, can mark a sentence or a mistake, suggest an edit and send it privately to the author. The author can apply the edit it on their own time if they feel like to.

What do you think?

**Comment by jessleenyc** [comment]
Reopening this issue since I think a grammarly plugin could still be interested. Created a new issue related to the community helping one another edit posts: https://github.com/thepracticaldev/dev.to/issues/2055

**Comment by Link2Twenty** [comment]
I'll just pop this in here <https://github.com/languagetool-org/languagetool>

**Comment by cmgorton** [comment]
Hello! Thanks for your contributions here.  We have a new process moving forward to address feature requests.
TLDR: we have new internal RFC process for feature requests. Any features that are more substantial and require more thought and detail will need to be discussed in [forem.dev](https://forem.dev/).

You can read more about our Internal RFC Process and forem.dev Discussions in [this post](https://forem.dev/foremteam/internal-rfc-process-and-forem-dev-discussions-3gl4).
