### ISSUE TITLE
Ability to select a piece of text and share over social media.

### ISSUE THREAD

**Issue by ZAfricanDev** [forem/forem#4687]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to select a piece of text, and share the quote over social media.

1 ) Select piece of code. 
2 ) Have a button that detects the text selection and allows you share directly over social media platforms. 

**Describe alternatives you've considered**

None really, thought it would be a cool feature.

**Additional context**

Similar to what exists on medium.

**Comment by jessleenyc** [comment]
There are a few other things we want to consider as it relates to selecting text (i.e. highlighting functionality) and we'd want to think about it all together more holistically so let's hold off on this for now.

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
