### ISSUE TITLE
Add GraphQL API

### ISSUE THREAD

**Issue by abenettt** [forem/forem#4700]
**Is your feature request related to a problem? Please describe.**
Nope no problems!

**Describe the solution you'd like**
I’d like to suggest implementing a GraphQL API it would allow for selective querying and even streaming and subscriptions. I think that at least for reading operations GraphQL might be a good solution as after the types are built there is not much else to be done. The drawback would be that we might end up supporting two different APIs that have different capabilities. 

**Describe alternatives you've considered**
Not implementing GraphQL. 

**Additional context**

**Comment by abenettt** [comment]
Also as GraphQL only uses a single endpoint caching would have to be done on the application layer itself as far as I know, so that might also be a drawback.

**Comment by jessleenyc** [comment]
Thanks for the request @abenettt. This would be a pretty big undertaking so we're still discussing as a team to see if and how we'd approach this. Our general thought is that this can be a community-oriented project but we want to make sure we have the capacity to support it before anyone moves forward.

**Comment by yashwanth2804** [comment]
Graphql going to help api requesters to save bandwidth, So hoping it will be implented soon

**Comment by cmgorton** [comment]
I think this would make a great discussion post on  [forem.dev](forem.dev).

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
