### ISSUE TITLE
Create a User Settings/Preferences Table

### ISSUE THREAD

**Issue by mstruve** [forem/forem#4940]
Our user table has gotten rather large recently and in an effort to break it up and not end up with hundreds of fields on a single model we want to break off the user settings columns. Settings that could be moved
* email settings
* notification settings
* display settings
* language settings

**Comment by mstruve** [comment]
@citizen428 what do you think about closing this issue since we are now using ProfileData to fill in custom fields? I could see these kinds of settings ending up there.

**Comment by citizen428** [comment]
@mstruve Gut feeling I'd prefer a dedicated table for this. Here's how I think about it:

* `User`: the actual account, backed by Devise, used for auth, etc.
* `Profile`: pretty much just covering the data for displaying/updating the profile page. Since the fields are community specific, we use a JSONB column instead of dedicated columns per attribute.

While we could also add dedicated columns to `profiles`, I'm slightly reluctant to turn this table into the target for things we want to move out of `users` as we might eventually just end up with two semi-bloated tables. 

A dedicated model with a backing table with explicit columns seems like a better choice long-term since it also provides a nice place to put some basic sanity checks and validations that are really settings specific.

**Comment by mstruve** [comment]
This is all being handled by profile generalization so I'm going to close this.
