### ISSUE TITLE
Improve hidden comments by marking them and allowing them to be expanded

### ISSUE THREAD

**Issue by res33155** [forem/forem#5091]
**Is your feature request related to a problem? Please describe.**

[Original comment from me on the DEV announcement](https://dev.to/ryansmith/comment/imnp). 

For the hidden comment feature, it hides the comment completely. Users see a message at the bottom of the post, but there is no way to access that comment. I think this could lead to unwarranted censorship which can leave the readers and commenters feeling slighted.

![](https://res.cloudinary.com/practicaldev/image/fetch/s--_gu1ZZn2--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://thepracticaldev.s3.amazonaws.com/i/ffnbdobk2xpxq14pb472.png)

If the hide comment feature is abused, it could affect community safety and inclusivity. A post could contain content that is against the code of conduct or the terms and a community member could leave a comment explaining that. If that comment gets hidden by the author, they are effectively silenced from speaking out. While there are moderation tools and report functionality, there may not be immediate action taken on the post, so a comment can be helpful to explain the issue to the readers.

It is too early to say that this _will_ happen, but I have seen comments made that I could see this happening to. One was calling out that the entire post was an advertisement and another was calling out to ableism in the post. I can find these specific examples if requested.

**Describe the solution you'd like**

I am suggesting to make hidden comments less discoverable, but allow them to be expanded to view the content. That would allow the author to have control while also allowing the reader to determine for themselves if the comment was constructive.

I also think that being able to expand the comment could also apply to the low-quality content indicator. Those comments are currently marked, but the content is visible by default.

![Screenshot showing DEV's low-quality content indicator as an expandable comment](https://thepracticaldev.s3.amazonaws.com/i/4nxpntxnm92cuozy4tlr.jpg)

**Describe alternatives you've considered**

Alternatives options could be:
* In the hidden comment message at the bottom there could be a separate link to view hidden comments.
* Hidden comments could go to the moderators to determine if it should remain hidden or if it is a valid comment.

Thanks!

**Comment by Zhao-Andy** [comment]
Hi Ryan, thanks for the feedback. We’re definitely taking this into consideration, and will be taking steps to improve it in the next iteration. I like the idea of collapsing comments that have been marked as low quality/non-constructive.

On a different note, we think there’s an important distinction that we don’t show the same visual patterns for low quality comments and for hidden comments though, since authors can in fact hide comments for reasons that are not violating the code of conduct.

Discoverability is a good point to think about, too, and we’re going to revisit the feature soon. Thanks again for sharing!

**Comment by ryan3E0** [comment]
Thanks @Zhao-Andy, sounds good! Feel free to close this one if it is being handled elsewhere.

**Comment by marko-hologram** [comment]
Is there any progress or ETA on this part about hidden comments? 

I think it is really important to indicate hidden comments in some way because authors can decide to hide comments that might not agree with their point of view and show a discussion that is one sided and not really truthful and realistic.

I don't want to give specific examples, but I've been involved in a thread where author was hiding most of the comments that didn't align with his point of view and thus created a discussion that painted a picture where most of the people agreed with him and his points, which isn't really the truth.

I would propose to maybe add an exact number of hidden comments. For example if you have a discussion where there are 100 comments and 20-30 or even more of them are hidden, it might indicate that comments are being hidden not just because the author might have found them insulting or something else, but might indicate that the author is hiding a large percentage of the comments for some other reason.

I also really like this idea "_In the hidden comment message at the bottom there could be a separate link to view hidden comments._" because I think it is important to show the full discussion and not just the "moderated" version. If the author sees the need to hide some comments that's ok, but I would still like them to be available to everybody just like regular comments. I think this would be in the spirit of openness and transparency that dev.to is promoting.

**Comment by cmgorton** [comment]
Thank you for opening this request.
Features tend to be subjective and might spur some debate. The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
