### ISSUE TITLE
Basic markdown in title

### ISSUE THREAD

**Issue by Delta456** [forem/forem#5161]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allow basic markdown like bold, italics, underline, strikeout and `code` (only single ``) in title.

**Describe alternatives you've considered**
No

**Additional context**

**Comment by cmgorton** [comment]
Hey! Moving forward, we would love for people to head over to [forem.dev](forem.dev) for many of these feature requests that we need more discussion around.

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
