### ISSUE TITLE
Offline page does not look right

### ISSUE THREAD

**Issue by RehmatFalcon** [forem/forem#5162]
**Describe the bug**

The offline page for dev.to does not seem to be correct. I mean, it does not look like before. 

Only the bottom half of the Dev logo is visible.  As much as I can remember, the dev logo was centered in the screen and there were no footer.

**To Reproduce**

View Dev page in offline mode.

**Expected behavior**

Offline page as before.

**Screenshots**

![image](https://user-images.githubusercontent.com/28915667/71057014-5644c000-2183-11ea-9612-7c5590753e6e.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome 
- Version: 79.0.3945.79

**Comment by xtrp** [comment]
This might be due to the new addition of the default footer and navbar before load using a service worker.

Ben Halpern (founder of DEV) wrote about the addition of a service worker on his own blog post: https://dev.to/devteam/instant-webpages-and-terabytes-of-data-savings-through-the-magic-of-service-workers-1mkc

Looks like this could be solved by possibly removing that service worker JS file in the 404 page?

**Comment by Bam92** [comment]
I think I can help fix this. Is there someone working on already?

**Comment by cmgorton** [comment]
This appears to be fixed now. If you are still seeing this issue let me know and we can open this again. Thanks.
