### ISSUE TITLE
Add an easily accessible button in the UI to switch themes on the fly

### ISSUE THREAD

**Issue by sebastiantf** [forem/forem#5431]
**Problem**
Switching Dark Mode on and off requires the user to go to `Settings --> UX` which could be made a better user experience.

**Solution**
A simple one-click Dark Mode toggle button in the navbar/sidebar/profile-dropdown would be much more convenient and time-saving.

**Comment by rhymes** [comment]
Thanks @sebastiantf for the suggestion. Keep in mind that there are multiple themes so a selector should take that into account

**Comment by sebastiantf** [comment]
Yes @rhymes the selector would be really powerful if it could switch between the themes.

The main idea is to make switching between dark and light themes more fast, easy and convenient than going into the Settings.

It would be great if the button/solution could also switch between all the themes.

**Comment by rhymes** [comment]
Your suggestion makes sense, though I imagine it might have to be balanced with the fact that the feature "change theme" might not be needed with a frequency that a readily available button entails. If instead the frequency is higher (personally I never change theme so I don't qualify ahahha) as how your issue suggests, probably we should understand why.

What would your use case be @sebastiantf? Why do you find yourself changing the theme so often?

**Comment by sebastiantf** [comment]
I find myself reading posts at **`dev.to`** whenever I get some time. This free time might sometimes be during the daytime, and sometimes at night.

When I'm reading during the daytime, I really do prefer a light theme and at night, a dark theme. So I find myself doing the `Settings --> UX --> Change Theme` many times a week or so. It gets really boring when you do that a couple of times 🙁

That's my use case. If there isn't a huge support among the users for this feature, you may close this issue.

**Comment by rhymes** [comment]
@sebastiantf thanks for clarifying! It makes sense, I'm going to rename the title of this issue and keep it open. There's also an open issue on automatic switching https://github.com/thepracticaldev/dev.to/issues/2421

**Comment by sebastiantf** [comment]
Great @rhymes! Hoping for this issue to be implemented and closed soon.

#2421 is also a great requirement for **`dev.to`** Hoping to see that implemented too.

**Comment by ludwiczakpawel** [comment]
There are couple issues we should think about. One is the fact that we have multiple themes right now (three of them could be considered as _light_  and two of them as _dark_ ). We could just add a toggle in profile dropdown to quickly switch between each of them.

![image](https://user-images.githubusercontent.com/108287/72508901-ca3bbc00-3846-11ea-9348-e6cc4ff798f5.png)

But what if at some point we decide to support native dark mode (using `@media (prefers-color-scheme: dark)`)? We won't be easily able to switch between light and dark version of _pink_ theme or _10x hacker_ theme because they simply don't exist. And creating two variants for each them gonna be hard to maintain, especially if we ever add new themes.

---

So my suggestion is: lets have one default (aka OFFICIAL) theme for DEV. This one theme would have two variants: light & dark. Current variant would be obviously dependent on the media query I mentioned above. Additionally we could add a toggle for user to switch between light and dark variants manually - this toggle would exist in the same profile dropdown. But if user ever switch to some of the custom themes then we won't serve alternate color scheme.

So generally I think this discussion is about switching between light and dark variant (color scheme) rather than switching between actual themes.

![image](https://user-images.githubusercontent.com/108287/72510720-3966df80-384a-11ea-9a56-66f5f46f37d3.png)

**Comment by sebastiantf** [comment]
Great suggestion @ludwiczakpawel.

Can't we still show the theme switcher menu like the one shown in your first image if the user is on any of the custom themes?

So there could be two things to implement:
1. If the user is on the default/official theme, show only the **`Toggle dark/light mode option`** (2nd image)
2. If the user is on any of the custom themes, show only the custom theme switcher (1st image)

Would this be somehow better? Will **`2`** still cause problems/confusions if we decide to support native dark mode in the future?

**Comment by ludwiczakpawel** [comment]
@sebastiantf yea, I think that could work although we should check if it's worth the effort. In other words: is custom theme switcher used often enough to a) sacrifice such a prominent area in UI and b) actually spend time implementing that...

But overall, that's definitely interesting one :)

**Comment by sebastiantf** [comment]
As mentioned before, I did find myself reading DEV between day and night and switching between the themes often for better reading experience.

It would be good to know the views of other users in this issue and then make a decision.

**Comment by codeluggage** [comment]
I came here looking for this. 

Adding my thoughts to the discussion: 

1. Themes can generally be grouped into light and dark themes
2. Future features that switch themes based on time-of-day would ideally know which light theme you prefer, and which dark theme you prefer
3. Toggling quickly is ideal for many reasons. It is very pleasant for first time users, and to avoid too much light when trying to wind down for the day. 

For me personally the ideal case is a new button in the bar itself that can be clicked to toggle :)

**Comment by cmgorton** [comment]
Because of our recent changes to themes. I am going to close this issue.
