### ISSUE TITLE
Following a tag should update user sidebar stats

### ISSUE THREAD

**Issue by vaidehijoshi** [forem/forem#5657]
**Describe the bug**

After following a tag, the number of "followed" tags statistic on the user's sidebar does not update accordingly.

**To Reproduce**

1. Check how many tags you follow on your profile.
2. Go follow another tag.
3. Check your profile again, looking at the sidebar; the number won't have updated.

**Expected behavior**

I'd expect the "followed tags" count to increment.

**Screenshots**
On the dashboard, the number of tags is correctly accounted for:
<img width="954" alt="Screen Shot 2020-01-22 at 11 24 38 AM" src="https://user-images.githubusercontent.com/6921610/72927114-74fe1f80-3d0a-11ea-9063-137e66630854.png">

However, on the user page, the side bar stats don't reflect this:
<img width="979" alt="Screen Shot 2020-01-22 at 11 24 13 AM" src="https://user-images.githubusercontent.com/6921610/72927120-77f91000-3d0a-11ea-9b24-d7a4f9cc912e.png">

**Desktop (please complete the following information):**

OS: Mac Mojave 10.14.5
Browser: Chrome
Version: 79.0.3945.130 (Official Build) (64-bit)

**Additional context**

I suspect this is related to the caching logic behind tags; would probably start by looking into `@user.decorate.cached_followed_tags`.

**Comment by sunny-b** [comment]
I'm curious if it has to do with the fact that the `@user.decorate.cached_followed_tags` uses `updated_at` instead of `updated_at.rfc3339`

https://github.com/thepracticaldev/dev.to/blob/master/app/decorators/user_decorator.rb#L24

Every other `fetch` query that uses `updated_at` uses `updated_at.rfc3339`

Example: https://github.com/thepracticaldev/dev.to/blob/7c650dcb1c20efeebf209e2afd094b4c347409fd/app/labor/follow_checker.rb#L13

Using `updated_at` by itself will include spaces in the cache key while `updated_at.rfc3339` doesn't.

**Comment by sunny-b** [comment]
Actually, nevermind, I was able to reproduce this same stale cache behavior with comments as well. So it's not isolated to tag caching.

I think the issue is probably with this line:

https://github.com/sunny-b/dev.to/blob/d638f029e091b92eab0c3567350a25f9d59fed0b/app/views/users/_sidebar.html.erb#L47

That line caches the entire sidebar

**Comment by krzysiek1507** [comment]
I guess I should claim it since I submitted a PR already?

**Comment by vaidehijoshi** [comment]
> I guess I should claim it since I submitted a PR already?

You can! Or, since you already have "closes #5657" in your PR description, GitHub will automatically link your PR to this issue and when your PR is merged, this issue will be closed :)
