### ISSUE TITLE
Wireframing proposal for the videos page

### ISSUE THREAD

**Issue by madzadev** [forem/forem#5712]
**Is your feature request related to a problem? Please describe.**

Dev.to has a separate video page dev.to/videos.  It needs some more structure and layout, so I decided to do some wireframing on initial ideas to improve the particular section of site.

**Describe the solution you'd like**

**1.Dashboard**
This would be the landing page of the video section. The main section would be dedicated for most curated videos. The content feed could be made more personalized by developing an algo for it. User would also be able to see the uploads on specific tags he/she has subscribed as well as from persons he/she follows. There would be an option to heart and save for later on each video.

![Dashboard (3)](https://user-images.githubusercontent.com/42511917/73095539-87837f00-3eeb-11ea-887e-254350180a8d.png)

**2.Courses**
Content in each course would be hand-picked manually. User would be able to select his/her experience level (beginner-intermediate-advanced) to select the complexity of course concepts. The content would be sorted accordingly to provide a proper learning path.

![Courses](https://user-images.githubusercontent.com/42511917/73097381-bb60a380-3eef-11ea-87f4-f90dc0cb6924.png)

**3.Explore**
User would be able to explore the technologies of their interest (based on tags videos would get during the publish phase). There would be an option to sort displayed results based on the curates and most recent ones. There would be an option to heart and save for later as well.

![Explore](https://user-images.githubusercontent.com/42511917/73097398-c1ef1b00-3eef-11ea-8d46-33a5286dfabe.png)

**4.Favorites**
This section would display users activities - recently watched videos and saved for later list. Furthermore user would also be able to make collections, by sorting the videos he/she has liked.

![Favorites](https://user-images.githubusercontent.com/42511917/73097408-c87d9280-3eef-11ea-9abb-a23462161f27.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by maestromac** [comment]
Wow, thank you for all these wireframes and suggestions @madarsbiss ! I'm not sure how actionable it is at the moment but we appreciate the proposal.

**Comment by ludwiczakpawel** [comment]
Oh wow, this is great, indeed! Some of these ideas are really good ones and worth incorporating, for example:
- generally revamping /videos page
- having more personalized "feed" on /videos instead of just "the latest" is a no-brainer to me
- "courses" section is definitely neat idea, especially for less experienced devs trying to learn new things from video tutorials. 
- and obviously rethinking the grid itself - presenting bunch of collections of videos at the same time instead of a simple listing could be potentially much more engaging for user.

So yes, definitely some great ideas here.

Good thing is we're now exploring some improvements for Home Page feed. And that's something we will be doing for probably next couple weeks. Videos page would probably also benefit from the home page work we're doing right now so I think figuring out new version of /videos would be a great candidate for one of the upcoming cycles, once the Home feed is improved.

And of course, keep coming these great ideas! :)

**Comment by madarsbiss** [comment]
Thanks @maestromac and @ludwiczakpawel ! Dev.to is such an awesome resource with best community out there, so i figured out i was kinda cheating by using it and not giving back to improve it, hahah xdd

Its not a secret many of us prefer learning by watching videos rather than reading, so hopefully you will find a good use of the initial ideas :)

**Comment by cmgorton** [comment]
This was a beautiful wireframing 💜. 
This request has been around a while with not much traction.
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around it! 🙏
