### ISSUE TITLE
Add comments to moderation decisions

### ISSUE THREAD

**Issue by StefanDorresteijn** [forem/forem#589]
## Feature Request or Task
I'd like to see a comment field added to the moderation decisions.

### User Story / Description
As a moderator, I want to add a comment to my moderation decisions.

### Definition of Done
When a comment field has been added, the comment gets saved in the database and the staff can see the comment along with the decision (downvote/emoji that's about to throw up) and the person who made the decision.

### Benefit
This will allow users/moderators to explain why they made their chosen decision. This should make it quicker for staff to understand the decision and take action.

**Comment by benhalpern** [comment]
I think this makes sense. The internal tool we have right now is the "notes" model, which we could attach to either the reaction or the comment/article the user is reacting to. I think the latter would be the saner choice. Basically those act as internal comments.

We have the concept of "note" instead of an "internal" or "private" type of comment. I feel like that's what we want to run with.

**Comment by Zhao-Andy** [comment]
Not stale

**Comment by maestromac** [comment]
not stale

**Comment by cmgorton** [comment]
Thanks for bringing this up but this issue has appeared to become stale. I am going to go a head and close this issue. 
Please feel free to open up it up again in the future if you believe it would still be a useful feature.
