### ISSUE TITLE
Overview of my own series

### ISSUE THREAD

**Issue by jhermann** [forem/forem#6938]
**Describe the solution you'd like**

In the personal menu, near "Dashboard", there should be a "My Series" item, leading to an overview of series I created. Alternatively, dashboard could get "All" (like now), "Posts", "Series", and "Comments" tabs.

The "Series: …" indicator above articles in the dashboard should link to an overview page for that series (cf. #2424).

*Other users* could get a link to the “all series by…” overview on my profile page.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by jessleenyc** [comment]
Hey @jhermann! A series filter on the dashboard makes sense. We'll need to think further on what an external shareable link would look like for a series though. If you have suggestions on the design/layout/implementation, feel free to share and we can discuss further.

For any contributors - right now this issue is approved for adding a series filter but an external link is TBD.

**Comment by Oghenebrume50** [comment]
![seriessss](https://user-images.githubusercontent.com/37092867/85602942-c9098900-b647-11ea-9121-8a159d4be288.png)

Hi, @jessleenyc @jacobherrington if I am correct, the solution needed here is to have an extra tab(my_series), show up in the dropdown tab, just like the above screenshot and when it is clicked on a page of the user's series display with each series grouped together nicely, is this the right approach? if not I will need more clarity so I can go ahead with this

**Comment by jacobherrington** [comment]
@Oghenebrume50 I think that is one option, but I might go with adding a filter on the existing dashboard because I think it provides a better user experience. I think it makes sense to group it in the same place we currently list all of a user's articles.

I'd put a link somewhere [on the dashboard](https://dev.to/dashboard), maybe next to "Show archived"?

![image](https://user-images.githubusercontent.com/11466782/85634639-75943c80-b641-11ea-818d-cbdc28f0eb4c.png)

**Comment by rhymes** [comment]
pinging @lisasy and @ludwiczakpawel as they are our resident designers

**Comment by ludwiczakpawel** [comment]
Hey! This is a neat idea, I really like it. We're currently working on some dashboard updates so lets wait couple more days until we ship these and then lets come back to this idea and think how this could potentially fit there.

I'm not a big fan of adding this link to the profile dropdown though - it doesn't seem to me like a good place for this not-so-common action. But dashboard - yea, that feels much more appropriate.

**Comment by Oghenebrume50** [comment]
@ludwiczakpawel awesome, I guess I would wait a while for the new dashboard design before I continue working on this

**Comment by Oghenebrume50** [comment]
Hi, @ludwiczakpawel now that the new dashboard is up, I guess it is okay to start working on this, will the position on the below screenshot be okay ?
![series rails](https://user-images.githubusercontent.com/37092867/86039150-ebc9e200-ba39-11ea-8e68-76387d9b1931.png)

**Comment by ludwiczakpawel** [comment]
@Oghenebrume50 I'm not sure if it deserves its own spot in this subnavigation. Instead I'd do some shuffling on top of the posts table. Right now we have 3 controls there:

- Show archived (button acting like a toggle)
- Sorting options (select)
- Source (if you're part of organization you can see a field which lets you filter whether you see personal posts or organization posts)

![image](https://user-images.githubusercontent.com/108287/86235489-cc959680-bb98-11ea-90bd-2fa0e64e0863.png)

Instead of that very first button I think it would make sense to have another select there with "filtering options" like:
- Active (non-archived) posts
- Archived posts
- **Series**

Something like this: https://d.pr/v/V8lhKe

**Comment by rhymes** [comment]
@ludwiczakpawel the issue I see in that proposal is that series is not a type of articles, it's a label for a collection of articles

**Comment by Oghenebrume50** [comment]
@rhymes @ludwiczakpawel I actually have a draft PR for this already based on my first proposal maybe I can open that and mention you guys there, I also think it will be confusing having series in that filter but maybe the PR will give more insight :slightly_smiling_face:

**Comment by ludwiczakpawel** [comment]
> the issue I see in that proposal is that series is not a type of articles, it's a label for a collection of articles so it's a bit weird to see it as a third boolean option of archived or non archived

@rhymes @Oghenebrume50 I hear you, but "archived" is also not a post type, right? It's just kind of a flag that let you narrow down the list of posts. I think we could have even more "flags" like this and all of them could be put in one select:

- Published (selected by default)
- Drafts
- Series
- Archived
- Videos
- ...

Do you think that doesn't make sense?

**Comment by Oghenebrume50** [comment]
@ludwiczakpawel got it, but quick question, currently when the "show archived" button is clicked the archive post is added to the list of active post, I guess if we are to add series to that we cannot do that, but we would have to replace the content of that `div` with the list of series

**Comment by ludwiczakpawel** [comment]
@Oghenebrume50 I think the current solution is suboptimal - I think once you hit "show archived" it should replace the list of posts instead of adding them to the existing list. And that would/should be a behavior for other "filters" I mentioned earlier. I think... :)

**Comment by rhymes** [comment]
@ludwiczakpawel you're right, `archived` is a flag, but it's a property of an article. Series is actually not even an article object in domain terms. That's why I think it'd be weird to have it in the list of articles. 

`archived: true` means "load all articles that have `archived` set to true" from https://github.com/thepracticaldev/dev.to/blob/master/app/models/article.rb
`series` means `load all series` from https://github.com/thepracticaldev/dev.to/blob/master/app/models/collection.rb

**Comment by ludwiczakpawel** [comment]
> series means load all series from https://github.com/thepracticaldev/dev.to/blob/master/app/models/collection.rb

@rhymes wait wait wait.. what I thought this was about is that we're not going to have an entity (model) for SERIES and therefor this view will not list SERIES. I thought that view was about to display only posts being part of any series...

Are we on the same page?

**Comment by rhymes** [comment]
@ludwiczakpawel I think it's just the list of the series:

> The "Series: …" indicator above articles in the dashboard should link to an overview page for that series (cf. #2424).

It'll be augmented with links to a landing page if we go ahead and implement https://github.com/thepracticaldev/dev.to/issues/2424

That's how I understood this :D

**Comment by ludwiczakpawel** [comment]
Ok yea, then that makes more sense I guess :)

**Comment by Oghenebrume50** [comment]
@rhymes yes, I think #2424 would be the landing page for each series being shown, I have direct access to the @AlbertoPdRF so we can work together on making both issues together, @ludwiczakpawel going by the newest development, is #9054 still the way to go? :thinking:

**Comment by ludwiczakpawel** [comment]
@Oghenebrume50 yeap, green light. As mentioned in #2424 

> I'm happy to jump in and help with UI and frontend whenever the backend part is ready :) Just let me know!
