### ISSUE TITLE
Generalize specific user's profile fields

### ISSUE THREAD

**Issue by lightalloy** [forem/forem#6994]
We have several fields in the `User` model that are specific to developers, like `currently_hacking_on`, or work-related ones, like `employment_title` or `employer_name`.

The fields are:
- set up on the user's profile form (`app/views/users/_profile.html.erb`)
- displayed on the user's profile page (`app/views/users/_sidebar.html.erb`)
- displayed on the article sidebar: (`app/views/articles/_user_metadata.html.erb`)

We may want to make the fields that are set by a user and displayed on the user's and article's pages.

**Comment by lightalloy** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by Ridhwana** [comment]
@lightalloy wanted to find out what your thoughts were on implementation details for the above?

**Comment by lightalloy** [comment]
@Ridhwana I don't have a complete solution in my mind right now but here are some thoughts:
We could have a `jsonb` field in `users` (or a related table) to store community-specific fields. The community-specific fields themselves could be set up in the `SiteConfig`.
All of these fields will be set up in the user form, so there is no need for a configuration here.
But we'll need a configuration to set up which fields will be displayed in the article sidebar and on the user profile page. This could be another configuration in `SiteConfig` (could be set up together with the list of the community-specific fields, but for now it seems like a separate one, should be more clear while working on it)

However, we should keep in mind that this approach will require existing data migration, and think of the cases when the configuration changes (if it will cause problems or not).

**Comment by benhalpern** [comment]
I think we should move to get this implemented.

I think we should use the `user_optional_fields` so each user can have a `has_many` relationship with their fields. We can use `SiteConfig` to manage which user fields exist, but then dynamically generate them if they are added in settings or onboarding.

We can have an `onboarding_profile_fields` config to dictate which are included.

...And then finally, the primary reason this table was added was to literally include _optional_ fields, so I think we could add the ability to define some custom fields such as pronouns etc. But I think that could be secondary to getting this working for generalization/onboarding.

**Comment by citizen428** [comment]
I had a look at this now. `user_optional_fields` were added in April (#7246) to accommodate custom pronouns (#2365). As part of the discussion on that issue, it was [suggested](https://github.com/thepracticaldev/dev.to/issues/2365#issuecomment-555044836) that

(a) custom fields should be implemented in a separate model and
(b) limited in number (the current maximum is 3, see `validate_quota` in `app/models/user_optional_field.rb`﻿﻿).

Some thoughts/questions/points for discussion:

* The current implementation caters for completely custom fields, where  users can define both label and value. This might get confusing if people start using different labels for essentially the same thing. Using "`onboarding_profile_fields` config to dictate which are included" would remedy that to a certain degree, but a Forem may want to have an "official list" of fields but not force the users to fill them in during onboarding or make the form dauntingly long. So I wonder if we should have a `ProfileField` model that is managed by admins through `/internal/config`, which configures the "official" fields so `onboarding_profile_fields` would be a subset of `available_profile_fields` or whatever we want to call that setting.

* If we do what's outlined above, we could still keep optional user fields to give users more freedom, but keep them limited (but maybe make the limit configurable instead of hardcoding it to 3).

* We'll need an official list of fields to move to `UserOptionalField` and/or `ProfileField`. `User` has a lot of attributes (`user.attributes.keys.size #=> 125`) and quite a few only make sense in the context of software development. We also need a migration strategy for this (i.e. creating the fields, backfilling the values, then making the switch, potentially field by field).

**Comment by benhalpern** [comment]
Yeah, I think we may want to have `UserOptionalField` be one thing and `ProfileField` be another (as defined by the platform)... Either way, there are the literal rows, always being x to a single user, and then there's the configuration of the schema as a whole probably defined in `SiteConfig`.

Either way I get the sense that @citizen428 you are thinking about this the right way so if you want to work this out I say go for it. Definitely in favor of migrating away from the software-specific stuff, deleting those rows, and then having a backfill strategy.

**Comment by citizen428** [comment]
> Either way I get the sense that @citizen428 you are thinking about this the right way so if you want to work this out I say go for it.

👍 I have some things I want to finish today, but I'll start putting together a plan after that

**Comment by AfroDevGirl** [comment]
@Ridhwana @citizen428 So now that we can customize the profile there is one slight issue I noticed. I think some of the fields on the actual profile view are hard coded. You can see the issue here on the left sidebar: https://community.iqasport.com/aewingmoody. The custom field descriptions should be 'Teams' and 'Positions' not 'skills/languages' and 'learning/trying' respectively.

**Comment by citizen428** [comment]
@AfroDevGirl Yes, there is still a lot of work outstanding in terms of profile generalization, but I hope we get to a point where we can involve the wider community soon, maybe as early as this week 🤞

**Comment by AfroDevGirl** [comment]
@citizen428 Definitely understandable. Unfortunately this is probably the last hang up I have with custom fields. I'd be happy to work on it if y'all feel comfortable doing that, but I completely understand if that's not possible at the moment. I'll just have to keep an eye on it so we can launch as soon as it's ready.

**Comment by citizen428** [comment]
@AfroDevGirl I had a quick look at this, the culprit was `app/views/users/_sidebar.html.erb`, you can see all the hard-coded fields there. I made a quick POC locally, will turn this into a proper PR now and tag you on there so you can follow along 😃

**Comment by benhalpern** [comment]
I think I have a decent handle on what's left to do... Throwing my hat in the ring with this PR I'll flesh out over the next few days.

https://github.com/forem/forem/pull/12015

**Comment by citizen428** [comment]
I think this issue has been around long enough, it's time to break it into smaller issues for the remaining subtasks, which I'll do now.
