### ISSUE TITLE
Filter reading list by author and/or date range

### ISSUE THREAD

**Issue by Stargator** [forem/forem#709]
## Feature Request or Task
Add ability to filter Reading List by Author and date range

### Definition of Done
The user is able to select an author from a list generated by all the authors who has at least one post saved as a bookmark by the user. Which then filters out all the posts so only those by the author appear. Can work in coordination with the tag selected and/or the date range defined by the user.

The user is able to define a date range that would then filter out all the saved posts in the Reading List so only the posts that fall within the date range are displayed. Can work in coordination with the tag selected and/or the author as selected by the user.

### Additional Info (device/browser, helpful links)
MacOS 10.13.1, Chrome 69

**Comment by jessleenyc** [comment]
Hey @Stargator, thanks for this issue. This is something we'll try to get to early next year. If anyone else wants to take a go at an implementation, by all means.

**Comment by Olyno** [comment]
Hi,
Like I said in a recent issue (see above), maybe add a search bar to just be able to find any article in our Reading List depending what we type could be really good in the Reading List header on the right of the title. It should not be a hard feature to implement, and should be really benefic to Dev.

**Comment by rhymes** [comment]
Hi @Olyno, I think since this issue was opened a few things have changed.

The reading list now has free form search and filtering by tag. You can find them on the left sidebar:

![Screenshot_2020-03-16 Reading List - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/76735070-7543f580-6764-11ea-943c-4c268cdfc0da.png)

if I type `api` the results are searched by that keyword:

![Screenshot_2020-03-16 Reading List - DEV Community 👩‍💻👨‍💻(1)](https://user-images.githubusercontent.com/146201/76735107-83921180-6764-11ea-995b-78c364465872.png)

Let me know if that's what you're looking for. I'm going to update the title of this issue to reflect the correct feature request

**Comment by Olyno** [comment]
Oooh indeed, I didn't see it, good to know, thanks for the information 😅

**Comment by rhymes** [comment]
Ahah don't know to be honest, I never know if sidebars should be on the right or on the left. There are plenty of cases for both of them. Anyhow, you could open a feature request to move the sidebar on the right.

I did with the developer tools and this is how it looks:

![Screenshot_2020-03-16 Reading List - DEV(local) Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/76744497-99a7ce00-6774-11ea-9699-58e8833328ce.png)

**Comment by Olyno** [comment]
I think not the place of the sidebar itself should be change. I mean, the search bar is in the sidebar, so technically it makes the same that the top search bar (the main one).
It's not explicit about the fact that this search bar is linked to the Reading List.
In my opinion, only the search bar should be move.

**Comment by rhymes** [comment]
@Olyno could you open a separate feature request about this? This way we don't lose this conversation as this issue is about another topic. Thank you!

**Comment by cmgorton** [comment]
Hey this issue has had a good discussion going but seems to be stale now. 
Since we have a search feature in our reading list implemented now I am not sure this date/author filtering is needed. I am going to go a head and close this issue. If you feel like this would still be a good feature please feel free to open an issue for this request again. Thanks.

**Comment by Stargator** [comment]
@cmgorton I do still feel it has value because I want to look at the older posts and currently I'd either have to know exactly what I am looking for or scroll down into the bottomless pit that is my reading list :D

Perhaps the search functionality could include attributes like a date range? That way the layout doesn't change too much
