### ISSUE TITLE
I am not subscribed to the comments of my new posts by default

### ISSUE THREAD

**Issue by emgoto** [forem/forem#7111]
**Is your feature request related to a problem? Please describe.**

When I create a new post, I am not subscribed to the comments, and so I wont receive any notifications if someone comments. After creating a post I have to make sure to subscribe to the comments.

**Describe the solution you'd like**

I create my posts via my personal website's RSS feed - I'm not sure if it this is related to the problem.

**Comment by citizen428** [comment]
Thanks for the report @emgoto!

We already have notifications for this type of thing:

![dev_notifications](https://user-images.githubusercontent.com/47985/78624382-a753fd80-78b3-11ea-9f1f-fbf7559cf375.png)

This is how a single notification looks like:

![dev_not](https://user-images.githubusercontent.com/47985/78624403-b5a21980-78b3-11ea-8f61-bedc7c7cdcc2.png)

Additionally, you can enable email notifications:

![dev_not_settings](https://user-images.githubusercontent.com/47985/78624427-c3f03580-78b3-11ea-8103-43d8cb6bd0fd.png)

A few questions in order to triage this issue so we are able to help you better:

1. Are you not receiving notifications as shown above?
2. If you are, are they sufficient or is there anything else you'd like to see?

**Comment by emgoto** [comment]
I do get notifications when people reply to one of my comments (i.e. that thing you're pointing to with the arrow in the image) but I don't get any notifications for when a person comments on my post, specifically - not in reply to one of my comments, but just as a comment on its own.

If I scroll back through my comment notifications, they're all just replies to my comments.

**Comment by citizen428** [comment]
Thanks for clarifying @emgoto, we'll look into it.

**Comment by cmgorton** [comment]
@emgoto is this still an issue for you. I am always notified when someone comments on one of my posts. I am going to close this issue but will reopen it if this is an ongoing issue for you. Thanks.

**Comment by emgoto** [comment]
Hiya! I've noticed that whenever I make a new blog post, by default I am
unsubscribed from the comments. So if I subscribe, it's okay. I'm not sure
why that is, though.

**Comment by cmgorton** [comment]
Thanks for letting me know @emgoto . I will open this back up for now while we continue to figure this out. 
One question. If you go to [https://dev.to/settings/notifications](https://dev.to/settings/notifications) do you have these areas checked? 
![Screen Shot 2021-01-28 at 3 27 57 PM](https://user-images.githubusercontent.com/21039864/106201128-9c899280-617d-11eb-8717-d334e0075be6.png)

**Comment by emgoto** [comment]
I have the mobile notifications on, but not the other two.

**Comment by cmgorton** [comment]
Could you try checking the bottom one? Once you have it checked I can try commenting on one of your posts and seeing if you get a notification. 
![Screen Shot 2021-01-28 at 3 46 47 PM](https://user-images.githubusercontent.com/21039864/106202877-29355000-6180-11eb-8c6e-4075634a3365.png)

**Comment by emgoto** [comment]
Sure - I've turned on that setting, and I have unsubscribed from my latest
blog post so you can comment on that one.

**Comment by cmgorton** [comment]
Thank you Emma. I commented on this post https://dev.to/emma/how-to-write-to-files-with-node-js-3439. Let me know if that wasn't your latest.
Let me know if you get a notification or not and we can delete my comment after you confirm one way or the other. And thanks for walking through these steps with me so we can try to figure out this bug.

**Comment by emgoto** [comment]
Hi, I didn't get a notification.

**Comment by emgoto** [comment]
Another thing that may be relevant is that I create my posts via the RSS feed.

**Comment by cmgorton** [comment]
Ok thanks for helping me narrow this down. 😄
I deleted my comment on your post and I will keep this issue open. Going to see if someone else on the team has any ideas!

**Comment by citizen428** [comment]
@rhymes Since you most recently touched the RSS importer code, can you think of a reason why this would happen when importing posts via RSS?

**Comment by rhymes** [comment]
I found the answer, the TLDR is that we don't create a subscription between the author and their article when we import via feed 

BTW that particular setting only manages reactions, not comments:

https://github.com/forem/forem/blob/82585464b9704cbf46b4a9016cafa0bb70259187/app/workers/notifications/new_reaction_worker.rb#L15-L16

https://github.com/forem/forem/blob/82585464b9704cbf46b4a9016cafa0bb70259187/app/workers/notifications/new_reaction_worker.rb#L19-L24

so if `reaction_notifications`, which is a boolean value in the `users` table set by the aforamentioned setting, is `true` then the notification is sent.

The text in the screenshot says "when someone reacts to my comments or my posts" which means "leaves a reaction to a post of mine or a reaction to a comment of mine". Comments in the code aren't `Reaction` object, they are just... comments. So that box won't determine if one is sent a notification for a brand new comment left under a post.

What determines if a notification for a comment is sent is the method `Notification.send_new_comment_notifications_without_delay` which is called here:

https://github.com/forem/forem/blob/82585464b9704cbf46b4a9016cafa0bb70259187/app/controllers/comments_controller.rb#L73

in the "create a new comment" action.

So, by following the thread of the code, `send_new_comment_notifications_without_delay` has this logic:

https://github.com/forem/forem/blob/82585464b9704cbf46b4a9016cafa0bb70259187/app/models/notification.rb#L47-L52

- don't send a notification if the comment was left under a podcast episode
- don't send a notification if the user has been blocked by the article's author

Finally, the class `Notifications::NewComment::Send.call(commnt)` gets triggered and does a bunch of stuff. Aside from not sending the notification if the comment's score is negative which I don't think it's the case here, it also does not send a notification to the article's author if they are not subscribed to the comments.

The logic here:

https://github.com/forem/forem/blob/82585464b9704cbf46b4a9016cafa0bb70259187/app/services/notifications/new_comment/send.rb#L19

- sends a notification to each of the comment's ancestors authors
- sends a notification to all users that have subscribed to `all_comments`
- sends an optional notification to all users that have subscribed to `top_level_comments` if the comment is indeed top level
- sends an optional notification to all users that have subscribed to `only_author_comments` if the comment was indeed left by the author of the article

According to

https://github.com/forem/forem/blob/82585464b9704cbf46b4a9016cafa0bb70259187/spec/services/notifications/new_comment/send_spec.rb#L51-L56

we do create a notification for the article's author but it took me a second to understand where in the logic we actually include the "article's author". The id of the article's author is not "explicit", it appears in `subscribed_user_ids` which, kinda make sense, treats the article's author as a regular user subscribed to all the comments.

So, we know there's no subscription. The reason being:

- articles created via the editor use the `Articles::Creator` class which sets up a subscription
- articles created via the API use the `Articles::Creator` class which sets up a subscription
- articles imported via feed don't use the class :-( 

We never did AFAIK, the [previous incarnation of the feed importer](https://github.com/forem/forem/pull/12169/files#diff-1aaacfa2aad355a348ccdefe47bd6a2b1bef2d9578d470093f08fdb895170d88) only created the article and never set up subscriptions. 

I think subscriptions came later and the feed importer was never updated which makes sense because articles imported via feed are imported as drafts, and we only send notifications when they are published.

Anyway, now we know what's going on. 

**Proposed solutions**

- we create the subscription inside `Feeds::Import` (we can't use `Articles::Creator` because it uses different params)
- we create the subscription inside `Articles::Updater` but the updater is only used in the API so we'd have to duplicate in the `ArticlesController#update`

We probably also need a "data update script" that re-creates subscriptions for the author for all existing articles imported via feed 😢

**Comment by rhymes** [comment]
My vote goes to creating the subscription inside `Feeds::Import` and adding the script to align existing articles

**Comment by cmgorton** [comment]
Thank you for looking into this more @rhymes. I appreciate the detailed investigation here.

**Comment by cmgorton** [comment]
Yay! @emgoto I know you opened this issue awhile ago but there is now a fix for this from PR #13717.
