### ISSUE TITLE
 ArgumentError at /users/auth/github/callback

### ISSUE THREAD

**Issue by dravitykeeper** [forem/forem#7134]
**Describe the bug**: When clicked on login in with github it shows 
ArgumentError at /users/auth/github/callback

wrong number of arguments (given 2, expected 0..1)

![image](https://user-images.githubusercontent.com/46466273/78666061-68926780-78f4-11ea-866f-d544ecb286bf.png)

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Firefox

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @dravitykeeper, thanks for the report! I think that coincidentally you've highlighted a different bug which prevents you to find out why you're experencing an authentication error.

What the error is saying is that `Rails.logger.error` accepts up to 1 argument, instead of 2. The reason why the code is like that is that we used to use Timber which unfortunately hijacks the `Rails.logger` changing its interface, allowing 2 arguments for structured logging. Since a while ago Timber logging is only enabled in production, hence that error.

What you can do to figure out what's going on is to add a `binding.pry` statement to the following method and investigate what's going on there, or just evaluate that hash and report back here so we can help :)

https://github.com/thepracticaldev/dev.to/blob/b1ebc32e454bd3fe70abf76edcb83b2ec74594ac/app/controllers/omniauth_callbacks_controller.rb#L15-L25

My suspicion is that something is not correctly configured withing your Github account, but it maybe a legit bug, don't know which yet :D 

We'll be fixing the problem with the logger in the meantime. 

Thank you!

**Comment by cmgorton** [comment]
I am closing this for now. But if you continue to experience any issues please let me know and we can reopen this!
