### ISSUE TITLE
Open-source marketplace

### ISSUE THREAD

**Issue by jonathan-irvin** [forem/forem#739]
## Feature Request or Task

Similar to the "pitch your Opensource" article @benhalpern does weekly, except it would a page that you could "register" your open-source project for other community members to discover.

Additionally, users can "follow" an open-source project on dev.to and get articles posted by that project in their feed.

This would also attract members to contribute and help discover new projects.

### Definition of Done

This is a big feature that would need to be fleshed out more, but the idea is maybe a 12-cell grid with a summary of projects and users could click on the project and get a summary of articles written by that project and get some details (possibly pulling from the Readme on github)

**Comment by benhalpern** [comment]
Sorry I didn't get to this sooner, but I am super duper duper in favor of this.

**Comment by maestromac** [comment]
not stale

**Comment by jonathan-irvin** [comment]
bump?

**Comment by cmgorton** [comment]
Hey Jonathan, thank you for your suggestion but since this is currently stale and given this is a very DEV-centric feature I would propose we forgo this and the added complexity it brings to our base codebase.
We have started to think more in terms of the overall needs of Forem. I am going to go a head and close this issue. If you feel like this could still be useful feel free to open an issue again.
