### ISSUE TITLE
Twitter timeline support

### ISSUE THREAD

**Issue by AntonyGarand** [forem/forem#7605]
**Describe the bug**

Twitter timelines, such as [this one](https://twitter.com/FreyaHolmer/timelines/1215413954505297922), are not supported by the liquid tags.
Instead, a "Liquid error: internal" message is shown.

**To Reproduce**

{% twitter 1215413954505297922 %}

**Expected behavior**

Either a message such as "Timelines are not supported", or a proper "embed" for these.

I'm not sure how the API handles these results or if we can actually embed them, but the website should beautifully handle this case.

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rafaltrojanowski** [comment]
I can't reproduce this issue. Most likely solved here 300ba1b33f
<img width="823" alt="Screen Shot 2563-10-07 at 10 09 01" src="https://user-images.githubusercontent.com/1567767/95304580-220ecd00-0885-11eb-8e60-8b1b1beaae4f.png">

**Comment by rhymes** [comment]
@rafaltrojanowski this is not an issue though, it's a feature request, to add support for timelines, this one for example https://twitter.com/FreyaHolmer/timelines/1215413954505297922, as embedded content

I can't find them in the the [API v1.1 documentation](https://developer.twitter.com/en/docs/twitter-api/v1) so I guess the only alternative is to embed, something like this, in an iframe:

```html
<a class="twitter-timeline" href="https://twitter.com/FreyaHolmer/timelines/1215413954505297922?ref_src=twsrc%5Etfw">Math - Curated tweets by FreyaHolmer</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
```

from https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2FFreyaHolmer%2Ftimelines%2F1215413954505297922&widget=Timeline

We should probably add a parameter to tell the Twitter liquid tag that that's a timeline

**Comment by rafaltrojanowski** [comment]
Hi @rhymes 

> We should probably add a parameter to tell the Twitter liquid tag that that's a timeline

I did a small POC and introduced a new liquid tag because it was simply an easier approach for me. I didn't want to mess up with Twitter logic and I would like to keep classes and templates as small as possible. I'm open to ideas on how to move this logic if it's needed.

There is a small drawback though, seems that the tag name does not support dashes, so I went with an underscore.
Another thing that I'm not super happy with is argument format, I could not come with anything better so here is how it goes:

```
{% tweet_timeline FreyaHolmer/timelines/1215413954505297922 %}
```

I believe it's still better than two parameters ie "user", "timeline_id". 
Just an idea - maybe we could go with `FreyaHolmer/1215413954505297922`?

After hitting save everything works as expected and the Twitter timeline is rendered correctly:

![Screen Shot 2563-10-12 at 12 04 57](https://user-images.githubusercontent.com/1567767/95733973-2c650880-0c83-11eb-804a-6420756a64eb.png)

By chance, I'd like to mention 2 things:
1) It does not work with the preview, I'm not sure if it's blocking or not and how much Javascript work it would require.
2) I don't understand how scripts are injected to liquid tags, and why the following script does not work:

```
SCRIPT = <<~JAVASCRIPT.freeze
    console.log('test);
    $( document ).ready(function() {
      console.log( "ready!" );
    })
    $( document ).on('turbolinks:load', function() {
      console.log("It works on each visit!")
    })
JAVASCRIPT

def self.script
  SCRIPT
end
```
Would appreciate it if somebody could explain what I'm doing wrong. It's not super important, I'm just curious :)

**Comment by rhymes** [comment]
Hi @rafaltrojanowski  

I think we could support the full URL so one can do copy and paste like we already do in some other liquid tags. This way you don't have to figure out an argument, format, just validate the URL. Tags like `AsciinemaTag`, `CodepenTag`, `GistTag`, `GitPitchTag` and others use URLs as arguments.

Maybe the name should be `twitter_timeline` instead of `tweet_timeline`, I'm not sure.

Regarding the preview I think we can figure it out in front of a PR, not sure what might be happening right now.

The reason why the `script` written in the tag doesn't reflect in the page is that it's manually injected in the ERB template here:

https://github.com/forem/forem/blob/177659fd2eddcbe97684e2e5b05dc20a0ed4c314/app/views/articles/show.html.erb#L246-L255

and here:

https://github.com/forem/forem/blob/177659fd2eddcbe97684e2e5b05dc20a0ed4c314/app/views/comments/index.html.erb#L131-L136
