### ISSUE TITLE
dev.to flooded by spam bot posts

### ISSUE THREAD

**Issue by ekafyi** [forem/forem#8459]
I'm not sure where to report this; feel free to close / move it elsewhere if not appropriate.

Lately I've seen an increasing number of Indonesian spam posts advertising dangerous illegal drugs. Judging from the content (same content with different city names), it seems to be auto generated with a bot/script.

Examples:
- https://dev.to/samsircedek/jual-obat-aborsi-di-palangkaraya-wa-085268881116-alamat-apotik-penjual-obat-cytotec-aborsi-penggugur-kandungan-di-palangkaraya-1h8k
- https://dev.to/081391421099/jual-obat-cytotec-obat-aborsi-malang-wa-081391421099-cara-menggugurkan-kandungan-paling-ampuh-5644
- https://dev.to/samsircedek/jual-obat-aborsi-di-kendari-wa-085268881116-penjual-obat-cytotec-aborsi-penggugur-kandungan-di-kendari-5b0c
- https://dev.to/081391421099/jual-obat-cytotec-obat-aborsi-jogja-wa-081391421099-obat-aborsi-jogja-3n
- https://dev.to/obatgransi/jual-obat-aborsi-cytotec-cod-jayapura-081230087272-bergransi-4bi1
- https://dev.to/obatgransi/jual-obat-aborsi-cytotec-di-banjarbaru-081230087272-bergransi-3nj0
- https://dev.to/samsircedek/jual-obat-aborsi-di-tegal-085268881116-penjual-obat-cytotec-aborsi-penggugur-kandngan-di-tegal-375o
- https://dev.to/obatgransi/jual-obat-aborsi-cytotec-cod-teggarong-081230087272-bergransi-fe8

I have no proposed solution, but maybe we could limit posts API for users based on level of community activity? And/or moderate first x posts of a user?

**Comment by Muhimen123** [comment]
Yes, I agree. I have also seen these spams here and there(not only in this repository). Though these spams aren't harming much, the authority must take steps. 

> maybe we could limit posts API for users based on the level of community activity

This sounds to be a good proposal but it is easy to open a fake account in Github(or anywhere else).  Closing the issues(spam) as soon as they appear will be a good solution according to me. 

I'm pretty sure the authority has seen this and will take a proper steps.

**Comment by Rafi993** [comment]
Websites like stackoverflow allow users who have reached certain points to unlock features or remove some limits. Eventhough this points may not be visible to user like stackoverflow  (since it might discourage new users) it might help to ward of spam.

**Comment by Rafi993** [comment]
> Websites like stackoverflow allow users who have reached certain points to unlock features or remove some limits. Eventhough this points may not be visible to user like stackoverflow (since it might discourage new users) it might help to ward of spam.

But this point system might introduce implicit biases so it should be thought really carefully.

**Comment by michael-tharrington** [comment]
Hey folks!

I appreciate y'all flagging these accounts to us. Yesterday we did get hit with quite a few spammers, so apologies if your feed got clogged up with junk for a bit.

Luckily, we have [moderators](https://dev.to/community-moderation) who were quick to flag this behavior to us so we could remove the content and deal with the users creating it. We also have this page - https://dev.to/report-abuse open to the public for reporting problem users and articles — quite a few helpful DEV users flagged these accounts to us via this system. A link to the "report abuse" page can be found just beneath the discussion/comments section of each post.

All this said, there are likely improvements we can make to our automated spam fighting capabilities, and we are definitely open to feedback there. While we'd prefer not to limit anyone's posting abilities from the get-go, we do currently have a way to watch over first posts by users. It's still reactive in nature because one must manually check these posts, but it's a good tool to have. 

We're continuously looking for both proactive and reactive ways to fight spam — the better we can get at this, the better the site will be for everyone. If you have an idea, don't hesitate to make a feature request. Also, you can look here - https://github.com/thepracticaldev/dev.to/labels/area%3A%20fighting%20abuse to see some of the ideas others have come up with if you want to comment on any of these.

Again, thanks for your help with flagging this spam!

**Comment by patarapolw** [comment]
How about an API playground, like `https://temp.dev.to`?

**Comment by Rafi993** [comment]
There were some spam bots today url https://dev.to/search?q=customer%20care%20number&filters=class_name:Article shows all the spam bots created in that time thanks to this comment  https://dev.to/khmarbaise/comment/15md9

**Comment by anishpr94** [comment]
dev.to is flooded with 
glowroad customer care number.9668236527_9668236527
kind of posts. Please bring in a way to filter out such spams, atleastby user. Even after blocking it is coming in my feed.
