### ISSUE TITLE
Allowed to enable Markdown RSS import ?

### ISSUE THREAD

**Issue by negue** [forem/forem#8794]
**Is your feature request related to a problem? Please describe.**

I'd like to enabled the Markdown RSS import. Cause the generated HTML might not be fully understood from the HTML-to-Markdown Parser.

I guess me #7923 and others #8457 not the only ones that want to import the raw markdown by rss instead of:

Markdown -> HTML (probably with their own site's flavor) -> RSS -> Import by DevTo -> HTML-to-Markdown

I want to do this:

Markdown -> RSS -> DevTo 

**Describe the solution you'd like**

If its ok, I'd like try to do this, if it is something that would be allowed & merged.

**Describe alternatives you've considered**

**Additional context**

Instead of `content:encoded` I may use `content:markdown` or something like that.

I don't have any experience in ruby yet, so this would be also a nice way to try it.

**Comment by citizen428** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
> Instead of content:encoded I may use content:markdown or something like that.

One thing to keep in mind here is that the RSS 2.0 spec doesn't really provide for this scenario:

> The content must be suitable for presentation as HTML and be encoded as character data in the same manner as the description element.
Source: https://www.rssboard.org/rss-profile#namespace-elements-content-encoded

Since there is no way to specify the format of the content, this should not require additional preprocessing steps. Markdown itself is not valid and I'd be reluctant to add a custom tag that only we know about.

One alternative that has been used for this scenario in the past is using a Github action in combination with the DEV API, see e.g. https://github.com/sinedied/publish-devto-template.

**Comment by cmgorton** [comment]
Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
