### ISSUE TITLE
Expand shortened URLs

### ISSUE THREAD

**Issue by moopet** [forem/forem#8852]
**Is your feature request related to a problem? Please describe.**

Shortened URLs are generally not useful for anything other than reading to people over the phone.

A link in a post to bit.ly/something123 gives no indication of where it goes, exposing people to possible spam sites.

**Describe the solution you'd like**

Automatically expand shortened URLs where they appear in comments and posts.

**Describe alternatives you've considered**

Experimentally open any URL in a post or comment and flag a warning if it doesn't return a 200. This would have the added benefit of telling people their link is broken.

**Additional context**

None

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
