### ISSUE TITLE
Can't create a listing / tags validation fails

### ISSUE THREAD

**Issue by kbariotis** [forem/forem#9116]
**Describe the bug**

It seems like I can't create a listing due to the tag validation failing. If I leave tags blank and then try to edit, it then allows me to.

**To Reproduce**

1. Go to "Home page"
2. Click on "Create new listing"
3. Try to add a tag
4. See validation error 

**Expected behavior**

To be able to create a listing with tags.

**Screenshots**

![image](https://user-images.githubusercontent.com/605742/86520014-2a93d980-be38-11ea-971f-65e2b7097938.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 83.0.4103.116

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by Rafi993** [comment]
Hi there, If this issue is not taken I would like to help.

**Comment by rhymes** [comment]
@Rafi993 go ahead! thanks!

**Comment by Rafi993** [comment]
> @Rafi993 go ahead! thanks!

Thank you @rhymes

**Comment by nickytonline** [comment]
Just to give a little more info on this. The `pattern` attribute on the input is wrong which is why it fails. It should accept a comma (maybe even whitespace that gets removed on blur or on keyup it just doesn't let a space) in between tags. To make it friendlier, consider taking off the trailing comma if there is one.

So valid use cases:

- someAlphanumericTag1, someAlphanumericTag2, someAlphanumericTag3
- someAlphanumericTag1, someAlphanumericTag2, someAlphanumericTag3,
- someAlphanumericTag1,
- someAlphanumericTag1

The pattern should also allow for n number of tags. Currently it's 8 tags (see placeholder text). This is coming from `maxTags` in tags.jsx.

![image](https://user-images.githubusercontent.com/833231/86551625-95661300-bf13-11ea-8ab7-8cc29653a0c5.png)

**Comment by jacobherrington** [comment]
@nickytonline This is an interesting difference between the behavior on listings and articles. I'm guessing this was introduced in https://github.com/thepracticaldev/dev.to/pull/9006/files, which didn't have this issue in adding tags to articles, but does break listings.

**Comment by Rafi993** [comment]
> @nickytonline This is an interesting difference between the behavior on listings and articles.
> 
> This was introduced in https://github.com/thepracticaldev/dev.to/pull/9006/files (reverting [83ba6b6](https://github.com/thepracticaldev/dev.to/commit/83ba6b64c90c2dcff4aaace933dbfc92318ceee5) fixes this), which didn't have this issue in adding tags to articles, but does break listings.

I think it removes the regex but I think it will remove all validations in the input itself.

**Comment by Rafi993** [comment]
@jacobherrington  since you have a pr to close this issue feel free to change assignee.
