### ISSUE TITLE
Support webp format for image upload

### ISSUE THREAD

**Issue by icncsx** [forem/forem#9118]
### Issue

webp is a popular image format originally developed by Google. I get an "Image has an unsupported type" error when I try to upload a webp image.

Is this something we can possibly support?

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by subodhk01** [comment]
@icncsx Can you describe where exactly you are trying to upload the image?

**Comment by rhymes** [comment]
@subodhk01 I guess the article uploader or the comment uploader, neither supports webp in input.

**Comment by icncsx** [comment]
@rhymes you got it!

**Comment by nickytonline** [comment]
The article image uploaders support it on the frontend. It's the backend that can't process it. See the `accept="image/*"` attribute.

![image](https://user-images.githubusercontent.com/833231/86622240-920f6d80-bf8d-11ea-956f-c5b3a3714b6f.png)

![image](https://user-images.githubusercontent.com/833231/86622283-a6ec0100-bf8d-11ea-9f34-6a85e0a25073.png)

**Comment by rhymes** [comment]
Even though I previously assigned myself here and created a draft PR #9156, I'm going to relinquish this as I think it's going to be addressed by us switching to imgproxy and that's the work that @maestromac and @jdoss have been doing. I don't think it's worth the effort to try to add WebP support to carrierwave. 

Will imgproxy be webp-enabled @maestromac ?

**Comment by maestromac** [comment]
@rhymes Webp is supported on Imgproxy but we would still need to update Carrierwave too because it is the first recipient of the uploaded content, then it get modified/cached by Imgproxy.

**Comment by mstruve** [comment]
@vaidehijoshi I feel like this might need product sign off before deciding to support another upload type. What are your thoughts?

**Comment by vaidehijoshi** [comment]
@mstruve supporting webp is a very developer-specific route; looking at our current set of priorities and product statement, I would say that this is something we might be able to support within the broader forem ecosystem down the road, but I don't think we have the bandwidth to implement and maintain this right now

**Comment by rhymes** [comment]
A quick non empirical investigation: upload from phone works, that's because smartphones don't store images in webp and, at least for the iPhone, even if they store images in HEIC, they're smart enough to convert them to JPG pre-upload. I can't upload HEIC to Forem (verified by sending a photo taken from the iPhone to the desktop computer via Airdrop to avoid conversion). 

I'm quite confident Android uses JPEG internally as well. So on the mobile front we're covered.

System level screenshots are usually in PNG and we support that. Photo editing apps usually export either in raw formats or in JPEG or PNGs. Photoshop for example, doesn't natively support WebP as a format, only through [a plugin to be installed manually](https://github.com/webmproject/WebPShop). 

The only scenario where WebP upload is probably needed is when someone downloads an image that's already a WebP and wants to upload it to a Forem, which, again without any empirical data, it doesn't seem to happen very often (and it's one export/conversion away anyway).

Don't know of any other scenarios where WebP as an imported format might be required.

So yeah, we'll eventually need this but not right now.

**Comment by cmgorton** [comment]
> @mstruve supporting webp is a very developer-specific route; looking at our current set of priorities and product statement, I would say that this is something we might be able to support within the broader forem ecosystem down the road, but I don't think we have the bandwidth to implement and maintain this right now

Given Vaidehi and Rhymes's response I am going to go a head and close this issue for now and we can revisit this kind of feature request in the future.

**Comment by joshuacortes** [comment]
WebP is required as a next gen format, when we will receive it?

**Comment by bartread** [comment]
I'd like to request this as well. In 2020 or 2021 webp might not have seemed like it had that much traction but, in 2024, I'm increasingly working with images in this format and not being able to simply drop them into, for example, an issue, PR, or the wiki from Finder or Explorer without first converting them manually is a pain, and represents unnecessary and unwelcome friction.
