### ISSUE TITLE
How to get rid of "InvalidAuthenticityToken"

### ISSUE THREAD

**Issue by akhil-naidu** [forem/forem#9147]
I am new to any opensource projects and also to ruby on rails,

But, somehow, I was able to launch an instance using a container guide, provided in docs.

Platform: Vultr.com
Ram: 4GB
OS: Ubuntu 20.04

Only changes I did to the forked repository is adding GITHUB_KEY and GITHUB_SECRET

When I am facing this error:

For some reason, I was not able to create a post or write a post  => if any suggestion, I would be glad
As I was not able to create posts, I gave a user super_admin privileges and tried to create one, but I failed to create one but able to get this error.

I like to write a test post, and I need some suggestions to move forward.

**Comment by CDDelta** [comment]
Lucky for you Ben Halpern just made a post on this: https://dev.to/ben/actioncontroller-invalidauthenticitytoken-what-s-going-on-here-2828

**Comment by akhil-naidu** [comment]
@CDDelta  Thanks for the mentioning about that blog

**Comment by rhymes** [comment]
@akhil-naidu is your issue solved? Let us know.

**Comment by akhil-naidu** [comment]
@rhymes No, I'm still working on it, the error is persisting again and again.

**Comment by rhymes** [comment]
@akhil-naidu have you configured `SECRET_KEY_BASE`? Can you add a bit more context as to what it happening? Is it locally? on a production environment?

**Comment by akhil-naidu** [comment]
@rhymes I added my SECRET_KEY_BASE in **dev.to/config/application.yml**, which was generated using `docker-compose run web rack secret`

It is not local and it is hosted on a VM, I am not sure what production actually means now. Can I say an active deployment in a VM as Production?
Right Now, I am assuming production as VM + SECRET_KEY_BASE + the Last 3 variables in ENVfile. 

> If I am wrong, please let me know

**Comment by rhymes** [comment]
I think production means running with the `RAILS_ENV` set to `production` but I'm pinging @jdoss as I'm unfamiliar with our docker setup.

Thanks for the details!

**Comment by akhil-naidu** [comment]
I forgot to mention this!

Actually, I changed the RAILS_ENV variable in 7 placements in a single file, as it is mentioned 7 times in a single file. I changed it from `RAILS_ENV: development` to `RAILS_ENV: production` in **dev.to/container-compose.yml**

> If you want I can reinstall everything, it takes around 15 mins, not a problem for me.

**Comment by pjar** [comment]
Having the same issue as @markomannux - just managed to install everything with docker on mac, and wanted to login with a user that I added `:super_admin` role and set his password - all in rails console. I did that as I wanted to get rid of `Setup not completed yet, please visit the configuration page.` flash message which leads to a page behind authentication. 

I will debug it more later but from the surface it seems odd as `config/secrets.yml` has a key set up for development.  I also run `rake secret` along with restarting the whole stack but to no avail. When I check `Rails.configuration.secret_key_base` in rails console it returns `nil`.

**Comment by markomannux** [comment]
I can confirm that, like @pjar stated, `config/secrets.yml` has a key for dev and `Rails.configuration.secret_key_base` is `nil`. However, it seems that `secret_key_base` is stored both under `Rails.application.secrets.secret_key_base` and `Rails.application.secret_key_base` (the former is used by Sidekiq to search for the session secret - I found a hint in `config/routes.rb`).
Is it expected to be under `Rails.configuration.secret_key_base`? I tried to put it there too with no result...

Not really sure of how it should work, but I see that when rendering `<base_url>/enter`, the content attribute of `csrf-token` meta tag always differs from the value in the hidden field inside the form. Also, `_csrf_token` cookie bears another different value (not really sure what its purpose is). Inside redis session keys there are values like:

`{I"_csrf_token:EFI"1+l22bEmwqc0X7lRlhFzQbblFckRXIFzvaI3sxK06DyI=;`

which are different too but I assume they are somehow encoded.

How can I inspect the expected value of authenticity_token, in order to better understand what is happening?

**Comment by markomannux** [comment]
Raised an [issue on forem.dev](https://forem.dev/markomannux/invalidauthenticitytoken-with-docker-setup-5c3i).
Turns out my problem (and @pjar's, I assume) could be related to domain name used in dev.
I navigated the app using localhost, but in `container-compose.yml` APP_DOMAIN is declared as `rails`.

Adding a record to my hosts file

```
127.0.0.1 rails
```

and navigating with base url `http://rails:3000` seems to solve my issue, even if I'm not really sure how this is related to token verification...

However, I hope this could help others as well.

**Comment by akhil-naidu** [comment]
> ## Resolved

## Solution 01: If the Forem is hosted in VPS
 This is how I eliminated most of the issues related to `onboarding message errors` and `InvalidAuthenticityToken error`

1. I have a domain in Cloudflare, so I created a CNAME record on the subdomain(ex: dev.leewardslope.com) and attached the external IP address. Only the IP, no need of port.
2. As the Forem service is running on the port 3000, we need to look at this issue too, so I installed Nginx and port forwarded the fort 3000 to 80. So that there is no need to use the port 3000 anymore. Here is a more detailed [guide](https://www.digitalocean.com/community/questions/how-do-i-point-my-custom-domain-to-my-ip-port-41-111-20-36-8080) which might be useful in configuring IP: PORT to a domain name.
3. In .env file, change the APP_DOMAIN to your domain, in my case: dev.leewardslope.com
4. Also, don't forget to update these in GitHub too, the URL for authentication, I guess you used localhost:3000 or your IP:3000.

> Also if you don't have a domain of your own and don't want to invest some bucks right now, you can use this site to create a [free domain](https://www.freenom.com/) for now.

## Solution 02: If your Forem is in Local Machine
While accessing Forem in the browser, I guess you are using: http://127.0.0.1:3000
Rather than that try using: http://localhost:3000
