### ISSUE TITLE
[Feature] Settings: add autocompletion for skills

### ISSUE THREAD

**Issue by MenaiAla** [forem/forem#9259]
**Description.**

When I want to write my skills there's not an autocomplete that helps me to write quickly and/or fix typo errors.

**Recommended solution**

 Add autocomplete for skills tags.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
