### ISSUE TITLE
RSS Feed Entries are Too Long

### ISSUE THREAD

**Issue by ThomasOwens** [forem/forem#9265]
**Describe the bug**

I subscribe to the feed at https://dev.to/feed. This feed returns the full body of the article for all articles.

I subscribe via an RSS to email service (Blogtrottr), delivered to a Gmail email inbox. In this case, it sometimes leads to truncated messages. In other feed readers, it can lead to a lot of scrolling due to the length of some articles. Some feed readers may allow for different views, but this is a functionality of the feed reader and should not be relied on to provide a good experience.

**To Reproduce**

Subscribe to https://dev.to/feed in various feed readers and observe.

**Expected behavior**

It should be easy to scroll through the list of articles in a feed reader or RSS to email service delivery.

The RSS feed should either deliver a truncated form of the body or no body at all. For truncation, this can be done by counting the number of words or looking for a divider of some kind. However, if a divider is used, there still needs to be care to prevent authors from creating portions that are simply too large to be effective in a feed reader or RSS to email service.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
Hi @ThomasOwens, thanks a lot of raising this issue!

It's interesting because I have the opposite view, I always get annoyed when feeds truncate the content forcing me to click and go read the original article :-D

I think it should be the responsibility of the client to truncate the item's content. The same way we wouldn't expect an API to return just part of the text of an article. Once you have the full body you can show to the end user just an excerpt, not the other way around.

A compromise could be to do like some sites do and have feeds with partial content (how partial should it be?) on a different URL or served through a specific param.

What do you think?

**Comment by ThomasOwens** [comment]
@rhymes I think a parameter or alternate endpoint for partial content is fine. I don't think there is a need for too many options, though. Maybe just "full" and "titles only". I think it would be fine for "titles only" to include some metadata - author, tags, date posted, estimated reading length. Just not the whole content so I can get it delivered to my inbox without truncating content and missing articles. Honestly, I'm OK with that since I'm more likely to engage with a post if I'm on the target site rather than just reading in my feed reader, which is why I've switched my preferences from full-content to titles only.

**Comment by cmgorton** [comment]
Thank you for opening this request.
Features tend to be subjective and might spur some debate as you can see in this issue 😄.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
