### ISSUE TITLE
A request invitation button

### ISSUE THREAD

**Issue by leewynne** [forem/forem#9344]
This feature request is related to PR #9294 

I think a really cool addition to this would be a simple 'request an invite' button someone after a visitor clicks on 'more sign in options'. Maybe that then renders a simple for requesting email address and some other details?

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Thank you for opening this request Lee!
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
