### ISSUE TITLE
API: Sandbox or Testing instance to use in AppVeyor

### ISSUE THREAD

**Issue by fgiuliani** [forem/forem#9408]
Hello!

I'm contributing on an open source project, a .NET interface for Forem API
https://github.com/Turnerj/forem-dotnet

Do you have plans to create any kind of sandbox for Forem API so it is possible to run tests with a CI calling it?
Maybe a container with the API and a test database with data seeded to call?

Thank you!

**Comment by citizen428** [comment]
Thanks for the issue @fgiuliani! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
Thank you for opening this request!
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
