### ISSUE TITLE
Title to Slug Creation Does Not Account for Internationalization

### ISSUE THREAD

**Issue by bencgreenberg** [forem/forem#9425]
**Describe the bug**

Currently, forem's `Article.title_to_slug` method uses Rails' built-in `#parameterize` to build slugs for articles. The problem is that `#parameterize` is awful with the context of forem, which is a user community from around the world, potentially building new content in any number of languages and character types. 

The common route to address this is to add custom `I18n` translation rules for each locale, but given forem's ever growing community, that seems not sustainable. 

One possible suggestion is to remove the usage of `#parameterize` and build an in-house method that does the same thing, but doesn't erase non-Latin characters from the slug.

**To Reproduce**

1. Create a new article
2. Provide it with a title not in Latin characters
3. Click publish
4. The slug will be something like: `/-n68`

**Expected behavior**

The expected behavior is that the slug generation uses the title regardless of character set.

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by cmgorton** [comment]
I have opened a discussion on internationalization especially around Non-ASCII characters. Please visit this post to add any additional thoughts there. 

https://forem.dev/foremteam/non-ascii-title-makes-a-weird-url-on-forem-dev-to-2255

**Comment by yheuhtozr** [comment]
@djuber Hi, slug i18n is great, but I doubt Sterile does the job correctly. Sterile straightforwardly uses Stringex, which is an implementation of Unidecode. Unidecode was created in 2001, and by today's standard, no more considered to be a universal solution or even "better than nothing" one. It (a) forces one-to-one mapping of any Unicode character to a ASCII sequence, (b) utilizing Unicode's quite opinionated character names. Thus the readability of resulted strings varies tremendously according to language.

For example, as you mentioned Telugu in #15051, it works relatively reliably for the language until the word contains vowel _a_, when the Unidecode always deletes the vowel. `అక్షరము` (akṣaramu "letter") will turn into `akssrmu` which is hard even to find the syllable boundary. `కళ` (kaḷa "art") to `kll` and always indistinguishable with `కల్ల` (kalla "fake") due to the Unicode name (it's like confusing "bitter" and "biter"). Gnrally, sinc "a" is th most frqunt vowl in many Indian languags lik English "e", Unidcod stadily producs somthing lik this sntnc in thir languags. The situation gets worse in Arabic, Hebrew, Thai, Tibetan, or Japanese due to the algorithm.

While the slug is better kept clean than not, we need a library that does not pretend it can handle things that it doesn't, because modern browsers automatically decode percent encoding in URL bar so that the UX impact of URL has been limited. In this light, I suggest [Babosa](/norman/babosa) for the time being. It basically only accounts for Latin, Cyrillic, and Greek that are largely homomorphic to Latin, and has some options for potential locale-based tweaks (like German `ä` → `ae`).
