### ISSUE TITLE
DEV.TO API - Add an optional parameters to GET minimal detail of articles fetched

### ISSUE THREAD

**Issue by abbasogaji** [forem/forem#9464]
**Is your feature request related to a problem? Please describe.**
Add an optional parameters to GET articles minus body_markdown (i.e just the links and images)

**Describe the solution you'd like**
for example /articles/me?minimal=true (only fetches title, cover image and link)

**Describe alternatives you've considered**

**Additional context**

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @forem/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/forem/forem/blob/master/CONTRIBUTING.md).

**Comment by rhymes** [comment]
I switched to `difficulty: medium` as we edge cache the API so whoever works on this will have to figure out how to have 2 different representations of the same resource, both cached and both purgeable in one sweep

**Comment by thefaded** [comment]
Hi, I want to start working on this. For `/articles/me?minimal=true` must be returned for each – title, cover_image and link?

**Comment by citizen428** [comment]
@thefaded This is correct, but see @rhymes' comment above in regards to edge-caching.

**Comment by rhymes** [comment]
How do we agree upon the minimal representation? The OP suggests title, cover image and link, but are those enough?

**Comment by citizen428** [comment]
Basic author information (at least name and/or username) should probably be included as well. I think we can define the subset of attributes here in this discussion and then update the issue description with the consensus.

**Comment by shilpi230** [comment]
@rhymes from constraints of edge caching do you mean this minimal API shouldn't use edge caching ? But the original one which gives all the info should ?

**Comment by citizen428** [comment]
No, it means that both should be cached, but you'd need to ensure that the edge cache handles this scenario correctly (same endpoint, different params).

**Comment by shilpi230** [comment]
Okay @citizen428  Do we want to use [fastly](https://www.fastly.com/) or use something of our own ?

**Comment by rhymes** [comment]
Hi @shilpi230, I think by setting surrogate keys you should be able to use both Fastly and Nginx.

I'm going to cc @vaidehijoshi and @atsmith813 here to make sure :)

**Comment by shilpi230** [comment]
Okay thanks @rhymes !

**Comment by atsmith813** [comment]
This would depend on where exactly this functionality will live. Is it only on `/articles/me`? If so, that endpoint isn't cached.
https://github.com/forem/forem/blob/9b693a8a8de771f28095d042e711d54bcecbd06c/app/controllers/api/v0/articles_controller.rb#L10

If not, are we trying to add `?minimal=true` to `index`/`/articles`? If so, to make this work, we'll need to double-check the `CacheBuster` to ensure we are busting the path with the param. Currently, we bust the root path for an article explicitly here:
https://github.com/forem/forem/blob/9b693a8a8de771f28095d042e711d54bcecbd06c/app/labor/cache_buster.rb#L42

We' likely want to add something like `bust("/api/articles?minimal=true")`, depending on the exact endpoint, or introduce wildcards `bust("/api/articles?*")`. _Currently, Nginx doesn't have "purge by key" functionality setup. We bust everything by path there so we'd want to go ahead and bust by path, not key/surrogate key, to support both edge services._

We'll also want to make sure we update the VCL to account for this new param by adding `minimal` to the [safe list](https://github.com/forem/forem/blob/master/config/fastly/snippets/safe_params_list.vcl).

++++

**More on surrogate keys**

The surrogate keys are used _only_ in Fastly and they're only for busting content. We do busting by key here:
https://github.com/forem/forem/blob/9b693a8a8de771f28095d042e711d54bcecbd06c/app/labor/cache_buster.rb#L29

The surrogate keys are only for purging in certain areas where we explicitly set the `set_surrogate_key_header` to match the default key. In other words, the `set_surrogate_key_header` is only doing something in spots where we make the value `articles` (the [table key](https://github.com/forem/forem/blob/9b693a8a8de771f28095d042e711d54bcecbd06c/app/models/concerns/purgeable.rb#L22-L24)) or something like `articles/1` (the [record key](https://github.com/forem/forem/blob/9b693a8a8de771f28095d042e711d54bcecbd06c/app/models/concerns/purgeable.rb#L41-L43)). You'll see in some areas we [set nifty surrogate keys like `events_index_page`](https://github.com/forem/forem/blob/9b693a8a8de771f28095d042e711d54bcecbd06c/app/controllers/events_controller.rb#L8), but when you search the codebase you'll find that we never actually make a call to bust by that key. We aren't leveraging the surrogate keys too much.

The `cache_control_headers` are what we use to tell the edge to cache the response.

**Comment by rhymes** [comment]
@atsmith813 great find! I didn't notice `/me` wasn't cached, but as I think the PR on this should also cover the regular `index` view, I think we should use separate endpoints and separate Rails actions.

I don't like it too much as it makes the API a little bit spaghetti code but we already have a few idiosincrasies in v0 so I don't think it would complicate things too much.

A possible proposal is:

`/api/articles/minimal` which returns `index` but with less fields, and this is the public route that has edge caching and uses surrogate keys (we need to figure out how to use them for 2 different representations)
`/api/articles/me/minimal` which returns the minimal version but with authentication, and this we can keep cache-less as you mentioned

I'm still unconvinced that this is the right path though, as it clearly complicate the API. 

I wonder if the other route, similar to JSON API's concept of [sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets), where the API by default returns what we want but then the client can choose which fields they need, this way if the user selects (always between a set of allowed fields) a subset of the full representation, we bypass the edge cache and serve what they need.

What do you think @atsmith813 @citizen428 ?

**Comment by atsmith813** [comment]
@rhymes 

- With regards to caching- it's essentially all the same either way. I think we can pretty much set aside the concept of surrogate keys. That only works for Fastly. So either way, with any of these implementations suggested, we'll need to update the `CacheBuster` to bust whatever new path/querystring we use so that it works with Fastly _and_ Nginx. We also don't use surrogate keys much, so setting it (whether it's a new key or existing) isn't going to do anything because we don't explicitly bust by keys in code anyways. Both providers (Fastly and Nginx) automatically cache by the path so the 2 different representations is, more or less, handled for us. So if we added something like `/api/articles/minmal` (just as an example), we would need to set the cache-control headers, bust this new path in the `CacheBuster`, and then it should Just Work™️ (famous last words 🙈 ) on both Fastly and Nginx.

- With regards to the endpoints - that's a great question 😅 . I don't know that I have a strong preference on that front. The last approach where you mentioned
> the client can choose which fields they need, this way if the user selects (always between a set of allowed fields) a subset of the full representation, we bypass the edge cache and serve what they need

Sounds _sweet_! My only hesitation is it's another endpoint that has a switch to bypass edge caching. Granted, we have rate-limiting and other features in place to help combat malicious users so if we double-check those guards we should be good. I love the idea of being able to define exactly what you need 🎉 .

**Comment by atsmith813** [comment]
@rhymes Quick clarification - when I mentioned
>  I think we can pretty much set aside the concept of surrogate keys.

I mean if we do make a change to surrogate keys, it would only be necessary if we stuck the `minimal` code inside the `index` action. We wouldn't have to set a new key, necessarily, for minimal. I believe we would want to keep the current keys clean - basically put the current keys behind a "guard" where we don't set the existing ones if `minimal` is `true`.

**Comment by rhymes** [comment]
@atsmith813 how do we deal, without surrogate keys, with the fact that `GET /api/articles` can already return different sets of articles as it has many params? See https://github.com/forem/forem/blob/5d5be2e88331f8ca1c901011944388833c3ed5ed/app/services/article_api_index_service.rb#L5-L15

Right now, on Fastly, the surrogate keys decide which set of articles responds to which query based on the fact that, for example, the combination of `page` and `state` return article 1, 4 and 5. It doesn't use the path. As the path is the same (minus the params)

**Comment by atsmith813** [comment]
@rhymes the surrogate keys are only for busting caches, they are not used in cache lookups.

The cache lookup uses the path and the params. Each path with params is treated as a separately cached object. `/api/articles?state=fresh`, `/api/articles?state=all`, `/api/articles?page=2&state=fresh` are all separately cached objects in Fastly.

An example of this is us handling the internal navigator param of `?i=i`. In the `CacheBuster`, we explicitly bust those paths because they're technically all separate in the eyes of edge caching:
https://github.com/forem/forem/blob/dea92ea5e04337fee40cd947f5f8f48e78df742d/app/labor/cache_buster.rb#L33-L35

That's also a lot of why we have the concept of [the safe params list](https://github.com/forem/forem/blob/master/config/fastly/snippets/safe_params_list.vcl). If we didn't strip out random querystring params provided by a user, we end up with random caches. For example, a user could do `/api/articles?some_non_existant_param=some_value`. If we didn't strip that out at the edge like we currently do with the VCL, we would have to manually bust that random, nonexistent cache or wait for it to expire.

The surrogate key's purpose is to make busting cache easier. We can purge content "tagged" with a specific surrogate key (i.e. `article/1`) instead of having to write out each path across many endpoints. Let's say a user updates an `Article` with `id` of `1`. Without the surrogate key, we have to bust a handful of endpoints (the feed, the API, etc.). The surrogate key allows us to basically say, _"Hey, Fastly! Please bust all caches tagged with the surrogate key of articles/1"_. The alternative would be we manually bust paths like `/`, `/api/articles`, etc. You'll see in the `CacheBuster` we actually do manually bust by paths 🙈 . The surrogate keys aren't used much.

**Comment by rhymes** [comment]
Thanks for the refreshing explanation, sometimes I get confused by how our caching system works from the outside in and from the inside out. 

That said, I think my suggestion of adding a `fields` param is feasible. It'd be another param that will determine which endpoint to lookup in the cache, cache busting is already present and all should click in, at least for now :D 

We just need to add `fields` to the safe params list

**Comment by shilpi230** [comment]
Hey guys @rhymes @atsmith813 as far as I could understood from the above conversation: 😄
- Need to add another endpoint `/api/articles/minimal` with `fields` params to whatever user wants to select.
- Adding `fields` to vcl.
- For edge caching not getting into surrogate_keys instead it will be using `cache_buster` for now.

**Comment by atsmith813** [comment]
@rhymes No problem - I also get confused by it all the time! That's part of why I put specific code references - force myself to double-check my own understanding.

I love the `fields` idea! +1

That does remind me...we'll need to consider what the format of the `fields` param is with this approach. We've had trouble permitting and handling `Array` params with Fastly 🙈 . One example is [here](https://github.com/forem/forem/pull/7914) where I tried to handle it better and it didn't quite work.

Currently, we do use `Array` params but it's used under a catch-all:
https://github.com/forem/forem/blob/5d5be2e88331f8ca1c901011944388833c3ed5ed/config/fastly/snippets/safe_params_list.vcl#L4
`/search` takes some parameters that are an `Array` and that works because we are allowing any parameter under `/search` right now.

Off the top of my head, I'm not clear on if Fastly will recognize that a differently ordered `Array` is essentially the same cached object. In other words, I don't know if Fastly will see that
- `/api/articles/minimal?fields=[title, author]`
- `/api/articles/minimal?fields=[author, title]`

are actually the same thing 🤔 . If it didn't see that it was the same, technically we could write some edge logic to always alphabetized that param. That gets complicated because we'll need to do that edge logic one way in Fastly and another in Nginx - not as scalable 🙈 .

We can explore further how to better support Array params at the edge. We can also restructure it to not have to deal with it right now. Spitballing to more clearly demonstrate the concept - that could be something like `/api/articles/minimal?title=true&author=true`, etc.

**Comment by atsmith813** [comment]
@shilpi230 correct! At least, that's how I'm understanding it 😅 

I think the best move may be to get one more set of eyes from someone on the team about these ideas around caching and endpoints before we go ahead with this approach 👍 . I'll also help to ensure the agreed-upon approach is re-summarized - I recognize some of this deep in the weeds. What do you think, @rhymes?

And @shilpi230 how does the approach outlined, so far, sound to you?

**Comment by rhymes** [comment]
Sorry @shilpi230 @atsmith813, it's all correct except that we don't need a new endpoint, ie. `/minimal`

The changes will be adding `fields` to `GET /api/articles` and `GET /api/articles/me`

So I would imagine something like:

`GET /api/articles?page=2&fields=body_markdown,title` which would return only those fields (in addition to the ID which I would always put in in the final presentation)

This way we should also skirt the issue of arrays vs non array params.

I'll summarize:

- `/api/articles` and `/api/articles/me` get a new param called `fields` which is a comma separated string
- this comma separated string is validated server side (the fields specified need to be included in the current list of fields we return for each of the endpoint)
- we don't need the array param as we don't use JSON API yet. If a client selects `fields=receive,user` they will receive the whole `user` object as we have now, we don't need to go into depth here
- edge caching should work as `GET /api/articles?page=2&fields=body_markdown,title` will be cached differently than `GET /api/articles?page` so there shouldn't be overlapping with representations, but we can discuss it further once we have a draft PR we can test

Would that work @atsmith813 @shilpi230 ?

**Comment by atsmith813** [comment]
@rhymes 👍  sounds great to me, thanks!

**Comment by shilpi230** [comment]
Yes thanks @rhymes @citizen428 sounds great! Will get the draft PR ready. Thanks!

**Comment by cmgorton** [comment]
Hey all. Thanks for the conversation here.  
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature like this one, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
