### ISSUE TITLE
Can not write blog

### ISSUE THREAD

**Issue by imdhruv99** [forem/forem#9508]
It's been 2 week that i have been reporting about thing that i can not write blog and also can not edit any of my blog. But because of your poor services i can not write anything.

**Comment by 8bithemant** [comment]
Hii Dhruv,

There is no such issue on DEV, the issue is particularly for your account and possibly because of violation of code of conduct policy.

Check your mail box with a violation mail which will let you know the services aren't poor at all.

Also I am a Dev Community Fan 🙂, and let me remind you Dev Team is really busy on stuffs and they have a fast growing team so they may be slow to respond but Really good on their side.


Thank You.

Please check your mail once

**Comment by citizen428** [comment]
Hello @imdhruv99, thanks for notifying us of this problem, this looks an issue specific to your account. Please email yo@dev.to for more help.

@8bithemant While it's nice that you tried to defend us here, let's please stay civil and not accuse people of CoC violations or similar.
