### ISSUE TITLE
Add syntax highlighter for x86 / x64 assembler syntax

### ISSUE THREAD

**Issue by PELock** [forem/forem#9552]
Please add syntax highlighting for the source code in assembler (MASM / FASM / NASM using ````asm`

**Comment by citizen428** [comment]
We're using the [Rouge gem](https://github.com/rouge-ruby/rouge) for syntax highlighting. It supports both Arm assembly (`armasm`) and NASM (`nasm`) syntax highlighting. Here's an example:

<img width="758" alt="Screen Shot 2020-07-28 at 17 25 23" src="https://user-images.githubusercontent.com/47985/88654445-98f64f80-d0f7-11ea-9ba4-59d8a1f46ac1.png">

There's no support for GAS yet but there's an [open issue](https://github.com/rouge-ruby/rouge/issues/1427) in their issue tracker.

Can we close this issue here?

**Comment by PELock** [comment]
ARM and NASM syntaxes are the least used ones! The most popular one is MASM syntax. Close it if you wish, just saying.

**Comment by citizen428** [comment]
To clarify: I wasn't suggesting closing this issue because I don't think your concern is valid, but because this isn't the right repository to ask for it. We did not implement our own syntax highlighting but instead rely on Rouge, an external library. Any new language that gets added there will also be supported by DEV/Forem.

**Comment by rhymes** [comment]
Hi @PELock, thanks for opening the feature request! As @citizen428 suggested we defer syntax highlighting of specific languages to a third party library. My suggestion is to request this syntax upstream to https://github.com/rouge-ruby/rouge/issues - If you let us know the issue ID we'll closely monitor the progression and when it's merged and released we'll update our code accordingly.

Thank you again!
