### ISSUE TITLE
Add a 'Back to Top' Button on homepage

### ISSUE THREAD

**Issue by kfatmakausar** [forem/forem#9607]
**Is your feature request related to a problem? Please describe.**

Sometimes the feed can get pretty long so I was suggesting a 'Back to Top' button on the home page

**Describe the solution you'd like**

The 'Back to Top' button would allow the user to go back up to the start with just one click and I was thinking the button would appear once the user started scrolling on the home page

**Comment by rhymes** [comment]
This is similar to https://github.com/forem/forem/issues/2618, maybe we should keep only that one @kfatmakausar ?

**Comment by kfatmakausar** [comment]
I was actually working on that issue until someone suggested it be closed because the side bar is already made 'sticky' @rhymes

**Comment by rhymes** [comment]
@kfatmakausar make sense, let's keep this open! Thank you for the clarification

**Comment by kfatmakausar** [comment]
I'd like to work on the issue

**Comment by rhymes** [comment]
@kfatmakausar go ahead, I've assigned it to you

**Comment by Link2Twenty** [comment]
Have there been designs done? 

It makes sense to for the button to match the `Skip to content` and `Write a post` button style but on mobile I'm not sure where it would work best. Convention is bottom right but that will cover the save button of a post low down on the page but perhaps that is ok.

**Comment by rhymes** [comment]
Hi @kfatmakausar, are you still working on this? Let us know if you need any help

**Comment by ludwiczakpawel** [comment]
Since it's been inactive for a while I think I'll close it, especially we don't have designs for this and there are things we haven't really thought-through as much as we should, for example:

- how would it look like?
- on mobile, there's already native interaction for going back to top (at least iOS)
- there's a potential UI conflict with other "floating" elements like Mod button (bottom right corner) or podcast player...
