### ISSUE TITLE
Sign in with Microsoft account

### ISSUE THREAD

**Issue by martingbrown** [forem/forem#9654]
**Is your feature request related to a problem? Please describe.**
If I sign in with Twitter or Githup I have to remember my password. I use a windows PC and am always signed in with my MS account already.

Same as twitter / github but using MS as the auth provider. 

**Additional context**

**Comment by cmgorton** [comment]
Thank you for opening this request.
Since this has been open for awhile without much progress I am going to close it here. 
The Forem core team now uses an internal RFC ("request for comments") process to assess and prioritize new features. This process is intended to provide a consistent and standardized path for new changes to enter the Forem ecosystem. If you'd like to propose a new feature, please visit [forem.dev](https://forem.dev/) to start a discussion around a new feature! 🙏
