### ISSUE TITLE
Signal to the user that clicking the notification bell will transition the page / On-page viewing of notifications

### ISSUE THREAD

**Issue by Fire-** [forem/forem#968]
**Is your feature request related to a problem? Please describe.**
I was reading an article today, noticed that I had a badge on my notifications bell, and went to hover over it to get some information ( like when you hover over your profile image ). 
Instead of showing me a list of notifications, nothing happened. 
I clicked it, expecting it to open a flyout with the aforementioned list, but instead it transitioned the page abruptly to a standalone notifications page.

**Describe the solution you'd like**
Either:

- Hovering over the notification bell should display a flyout of recent notifications in a list.
- Hovering over the notification bell should provide some sort of visual feedback, and clicking on the notification bell should display a flyout of recent notifications in a list

**Additional context**

bad mock: 
![image](https://user-images.githubusercontent.com/1456217/47249681-35d87480-d3cb-11e8-8fb0-fbbf5d96f639.png)

**Comment by jessleenyc** [comment]
Hey @Fire-, thanks for the feedback. These are two design considerations we'll continue discussing. It's been intentional to re-direct to a separate notifications page (similar to how Twitter does it) and I'm sure @benhalpern will have more thoughts on that, plus the hover notification request.

**Comment by rhymes** [comment]
I have the feeling this is somewhat related to the UX of this other https://github.com/thepracticaldev/dev.to/issues/1110

There the OP is asking to have a menu that appears on click and not just on hover, and here we're asking to have a hover menu because the click is an action.

I feel these two require a little bit of decisions about the design and UX before they are tackled

**Comment by cmgorton** [comment]
Hey all! Moving forward, we would love for people to head over to [forem.dev](https://github.com/forem/forem#community) for many of these feature requests that we need more discussion around. 

Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](https://forem.dev/). There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
