### ISSUE TITLE
dev.to announcements banner hides "chat invitation" notifications in chat window

### ISSUE THREAD

**Issue by nitya** [forem/forem#9683]
**Describe the bug**

**Context**
When a user is invite to a private chat channel, they are alerted to invite via a visual notification.
This is delivered via an indicator (shown by a users icon) in the chat session _sidebar_ menu (top left)
Users need to see and accept the invite in order to join the channel (and this is the ONLY notification)

**Bug**
 When the announcement banner is shown, it effectively masks the entire chat session sidebar menu including the filters (All-Direct-Group) and the notifications alert (users icon) there. This meant that invited users would remain unaware of pending invites. Further, since many are new to the chat feature, they might not even know this sidebar menu existed (folks tend to look at the main notifications alert at top right of page)

**To Reproduce**

1. Visit the chat page https://dev.to/connect/
2. Verify that the sidebar menu (All-Direct-Group filter, and users-icon notification) is visible
3. Trigger the announcements banner in some way (not in end user control)
4. Check if the sidebar menu is still visible (on https://dev.to/connect/)

**Expected behavior**

Notifications should always remain visible at all times - but when announcement banner is live, these get hidden behind it. (Note: the only solution is to close the banner by clicking the X - but many users are unaware of this)

**Screenshots**
The triggering of announcements is not in my control. I first observed this at CodelandConf - and didn't capture screenshots then. However in a [recent twitter exchange ](https://twitter.com/vaidehijoshi/status/1291784064337248257) I realized the same announcement banner was used in other notifications (e.g, maintenance updates) so I am sharing a screenshot of that instead.

Shows page location of announcement banner.
![banner-location](https://user-images.githubusercontent.com/279083/89710735-94c9fd80-d953-11ea-9e45-505ffdee5b37.png)

Shows the equivalent chat page (without banner) showing the chat menu sidebar (top left) - with All-Direct-Group-AlertIcon options. **I don't have a screenshot showing the exact page with a banner on it and I cannot reproduce that since banner creation is not in our control, but hope the side by side images show how the banner location occludes the alert menu**
![chatmenu-location](https://user-images.githubusercontent.com/279083/89710738-98f61b00-d953-11ea-8f45-43d47709e701.png)

**Desktop (please complete the following information):**

- OS: MacOS (Catalina)
- Browser: Edge
- Version: Version 84.0.522.52

[Twitter conversation that prompted me to file this.](https://twitter.com/nitya/status/1291524673650528256)
I'm a huge fan - thank you all for doing what you do. ♥️

**Comment by vaidehijoshi** [comment]
Hi, @nitya! 👋 I was able to reproduce this since we currently have an active announcement on our site right now 😉

It looks like, with the `Fixed to window` setting for the site navbar, this isn't an issue:
<img width="1732" alt="Screen Shot 2020-08-08 at 5 16 49 PM" src="https://user-images.githubusercontent.com/6921610/89722187-7556c300-d99b-11ea-96f3-5b9f8734809a.png">

However, with the `Static top of page` setting for the site navbar, we see the exact problem of "announcement hiding the notification count" that you described:
<img width="1537" alt="Screen Shot 2020-08-08 at 5 19 53 PM" src="https://user-images.githubusercontent.com/6921610/89722193-8f90a100-d99b-11ea-8cad-648fd3958608.png">

I'm thinking that perhaps we want to only have one form of styling on `/connect` page, or maybe we want to disable announcements from rendering on `/connect` pages altogether? 🤔 Thanks for bringing this up and filing an issue, I can totally see how it would be problematic for someone who is viewing the `/connect `page but whose notifications are obfuscated! I'll investigate what the right course of action is here 😃

**Comment by leewynne** [comment]
👋🏼 yep definitely have had this issue on thisMMAlife but thought it was isolated to me! Great find 😎
