### ISSUE TITLE
Node version installed by Fedora containers incompatible with package.json specification

### ISSUE THREAD

**Issue by christineyen** [forem/forem#9746]
**Describe the bug**

The locked version of node in `package.json` is `12.16.x`, but `dnf` installs `12.18.x`. https://github.com/forem/forem/issues/8270#issuecomment-638868319 describes the intent of the locked version in `package.json` as matching the version that the Fedora-based containers use, but it looks like `dnf` is pulling in something else now.

**To Reproduce**

1. Clone a fresh copy of `forem`
2. Run `bin/containersetup`
3. Observe the following:

```
error dev.to@1.0.0: The engine "node" is incompatible with this module. Expected version "12.16.x". Got "12.18.3"
error Found incompatible module.
```

**Expected behavior**

No failures during setup :)

**Screenshots**

```
Step 26/31 : RUN yarn install
 ---> Running in 46e9ce9cd84d
yarn install v1.22.4
[1/5] Validating package.json...
error dev.to@1.0.0: The engine "node" is incompatible with this module. Expected version "12.16.x". Got "12.18.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'rails' failed to build: The command '/bin/sh -c yarn install' returned a non-zero code: 1
```

**Desktop (please complete the following information):**

- OS, version: N/A; Docker

**Additional context**

Since I can't use `nvm` with the container setup, I got around this by changing the `package.json` version to `12.18.x`, since I ... don't have a Fedora container handy to use to figure out what version of node to peg the `dnf` install to, if that was preferable. ¯\_(ツ)_/¯

**Comment by rhymes** [comment]
@jdoss would it be fine if we updated the global Node version to the new LTS? We use to up the version for each new LTS but now we locked it to follow Fedora's cycles, which apparently is one minor version ahead now.

**Comment by emartindev** [comment]
Sorry for my duplicate.

I upgraded node to 12.18, however I am still getting the same error.
My node version:
`nvm which
Found '/home/forem/forem/.nvmrc' with version <12.18>
/home/forem/.nvm/versions/node/v12.18.3/bin/node
`
`node -v
v12.18.3
`
The error i'm referring to:
`error dev.to@1.0.0: The engine "node" is incompatible with this module. Expected version "12.16.x". Got "12.18.3"
error Found incompatible module.`

**Comment by rhymes** [comment]
Hi @emartindev, have exited the directory after pulling the latest version? When I switch Node version I do the following:

```
nvm alias default v12.18
cd $
cd back the in the directory with Forem
```

let me know if then `bin/container-setup` works

**Comment by jdoss** [comment]
Sorry for the late reply. @rhymes I would just track whatever version the container has and when that upgrades we can follow that within the app.

**Comment by emartindev** [comment]
Hey @rhymes, Thanks for getting back to me. You're guys' support is great!
So that did work!! -however- I am getting this loop constantly:
`sidekiq_1        | 2020/08/13 15:07:53 Problem with request: Get http://rails:3000: dial tcp: lookup rails on 127.0.0.11:53: no such host. Sleeping 1s
seed_1           | 2020/08/13 15:07:54 Problem with request: Get http://rails:3000: dial tcp: lookup rails on 127.0.0.11:53: no such host. Sleeping 1s
sidekiq_1        | 2020/08/13 15:07:54 Problem with request: Get http://rails:3000: dial tcp: lookup rails on 127.0.0.11:53: no such host. Sleeping 1s
`
And then it finally ended after ~1 hour with:

`sidekiq_1        | 2020/08/13 15:07:55 Problem with request: Get http://rails:3000: dial tcp: lookup rails on 127.0.0.11:53: no such host. Sleeping 1s
sidekiq_1        | 2020/08/13 15:07:56 Timeout after 45m0s waiting on dependencies to become available: [tcp://db:5432 http://elasticsearch:9200 tcp://redis:6379 http://rails:3000]
forem_sidekiq exited with code 1
`

I did try doing this from the issue #9532
`Find "-timeout", "2700s" in https://github.com/forem/forem/blob/master/docker-compose.yml and set it to "-timeout", "5400s", save the file and then run ./bin/container-setup again.`
