### ISSUE TITLE
False positives with error: "canonical_url: has already been taken"

### ISSUE THREAD

**Issue by michael-tharrington** [forem/forem#9759]
**Describe the bug**

Occasionally users try to input a canonical url for their post and get hit with the following warning: 
`Whoops, something went wrong: canonical_url: has already been taken`

This warning is meant to block people from reposting an article that was already posted, but it's currently causing issues. The main problem is that the warning appears even if the article that first used the canonical is only in draft mode (unpublished), which occasionally causes issues for folks in the same org.

This generally occurs because organizations don't currently have a way to share RSS, though there is a request for this - https://github.com/forem/forem/issues/4373 / https://github.com/forem/forem/issues/3363. We occasionally end up with a situation where a user in an org will set up the feature Publishing from RSS (https://dev.to/settings/publishing-from-rss) and input the RSS for their org blog, loading in all of their org member's posts into their dashboard. When loading in posts this way, the canonical URL for these posts is set automatically. Often, the person loading in posts this way will just leave the drafts that aren't theirs unpublished in their user dashboard. This is how we end up with drafted posts blocking canonicals.

**Expected behavior**

One short term fix would be to make it so that unpublished posts can't block canonical_urls. I can't think of any downsides to this.

In the long-term, I think we should also allow members of the same org to have access to a shared RSS ( https://github.com/forem/forem/issues/4373 / https://github.com/forem/forem/issues/3363)

**Screenshots**

Here's a screenshot of the warning

<img width="821" alt="Screenshot 2020-08-10 at 17 19 47" src="https://user-images.githubusercontent.com/16007075/90055290-1f3f9380-dcab-11ea-819b-c5ee52639bf8.png">

**Additional context**

This could be a separate request, but I think we should also consider adapting the error message to offer more info for the recipient. 

The current message says:

`Whoops, something went wrong: canonical_url: has already been taken`

But it doesn't provide any info about which post used the canonical url. If it linked to the post instead:

`Whoops, something went wrong: The canonical_url you designated is already in use on the following post https://dev.to/michaeltharrington/1234. If you think there is a mistake, please email yo@dev.to.`

... then the user could potentially help us to triage an issue where one person is claiming the canonical URL for another person's post.

**Comment by eliblocks** [comment]
I took a stab at it with the above PR.

**Comment by rhymes** [comment]
Adding a bit of context for whomever will pick this up in the future.

Currently we check the uniqueness of the `canonical_url` globally in the `articles` table, regardless of publication status. This means that if someone has a draft article with https://example.com/blog/hello as `canonical_url`, then no one else can publish an article with that URL as the `canonical_url`.

This, which was (I think) motivated by the understandable technical requirement of not having two published articles with the same URL, has the unintended effect of:

- prohibiting anyone to save a draft or published article with the same URL
- prohibiting the import of articles from the RSS with the same URL

I think we should reconsider this requirement and evaluate if it makes sense for us to ease the check to only make sure that only published articles have a unique `canonical_url`.

The other proposal, improving the error message, is probably worth considering too but I wonder if it might nudge people into contacting each other (can this lead to harassment I wonder?)

This is technically a bug but since it changes the user experience, before signing off, we might want to loop the product team in for a final blessing, at least for the message part of the issue.

cc @cmgorton @michael-tharrington

**Comment by solvingj** [comment]
Another case here. I think in my case, I'm seeing a bug where I:

1. set the URL correctly
2. changed it to an incorrect URL accidentally and saved it
3. wasn't seeing the changes after refresh, so I unpublished and republished
4. now I cannot set the correct value again, seemingly no matter what I do

So, it feels like maybe the process which checks "all articles" might be caching and not letting go of canonical URL's that it sees, maybe it's a matter of time. 

I've even now un-published the article, so there is only a draft.  I still cannot save the correct canonical URL value even though there's no other post anywhere which has it.
