### ISSUE TITLE
Generalise reaction images

### ISSUE THREAD

**Issue by leewynne** [forem/forem#9850]
I feel that there is a case to generalise the reaction images for the 3 actions you can take on an article (heart, unicorn, save). I think it helps with a bit of uniqueness throughout the Forem ecosystem as it grows.

**Describe the solution you'd like**

An area in SiteConfig that allows an Forem administrator to change the default icons for heart, unicorn and save.

**Describe alternatives you've considered**

Nothing other than hardcoding :(

**Comment by lisasy** [comment]
@leewynne Hey Lee! Thanks for sharing this issue. I think this would be a pretty interesting conversation to have on Forem.dev so that we could all talk about the trade-offs, complexities, and user experience behind this. We've explored design ideas related to this topic :) Would you be interested in kicking off a conversation on Forem.dev? If you want, I am happy to do that and tag you in it.
