### ISSUE TITLE
🔔 Web and Mobile PWA Notification? [Feature Request]

### ISSUE THREAD

**Issue by bauripalash** [forem/forem#997]
When I write a blog post or a comment I have to check dev.to few minutes after after to check if i got any response or not.

I think it would be useful if we got notifications on Mobile or Desktop Web which can be found on visiting on the notifications page.

**Comment by Zhao-Andy** [comment]
@bauripalash thanks for the feature request! We're currently working on refactoring how on-site notifications are handled. Once that's done, it should be easier to add in push notifications.

**Comment by maestromac** [comment]
not stale!

**Comment by r-ush** [comment]
I'm waiting for the notifications on the PWA, its better than the native app

**Comment by cmgorton** [comment]
Since this one has been around for a while without much traction I am going to close it and encourage anyone who would like to see this feature in the future to open a discussion in [forem.dev](forem.dev) . There we can get more eyes on potential features and highlight any we really would love the community to contribute too. Thanks!
